### ISSUE TITLE
OSX version 

### ISSUE THREAD

**Issue by a06kin** [romkatv/gitstatus#1]
Hi, @romkatv 

I tried your powerlevel10k and its aweasome. Thanks for your work.

And as you suggest I tried it with gitstatus and discover that I can't use it on my osx machine. I couldn't compile it too.

In my fork I made some small changes to make it work in osx. Tested only on my machine with Mojave osx.

It's not crossplatform code. So if you can make it work for all platforms that will be great.

[My fork](https://github.com/a06kin/gitstatus)

**Comment by a06kin** [comment]
`brew install libgit2` -> to install libgit2 on osx

**Comment by romkatv** [comment]
Hi Alex,

This is great stuff, thank you!

I’ll gladly make this code portable but I’ll need your help as I don’t have
access to a Mac.

Please run this command and send me its output:

bash -xc 'pkg-config --cflags libgit2; pkg-config --libs libgit2;
pkg-config --libs --static libgit2; pkg-config --libs-only-L libgit2 |
cut -c 3- | xargs ls | grep libgit2'

Why did you replace calls to std::quick_exit() with std::abort()? Did it
not compile or for some other reason?

Are you overriding any variables (like CXX) dynamically when calling make?

Did Powerlevel10k with gitstatus actually work for you on OSX? You can
check with cat $GITSTATUS_DAEMON_LOG. You should see recent requests in
there.

Roman.

**Comment by a06kin** [comment]
Output of the command:
```
+ pkg-config --cflags libgit2
-I/usr/local/Cellar/libgit2/0.27.8/include
+ pkg-config --libs libgit2
-L/usr/local/Cellar/libgit2/0.27.8/lib -lgit2
+ pkg-config --libs --static libgit2
-L/usr/local/Cellar/libgit2/0.27.8/lib -L/usr/local/Cellar/libssh2/1.8.0/lib -lgit2 -lcurl -framework CoreFoundation -framework Security -lz -lssh2 -liconv
+ pkg-config --libs-only-L libgit2
+ cut -c 3-
+ xargs ls
+ grep libgit2
libgit2.0.27.8.dylib
libgit2.27.dylib
libgit2.a
libgit2.dylib
```

quick_exit is missing in osx implementation. [Stack1](https://stackoverflow.com/questions/30408197/how-to-compile-with-c11-standard-library-on-os-x-with-clang) and [Stack2](https://stackoverflow.com/questions/11681403/state-of-c11-standard-support-in-libc)

No, I didn't override variables dynamically 
Here is output from `make -j 20`
```
mkdir -p obj
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -MM -MT obj/gitstatus.o src/gitstatus.cc >obj/gitstatus.dep
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -MM -MT obj/repo_cache.o src/repo_cache.cc >obj/repo_cache.dep
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -MM -MT obj/timer.o src/timer.cc >obj/timer.dep
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -MM -MT obj/request.o src/request.cc >obj/request.dep
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -MM -MT obj/response.o src/response.cc >obj/response.dep
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -MM -MT obj/git.o src/git.cc >obj/git.dep
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -MM -MT obj/logging.o src/logging.cc >obj/logging.dep
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -Wall -c -o obj/request.o src/request.cc
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -Wall -c -o obj/timer.o src/timer.cc
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -Wall -c -o obj/repo_cache.o src/repo_cache.cc
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -MM -MT obj/options.o src/options.cc >obj/options.dep
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -Wall -c -o obj/gitstatus.o src/gitstatus.cc
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -Wall -c -o obj/response.o src/response.cc
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -Wall -c -o obj/git.o src/git.cc
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -Wall -c -o obj/logging.o src/logging.cc
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include -Wall -c -o obj/options.o src/options.cc
c++  obj/gitstatus.o  obj/repo_cache.o  obj/timer.o  obj/request.o  obj/response.o  obj/git.o  obj/logging.o  obj/options.o -L/usr/local/Cellar/libgit2/0.27.8/lib -lgit2 -o gitstatusd
```

And yes, gitstatus actually work for me on OSX. Part of the `cat $GITSTATUS_DAEMON_LOG` output:

```
CPU time (ms): 1551615853.5529088974 : 18.788
[2019-03-03 14:24:13 INFO src/gitstatus.cc:121] Successfully processed request: 1551615853.5529088974 [/Users/aaa/.oh-my-zsh/custom/plugins]
[2019-03-03 14:24:16 INFO src/gitstatus.cc:118] Processing request: 1551615856.0940380096 [/Users/aaa/.oh-my-zsh/custom/plugins/gitstatus]
CPU time (ms): 1551615856.0940380096 : 2.087
[2019-03-03 14:24:16 INFO src/gitstatus.cc:121] Successfully processed request: 1551615856.0940380096 [/Users/aaa/.oh-my-zsh/custom/plugins/gitstatus]
[2019-03-03 14:24:17 INFO src/gitstatus.cc:118] Processing request: 1551615857.1542749405 [/Users/aaa/.oh-my-zsh/custom/plugins/gitstatus]
CPU time (ms): 1551615857.1542749405 : 1.96
```

**Comment by a06kin** [comment]
Here is all variables:

```
Makefile:28: .DEFAULT_GOAL=all (all)
Makefile:28: APPNAME=gitstatusd (gitstatusd)
Makefile:28: CURDIR=/Users/aaa/.oh-my-zsh/custom/plugins/gitstatus (/Users/aaa/.oh-my-zsh/custom/plugins/gitstatus)
Makefile:28: CXXFLAGS=-std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror -I/usr/local/Cellar/libgit2/0.27.8/include (-std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror $(shell pkg-config --cflags libgit2))
Makefile:28: LDFLAGS=-L/usr/local/Cellar/libgit2/0.27.8/lib -lgit2 ($(shell pkg-config --libs libgit2))
Makefile:28: MAKEFILE_LIST= Makefile ( Makefile)
Makefile:28: MAKEFLAGS= ()
Makefile:28: OBJS= obj/gitstatus.o  obj/repo_cache.o  obj/timer.o  obj/request.o  obj/response.o  obj/git.o  obj/logging.o  obj/options.o ( obj/gitstatus.o  obj/repo_cache.o  obj/timer.o  obj/request.o  obj/response.o  obj/git.o  obj/logging.o  obj/options.o)
Makefile:28: SHELL=/bin/sh (/bin/sh)
Makefile:28: SRCS=src/gitstatus.cc src/repo_cache.cc src/timer.cc src/request.cc src/response.cc src/git.cc src/logging.cc src/options.cc (src/gitstatus.cc src/repo_cache.cc src/timer.cc src/request.cc src/response.cc src/git.cc src/logging.cc src/options.cc)
```

**Comment by romkatv** [comment]
Thanks! That's all I need. When I get home, I'll incorporate your changes
and adapt them a little, then ping you to verify it works for you.

Roman.

**Comment by romkatv** [comment]
@a06kin I've submitted a modified version of your patch. Please try building it and see if it works.

**Comment by gbpoole** [comment]
Hey there.  Independently, I'm trying to compile on an up-to-date OSX machine at the moment (I just pulled from master; hash e2ae99d) and am getting this error:

```
src/logging.cc:77:5: error: static_assert failed due to requirement 'std::is_same<decltype(x), char *>()'
    static_assert(std::is_same<decltype(x), char*>());
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
Not sure if this patch fixes this.

**Comment by romkatv** [comment]
@gbpoole I just submitted a fix for this. Please try again.

**Comment by gbpoole** [comment]
Thanks for the quick response.  I'm getting this now:

```
c++ -std=c++17 -funsigned-char -O3 -DNDEBUG -Wall -Werror  -Wall -c -o obj/logging.o src/logging.cc
src/logging.cc:74:24: error: constexpr if condition is not a constant expression
  } else if constexpr (std::is_same<decltype(x), char*>()) {
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/logging.cc:74:24: note: undefined function 'operator bool' cannot be used in a constant expression
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:522:27: note: declared here
        _LIBCPP_CONSTEXPR operator value_type() const _NOEXCEPT {return value;}
                          ^
1 error generated.
make: *** [obj/logging.o] Error 1
```

**Comment by romkatv** [comment]
Damn. Try again...

P.S.

I really need to figure out how to build on OS X myself.

**Comment by romkatv** [comment]
I managed to compile gitstatusd on OS X and added dispatch by architecture.

Could any of you test whether gitstatus works on OS X out of the box without having to compile anything?

Basically this:

```zsh
git clone https://github.com/romkatv/gitstatus.git /tmp/gitstatus
source /tmp/gitstatus/gitstatus.plugin.zsh
gitstatus_query_dir && echo OK || echo ERROR
```

**Comment by a06kin** [comment]
I tried it.
Get err:
```
gitstatus_query_dir:13: _GITSTATUS_REQ_FD: parameter not set
```

**Comment by a06kin** [comment]
I tried to test directly from console. Maybe I do something wrong but I get this:
For file
```
> ./bin/gitstatusd-darwin-x86_64 < /tmp/gitstatus/LICENSE

[2019-03-04 22:56:54 INFO src/gitstatus.cc:109] Parent PID: -1
[2019-03-04 22:56:54 INFO src/request.cc:83] EOF. Exiting.
```

For directory
```
> ./bin/gitstatusd-darwin-x86_64 < /tmp/gitstatus

[2019-03-04 22:57:08 INFO src/gitstatus.cc:109] Parent PID: -1
[2019-03-04 22:57:08 FATAL src/request.cc:81] (n = read(fd_, buf, sizeof(buf))) >= 0: Is a directory
[1]    44288 abort      ./bin/gitstatusd-darwin-x86_64 < /tmp/gitstatus
```

**Comment by romkatv** [comment]
@a06kin Did you already have gitstatus loaded when you sourced the new version? If yes, then please try to load it from clean shell that doesn't have gitstatus yet. For example:

```zsh
git clone https://github.com/romkatv/gitstatus.git /tmp/gitstatus
zsh -d -f -i
```

Then type:

```
source /tmp/gitstatus/gitstatus.plugin.zsh
gitstatus_query_dir && echo OK || echo ERROR
```
 > I tried to test directly from console...

This is normal. The protocol is different now. If you really want to send a request manually, you can do this:

```zsh
RESP=$(echo -nE $'hello\x1f\x1e' | ./gitstatusd | head -c 8) && test "$RESP" == $'hello\x1f0\x1e' && echo WORKS || echo BROKEN
```

**Comment by romkatv** [comment]
I just realized that `gitstatus_query_dir && echo OK || echo ERROR` doesn't work, but `gitstatus_query_dir; echo $?` does. I'll try to fix.

Also, the output of the command you gave me is enough to see that the binary works. It doesn't fail to find dynamic libraries or anything like that. That's great!

**Comment by romkatv** [comment]
Closing as I believe gitstatus now works out of the box on OS X.

If you already have gitstatus enabled, please remove it and `git clone` the latest version. No need to build it manually anymore.

**Comment by gbpoole** [comment]
Almost there (not sure what a06kin is using, but I'm using `clang` which has somewhat stricter checks than `gcc` for example).  I get:

```
c++  obj/gitstatus.o  obj/repo_cache.o  obj/timer.o  obj/request.o  obj/response.o  obj/git.o  obj/logging.o  obj/options.o -s -l:libgit2.a -L/Users/gpoole/3rd_Party/lib -o gitstatusd
ld: warning: option -s is obsolete and being ignored
ld: library not found for -l:libgit2.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

which can be fixed by editing the Makefile, removing the `-s` in `LDFLAGS` and changing the `-l` flag (I've not seen that syntax with the `:` before), so that the line reads: `LDFLAGS += -lgit2`

**Comment by romkatv** [comment]
@gbpoole You can ignore the warning. The real error you've got is "library not found for -l:libgit2.a". This is because you don't have a statically-linked libgit2. The change you've made to `Makefile` caused libgit2 to be linked dynamically. It's OK for personal use but pain for distribution.

The `-l:libfoo.a` syntax allows you to specify static/dynamic linking on a per-library basis (-l:libfoo.so would be link dynamically). Conversely, `-lfoo` will look either for the static or dynamic version depending on whether you are building a static or a dynamic library (this is controlled by `--static`). The whole `gitstatusd` is a dynamically-linked binary because it's a real challenge to create statically-linked binaries that use certain glibc functions (e.g., `getaddrinfo` or `dlopen`).

Here's a command you can use to compile `gitstatusd` on OS X:

```zsh
bash -cxue '
  # Install CMake and pkg-config.
  echo brew install cmake pkg-config

  # Clone, compile and install libgit2.
  rm -rf /tmp/gitstatus
  mkdir -p /tmp/gitstatus
  cd /tmp/gitstatus
  git clone https://github.com/libgit2/libgit2.git
  cd libgit2
  mkdir build
  cd build
  cmake                                \
    -DCMAKE_OSX_ARCHITECTURES="x86_64" \
    -DUSE_SSH=OFF                      \
    -DUSE_HTTPS=OFF                    \
    -DTHREADSAFE=OFF                   \
    -DBUILD_SHARED_LIBS=OFF            \
    -DUSE_EXT_HTTP_PARSER=OFF          \
    -DUSE_BUNDLED_ZLIB=ON              \
    -DCMAKE_BUILD_TYPE=Release         \
    ..
  make VERBOSE=1 -j 20
  sudo make install

  # Clone and compile gitstatus.
  cd /tmp/gitstatus
  git clone https://github.com/romkatv/gitstatus.git
  cd gitstatus
  CXX=clang++ make -j 20'
```

As I mentioned, there is a darwin-x86_64 binary now in the repo. Unless you override `GITSTATUS_DAEMON`, gitclient plugin will automatically pick `gitstatusd` from https://github.com/romkatv/gitstatus/tree/master/bin with the right architecture.
