### ISSUE TITLE
Error on zsh startup

### ISSUE THREAD

**Issue by tharman-telmar** [romkatv/gitstatus#100]
Hi

Here is the error message I get when zsh starts up.

    The content of /tmp/gitstatus.374.xtrace.1581588767.4421989918.17530 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local os
    +gitstatus_start_impl:8> local daemon=/home/tanandasivathas/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-6.3-x86_64
    +gitstatus_start_impl:9> [[ -n /home/tanandasivathas/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-6.3-x86_64 ]]
    +gitstatus_start_impl:16> [[ -x /home/tanandasivathas/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-6.3-x86_64 ]]
                               ^ this command failed

  Your system information:

    zsh:      5.5.1
    uname -a: CYGWIN_NT-6.3 DevDataYG03 3.1.2(0.340/5/3) 2019-12-21 15:25 x86_64 Cygwin

**Comment by romkatv** [comment]
What windows version is this?

**Comment by tharman-telmar** [comment]
Windows Server 2012 R2 Standard

**Comment by romkatv** [comment]
I only provide prebuilt gitstatusd binaries for the most popular operating systems. Windows Server 2012 didn't make the cut. You can try building it yourself. It's not very difficult. See https://github.com/romkatv/gitstatus#compiling.

**Comment by romkatv** [comment]
There might be an easy way out. Please try running the binary for windows 10 by typing the following command:

```zsh
/home/tanandasivathas/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64
```

Does it work?

**Comment by tharman-telmar** [comment]
Running on Windows 10 I get the following:
     [2020-02-13 20:24:11 0000000800038730 INFO src/gitstatus.cc:177] argv[0]: "/home/tanandasivathas/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64"
     [2020-02-13 20:24:11 0000000800038730 INFO src/thread_pool.cc:81] Spawning 1 thread(s)

**Comment by romkatv** [comment]
Nice! It works. I've symlinked it.

Please [update powerlevel10k](https://github.com/romkatv/powerlevel10k#how-do-i-update-powerlevel10k) and restart zsh. The error should be gone.

**Comment by Tharman1** [comment]
Awesome! This has fixed things for me. Great work

**Comment by romkatv** [comment]
Thanks for the confirmation!
