### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by StandardNerd** [romkatv/gitstatus#101]
The content of /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.xtrace.1581632550.0028719902.27911 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local os
    +gitstatus_start_impl:8> local daemon=/Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
    +gitstatus_start_impl:9> [[ -n /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 ]]
    +gitstatus_start_impl:16> [[ -x /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 ]]
    +gitstatus_start_impl:18> lock_file=/var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.lock.1581632550.0033440590.5810
    +gitstatus_start_impl:19> echo -n
    +gitstatus_start_impl:20> zsystem flock -f lock_fd /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.lock.1581632550.0033440590.5810
    +gitstatus_start_impl:22> req_fifo=/var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.req.1581632550.0035510063.5356
    +gitstatus_start_impl:23> resp_fifo=/var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.resp.1581632550.0035839081.6139
    +gitstatus_start_impl:24> mkfifo /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.req.1581632550.0035510063.5356 /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.resp.1581632550.0035839081.6139
    +gitstatus_start_impl:26> local -i threads=8
    +gitstatus_start_impl:27> ((  threads > 0 ))
    +gitstatus_start_impl:37> local -a daemon_args=( '--lock-fd=3' '--parent-pid=8705' '--num-threads=8' '--max-num-staged=-1' '--max-num-unstaged=-1' '--max-num-conflicted=-1' '--max-num-untracked=-1' '--dirty-max-index-size=-1' '--log-level=DEBUG' )
    +gitstatus_start_impl:49> local cmd=$'\n        exec >&4\n        echo $$\n        /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 --lock-fd=3 --parent-pid=8705 --num-threads=8 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n        if [[ $? != (0|10) && $? -le 128 && -f /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static ]]; then\n          /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static --lock-fd=3 --parent-pid=8705 --num-threads=8 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n        fi\n        echo -nE $\'bye\\x1f0\\x1e\''
    +gitstatus_start_impl:61> local zsh=/proc/self/exe
    +gitstatus_start_impl:62> [[ -x /proc/self/exe ]]
    +gitstatus_start_impl:62> zsh=zsh
    +gitstatus_start_impl:63> cmd='cd /; read; unsetopt bg_nice; zsh -dfxc $'\''\n'\''\ \ \ \ \ \ \ \ exec\ \>\&4$'\''\n'\''\ \ \ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ \ \ /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64\ --lock-fd=3\ --parent-pid=8705\ --num-threads=8\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ if\ \[\[\ \$\?\ !=\ \(0\|10\)\ \&\&\ \$\?\ -le\ 128\ \&\&\ -f\ /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static\ \]\]\;\ then$'\''\n'\''\ \ \ \ \ \ \ \ \ \ /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static\ --lock-fd=3\ --parent-pid=8705\ --num-threads=8\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ fi$'\''\n'\''\ \ \ \ \ \ \ \ echo\ -nE\ \$\'\''bye\\x1f0\\x1e\'\'' &!; rm -f /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.req.1581632550.0035510063.5356 /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.resp.1581632550.0035839081.6139 /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.lock.1581632550.0033440590.5810'
    +gitstatus_start_impl:68> sysopen -w -o cloexec,sync -u req_fd /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.req.1581632550.0035510063.5356
    +gitstatus_start_impl:69> sysopen -r -o cloexec -u resp_fd /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.resp.1581632550.0035839081.6139
    +gitstatus_start_impl:70> echo -nE $'0\nhello\C-_\C-^'
    +gitstatus_start_impl:73> ((  async  ))
    +gitstatus_start_impl:76> local reply IFS=''
    +gitstatus_start_impl:77> read -ru 21 reply
    +gitstatus_start_impl:66> zsh -dfmxc 'cd /; read; unsetopt bg_nice; zsh -dfxc $'\''\n'\''\ \ \ \ \ \ \ \ exec\ \>\&4$'\''\n'\''\ \ \ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ \ \ /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64\ --lock-fd=3\ --parent-pid=8705\ --num-threads=8\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ if\ \[\[\ \$\?\ !=\ \(0\|10\)\ \&\&\ \$\?\ -le\ 128\ \&\&\ -f\ /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static\ \]\]\;\ then$'\''\n'\''\ \ \ \ \ \ \ \ \ \ /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static\ --lock-fd=3\ --parent-pid=8705\ --num-threads=8\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ fi$'\''\n'\''\ \ \ \ \ \ \ \ echo\ -nE\ \$\'\''bye\\x1f0\\x1e\'\'' &!; rm -f /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.req.1581632550.0035510063.5356 /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.resp.1581632550.0035839081.6139 /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.lock.1581632550.0033440590.5810'
    +gitstatus_start_impl:78> [[ 8860 == <1-> ]]
    +gitstatus_start_impl:79> daemon_pid=reply
    +gitstatus_start_impl:90> zle -F 21 _gitstatus_process_response_POWERLEVEL9K
    +gitstatus_start_impl:92> read -r -d $'\C-^' -u 21 -t 5.0000000000 reply
    +gitstatus_start_impl:93> [[ $'bye\C-_0' == hello0 ]]
                               ^ this command failed

  The content of /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.daemon-log.1581632550.0028469563.32619 (gitstatus daemon log):

    +zsh:1> cd /
    +zsh:1> read
    +zsh:1> unsetopt bg_nice
    +zsh:1> rm -f /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.req.1581632550.0035510063.5356 /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.resp.1581632550.0035839081.6139 /var/folders/cf/8sbgd8rx0wd1d5zhmgcqd5hw0000gn/T//gitstatus.8705.lock.1581632550.0033440590.5810
    +zsh:1> zsh -dfxc $'\n        exec >&4\n        echo $$\n        /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 --lock-fd=3 --parent-pid=8705 --num-threads=8 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n        if [[ $? != (0|10) && $? -le 128 && -f /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static ]]; then\n          /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static --lock-fd=3 --parent-pid=8705 --num-threads=8 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n        fi\n        echo -nE $\'bye\\x1f0\\x1e\''
    +zsh:3> echo 8860
    +zsh:4> /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 '--lock-fd=3' '--parent-pid=8705' '--num-threads=8' '--max-num-staged=-1' '--max-num-unstaged=-1' '--max-num-conflicted=-1' '--max-num-untracked=-1' '--dirty-max-index-size=-1' '--log-level=DEBUG'
    dyld: Symbol not found: __ZdlPvm
      Referenced from: /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 (which was built for Mac OS X 10.13)      Expected in: /usr/lib/libc++.1.dylib
     in /Users/choi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
    +zsh:5> [[ 133 != (0|10) && 133 -le 128 ]]
    +zsh:8> echo -nE $'bye\C-_0\C-^'

  Your system information:

    zsh:      5.7.1
    uname -a: Darwin Methusalix.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

**Comment by romkatv** [comment]
See https://github.com/romkatv/gitstatus/issues/83.
