### ISSUE TITLE
gitstatus failed in some repositories

### ISSUE THREAD

**Issue by fei6409** [romkatv/gitstatus#103]
I've been using `powerlevel10k` for a while and everything was fine until yesterday. All in a sudden I found `gitstatus` failed to show anything in some specific repositories like this:  
![Screenshot from 2020-02-19 16-39-16](https://user-images.githubusercontent.com/6943703/74813243-679f7980-5338-11ea-9a0b-b18713d7248f.png)

As shown in snapshot, the first repository is under git's control but vcs is not working, and later status comes back after jumping to another one.

I've followed #102 and ran
`GITSTATUS_LOG_LEVEL=DEBUG GITSTATUS_NUM_THREADS=24 GITSTATUS_DAEMON=~/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-- gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 -a POWERLEVEL9K` but nothing showed.
[p10k.txt](https://github.com/romkatv/gitstatus/files/4223758/p10k.txt) is attach as well though I'm not sure if suitable in this case.

Extra random notes:
- Reinstalling `powerlevel10k` and restarting zsh doesn't help.
- Solely installed `gitstatus` and still got the same result, which proves `powerlevel10k` can be innocent here.
- The kernel repository is tremendous e.g. `git branch -a | wc -l` gives 3701, possibly related to performance or racing?

System information:
```
zsh:  5.7.1
uname: Linux 5.2.17-1rodete3-amd64 #1 SMP Debian 5.2.17-1rodete3 (2019-10-21 > 2018) x86_64 GNU/Linux
```

**Comment by romkatv** [comment]
This the top-level repository public? How do I clone it?

**Comment by fei6409** [comment]
Thanks for the swift reply! You can follow the [full instruction](https://chromium.googlesource.com/chromiumos/docs/+/master/developer_guide.md) if needed.  
As we merely want the source here, I guess [installing depot_tools](https://chromium.googlesource.com/chromiumos/docs/+/master/developer_guide.md#install-depot_tools) then [get the source](https://chromium.googlesource.com/chromiumos/docs/+/master/developer_guide.md#get-the-source) should be enough (hopefully).

**Comment by romkatv** [comment]
I checked out the sourced (took a while!) and was able to reproduce this problem. This repository is using extensions. Git spec demands that any implementation that doesn't understand at least one key or value in the list of extensions must not proceed. gitstatusd doesn't understand any Git extensions, so it refuses to open this repository.

The extension this repository uses is called *preciousobjects*. It doesn't require anything from gitstatusd, so gitstatusd could open repositories with this extension without any issues. I'll change the code to this effect. Will post an update when done.

P.S.

That repo is not tiny but also not tremendous by any means. It takes gitstatusd 7 milliseconds to compute full Git status for it. Plain `git status` is only 4 times slower.

**Comment by fei6409** [comment]
Ah I see, didn't know extensions get involved here and great to learn that (also thanks for correcting my nonsense guess :P).  
Appreciate all the awesome effort!

**Comment by romkatv** [comment]
Fixed.

The ability to open repositories with `extensions.preciousobjects` is a new feature rather than a bug fix. Therefore, it doesn't warrant an emergency release of gitstatusd for all supported platforms. I can, however, release a new version for the platform you are using so that you don't have to wait indeterminate amount of time.

What OS are you using?

**Comment by fei6409** [comment]
Linux x86_64.

**Comment by romkatv** [comment]
> Linux x86_64.

Pushed. Once you update powerlevel10k and restart zsh, you should see Git status in prompt while in `~/chromiumos/src/third_party/kernel/v4.19`.

**Comment by fei6409** [comment]
Yes it's back, thanks again!

**Comment by romkatv** [comment]
Thanks for the confirmation!

By the way, your config looks like Pure Power? It's totally fine to use but I just wanted to make sure you know about the new configs. You can see some of the features here: https://github.com/romkatv/powerlevel10k#features. And you can play around with different configs by typing `p10k configure`.

**Comment by fei6409** [comment]
Yes it was Pure Power by the time I took that snapshot, and I've set up a new config via p10k wizard short after pulling latest powerlevel10k.  
Another cool and handy feature guiding users customize config with visualized prompt, love it.  :)
