### ISSUE TITLE
gitstatus failing to intialise

### ISSUE THREAD

**Issue by Jeklah** [romkatv/gitstatus#109]
As mentioned in the other comment, I'm having some wierd issues with gitstatus.
[gitstatusErr.txt](https://github.com/romkatv/gitstatus/files/4286916/gitstatusErr.txt)

I have no idea why it was failing to intiialise but is now working after re-compiling a few times, following the same instructions each time...
I have found a fix, although I'm not sure why it works. After compiling and copying it to the correct dir, and setting GITSTATUS_DAEMON, I source .zshrc and it works. I run zsh and it stops working? I run source .zshrc and it works again.
I don't understand this as it was my understanding that whenever a new zsh is launched, it ran .zshrc.

**Comment by romkatv** [comment]
Please try the following.

1. Undo everything you've tried. If you have built any custom binaries, delete them. If you have defined any `GITSTATUS` parameters, remove them.
2. Update powerlevel10k to the latest version.

Can you still reproduce the issue? If so, please post the error message.

**Comment by Jeklah** [comment]
That was with a freshly updated powerlevel10k.

**Comment by romkatv** [comment]
The logs you've posted contain calls to function `gitstatus_start_impl`. There is no such function in the latest version of powerlevel10k.

**Comment by Jeklah** [comment]
Ok I will try and reproduce on a VM when I'm not at work. Don't want to mess up a working config on work laptop now it is finally working haha. I guess I must have been using an old version of powerlevel10k.

**Comment by Jeklah** [comment]
I can confirm it still only starts working after running source .zshrc.

**Comment by romkatv** [comment]
> Can you still reproduce the issue? If so, please post the error message.

Please ☝️

**Comment by Jeklah** [comment]
I will try when I get home from work.

**Comment by Jeklah** [comment]
> 
> 
> Please try the following.
> 
>     1. Undo everything you've tried. If you have built any custom binaries, delete them. If you have defined any `GITSTATUS` parameters, remove them.
> 
>     2. Update powerlevel10k to the latest version.
> 
> 
> Can you still reproduce the issue? If so, please post the error message.

I tried the above and cannot reproduce the issue. Thanks for the good work!

**Comment by romkatv** [comment]
Great!

FWIW, I haven't fixed anything. It doesn't seem like anything was broken in powerlevel10k or gitstatus.
