### ISSUE TITLE
gitstatus failed to initialize.

### ISSUE THREAD

**Issue by xgs0921** [romkatv/gitstatus#115]
Your Git prompt may disappear or become slow.

  The content of /private/var/folders/kf/60hr97rd5rz6z41jb7fddmwh0000gn/T/gitstatus.POWERLEVEL9K.501.6396.1585547124.2.xtrace.log (gitstatus_start xtrace):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/kf/60hr97rd5rz6z41jb7fddmwh0000gn/T/gitstatus.POWERLEVEL9K.501.6396.1585547124.2.lock
    +(anon):15> [[ 13 == <1-> ]]
    +(anon):17> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> '(anon)' /dev/fd/15
    +(anon):1> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=6481'
    +(anon):2> sysopen -r -o cloexec -u resp_fd -- /dev/fd/15
    +(anon):3> [[ 17 == <1-> ]]
    +(anon):4> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):120> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):123> ((  ! async  ))
    +(anon):124> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):126> local pgid
    +(anon):127> ((  0 < 20  ))
    +(anon):128> [[ -t 17 ]]
    +(anon):129> sysread -s 20 -t 5.0000000000 -i 17 'pgid[$#pgid+1]'
    +(anon):129> return
                         ^ this command failed (5)

  The content of /private/var/folders/kf/60hr97rd5rz6z41jb7fddmwh0000gn/T/gitstatus.POWERLEVEL9K.501.6396.1585547124.2.daemon.log (gitstatus daemon log):

    +(anon):22> local pgid=6481
    +(anon):23> [[ 6481 == <1-> ]]
    +(anon):104> ((  lock_fd == -1  ))
    +(anon):27> trap '' PIPE
    +(anon):29> [[ -z '' ]]
    +(anon):30> local kernel
    +(anon):107> zsystem flock -- /private/var/folders/kf/60hr97rd5rz6z41jb7fddmwh0000gn/T/gitstatus.POWERLEVEL9K.501.6396.1585547124.2.lock
    +(anon):31> kernel=+(anon):31> uname -s
    +(anon):31> kernel=darwin
    +(anon):32> [[ -n darwin ]]
    +(anon):35> [[ '' == /* ]]
    +(anon):37> ((  0  ))
    +(anon):39> [[ -n '' ]]
    +(anon):42> local -aU os
    +(anon):43> case darwin (linux)
    +(anon):43> case darwin (cygwin_nt-*)
    +(anon):43> case darwin (mingw* | msys*)
    +(anon):43> case darwin (*)
    +(anon):50> os=( darwin )
    +(anon):52> local arch
    +(anon):53> arch=+(anon):53> uname -m
    +(anon):53> arch=x86_64
    +(anon):54> [[ -n x86_64 ]]
    +(anon):55> local daemons=( /Users/guisheng/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-x86_64 /Users/guisheng/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-x86_64-static /Users/guisheng/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 /Users/guisheng/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static )
    +(anon):59> local files=( )
    +(anon):60> daemons=( )
    +(anon):62> ((  stderr_fd && 0 != 0  ))
    +(anon):72> ((  0  ))
    +(anon):72> return
    +(anon):99> local -i ret=1
    +(anon):100> kill -- -6481

  Your system information:

    zsh:      5.7.1
    uname -a: Darwin a-MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Comment by romkatv** [comment]
Please post the output of the following command:

```zsh
() {
  emulate -L zsh -o xtrace
  local dir='/Users/guisheng/.oh-my-zsh/custom/themes/powerlevel10k'
  command git -C $dir status
  command git -C $dir rev-parse HEAD
  command ls -l -- $dir $dir/gitstatus $dir/gitstatus/bin
}
```

**Comment by romkatv** [comment]
Have you managed to solve this problem? Would you mind posting a short explanation for the benefit of future users?

**Comment by xgs0921** [comment]
reload install.
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
Set ZSH_THEME="powerlevel10k/powerlevel10k" in ~/.zshrc.

The reason is that I downloaded the zip package manually

**Comment by romkatv** [comment]
Thanks for the details.
