### ISSUE TITLE
[ERROR]: gitstatus failed to initialize

### ISSUE THREAD

**Issue by bryangreener** [romkatv/gitstatus#116]
### Environment
Linux raspberrypi 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l GNU/Linux

Using oh-my-zsh with powerlevel10k inside
`/home/pi/.oh-my-zsh/custom/themes/`
and within ~/.zshrc I have 
`ZSH_THEME="powerlevel10k/powerlevel10k"`

### Error Message
![image](https://user-images.githubusercontent.com/16657209/78933908-ffd3f800-7a77-11ea-961e-9f7c3b82e0ce.png)

### Debug Info
![image](https://user-images.githubusercontent.com/16657209/78933932-0a8e8d00-7a78-11ea-8973-23c53fefeeb1.png)
![image](https://user-images.githubusercontent.com/16657209/78933948-137f5e80-7a78-11ea-9ad3-19a347f9259a.png)

### Additional Debug Info
As requested in #115 

![image](https://user-images.githubusercontent.com/16657209/78933987-25610180-7a78-11ea-94d0-514110e109e3.png)
                       

Please let me know if there is anything else you'd like me to test.

**Comment by romkatv** [comment]
I don't build binaries for armv6l. You can build one yourself off you like. The instructions are on the homepage.

**Comment by bryangreener** [comment]
> I don't build binaries for armv6l. You can build one yourself off you like. The instructions are on the homepage.

Ah okay thank you. I saw that you updated for armv7l but wasn't sure if that was the cutoff. I'll look into that. :D

**Comment by romkatv** [comment]
I've added `gitstatusd-linux-armv6l`. Please give it a try.

```zsh
() {
  emulate -L zsh -o err_return
  local dir=/home/pi/.oh-my-zsh/custom/themes/powerlevel10k
  rm -rf -- $dir/gitstatus/usrbin
  git -C $dir pull
  exec zsh
}
```

**Comment by bryangreener** [comment]
Works like a charm. No further errors or warnings. Thank you for your additional help even after closing this issue.
