### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by sevenday4** [romkatv/gitstatus#117]
[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  The content of /tmp/gitstatus.POWERLEVEL9K.1000.1431.1587333161.1.xtrace.log (gitstatus_start xtrace):

    +(anon):7> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):8> [[ -r /proc/version && 'Linux version 5.6.4-zen1-1-zen (linux-zen@archlinux) (gcc version 9.3.0 (Arch Linux 9.3.0-1)) #1 ZEN SMP PREEMPT Mon, 13 Apr 2020 12:21:24 +0000' == *Microsoft* ]]
    +(anon):11> print -rn
    +(anon):12> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.1000.1431.1587333161.1.lock
    +(anon):13> [[ 17 == <1-> ]]
    +(anon):15> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):18> '(anon)' /proc/self/fd/19
    +(anon):1> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=1453'
    +(anon):2> sysopen -r -o cloexec -u resp_fd -- /proc/self/fd/19
    +(anon):3> [[ 21 == <1-> ]]
    +(anon):4> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):118> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):121> ((  ! async  ))
    +(anon):7> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):121> ((  ! async  ))
    +(anon):122> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):124> local pgid
    +(anon):125> ((  0 < 20  ))
    +(anon):126> [[ -t 21 ]]
    +(anon):127> sysread -s 20 -t 5.0000000000 -i 21 'pgid[$#pgid+1]'
    +(anon):127> return
                         ^ this command failed (5)

  The content of /tmp/gitstatus.POWERLEVEL9K.1000.1431.1587333161.1.daemon.log (gitstatus daemon log):

    +(anon):20> local pgid=1453
    +(anon):21> [[ 1453 == <1-> ]]
    +(anon):102> ((  lock_fd == -1  ))
    +(anon):25> trap '' PIPE
    +(anon):27> [[ -z '' ]]
    +(anon):28> local kernel
    +(anon):105> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.1000.1431.1587333161.1.lock
    +(anon):29> kernel=+(anon):29> uname -s
    +(anon):29> kernel=linux 
    +(anon):30> [[ -n linux ]]
    +(anon):33> [[ '' == /* ]]
    +(anon):35> ((  0  ))
    +(anon):37> [[ -n '' ]]
    +(anon):40> local -aU os
    +(anon):41> case linux (linux)
    +(anon):43> os=+(anon):43> uname -o
    +(anon):43> os=( gnu/linux ) 
    +(anon):44> [[ gnu/linux == android ]]
    +(anon):44> os=( linux ) 
    +(anon):50> local arch
    +(anon):51> arch=+(anon):51> uname -m
    +(anon):51> arch=x86_64 
    +(anon):52> [[ -n x86_64 ]]
    +(anon):53> local daemons=( /home/sevenday4/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-x86_64 /home/sevenday4/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-x86_64-static /home/sevenday4/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 /home/sevenday4/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static )
    +(anon):57> local files=( /home/sevenday4/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 /home/sevenday4/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static )
    +(anon):58> daemons=( ) 
    +(anon):60> ((  stderr_fd && 0 != 2  ))
    +(anon):61> unsetopt xtrace
    
    ERROR: missing execute permissions on gitstatusd file(s):
    
      /home/sevenday4/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64
      /home/sevenday4/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static
    
    +(anon):70> ((  0  ))
    +(anon):70> return
    +(anon):97> local -i ret=1
    +(anon):98> kill -- -1453

  Your system information:

    zsh:      5.8
    uname -a: Linux Guys-pc 5.6.4-zen1-1-zen #1 ZEN SMP PREEMPT Mon, 13 Apr 2020 12:21:24 +0000 x86_64 GNU/Linux

  If you need help, open an issue and attach this whole error message to it

**Comment by romkatv** [comment]
See the `ERROR` line in the message you've posted.
