### ISSUE TITLE
Add brew installation

### ISSUE THREAD

**Issue by vaxXxa** [romkatv/gitstatus#118]
Will be very useful to get possibility to install `gitstatus` by `brew`:

```bash
$ brew install gitstatus
```

**Comment by romkatv** [comment]
I acknowledge the feature request. It's on my TODO list but no ETA yet. Could be months.

Just to clarify, you want to use gitstatus from bash, right?

**Comment by vaxXxa** [comment]
Right, from bash/zsh. And maybe I will use your tool in my status-line or like separated command, instead of `git status`.

Oh, I'm currently using `powerlevel9k/powerlevel9k` and maybe I must migrate to `powerlevel10k` :)

**Comment by romkatv** [comment]
> Right, from bash/zsh.

If you want to use it from zsh, then it's much better to use powerlevel10k instead. It can even be installed with brew.

> Oh, I'm currently using `powerlevel9k/powerlevel9k` and maybe I must migrate to `powerlevel10k` :)

Maybe.

**Comment by romkatv** [comment]
Done: https://github.com/romkatv/homebrew-gitstatus.

**Comment by vaxXxa** [comment]
@romkatv Cool, thanks.

One more question: If I use `Powerlevel10k`, I don't need to install `gitstatus` apart (after `Powerlevel10k` installation)?

**Comment by romkatv** [comment]
> One more question: If I use `Powerlevel10k`, I don't need to install `gitstatus` apart (after `Powerlevel10k` installation)?

Correct.
