### ISSUE TITLE
zsh+powerlevel10k on an ASUS router

### ISSUE THREAD

**Issue by kurktchiev** [romkatv/gitstatus#120]
So I run an ASUS router which basically uses a slightly different arch and it seems gitstatus is having a hard time with something (could be a missing command as I had to install mktemp and unlink from Entware to get configuration to work)

  The content of /tmp/gitstatus.POWERLEVEL9K.0.2425.1588334426.3.xtrace.log (gitstatus_start xtrace):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 2.6.36.4brcmarm (merlin@ubuntu-dev) (gcc version 4.5.3 (Buildroot 2012.02) ) #1 SMP PREEMPT Sat Apr 25 22:35:50 EDT 2020' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.0.2425.1588334426.3.lock
    +(anon):15> [[ 13 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):19> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=2459'
    +(anon):21> [[ -n '' ]]
    +(anon):42> sysopen -r -o cloexec -u resp_fd /proc/self/fd/12
    +(anon):45> [[ 15 == <1-> ]]
    +(anon):46> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):42> _gitstatus_daemon
    +(anon):47> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):50> ((  ! async  ))
    +(anon):51> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):53> local pgid
    +(anon):54> ((  0 < 20  ))
    +(anon):55> [[ -t 15 ]]
    +(anon):56> sysread -s 20 -t 5.0000000000 -i 15 'pgid[$#pgid+1]'
    +(anon):54> ((  20 < 20  ))
    +(anon):58> [[ '                2601' == \ #<1-> ]]
    +(anon):59> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):61> sysopen -w -o cloexec -u req_fd -- /tmp/gitstatus.POWERLEVEL9K.0.2425.1588334426.3.fifo
    +(anon):62> [[ 14 == <1-> ]]
    +(anon):63> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):74> zle -F 15 _gitstatus_process_response_POWERLEVEL9K
    +(anon):85> add-zsh-hook zshexit _gitstatus_cleanup_POWERLEVEL9K
    +add-zsh-hook:15> emulate -L zsh
    +add-zsh-hook:17> local -a hooktypes
    +add-zsh-hook:18> hooktypes=( chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name )
    +add-zsh-hook:22> local usage='Usage: add-zsh-hook hook function\nValid hooks are:\n  chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name'
    +add-zsh-hook:24> local opt
    +add-zsh-hook:25> local -a autoopts
    +add-zsh-hook:26> integer del list help
    +add-zsh-hook:28> getopts dDhLUzk opt
    +add-zsh-hook:55> shift 0
    +add-zsh-hook:57> ((  list  ))
    +add-zsh-hook:60> ((  help || 2 != 2 || 6 == 0  ))
    +add-zsh-hook:65> local hook=zshexit_functions
    +add-zsh-hook:66> local fn=_gitstatus_cleanup_POWERLEVEL9K
    +add-zsh-hook:68> ((  del  ))
    +add-zsh-hook:83> ((  0  ))
    +add-zsh-hook:89> typeset -ga zshexit_functions
    +add-zsh-hook:90> set -A zshexit_functions _gitstatus_cleanup_POWERLEVEL9K
    +add-zsh-hook:92> autoload -- _gitstatus_cleanup_POWERLEVEL9K
    +(anon):90> print -nru 14 -- $'hello\C-_\C-^'
    +(anon):91> local expected=$'hello\C-_0\C-^' actual
    +(anon):92> ((  0 < 8  ))
    +(anon):93> [[ -t 15 ]]
    +(anon):94> sysread -s 8 -t 5.0000000000 -i 15 'actual[$#actual+1]'
    +(anon):94> return
                         ^ this command failed (5)

  The content of /tmp/gitstatus.POWERLEVEL9K.0.2425.1588334426.3.daemon.log (gitstatus daemon log):

    +_gitstatus_daemon:3> local pgid=2601
    +_gitstatus_daemon:4> [[ 2601 == <1-> ]]
    +_gitstatus_daemon:87> ((  lock_fd == -1  ))
    +_gitstatus_daemon:8> trap '' PIPE
    +_gitstatus_daemon:10> [[ -z '' ]]
    +_gitstatus_daemon:11> local kernel
    +_gitstatus_daemon:90> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.0.2425.1588334426.3.lock
    +_gitstatus_daemon:12> kernel=+_gitstatus_daemon:12> uname -s
    +_gitstatus_daemon:12> kernel=linux
    +_gitstatus_daemon:13> [[ -n linux ]]
    +_gitstatus_daemon:16> [[ '' == /* ]]
    +_gitstatus_daemon:18> ((  0  ))
    +_gitstatus_daemon:20> [[ -n '' ]]
    +_gitstatus_daemon:23> local -aU os=( linux )
    +_gitstatus_daemon:24> case linux (linux)
    +_gitstatus_daemon:26> local os_flavor
    +_gitstatus_daemon:27> os_flavor=+_gitstatus_daemon:27> uname -o
    +_gitstatus_daemon:27> os_flavor=asuswrt-merlin
    +_gitstatus_daemon:27> os+=( )
    +_gitstatus_daemon:34> local arch
    +_gitstatus_daemon:35> arch=+_gitstatus_daemon:35> uname -m
    +_gitstatus_daemon:35> arch=armv7l
    +_gitstatus_daemon:36> [[ -n armv7l ]]
    +_gitstatus_daemon:37> local daemons=( /tmp/mnt/usb_stick/entware/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-armv7l /tmp/mnt/usb_stick/entware/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-armv7l-static /tmp/mnt/usb_stick/entware/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-armv7l /tmp/mnt/usb_stick/entware/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-armv7l-static )
    +_gitstatus_daemon:41> local files=( /tmp/mnt/usb_stick/entware/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-armv7l )
    +_gitstatus_daemon:42> daemons=( /tmp/mnt/usb_stick/entware/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-armv7l )
    +_gitstatus_daemon:44> ((  stderr_fd && 1 != 1  ))
    +_gitstatus_daemon:54> ((  1  ))
    +_gitstatus_daemon:56> [[ '' == <1-> ]]
    +_gitstatus_daemon:59> local cpus
    +_gitstatus_daemon:60> ((  ! 0  ))
    +_gitstatus_daemon:62> ((  ! 0  ))
    +_gitstatus_daemon:63> cpus=8
    +_gitstatus_daemon:66> args+=( -t 16 )
    +_gitstatus_daemon:69> mkfifo -- /tmp/gitstatus.POWERLEVEL9K.0.2425.1588334426.3.fifo
    +_gitstatus_daemon:70> print -rn -- '                2601'
    +_gitstatus_daemon:72> zf_rm -- /tmp/gitstatus.POWERLEVEL9K.0.2425.1588334426.3.fifo
    +_gitstatus_daemon:74> local daemon
    +_gitstatus_daemon:75> daemon=/tmp/mnt/usb_stick/entware/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-armv7l
    +_gitstatus_daemon:76> /tmp/mnt/usb_stick/entware/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-armv7l -s 1 -u 1 -d 1 -c 1 -m -1 -v DEBUG -t 16
    +_gitstatus_daemon:77> local -i ret=132
    +_gitstatus_daemon:78> ((  ret == 0 || ret == 10 || ret > 128  ))
    +_gitstatus_daemon:78> return ret
    +_gitstatus_daemon:81> local -i ret=132
    +_gitstatus_daemon:82> zf_rm -f -- /tmp/gitstatus.POWERLEVEL9K.0.2425.1588334426.3.lock /tmp/gitstatus.POWERLEVEL9K.0.2425.1588334426.3.fifo
    +_gitstatus_daemon:83> kill -- -2601

  Your system information:

    zsh:      5.7.1
    uname -a: Linux RT-AC68R-29F0 2.6.36.4brcmarm #1 SMP PREEMPT Sat Apr 25 22:35:50 EDT 2020 armv7l ASUSWRT-Merlin

**Comment by romkatv** [comment]
Does armv6l work?

```zsh
/tmp/mnt/usb_stick/entware/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-armv6l
```

**Comment by kurktchiev** [comment]
I think it needs sf. here is opkg.conf:
src/gz entware http://bin.entware.net/armv7sf-k2.6
dest root /
dest ram /opt/tmp
lists_dir ext /opt/var/opkg-lists
option tmp_dir /opt/tmp
arch all 100
arch armv7soft 150
arch armv7-2.6 160

**Comment by kurktchiev** [comment]
Yeah 
```
12:07:25 admin@RT-AC68R-29F0 ~
❯ /tmp/mnt/usb_stick/entware/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-armv6l

[1]    4892 illegal hardware instruction
```

**Comment by romkatv** [comment]
> I think it needs sf. here is opkg.conf:

I don't understand this comment.

Your firs log indicates that the armv7l binary crashes with SIGILL. Your last comments indicates that the armv6l binary also crashes with SIGILL.

If you really need Git status in your prompt when connected to the router, you might need to tinker with gitstatus. If you figure out how to make it work, please let me know.

**Comment by romkatv** [comment]
> Yeah the arch miight be the problem

I don't understand this comment.

**Comment by kurktchiev** [comment]
firing up gitstatus on its own just sigkills with HW instruction failure: [1]    4892 illegal hardware instruction

**Comment by romkatv** [comment]
Yes, I see that from the logs you've posted.

**Comment by kurktchiev** [comment]
Yeah what i guess I am saying is that it needs a slightly different arch compile. I am not sure what the difference between armv6l and armv6sf are.

**Comment by romkatv** [comment]
Unless the binary is corrupted, the error indicates that the CPU doesn't support the common subset of the ARMv7-A, ARMv7-R and ARMv7-M CPU architectures. Given that `uname -m` says `armv7l`, this is surprising.

I don't know what armv7sf is. To the best of my knowledge, there is no ARM architecture with this or similar name. Maybe sf indicates the absence of some instructions. Or maybe it's something else.

FWIW, if you have a bit of experience with GCC, gdb and assembler, it shouldn't be difficult to figure out what's going on and to build gistatusd that works on the router. Granted, you probably don't want to run gitstatusd on the router in the first place.
