### ISSUE TITLE
Git diverged status

### ISSUE THREAD

**Issue by jregistr** [romkatv/gitstatus#121]
Hello,
I'm wondering if there'd be any interest in adding branch diverged status.

I see we have VCS_STATUS_COMMITS_BEHIND and VCS_STATUS_COMMITS_AHEAD. Now I'm wondering if we could add the one where the upstream branch and local have different commits. This would be useful for the case where the branch was rebased by someone else.

Does this currently exist in this package and I'm just skipping it?

Thank you!

**Comment by romkatv** [comment]
In git parlance "diverged" means local branch is both behind and ahead of the remote. This is displayed by powerlevel10k as a two arrows (one pointing down, another pointing up). Are you thinking of something else?

**Comment by jregistr** [comment]
aaaah, I see it now. I was specifically searching for diverged in the config file.
Great! That's exactly what I was looking for!

**Comment by jregistr** [comment]
Thank You! I'll go ahead and close this 😄
