### ISSUE TITLE
Versions after 1.0.0 still report 1.0.0 as the version number

### ISSUE THREAD

**Issue by bdesham** [romkatv/gitstatus#126]
If I check out the `v1.1.0` tag, build the project, and then run `gitstatusd --version`, the version reported is still “v1.0.0”. It seems like build.info and maybe install.info need to be updated.

I would have just submitted a pull request but I’m not sure how you generate the digests/hashes in install.info 🙂

**Comment by romkatv** [comment]
This is expected. gitstatusd doesn't change often. You can see in [releases](https://github.com/romkatv/gitstatus/releases) that there are no binaries except in v1.0.0. All releases after that only have changes in shell bindings, infrastructure and docs. So your binary is indeed still v1.0.0, but your shell bindings know to expect exactly this. What shell bindings expect on different platforms is specified in [install.info](https://github.com/romkatv/gitstatus/blob/master/install.info).

**Comment by bdesham** [comment]
Got it, thanks.
