### ISSUE TITLE
Fails on MacOS 10.15.4 with -bash: ${uname_sm,,}: bad substitution

### ISSUE THREAD

**Issue by esprehn** [romkatv/gitstatus#131]
$ source /usr/local/opt/gitstatus/gitstatus.prompt.sh 
-bash: ${uname_sm,,}: bad substitution

System info:

Darwin MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

bash --version
GNU bash, version 5.0.17(1)-release (x86_64-apple-darwin19.4.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by esprehn** [comment]
Note if I comment out the failing substitution line it still fails with:

-bash: /var/folders/gy/md0zh85x0j7br98_lwsp9j0m0000gn/T//gitstatus.bash.72810.m1uQGhcBuh/req.fifo: Interrupted system call
gitstatus_start: failed to start gitstatusd

**Comment by romkatv** [comment]
> $ source /usr/local/opt/gitstatus/gitstatus.prompt.sh
> -bash: ${uname_sm,,}: bad substitution

This happens when you use a very old version of bash.

> bash --version
> GNU bash, version 5.0.17(1)-release (x86_64-apple-darwin19.4.0)

Apparently you have a new version of bash in addition to the very old one. I suggest that you use the new version then.

You can make it your login shell with this command:

```shell
chsh -s "$(which bash)"
```
