### ISSUE TITLE
Undocumented status

### ISSUE THREAD

**Issue by kellyelton** [romkatv/gitstatus#132]
For a status I'm seeing `mybranch am 1/1` but I don't see anything in the README about what `am 1/1` means.

**Comment by romkatv** [comment]
You haven't posted enough information to answer the question. My best guess is that your git repository is in state `GIT_REPOSITORY_STATE_APPLY_MAILBOX`.

Please reopen if I haven't answered your question. If you do, ask a question I can answer.

**Comment by kellyelton** [comment]
I don't understand. I'm explaining that the documentation doesn't explain what `am 1/1` means. That's my question. I'm not sure why you can't answer it, didn't you write this application? That text must be coming from somewhere.

**Comment by romkatv** [comment]
It is what it is. Sorry that my answer wasn’t helpful.

**Comment by kellyelton** [comment]
You don't think that it would be beneficial to document it, considering you have lots of good documentation already?

**Comment by romkatv** [comment]
No.
