### ISSUE TITLE
gitstatus_start fails to execute

### ISSUE THREAD

**Issue by ahmubashshir** [romkatv/gitstatus#133]
[gitstatus.ls.1000.772527.1589949153.3.daemon.log](https://github.com/romkatv/gitstatus/files/4654635/gitstatus.ls.1000.772527.1589949153.3.daemon.log)

**Comment by romkatv** [comment]
I see that you have gitstatus in `/usr/share/zsh/plugins/gitstatus`. How did you install it?

**Comment by ahmubashshir** [comment]
from AUR

**Comment by romkatv** [comment]
It's not my AUR. And it's apparently broken. If you care, point the AUR owner to this documentation: https://github.com/romkatv/gitstatus/blob/master/README.md#compiling-for-distribution.

In the meantime you'll have to use a different installation method. E.g., the time-honored:

```zsh
git clone --depth=1 https://github.com/romkatv/gitstatus.git ~/gitstatus
```
