### ISSUE TITLE
Error after installing powerlevel with gitstatus on MacOS

### ISSUE THREAD

**Issue by harshasrikara** [romkatv/gitstatus#136]
[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  The content of /private/var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T/gitstatus.POWERLEVEL9K.501.84343.1590007367.1.xtrace.log (gitstatus_start xtrace):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T/gitstatus.POWERLEVEL9K.501.84343.1590007367.1.lock
    +(anon):15> [[ 17 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ -n '' ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /dev/fd/16
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=84346'
    +(anon):46> [[ 19 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 19 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 19 'pgid[$#pgid+1]'
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '               84346' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /private/var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T/gitstatus.POWERLEVEL9K.501.84343.1590007367.1.fifo
    +(anon):63> [[ 18 == <1-> ]]
    +(anon):64> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):66> print -nru 18 -- $'hello\C-_\C-^'
    +(anon):67> local expected=$'hello\C-_0\C-^' actual
    +(anon):68> ((  1  ))
    +(anon):68> [[ ! -t 1 && ! -t 0 ]]
    +(anon):69> local -F deadline='EPOCHREALTIME + 4'
    +(anon):73> true
    +(anon):74> [[ -t 19 ]]
    +(anon):75> sysread -s 1 -t 5.0000000000 -i 19 actual
    +(anon):76> [[ . == h ]]
    +(anon):77> [[ . == . ]]
    +(anon):78> ((  EPOCHREALTIME < deadline  ))
    +(anon):78> continue
    +(anon):73> true
    +(anon):74> [[ -t 19 ]]
    +(anon):75> sysread -s 1 -t 5.0000000000 -i 19 actual
    +(anon):76> [[ . == h ]]
    +(anon):77> [[ . == . ]]
    +(anon):78> ((  EPOCHREALTIME < deadline  ))
    +(anon):78> continue
    +(anon):73> true
    +(anon):74> [[ -t 19 ]]
    +(anon):75> sysread -s 1 -t 5.0000000000 -i 19 actual
    +(anon):76> [[ . == h ]]
    +(anon):77> [[ . == . ]]
    +(anon):78> ((  EPOCHREALTIME < deadline  ))
    +(anon):78> continue
    +(anon):73> true
    +(anon):74> [[ -t 19 ]]
    +(anon):75> sysread -s 1 -t 5.0000000000 -i 19 actual
    +(anon):75> return
                         ^ this command failed (5)

  The content of /private/var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T/gitstatus.POWERLEVEL9K.501.84343.1590007367.1.daemon.log (gitstatus daemon log):

    +_gitstatus_daemon_p9k_:3> local pgid=84346
    +_gitstatus_daemon_p9k_:4> [[ 84346 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:78> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:81> zsystem flock -- /private/var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T/gitstatus.POWERLEVEL9K.501.84343.1590007367.1.lock
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='darwin x86_64'
    +_gitstatus_daemon_p9k_:13> [[ 'darwin x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=darwin
    +_gitstatus_daemon_p9k_:15> local uname_m=x86_64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:21> [[ darwin == linux ]]
    +_gitstatus_daemon_p9k_:22> cpus=+_gitstatus_daemon_p9k_:22> sysctl -n hw.ncpu
    +_gitstatus_daemon_p9k_:22> cpus=12
    +_gitstatus_daemon_p9k_:27> args+=( -t 24 )
    +_gitstatus_daemon_p9k_:30> mkfifo -- /private/var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T/gitstatus.POWERLEVEL9K.501.84343.1590007367.1.fifo
    +_gitstatus_daemon_p9k_:31> print -rnu 13 -- '               84346'
    +_gitstatus_daemon_p9k_:33> zf_rm -- /private/var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T/gitstatus.POWERLEVEL9K.501.84343.1590007367.1.fifo
    +_gitstatus_daemon_p9k_:35> local _gitstatus_zsh_daemon _gitstatus_zsh_version _gitstatus_zsh_downloaded
    +_gitstatus_daemon_p9k_:43> local gitstatus_plugin_dir_var=_gitstatus_plugin_dir_p9k_
    +_gitstatus_daemon_p9k_:44> local gitstatus_plugin_dir=/Users/harshasrikara/powerlevel10k/gitstatus
    +_gitstatus_daemon_p9k_:45> set -- -d /Users/harshasrikara/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_daemon_p9k_:47> [[ 1 == (|-|+)<1-> ]]
    +_gitstatus_daemon_p9k_:48> source /Users/harshasrikara/powerlevel10k/gitstatus/install
    +/Users/harshasrikara/powerlevel10k/gitstatus/install:373> [ -z '' ']'
    +/Users/harshasrikara/powerlevel10k/gitstatus/install:374> _gitstatus_install_main /Users/harshasrikara/powerlevel10k/gitstatus -d /Users/harshasrikara/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:1> [ -n 5.7.1 ']'
    +_gitstatus_install_main:2> emulate -L sh -o no_unset
    +_gitstatus_install_main:7> local argv1=/Users/harshasrikara/powerlevel10k/gitstatus
    +_gitstatus_install_main:8> shift
    +_gitstatus_install_main:10> local no_check='' no_install='' uname_s='' uname_m='' gitstatus_dir='' dl_status=''
    +_gitstatus_install_main:11> local opt='' OPTARG='' OPTIND=1
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/harshasrikara/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case d (h)
    +_gitstatus_install_main:14> case d (n)
    +_gitstatus_install_main:14> case d (f)
    +_gitstatus_install_main:14> case d (d)
    +_gitstatus_install_main:54> [ -n '' ']'
    +_gitstatus_install_main:58> [ -z /Users/harshasrikara/powerlevel10k/gitstatus ']'
    +_gitstatus_install_main:62> gitstatus_dir=/Users/harshasrikara/powerlevel10k/gitstatus
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/harshasrikara/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case s (h)
    +_gitstatus_install_main:14> case s (n)
    +_gitstatus_install_main:14> case s (f)
    +_gitstatus_install_main:14> case s (d)
    +_gitstatus_install_main:14> case s (p)
    +_gitstatus_install_main:14> case s (m)
    +_gitstatus_install_main:14> case s (s)
    +_gitstatus_install_main:87> [ -n '' ']'
    +_gitstatus_install_main:91> [ -z darwin ']'
    +_gitstatus_install_main:95> uname_s=darwin
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/harshasrikara/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case m (h)
    +_gitstatus_install_main:14> case m (n)
    +_gitstatus_install_main:14> case m (f)
    +_gitstatus_install_main:14> case m (d)
    +_gitstatus_install_main:14> case m (p)
    +_gitstatus_install_main:14> case m (m)
    +_gitstatus_install_main:76> [ -n '' ']'
    +_gitstatus_install_main:80> [ -z x86_64 ']'
    +_gitstatus_install_main:84> uname_m=x86_64
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/harshasrikara/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case p (h)
    +_gitstatus_install_main:14> case p (n)
    +_gitstatus_install_main:14> case p (f)
    +_gitstatus_install_main:14> case p (d)
    +_gitstatus_install_main:14> case p (p)
    +_gitstatus_install_main:65> [ -n '' ']'
    +_gitstatus_install_main:69> [ -z 'printf . >&13' ']'
    +_gitstatus_install_main:73> dl_status='printf . >&13'
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/harshasrikara/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:103> shift 9
    +_gitstatus_install_main:105> : /Users/harshasrikara/powerlevel10k/gitstatus
    +_gitstatus_install_main:107> [ -n '' -a -n '' ']'
    +_gitstatus_install_main:112> [ -z darwin ']'
    +_gitstatus_install_main:116> [ -z x86_64 ']'
    +_gitstatus_install_main:121> local daemon=''
    +_gitstatus_install_main:122> local cache_dir=/Users/harshasrikara/.cache/gitstatus
    +_gitstatus_install_main:124> [ -z '' ']'
    +_gitstatus_install_main:125> [ -n '' ']'
    +_gitstatus_install_main:129> [ -z '' ']'
    +_gitstatus_install_main:130> daemon=/Users/harshasrikara/powerlevel10k/gitstatus/usrbin/gitstatusd
    +_gitstatus_install_main:131> [ ! -e /Users/harshasrikara/powerlevel10k/gitstatus/usrbin/gitstatusd ']'
    +_gitstatus_install_main:132> daemon=/Users/harshasrikara/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-x86_64
    +_gitstatus_install_main:133> [ ! -e /Users/harshasrikara/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-x86_64 ']'
    +_gitstatus_install_main:134> daemon=''
    +_gitstatus_install_main:138> [ -n '' ']'
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line='uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355";'
    +_gitstatus_install_main:155> [ -n 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355";' ']'
    +_gitstatus_install_main:157> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
    +_gitstatus_install_main:158> eval 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355";'
    +_gitstatus_install_main:158> uname_s_glob=cygwin_nt-10.0
    +_gitstatus_install_main:158> uname_m_glob=i686
    +_gitstatus_install_main:158> file=gitstatusd-darwin-x86_64
    +_gitstatus_install_main:158> version=v1.0.0
    +_gitstatus_install_main:158> sha256=c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355
    +_gitstatus_install_main:160> [ -z cygwin_nt-10.0 -o -z i686 -o -z gitstatusd-darwin-x86_64 -o -z v1.0.0 -o -z c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355 ']'
    +_gitstatus_install_main:169> case darwin (cygwin_nt-10.0)
    +_gitstatus_install_main:169> case darwin (*)
    +_gitstatus_install_main:171> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line='uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad";'
    +_gitstatus_install_main:155> [ -n 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad";' ']'
    +_gitstatus_install_main:157> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
    +_gitstatus_install_main:158> eval 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad";'
    +_gitstatus_install_main:158> uname_s_glob=cygwin_nt-10.0
    +_gitstatus_install_main:158> uname_m_glob=x86_64
    +_gitstatus_install_main:158> file=gitstatusd-darwin-x86_64
    +_gitstatus_install_main:158> version=v1.0.0
    +_gitstatus_install_main:158> sha256=d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad
    +_gitstatus_install_main:160> [ -z cygwin_nt-10.0 -o -z x86_64 -o -z gitstatusd-darwin-x86_64 -o -z v1.0.0 -o -z d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad ']'
    +_gitstatus_install_main:169> case darwin (cygwin_nt-10.0)
    +_gitstatus_install_main:169> case darwin (*)
    +_gitstatus_install_main:171> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line='uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a";'
    +_gitstatus_install_main:155> [ -n 'uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a";' ']'
    +_gitstatus_install_main:157> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
    +_gitstatus_install_main:158> eval 'uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a";'
    +_gitstatus_install_main:158> uname_s_glob=darwin
    +_gitstatus_install_main:158> uname_m_glob=x86_64
    +_gitstatus_install_main:158> file=gitstatusd-darwin-x86_64
    +_gitstatus_install_main:158> version=v1.0.0
    +_gitstatus_install_main:158> sha256=c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a
    +_gitstatus_install_main:160> [ -z darwin -o -z x86_64 -o -z gitstatusd-darwin-x86_64 -o -z v1.0.0 -o -z c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a ']'
    +_gitstatus_install_main:169> case darwin (darwin)
    +_gitstatus_install_main:173> case x86_64 (x86_64)
    +_gitstatus_install_main:180> [ -z '' ']'
    +_gitstatus_install_main:182> local daemon=/Users/harshasrikara/.cache/gitstatus/gitstatusd-darwin-x86_64
    +_gitstatus_install_main:183> [ -e /Users/harshasrikara/.cache/gitstatus/gitstatusd-darwin-x86_64 ']'
    +_gitstatus_install_main:187> daemon=/Users/harshasrikara/.cache/gitstatus/gitstatusd-darwin-x86_64-darwin-x86_64
    +_gitstatus_install_main:188> [ -e /Users/harshasrikara/.cache/gitstatus/gitstatusd-darwin-x86_64-darwin-x86_64 ']'
    +_gitstatus_install_main:205> [ -n '' ']'
    +_gitstatus_install_main:210> local daemon=/Users/harshasrikara/.cache/gitstatus/gitstatusd-darwin-x86_64
    +_gitstatus_install_main:212> [ -n '' ']'
    +_gitstatus_install_main:216> [ -d /Users/harshasrikara/.cache/gitstatus ']'
    +_gitstatus_install_main:218> local tmpdir
    +_gitstatus_install_main:219> command -v mktemp
    +_gitstatus_install_main:220> tmpdir=+_gitstatus_install_main:220> mktemp -d /var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T//gitstatus-install.XXXXXXXXXX
    +_gitstatus_install_main:220> tmpdir=/var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T//gitstatus-install.x9n96tsTh1
    +_gitstatus_install_main:226> [ -n 5.7.1 ']'
    +_gitstatus_install_main:227> cd -q -- /var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T//gitstatus-install.x9n96tsTh1
    +_gitstatus_install_main:232> local fetch
    +_gitstatus_install_main:233> command -v curl
    +_gitstatus_install_main:234> fetch='command curl -fsSLo'
    +_gitstatus_install_main:242> local url1=https://github.com/romkatv/gitstatus/releases/download/v1.0.0/gitstatusd-darwin-x86_64.tar.gz
    +_gitstatus_install_main:243> local url2=https://gitee.com/romkatv/gitstatus/raw/release-v1.0.0/release/gitstatusd-darwin-x86_64.tar.gz
    +_gitstatus_install_main:266> local sig='INT QUIT TERM ILL PIPE'
    +_gitstatus_install_main:286> local trapped=''
    +_gitstatus_install_main:287> trap 'trapped=1' INT QUIT TERM ILL PIPE
    +_gitstatus_install_main:288> fetch 1 https://github.com/romkatv/gitstatus/releases/download/v1.0.0/gitstatusd-darwin-x86_64.tar.gz
    +_gitstatus_install_main:289> local pid1=84381
    +fetch:1> local trapped=''
    +fetch:2> trap 'trapped=1' INT QUIT TERM ILL PIPE
    +fetch:3> [ 1 '!=' 1 ']'
    +_gitstatus_install_main:290> fetch 2 https://gitee.com/romkatv/gitstatus/raw/release-v1.0.0/release/gitstatusd-darwin-x86_64.tar.gz
    +_gitstatus_install_main:291> local pid2=84382
    +_gitstatus_install_main:293> local die='trap - INT QUIT TERM ILL PIPE; kill -- 84381 84382 2>/dev/null; exit 1'
    +fetch:1> local trapped=''
    +_gitstatus_install_main:294> trap 'trap - INT QUIT TERM ILL PIPE; kill -- 84381 84382 2>/dev/null; exit 1' INT QUIT TERM ILL PIPE
    +fetch:2> trap 'trapped=1' INT QUIT TERM ILL PIPE
    +_gitstatus_install_main:295> [ -z '' ']'
    +_gitstatus_install_main:297> local n=''
    +fetch:3> [ 2 '!=' 1 ']'
    +_gitstatus_install_main:298> true
    +fetch:7> local pid=84383
    +_gitstatus_install_main:299> [ -z 'printf . >&13' ']'
    +fetch:6> curl -fsSLo 1.tar.gz -- https://github.com/romkatv/gitstatus/releases/download/v1.0.0/gitstatusd-darwin-x86_64.tar.gz
    +_gitstatus_install_main:299> eval 'printf . >&13'
    +fetch:8> local die='trap - INT QUIT TERM ILL PIPE; kill -- 84383 2>/dev/null; exit 1'
    +fetch:3> command -v sleep
    +_gitstatus_install_main:299> printf .
    +fetch:9> trap 'trap - INT QUIT TERM ILL PIPE; kill -- 84383 2>/dev/null; exit 1' INT QUIT TERM ILL PIPE
    +_gitstatus_install_main:300> command -v sleep
    +fetch:10> [ -z '' ']'
    +fetch:11> wait -- 84383
    +fetch:4> sleep 2
    +_gitstatus_install_main:301> sleep 1
    +fetch:12> local ret=77
    +fetch:13> echo -n
    +fetch:14> trap - INT QUIT TERM ILL PIPE
    +fetch:15> return 77
    +_gitstatus_install_main:305> [ -n 84381 -a -e 1.status ']'
    +_gitstatus_install_main:306> wait -- 84381
    +_gitstatus_install_main:307> local ret=77
    +_gitstatus_install_main:308> pid1=''
    +_gitstatus_install_main:309> [ 77 '=' 0 ']'
    +_gitstatus_install_main:313> [ -z 84382 ']'
    +_gitstatus_install_main:298> true
    +_gitstatus_install_main:299> [ -z 'printf . >&13' ']'
    +_gitstatus_install_main:299> eval 'printf . >&13'
    +_gitstatus_install_main:299> printf .
    +_gitstatus_install_main:300> command -v sleep
    +_gitstatus_install_main:301> sleep 1
    +fetch:7> local pid=84387
    +fetch:6> curl -fsSLo 2.tar.gz -- https://gitee.com/romkatv/gitstatus/raw/release-v1.0.0/release/gitstatusd-darwin-x86_64.tar.gz
    +fetch:8> local die='trap - INT QUIT TERM ILL PIPE; kill -- 84387 2>/dev/null; exit 1'
    +fetch:9> trap 'trap - INT QUIT TERM ILL PIPE; kill -- 84387 2>/dev/null; exit 1' INT QUIT TERM ILL PIPE
    +fetch:10> [ -z '' ']'
    +fetch:11> wait -- 84387
    +_gitstatus_install_main:305> [ -n '' -a -e 1.status ']'
    +_gitstatus_install_main:316> [ -n 84382 -a -e 2.status ']'
    +_gitstatus_install_main:298> true
    +_gitstatus_install_main:299> [ -z 'printf . >&13' ']'
    +_gitstatus_install_main:299> eval 'printf . >&13'
    +_gitstatus_install_main:299> printf .
    +_gitstatus_install_main:300> command -v sleep
    +_gitstatus_install_main:301> sleep 1
    +fetch:12> local ret=77
    +fetch:13> echo -n
    +fetch:14> trap - INT QUIT TERM ILL PIPE
    +fetch:15> return 77
    +_gitstatus_install_main:305> [ -n '' -a -e 1.status ']'
    +_gitstatus_install_main:316> [ -n 84382 -a -e 2.status ']'
    +_gitstatus_install_main:317> wait -- 84382
    +_gitstatus_install_main:318> local ret=77
    +_gitstatus_install_main:319> pid2=''
    +_gitstatus_install_main:320> [ 77 '=' 0 ']'
    +_gitstatus_install_main:324> [ -z '' ']'
    +_gitstatus_install_main:325> break
    +_gitstatus_install_main:330> trap - INT QUIT TERM ILL PIPE
    +_gitstatus_install_main:332> [ -z '' ']'
    +_gitstatus_install_main:333> echo '[gitstatus] error: failed to download gitstatusd from any mirror'
    [gitstatus] error: failed to download gitstatusd from any mirror
    +_gitstatus_install_main:334> echo ''

    +_gitstatus_install_main:335> echo '  1. https://github.com/romkatv/gitstatus/releases/download/v1.0.0/gitstatusd-darwin-x86_64.tar.gz'
      1. https://github.com/romkatv/gitstatus/releases/download/v1.0.0/gitstatusd-darwin-x86_64.tar.gz
    +_gitstatus_install_main:336> echo '  2. https://gitee.com/romkatv/gitstatus/raw/release-v1.0.0/release/gitstatusd-darwin-x86_64.tar.gz'
      2. https://gitee.com/romkatv/gitstatus/raw/release-v1.0.0/release/gitstatusd-darwin-x86_64.tar.gz
    +_gitstatus_install_main:337> exit 1
    +_gitstatus_install_main:356> local ret=1
    +_gitstatus_install_main:357> rm -rf -- /var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T//gitstatus-install.x9n96tsTh1
    +_gitstatus_install_main:358> [ 1 '=' 0 ']'
    +_gitstatus_install_main:358> return
    +_gitstatus_daemon_p9k_:48> return
    +_gitstatus_daemon_p9k_:72> local -i ret=1
    +_gitstatus_daemon_p9k_:73> zf_rm -f -- /private/var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T/gitstatus.POWERLEVEL9K.501.84343.1590007367.1.lock /private/var/folders/j9/8frlbp191blbz8312f3x2wbw0000gn/T/gitstatus.POWERLEVEL9K.501.84343.1590007367.1.fifo
    +_gitstatus_daemon_p9k_:74> kill -- -84346

  Your system information:

    zsh:      5.7.1
    uname -a: Darwin Harshas-MacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by romkatv** [comment]
This command doesn't work on your machine:

```zsh
curl -fsSLO https://github.com/romkatv/gitstatus/releases/download/v1.0.0/gitstatusd-darwin-x86_64.tar.gz
```

It returns error code 77, which according to `man curl` means:

> Problem with reading the SSL CA cert (path? access rights?).

**Comment by harshasrikara** [comment]
Thanks a lot! This actually helped in pointing me towards the right direction

**Comment by romkatv** [comment]
> Thanks a lot! This actually helped in pointing me towards the right direction

Could you share how you've fixed it?
