### ISSUE TITLE
[Help/Bug] All files modified in a repo with separate git dir

### ISSUE THREAD

**Issue by Syphdias** [romkatv/gitstatus#137]
I'm 70/30 that this is user error and not a bug. We talked about how [you](https://github.com/romkatv/dotfiles-public/blob/ae571837d2ab612397411608fa931bc89bb7e23a/.zshrc#L120-L126) handle [your](https://github.com/romkatv/dotfiles-public/blob/078e578482fbaa48bdc191333e55e571a0e3d9a0/dotfiles/bindings.zsh#L122-L139) dotfiles in other unrelated issues but I think it is better discussed here for find-ability.

I tired to copy some of your copy into my dotfiles but the gitstatus always marks every file as modified. To tell `vcs` where the git dir is I used `GIT_DIR=~/.config/dotgit/public`.

```
❯ git status                 
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit (use -u to show untracked files)
~ public master !121
❯ git add .viminfo 
~ public master +1 !122
❯ git status      
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .viminfo

Untracked files not listed (use -u option to show untracked files)
~ public master +1 !122
❯ git ls-files |wc -l
122
```

I copied the following functions, but I don't think they should have any impact on  the `vcs` segment. I even deleted my git dir and tried [your method of bootstrapping](https://github.com/romkatv/dotfiles-public/blob/b5b8dbc/bin/bootstrap-dotfiles.sh#L22-L30) with no change. Did I miss a crucial part in your config or does it look like a bug?

**Comment by Syphdias** [comment]
Possibly helpful
```
[2020-05-21 00:43:16 00007f9a304ffb20 DEBUG src/index.cc:156] Dirty candidate (unreadable): ".bashrc.d/"
[2020-05-21 00:43:16 00007f9a30790c78 INFO src/repo.cc:222] Found 37 dirty candidate(s) spanning from ".bashrc" to ".zshrc.d/"
[2020-05-21 00:43:16 00007f9a304dcb20 DEBUG src/repo.cc:310] git_diff_index_to_workdir from ".bashrc" to ".zshrc.d/"
[2020-05-21 00:43:16 00007f9a304dcb20 INFO src/repo.cc:260] Found unstaged file (deleted): ".bashrc"
```
I thought maybe permissions were at fault because files mostly have `0640` but changing that does not change the count, neither does deleting a file and checking it out again, e.g. `git checkout HEAD -- .bashrc` (tired umask 0027 and 0022)

**Comment by Syphdias** [comment]
Since you might ask for git config:
```
❯ git config --local -l |grep -v submo
core.repositoryformatversion=0
core.filemode=true
core.bare=false
status.showuntrackedfiles=no
remote.origin.url=ssh://git@example.com:1234/Syphdias/dotfiles-public.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```

**Comment by romkatv** [comment]
Try this:

```zsh
git --git-dir=$HOME/.config/dotgit/public config core.worktree $HOME
```

Also remove any `bare` mentions from the config. You can use `git --git-dir=$HOME/.config/dotgit/public config --edit` for that.

You also need to export `GIT_WORK_TREE`. Otherwise `git` commands will think your current directory is your work tree. For example, try `git status` without `GIT_WORK_TREE` when your current directory is not `$HOME`.

**Comment by romkatv** [comment]
This comment explains what's going on: https://github.com/romkatv/powerlevel10k/issues/491#issuecomment-586580015.

**Comment by Syphdias** [comment]
I think setting `core.worktree` makes `vcs` disappear
```
❯ # start
~ public  master +1 !122
❯ unset GIT_DIR GIT_WORK_TREE
~                                                                                                                                                                                                          09:25
❯ git --git-dir=$HOME/.config/dotgit/public config core.worktree $HOME
~
❯ exec zsh
~
❯ export GIT_WORK_TREE=~; export GIT_DIR=~/.config/dotgit/public
~ public
❯ git --git-dir=$HOME/.config/dotgit/public config --unset core.worktree
~ public
❯ pkill gitstatus
gitstatus_query_p9k_:print:50: write error: broken pipe                                                                                                                                                             
~ public
❯ exec zsh
~ public  master +1 !122
❯ git --git-dir=$HOME/.config/dotgit/public config core.worktree $HOME
~ public  master +1 !122
❯ git --git-dir=$HOME/.config/dotgit/public config --unset core.bare
~ public  master +1 !122
❯ pkill gitstatus; exec zsh
~ public                                                                                                                                                                                                   09:29:58
❯ 

```

Notes:
* I tried killing gitstatus to make sure it reads all variables anew
* I searched for any "bare" in local and global config, `core.bare` was the only one
* I also tried killing gitstatus, closing my terminal entirely, opening it again and setting `GIT_DIR`, `GIT_WORK_TREE`

**Comment by romkatv** [comment]
Setup:

```zsh
mkdir -p ~/.config/dotgit
export GIT_DIR=~/.config/dotgit/test
export GIT_WORK_TREE=~
git init
git config status.showuntrackedfiles no
git config core.worktree ~
```

Activate `test` repo in a new shell:

```zsh
export GIT_DIR=~/.config/dotgit/test
```

Once `test` the repo is activated, `vcs` shows status from it and all `git` commands target that repo.

**Comment by Syphdias** [comment]
> Once `test` the repo is activated, `vcs` shows status from it and all `git` commands target that repo.

Nope...
```
~
❯ export GIT_DIR=~/.config/dotgit/test
~ test
❯ git add .vimrc
~ test
❯ 
~ test
❯ git config --unset core.worktree
~ test
❯ 
~ test
❯ exec zsh
~ test  master +1 !1
❯ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .vimrc

Untracked files not listed (use -u option to show untracked files)
~ test  master +1 !1
❯ git commit -m "Let's see if the modified stays after the commit"
[master (root-commit) 5c38aa2] Let's see if the modified stays after the commit
 1 file changed, 81 insertions(+)
 create mode 100644 .vimrc
~ test  master !1
❯ git status
On branch master
nothing to commit (use -u to show untracked files)
```

Other things I tried:
- `z4h update`
- `mv ~/.gitconfig ~/.gitconfig.bak`

**Comment by Syphdias** [comment]
> Once `test` the repo is activated, `vcs` shows status from it and all `git` commands target that repo.

It works in a docker container. It has to be something local

**Comment by Syphdias** [comment]
Before you debug any further let me look deeper into what might be the cause. Maybe it's old p10k config.

**Comment by Syphdias** [comment]
ARG! HEUREKA! `POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'` in the `~/.p10k.zsh` was the culprit. What was really irritating, that it worked halfway if the git config didn't know the working dir was `~`

**Comment by romkatv** [comment]
> What was really irritating, that it worked halfway if the git config didn't know the working dir was `~`

It wasn't `~`. When it "worked", workdir was `$HOME/.config/dotgit`. See https://github.com/romkatv/powerlevel10k/issues/491#issuecomment-586580015 (I've linked to it earlier).

**Comment by romkatv** [comment]
I'll just mention again that it's a very good idea to add this prompt segment to your prompt (I put it right before `vcs`):

```zsh
function prompt_my_git_dir() {
  emulate -L zsh
  [[ -n $GIT_DIR ]] || return
  local repo=${GIT_DIR:t}
  [[ $repo == .git ]] && repo=${GIT_DIR:h:t}
  p10k segment -b 0 -f 208 -t ${repo//\%/%%}
}
```

Also this zle widget that you can bind to a key:

```zsh
function toggle-dotfiles() {
  () {
    emulate -L zsh
    case $GIT_DIR in
      '')
        export GIT_DIR=~/.config/dotgit/public
      ;;
      ~/.config/dotgit/public)
        export GIT_DIR=~/.config/dotgit/private
      ;;
      *)
        unset GIT_DIR
        unset GIT_WORK_TREE
      ;;
    esac
  }

  # This must run with user options (because of reset-prompt).
  local f
  for f in chpwd "${chpwd_functions[@]}" precmd "${precmd_functions[@]}"; do
    [[ "${+functions[$f]}" == 0 ]] || "$f" &>/dev/null || true
  done
  zle .reset-prompt
  zle -R
}
```

**Comment by Syphdias** [comment]
Thanks! Looks like you unified some of the `redraw-prompt` code.

I did two things to make it more modular. Patch it to left prompt only if I source that file:
```zsh
# patch before vcs
local -i vcs=POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[(I)vcs]
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[vcs,vcs-1]=(git_dir)
```
and adjust the the toggle to just loop through dirs:
```zsh
    () {
        emulate -L zsh
        local -a repos=("${XDG_CONFIG_HOME:-${HOME}/.config}/dotgit"/*)
        local -i current_idx=repos[(I)${GIT_DIR}]

        if [[ -n "${GIT_DIR}" \                                              
                && (${current_idx} == 0 || ${next_idx} == ${#repos}) \      
            ]]; then
            # foreign git dir or last one in list
            unset GIT_DIR
            unset GIT_WORK_TREE
        else                                        
            export GIT_DIR=${repos[${current_idx}+1]}
        fi
    }
```

I need to put my current dotfiles on github again...

I'll probably add a chpwd hook to disable it automatically if I move to a directory that isn't managed by the repo or if it's another git repo to avoid confusion. In the context of z4h should I put that in a specific place or just after `z4h init`? I don't think either z4h or p10k use chpwd hooks, so should be fine by my understanding.

**Comment by romkatv** [comment]
> Thanks! Looks like you unified some of the `redraw-prompt` code.
> 
> I did two things to make it more modular. Patch it to left prompt only if I source that file:
> 
> ```shell
> # patch before vcs
> local -i vcs=POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[(I)vcs]
> POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[vcs,vcs-1]=(git_dir)
> ```

I don't recommend patching `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`. I do it because I run `p10k configure` a million times a day. For you it's much better to simply put `git_dir` (which you should rename to `my_git_dir` to avoid clashes with future versions of Powerlevel10k) within `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` at the point where you define it.

> I'll probably add a chpwd hook to disable it automatically if I move to a directory that isn't managed by the repo or if it's another git repo to avoid confusion.

I tried doing this and it was more confusing. The current behavior of my setup is easy to understand and use. Having `GIT_DIR` automatically change on `cd` was inconvenient.

The presence of bright orange "public" or "private" in prompt is hard to miss. I often enable this "dotfiles" mode when my current directory is in fact another git repo. This makes sense because dotfiles are not tied to any directory.

Here's a typical usage scenario. I'm in `~/powerlevel10k` and I realize I want to change something in my `~/.zshrc`. I hit <kbd>Ctrl-P</kbd> and see that I already have some changes in the public dotfiles repo. `git status` shows that VS Code has written something to its settings file. `git diff` shows that changes makes sense, so I `git commit` them. Then I edit `~/.zshrc`, `exec zsh`, verify that my changes work as expected and `git commit` them. I hit <kbd>Ctrl-P</kbd> twice to get to regular git mode and see the status of `~/powerlevel10k` repo in prompt once again.

None of these actions required that I change my current directory. I just stayed in `~/powerlevel10k` the whole time.

**Comment by Syphdias** [comment]
For renaming: Makes sense, done.
For patching it into `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`: Since it fails silently, I guess there is no need to only include it if the function is defined.

> The presence of bright orange "public" or "private" in prompt is hard to miss.

I only missed it once so far and it was a harmless git command that failed. I will probably get used to switching back after I commited and pushed.
