### ISSUE TITLE
Document Profiling Graph Creation

### ISSUE THREAD

**Issue by skeirik2** [romkatv/gitstatus#14]
This isn't a tool issue; but I couldn't think of a better place to ask this question.

I was quite impressed seeing your profiling graphs in the README and your ListDir() optimization description. Did you create them manually or was it tool assisted? If they were made by some tool, could you add a sentence or two about how you created them?

Also, thanks for this tool; I use a git status prompt and occasionally bump into sluggishness so I'm eager to try this out.

**Comment by romkatv** [comment]
The CPU profiles were created with [gperftools](https://github.com/gperftools/gperftools) and
rendered with [pprof](https://github.com/google/pprof). I added this information to the docs.
