### ISSUE TITLE
gitstatus failed to initialize.

### ISSUE THREAD

**Issue by srt0** [romkatv/gitstatus#140]
> Error message below.

[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  The content of /tmp/gitstatus.POWERLEVEL9K.1000.1693.1590481419.1.xtrace.log (gitstatus_start xtrace):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 5.4.42-1-lts (linux-lts@archlinux) (gcc version 10.1.0 (GCC)) #1 SMP Wed, 20 May 2020 20:42:53 +0000' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.1000.1693.1590481419.1.lock
    +(anon):15> [[ 15 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ -n '' ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/14
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=1709'
    +(anon):46> [[ 17 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):41> _gitstatus_daemon_p9k_
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 17 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 17 'pgid[$#pgid+1]'
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '                1709' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /tmp/gitstatus.POWERLEVEL9K.1000.1693.1590481419.1.fifo
    +(anon):63> [[ 14 == <1-> ]]
    +(anon):64> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):66> print -nru 14 -- $'hello\C-_\C-^'
    +(anon):67> local expected=$'hello\C-_0\C-^' actual
    +(anon):68> ((  1  ))
    +(anon):68> [[ ! -t 1 ]]
    +(anon):71> local -F deadline=1
    +(anon):73> true
    +(anon):74> [[ -t 17 ]]
    +(anon):75> sysread -s 1 -t 5.0000000000 -i 17 actual
    +(anon):75> return
                         ^ this command failed (5)

  The content of /tmp/gitstatus.POWERLEVEL9K.1000.1693.1590481419.1.daemon.log (gitstatus daemon log):

    +_gitstatus_daemon_p9k_:3> local pgid=1709
    +_gitstatus_daemon_p9k_:4> [[ 1709 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:78> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:81> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.1000.1693.1590481419.1.lock
    +_gitstatus_daemon_p9k_:12> uname_sm='linux x86_64' 
    +_gitstatus_daemon_p9k_:13> [[ 'linux x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=linux
    +_gitstatus_daemon_p9k_:15> local uname_m=x86_64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:21> [[ linux == linux ]]
    +_gitstatus_daemon_p9k_:23> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:23> cpus=+_gitstatus_daemon_p9k_:23> getconf _NPROCESSORS_ONLN
    +_gitstatus_daemon_p9k_:23> cpus=2 
    +_gitstatus_daemon_p9k_:27> args+=( -t 4 ) 
    +_gitstatus_daemon_p9k_:30> mkfifo -- /tmp/gitstatus.POWERLEVEL9K.1000.1693.1590481419.1.fifo
    +_gitstatus_daemon_p9k_:31> print -rnu 14 -- '                1709'
    +_gitstatus_daemon_p9k_:33> zf_rm -- /tmp/gitstatus.POWERLEVEL9K.1000.1693.1590481419.1.fifo
    +_gitstatus_daemon_p9k_:35> local _gitstatus_zsh_daemon _gitstatus_zsh_version _gitstatus_zsh_downloaded
    +_gitstatus_daemon_p9k_:43> local gitstatus_plugin_dir_var=_gitstatus_plugin_dir_p9k_
    +_gitstatus_daemon_p9k_:44> local gitstatus_plugin_dir=/usr/share/zsh-theme-powerlevel10k/gitstatus
    +_gitstatus_daemon_p9k_:45> set -- -d /usr/share/zsh-theme-powerlevel10k/gitstatus -s linux -m x86_64 -p 'printf . >&14' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_daemon_p9k_:47> [[ 1 == (|-|+)<1-> ]]
    +_gitstatus_daemon_p9k_:48> source /usr/share/zsh-theme-powerlevel10k/gitstatus/install
    _gitstatus_daemon_p9k_:source:48: no such file or directory: /usr/share/zsh-theme-powerlevel10k/gitstatus/install
    +_gitstatus_daemon_p9k_:48> return
    +_gitstatus_daemon_p9k_:72> local -i ret=127
    +_gitstatus_daemon_p9k_:73> zf_rm -f -- /tmp/gitstatus.POWERLEVEL9K.1000.1693.1590481419.1.lock /tmp/gitstatus.POWERLEVEL9K.1000.1693.1590481419.1.fifo
    +_gitstatus_daemon_p9k_:74> kill -- -1709

  Your system information:

    zsh:      5.8
    uname -a: Linux archlinux 5.4.42-1-lts #1 SMP Wed, 20 May 2020 20:42:53 +0000 x86_64 GNU/Linux

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#arch-linux
