### ISSUE TITLE
gitstatus failed to initialize

### ISSUE THREAD

**Issue by ArpitSen** [romkatv/gitstatus#143]
Hi,

I am getting the following error while starting my terminal on Cygwin running on Windows.

-------------
The content of /tmp/gitstatus.POWERLEVEL9K.1770680.1749.1590519753.2.xtrace.log (gitstatus_start xtrace):

+(anon):7> setopt monitor
+(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
+(anon):10> [[ -r /proc/version && 'CYGWIN_NT-10.0-17763 version 3.1.4-340.x86_64 (corinna@calimero) (gcc version 7.4.0 20181206 (Fedora Cygwin 7.4.0-1) (GCC) ) 2020-02-19 08:49 UTC' == *Microsoft* ]]
+(anon):13> print -rn
+(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.1770680.1749.1590519753.2.lock
+(anon):15> [[ 17 == <1-> ]]
+(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
+(anon):20> [[ -n 'C:\Users\<user_id>' && -d /cygdrive ]]
+(anon):41> sysopen -r -o cloexec -u resp_fd /tmp/zshdMEL8a
+(anon):41> _gitstatus_daemon_p9k_
+_gitstatus_daemon_p9k_:1> local -i pipe_fd
+(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=-1'
+(anon):46> [[ 18 == <1-> ]]
+(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
+(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
+(anon):51> ((  ! async  ))
+(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
+(anon):54> local pgid
+(anon):55> ((  0 < 20  ))
+(anon):56> [[ -t 18 ]]
+(anon):57> sysread -s 20 -t 5.0000000000 -i 18 'pgid[$#pgid+1]'
+(anon):57> return
                         ^ this command failed (4)

The content of /tmp/gitstatus.POWERLEVEL9K.1770680.1749.1590519753.2.daemon.log (gitstatus daemon log):

+_gitstatus_daemon_p9k_:3> local pgid=1790
+_gitstatus_daemon_p9k_:4> [[ 1790 == <1-> ]]
+_gitstatus_daemon_p9k_:5> cd -q /
+_gitstatus_daemon_p9k_:78> ((  lock_fd == -1  ))
+_gitstatus_daemon_p9k_:9> trap '' PIPE
+_gitstatus_daemon_p9k_:11> local uname_sm
+_gitstatus_daemon_p9k_:81> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.1770680.1749.1590519753.2.lock
+_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
+_gitstatus_daemon_p9k_:81> [[ -e /tmp/gitstatus.POWERLEVEL9K.1770680.1749.1590519753.2.lock ]]
+_gitstatus_daemon_p9k_:12> uname_sm='cygwin_nt-10.0 x86_64' 
+_gitstatus_daemon_p9k_:13> [[ 'cygwin_nt-10.0 x86_64' == [^\ ]##\ [^\ ]## ]]
+_gitstatus_daemon_p9k_:14> local uname_s=cygwin_nt-10.0
+_gitstatus_daemon_p9k_:15> local uname_m=x86_64
+_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
+_gitstatus_daemon_p9k_:20> local cpus
+_gitstatus_daemon_p9k_:21> ((  ! 0  ))
+_gitstatus_daemon_p9k_:23> ((  ! 1  ))
+_gitstatus_daemon_p9k_:23> cpus=+_gitstatus_daemon_p9k_:23> getconf _NPROCESSORS_ONLN
+_gitstatus_daemon_p9k_:23> cpus=8 
+_gitstatus_daemon_p9k_:27> args+=( -t 16 ) 
+_gitstatus_daemon_p9k_:30> mkfifo -- /tmp/gitstatus.POWERLEVEL9K.1770680.1749.1590519753.2.fifo
+_gitstatus_daemon_p9k_:31> print -rnu 13 -- '                1790'
_gitstatus_daemon_p9k_:print:31: write error: broken pipe
+_gitstatus_daemon_p9k_:31> return
+_gitstatus_daemon_p9k_:72> local -i ret=1
+_gitstatus_daemon_p9k_:73> zf_rm -f -- /tmp/gitstatus.POWERLEVEL9K.1770680.1749.1590519753.2.lock /tmp/gitstatus.POWERLEVEL9K.1770680.1749.1590519753.2.fifo
+_gitstatus_daemon_p9k_:74> kill -- -1790

  Your system information:

    zsh:      5.5.1
    uname -a: CYGWIN_NT-10.0 <system_id> 3.1.4(0.340/5/3) 2020-02-19 08:49 x86_64 Cygwin

**Comment by ArpitSen** [comment]
Didn't see the previous bug that I created.

**Comment by romkatv** [comment]
> Didn't see the previous bug that I created.

Yep. You opened a bug, I asked a question and you disappeared. I closed it after 4 days.

**Comment by ArpitSen** [comment]
Sorry, I was offline for the last 4 days.
Please advice, if I should file another bug with details after I added the /cygdrive back as my root folder.
