### ISSUE TITLE
gitstatus failed to initialize

### ISSUE THREAD

**Issue by garyblocks** [romkatv/gitstatus#144]
I am trying to install powerlevel10k on macOS Catalina 10.15.4 with oh-my-zsh, then got this error message.

[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  Zsh log (/private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.31121.1590618238.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.31121.1590618238.1.lock
    +(anon):15> [[ 14 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ darwin19.0 == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /dev/fd/13
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=31367'
    +(anon):46> [[ 16 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 16 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 16 'pgid[$#pgid+1]'
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '               31367' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.31121.1590618238.1.fifo
    +(anon):63> [[ 15 == <1-> ]]
    +(anon):64> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):66> print -nru 15 -- $'hello\C-_\C-^'
    +(anon):67> local expected=$'hello\C-_0\C-^' actual
    +(anon):68> ((  1  ))
    +(anon):68> [[ ! -t 1 ]]
    +(anon):71> local -F deadline=1
    +(anon):73> true
    +(anon):74> [[ -t 16 ]]
    +(anon):75> sysread -s 1 -t 5.0000000000 -i 16 actual
    +(anon):75> return
                    ^ this command failed (5)

  Daemon log (/private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.31121.1590618238.1.daemon.log):

**Comment by romkatv** [comment]
Please post the full word message.

**Comment by garyblocks** [comment]
[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  Zsh log (/private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.33086.1590642900.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.33086.1590642900.1.lock
    +(anon):15> [[ 14 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ darwin19.3.0 == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /dev/fd/13
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=33345'
    +(anon):46> [[ 16 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 16 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 16 'pgid[$#pgid+1]'
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '               33345' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.33086.1590642900.1.fifo
    +(anon):63> [[ 15 == <1-> ]]
    +(anon):64> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):66> print -nru 15 -- $'hello\C-_\C-^'
    +(anon):67> local expected=$'hello\C-_0\C-^' actual
    +(anon):68> ((  1  ))
    +(anon):68> [[ ! -t 1 ]]
    +(anon):71> local -F deadline=1
    +(anon):73> true
    +(anon):74> [[ -t 16 ]]
    +(anon):75> sysread -s 1 -t 5.0000000000 -i 16 actual
    +(anon):75> return
                    ^ this command failed (5)

  Daemon log (/private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.33086.1590642900.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=33345
    +_gitstatus_daemon_p9k_:4> [[ 33345 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:78> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:81> zsystem flock -- /private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.33086.1590642900.1.lock
    +_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='darwin x86_64'
    +_gitstatus_daemon_p9k_:13> [[ 'darwin x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=darwin
    +_gitstatus_daemon_p9k_:15> local uname_m=x86_64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:21> [[ darwin == linux ]]
    +_gitstatus_daemon_p9k_:22> cpus=+_gitstatus_daemon_p9k_:22> sysctl -n hw.ncpu
    +_gitstatus_daemon_p9k_:22> cpus=16
    +_gitstatus_daemon_p9k_:27> args+=( -t 32 )
    +_gitstatus_daemon_p9k_:30> mkfifo -- /private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.33086.1590642900.1.fifo
    +_gitstatus_daemon_p9k_:31> print -rnu 15 -- '               33345'
    +_gitstatus_daemon_p9k_:33> zf_rm -- /private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.33086.1590642900.1.fifo
    +_gitstatus_daemon_p9k_:35> local _gitstatus_zsh_daemon _gitstatus_zsh_version _gitstatus_zsh_downloaded
    +_gitstatus_daemon_p9k_:43> local gitstatus_plugin_dir_var=_gitstatus_plugin_dir_p9k_
    +_gitstatus_daemon_p9k_:44> local gitstatus_plugin_dir=/Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_daemon_p9k_:45> set -- -d /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_daemon_p9k_:47> [[ 1 == (|-|+)<1-> ]]
    +_gitstatus_daemon_p9k_:48> source /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install
    +/Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install:389> [ -z '' ']'
    +/Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install:390> _gitstatus_install_main /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -d /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:1> [ -n 5.8 ']'
    +_gitstatus_install_main:2> emulate -L sh -o no_unset
    +_gitstatus_install_main:7> local argv1=/Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:8> shift
    +_gitstatus_install_main:10> local no_check='' no_install='' uname_s='' uname_m='' gitstatus_dir='' dl_status=''
    +_gitstatus_install_main:11> local opt='' OPTARG='' OPTIND=1
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case d (h)
    +_gitstatus_install_main:14> case d (n)
    +_gitstatus_install_main:14> case d (f)
    +_gitstatus_install_main:14> case d (d)
    +_gitstatus_install_main:54> [ -n '' ']'
    +_gitstatus_install_main:58> [ -z /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus ']'
    +_gitstatus_install_main:62> gitstatus_dir=/Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case s (h)
    +_gitstatus_install_main:14> case s (n)
    +_gitstatus_install_main:14> case s (f)
    +_gitstatus_install_main:14> case s (d)
    +_gitstatus_install_main:14> case s (p)
    +_gitstatus_install_main:14> case s (m)
    +_gitstatus_install_main:14> case s (s)
    +_gitstatus_install_main:87> [ -n '' ']'
    +_gitstatus_install_main:91> [ -z darwin ']'
    +_gitstatus_install_main:95> uname_s=darwin
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case m (h)
    +_gitstatus_install_main:14> case m (n)
    +_gitstatus_install_main:14> case m (f)
    +_gitstatus_install_main:14> case m (d)
    +_gitstatus_install_main:14> case m (p)
    +_gitstatus_install_main:14> case m (m)
    +_gitstatus_install_main:76> [ -n '' ']'
    +_gitstatus_install_main:80> [ -z x86_64 ']'
    +_gitstatus_install_main:84> uname_m=x86_64
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case p (h)
    +_gitstatus_install_main:14> case p (n)
    +_gitstatus_install_main:14> case p (f)
    +_gitstatus_install_main:14> case p (d)
    +_gitstatus_install_main:14> case p (p)
    +_gitstatus_install_main:65> [ -n '' ']'
    +_gitstatus_install_main:69> [ -z 'printf . >&15' ']'
    +_gitstatus_install_main:73> dl_status='printf . >&15'
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:103> shift 9
    +_gitstatus_install_main:105> : /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:107> [ -n '' -a -n '' ']'
    +_gitstatus_install_main:112> [ -z darwin ']'
    +_gitstatus_install_main:116> [ -z x86_64 ']'
    +_gitstatus_install_main:121> local daemon=''
    +_gitstatus_install_main:122> local cache_dir=/Users/wangjiayu/.cache/gitstatus
    +_gitstatus_install_main:124> [ -z '' ']'
    +_gitstatus_install_main:125> [ -n '' ']'
    +_gitstatus_install_main:129> [ -z '' ']'
    +_gitstatus_install_main:130> daemon=/Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd
    +_gitstatus_install_main:131> [ ! -e /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd ']'
    +_gitstatus_install_main:132> daemon=/Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-x86_64
    +_gitstatus_install_main:133> [ ! -e /Users/wangjiayu/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-x86_64 ']'
    +_gitstatus_install_main:134> daemon=''
    +_gitstatus_install_main:138> [ -n '' ']'
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line='uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355";'
    +_gitstatus_install_main:155> [ -n 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355";' ']'
    +_gitstatus_install_main:157> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
    +_gitstatus_install_main:158> eval 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355";'
    +_gitstatus_install_main:158> uname_s_glob=cygwin_nt-10.0
    +_gitstatus_install_main:158> uname_m_glob=i686
    +_gitstatus_install_main:158> file=gitstatusd-darwin-x86_64
    +_gitstatus_install_main:158> version=v1.0.0
    +_gitstatus_install_main:158> sha256=c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355
    +_gitstatus_install_main:160> [ -z cygwin_nt-10.0 -o -z i686 -o -z gitstatusd-darwin-x86_64 -o -z v1.0.0 -o -z c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355 ']'
    +_gitstatus_install_main:169> case darwin (cygwin_nt-10.0)
    +_gitstatus_install_main:169> case darwin (*)
    +_gitstatus_install_main:171> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line='uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad";'
    +_gitstatus_install_main:155> [ -n 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad";' ']'
    +_gitstatus_install_main:157> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
    +_gitstatus_install_main:158> eval 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad";'
    +_gitstatus_install_main:158> uname_s_glob=cygwin_nt-10.0
    +_gitstatus_install_main:158> uname_m_glob=x86_64
    +_gitstatus_install_main:158> file=gitstatusd-darwin-x86_64
    +_gitstatus_install_main:158> version=v1.0.0
    +_gitstatus_install_main:158> sha256=d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad
    +_gitstatus_install_main:160> [ -z cygwin_nt-10.0 -o -z x86_64 -o -z gitstatusd-darwin-x86_64 -o -z v1.0.0 -o -z d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad ']'
    +_gitstatus_install_main:169> case darwin (cygwin_nt-10.0)
    +_gitstatus_install_main:169> case darwin (*)
    +_gitstatus_install_main:171> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line='uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a";'
    +_gitstatus_install_main:155> [ -n 'uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a";' ']'
    +_gitstatus_install_main:157> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
    +_gitstatus_install_main:158> eval 'uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a";'
    +_gitstatus_install_main:158> uname_s_glob=darwin
    +_gitstatus_install_main:158> uname_m_glob=x86_64
    +_gitstatus_install_main:158> file=gitstatusd-darwin-x86_64
    +_gitstatus_install_main:158> version=v1.0.0
    +_gitstatus_install_main:158> sha256=c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a
    +_gitstatus_install_main:160> [ -z darwin -o -z x86_64 -o -z gitstatusd-darwin-x86_64 -o -z v1.0.0 -o -z c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a ']'
    +_gitstatus_install_main:169> case darwin (darwin)
    +_gitstatus_install_main:173> case x86_64 (x86_64)
    +_gitstatus_install_main:180> [ -z '' ']'
    +_gitstatus_install_main:182> local daemon=/Users/wangjiayu/.cache/gitstatus/gitstatusd-darwin-x86_64
    +_gitstatus_install_main:183> [ -e /Users/wangjiayu/.cache/gitstatus/gitstatusd-darwin-x86_64 ']'
    +_gitstatus_install_main:187> daemon=/Users/wangjiayu/.cache/gitstatus/gitstatusd-darwin-x86_64-darwin-x86_64
    +_gitstatus_install_main:188> [ -e /Users/wangjiayu/.cache/gitstatus/gitstatusd-darwin-x86_64-darwin-x86_64 ']'
    +_gitstatus_install_main:205> [ -n '' ']'
    +_gitstatus_install_main:210> local daemon=/Users/wangjiayu/.cache/gitstatus/gitstatusd-darwin-x86_64
    +_gitstatus_install_main:212> [ -n '' ']'
    +_gitstatus_install_main:216> [ -d /Users/wangjiayu/.cache/gitstatus ']'
    +_gitstatus_install_main:216> mkdir -p -- /Users/wangjiayu/.cache/gitstatus
    mkdir: /Users/wangjiayu/.cache/gitstatus: Permission denied
    +_gitstatus_install_main:216> return
    +_gitstatus_daemon_p9k_:48> return
    +_gitstatus_daemon_p9k_:72> local -i ret=1
    +_gitstatus_daemon_p9k_:73> zf_rm -f -- /private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.33086.1590642900.1.lock /private/var/folders/79/2xrg__0s5sb1tv539bc3jllr0000gn/T/gitstatus.POWERLEVEL9K.501.33086.1590642900.1.fifo
    +_gitstatus_daemon_p9k_:74> kill -- -33345

  System information:

    zsh:      5.8
    uname -a: Darwin Jiayus-MBP.attlocal.net 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by romkatv** [comment]
This is the reason:

```text
> mkdir -p -- /Users/wangjiayu/.cache/gitstatus
mkdir: /Users/wangjiayu/.cache/gitstatus: Permission denied
```

You need to fix it.

**Comment by garyblocks** [comment]
It worked! Thank you so much for the in time help. I am sorry I didn't notice the permission issue.

**Comment by romkatv** [comment]
Thanks for the confirmation.
