### ISSUE TITLE
Git status error after 10.15.5 update

### ISSUE THREAD

**Issue by smlombardi** [romkatv/gitstatus#145]
```
[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  The content of /private/var/folders/_l/6dfczh7x52dgc4srm2rw7zch0000gp/T/gitstatus.POWERLEVEL9K.502.4606.1590799470.2.xtrace.log (gitstatus_start xtrace):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/_l/6dfczh7x52dgc4srm2rw7zch0000gp/T/gitstatus.POWERLEVEL9K.502.4606.1590799470.2.lock
    +(anon):15> [[ 15 == <1-> ]]
    +(anon):17> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> '(anon)' /dev/fd/17
    +(anon):1> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=5048'
    +(anon):2> sysopen -r -o cloexec -u resp_fd -- /dev/fd/17
    +(anon):3> [[ 19 == <1-> ]]
    +(anon):4> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):121> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):124> ((  ! async  ))
    +(anon):125> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):127> local pgid
    +(anon):128> ((  0 < 20  ))
    +(anon):129> [[ -t 19 ]]
    +(anon):130> sysread -s 20 -t 5.0000000000 -i 19 'pgid[$#pgid+1]'
    +(anon):128> ((  20 < 20  ))
    +(anon):132> [[ '                5048' == \ #<1-> ]]
    +(anon):133> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):135> sysopen -w -o cloexec -u req_fd -- /private/var/folders/_l/6dfczh7x52dgc4srm2rw7zch0000gp/T/gitstatus.POWERLEVEL9K.502.4606.1590799470.2.fifo
    +(anon):136> [[ 16 == <1-> ]]
    +(anon):137> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):148> zle -F 19 _gitstatus_process_response_POWERLEVEL9K
    +(anon):159> add-zsh-hook zshexit _gitstatus_cleanup_POWERLEVEL9K
    +add-zsh-hook:15> emulate -L zsh
    +add-zsh-hook:17> local -a hooktypes
    +add-zsh-hook:18> hooktypes=( chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name ) 
    +add-zsh-hook:22> local usage='Usage: add-zsh-hook hook function\nValid hooks are:\n  chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name'
    +add-zsh-hook:24> local opt
    +add-zsh-hook:25> local -a autoopts
    +add-zsh-hook:26> integer del list help
    +add-zsh-hook:28> getopts dDhLUzk opt
    +add-zsh-hook:55> shift 0
    +add-zsh-hook:57> ((  list  ))
    +add-zsh-hook:60> ((  help || 2 != 2 || 6 == 0  ))
    +add-zsh-hook:65> local hook=zshexit_functions
    +add-zsh-hook:66> local fn=_gitstatus_cleanup_POWERLEVEL9K
    +add-zsh-hook:68> ((  del  ))
    +add-zsh-hook:83> ((  1  ))
    +add-zsh-hook:84> ((  0 == 0  ))
    +add-zsh-hook:85> typeset -ga zshexit_functions
    +add-zsh-hook:86> set -A zshexit_functions _p9k_worker_cleanup _gitstatus_cleanup_POWERLEVEL9K
    +add-zsh-hook:92> autoload -- _gitstatus_cleanup_POWERLEVEL9K
    +(anon):164> print -nru 16 -- $'hello\C-_\C-^'
    +(anon):165> local expected=$'hello\C-_0\C-^' actual
    +(anon):166> ((  0 < 8  ))
    +(anon):167> [[ -t 19 ]]
    +(anon):168> sysread -s 8 -t 5.0000000000 -i 19 'actual[$#actual+1]'
    +(anon):168> return
                         ^ this command failed (4)

  The content of /private/var/folders/_l/6dfczh7x52dgc4srm2rw7zch0000gp/T/gitstatus.POWERLEVEL9K.502.4606.1590799470.2.daemon.log (gitstatus daemon log):

    +(anon):22> local pgid=5048
    +(anon):23> [[ 5048 == <1-> ]]
    +(anon):105> ((  lock_fd == -1  ))
    +(anon):27> trap '' PIPE
    +(anon):29> [[ -z '' ]]
    +(anon):30> local kernel
    +(anon):108> zsystem flock -- /private/var/folders/_l/6dfczh7x52dgc4srm2rw7zch0000gp/T/gitstatus.POWERLEVEL9K.502.4606.1590799470.2.lock
    +(anon):31> kernel=+(anon):31> uname -s
    +(anon):31> kernel=darwin 
    +(anon):32> [[ -n darwin ]]
    +(anon):35> [[ '' == /* ]]
    +(anon):37> ((  0  ))
    +(anon):39> [[ -n '' ]]
    +(anon):42> local -aU os=( darwin )
    +(anon):43> case darwin (linux)
    +(anon):43> case darwin (cygwin_nt-*)
    +(anon):43> case darwin (msys_nt-*)
    +(anon):43> case darwin (mingw32_nt-*)
    +(anon):43> case darwin (mingw64_nt-*)
    +(anon):53> local arch
    +(anon):54> arch=+(anon):54> uname -m
    +(anon):54> arch=x86_64 
    +(anon):55> [[ -n x86_64 ]]
    +(anon):56> local daemons=( /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-x86_64 /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-x86_64-static /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static )
    +(anon):60> local files=( /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 )
    +(anon):61> daemons=( /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 ) 
    +(anon):63> ((  stderr_fd && 1 != 1  ))
    +(anon):73> ((  1  ))
    +(anon):75> [[ '' == <1-> ]]
    +(anon):78> local cpus
    +(anon):79> ((  ! 1  ))
    +(anon):79> [[ darwin == linux ]]
    +(anon):80> cpus=+(anon):80> sysctl -n hw.ncpu
    +(anon):80> cpus=8 
    +(anon):85> args+=( -t 16 ) 
    +(anon):88> mkfifo -- /private/var/folders/_l/6dfczh7x52dgc4srm2rw7zch0000gp/T/gitstatus.POWERLEVEL9K.502.4606.1590799470.2.fifo
    +(anon):89> print -rn -- '                5048'
    +(anon):91> zf_rm -- /private/var/folders/_l/6dfczh7x52dgc4srm2rw7zch0000gp/T/gitstatus.POWERLEVEL9K.502.4606.1590799470.2.fifo
    +(anon):93> local daemon
    +(anon):94> daemon=/Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
    +(anon):95> /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 -v DEBUG -t 16

  Your system information:

    zsh:      5.7.1
    uname -a: Darwin US-ST016LO-MLT 19.5.0 Darwin Kernel Version 19.5.0: Thu Apr 30 18:25:59 PDT 2020; root:xnu-6153.121.1~7/RELEASE_X86_64 x86_64

  If you need help, open an issue and attach this whole error message to it:
```

**Comment by romkatv** [comment]
The version of powerlevel10k you are using is quite old. Try updating and see if it helps:

```zsh
git -C /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k pull
exec zsh
```

**Comment by soaringk** [comment]
> The version of powerlevel10k you are using is quite old. Try updating and see if it helps:
> 
> ```shell
> git -C /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k pull
> exec zsh
> ```

Interestingly, I got the error after updating to Catalina 10.15.5.

```
[powerlevel10k] fetching gitstatusd .. \                                                                                          
[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:

    GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K

  If this command produces no output, add the following parameter to ~/.zshrc:

    GITSTATUS_LOG_LEVEL=DEBUG

  With this parameter gitstatus will print additional information on error.
```

I ran the command but it returned the following: `gitstatus_start: command not found`

So I added the variable into `.zshrc`, and the command failed at 
```
+(anon):82> unsetopt xtrace                         
                                                       ^ this command failed (5)
`

I somehow fixed the problem by sourcing the `gitstatus.prompt.zsh`. Hope this is helpful.

**Comment by romkatv** [comment]
> Interestingly, I got the error after updating to Catalina 10.15.5.
> 
> ```
> [powerlevel10k] fetching gitstatusd .. \                                                                                          
> [ERROR]: gitstatus failed to initialize.
> 
>   Your Git prompt may disappear or become slow.
> 
>   Run the following command to retry with extra diagnostics:
> 
>     GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K
> 
>   If this command produces no output, add the following parameter to ~/.zshrc:
> 
>     GITSTATUS_LOG_LEVEL=DEBUG
> 
>   With this parameter gitstatus will print additional information on error.
> ```

This error message indicates that you are using an old version of powerlevel10k. Or, you are using several versions at once. Or, you are manually sourcing gitstatus.

Please update powerlevel10k to the latest version and try again. Make sure you only have one powerlevel10k.

**Comment by soaringk** [comment]
> > Interestingly, I got the error after updating to Catalina 10.15.5.
> > ```
> > [powerlevel10k] fetching gitstatusd .. \                                                                                          
> > [ERROR]: gitstatus failed to initialize.
> > 
> >   Your Git prompt may disappear or become slow.
> > 
> >   Run the following command to retry with extra diagnostics:
> > 
> >     GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K
> > 
> >   If this command produces no output, add the following parameter to ~/.zshrc:
> > 
> >     GITSTATUS_LOG_LEVEL=DEBUG
> > 
> >   With this parameter gitstatus will print additional information on error.
> > ```
> 
> This error message indicates that you are using an old version of powerlevel10k. Or, you are using several versions at once. Or, you are manually sourcing gitstatus.
> 
> Please update powerlevel10k to the latest version and try again. Make sure you only have one powerlevel10k.

Let me clarify: I updated both of my macOS and powerlevel10k to the lastest version (I even tried to delete the powerlevel10k and everything to make sure there is no conflict).
It is working before I updating the powerlevel10k (after updating to 10.15.5), and then I got the problem of failed initialization after updating powerlevel10k to the latest.
And I somehow fixed it by sourcing `gitstatus.prompt.zsh`.

**Comment by romkatv** [comment]
> Let me clarify: I updated both of my macOS and powerlevel10k to the lastest version

The last error message you've posted is not from the latest version of powerlevel10k.

How have you updated powerlevel10k?

What is the output of the following command?

```zsh
print -r -- ${_p9k__param_pat%%$'\1'*}
```

> And I somehow fixed it by sourcing `gitstatus.prompt.zsh`.

Could you clarify? What exactly did you do?

**Comment by soaringk** [comment]
> How have you updated powerlevel10k?

I ran the following
```
cd $ZPREZTODIR
git pull
git submodule update --init --recursive
```

After that I deleted the zprezto folder and pull the powerlevel10k to make sure it's up-to-date.

> What is the output of the following command?

v87
> Could you clarify? What exactly did you do?

I just sourced the file and it finished `fetching gitstatusd`. Sorry, I didn't figure out what is going on
```
git clone --depth 1 --single-branch https://github.com/romkatv/gitstatus.git
source ./gitstatus.prompt.zsh
```

**Comment by romkatv** [comment]
> > How have you updated powerlevel10k?
> 
> I ran the following
> 
> ```
> cd $ZPREZTODIR
> git pull
> git submodule update --init --recursive
> ```

Thanks for the clarification. The very first log you've posted indicates that you are using powerlevel10k via oh-my-zsh, that's why I asked you to update it via this command:

```zsh
git -C /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k pull
```

Please do run it.

The version in prezto isn't the latest.

```zsh
git clone --depth 1 --single-branch https://github.com/romkatv/gitstatus.git
source ./gitstatus.prompt.zsh
```

> I just sourced the file and it finished `fetching gitstatusd`. Sorry, I didn't figure out what is going on.
> 
> ```
> git clone --depth 1 --single-branch https://github.com/romkatv/gitstatus.git
> source ./gitstatus.prompt.zsh
> ```

It's really not a good idea to source two themes at once. `gitstatus.prompt.zsh` is essentially a theme.

What helped you is that you've used the latest version of gitstatus. But what you should do instead is update powerlevel10k to the latest version.

**Comment by soaringk** [comment]
Maybe I should run `p10k configure` after updating powerlevel10k. This should get everything done.

**Comment by romkatv** [comment]
No, you should run the command I've written above:

```zsh
git -C /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k pull
exec zsh
```

**Comment by smlombardi** [comment]
> The version of powerlevel10k you are using is quite old. Try updating and see if it helps:
> 
> ```shell
> git -C /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k pull
> exec zsh
> ```

I get this:
```
Updating fb117b5..801bfbb
error: Your local changes to the following files would be overwritten by merge:
	gitstatus/bin/gitstatusd-darwin-x86_64
Please commit your changes or stash them before you merge.
Aborting
```

**Comment by romkatv** [comment]
Apparently you have a locally modified binary. This explains the error you've got earlier. You need to get rid of it:

```zsh
git -C /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k checkout -- .
git -C /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k reset --hard origin/master
git -C /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k clean -df
git -C /Users/st016lo/.oh-my-zsh/custom/themes/powerlevel10k pull
```

**Comment by romkatv** [comment]
Also, if you've define any parameters with names that start with `GITSTATUS`, **delete them**. Look at your `~/.zshrc` for them.
