### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by supryantowp** [romkatv/gitstatus#148]
Your Git prompt may disappear or become slow.

  Zsh log (/private/var/folders/q0/9fs2d8x94gj_0hg52j_fl4jc0000gn/T/gitstatus.POWERLEVEL9K.501.62545.1591701474.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/q0/9fs2d8x94gj_0hg52j_fl4jc0000gn/T/gitstatus.POWERLEVEL9K.501.62545.1591701474.1.lock
    +(anon):15> [[ 15 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ darwin19.0 == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /dev/fd/14
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=62560'
    +(anon):46> [[ 17 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 17 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 17 'pgid[$#pgid+1]'
    +(anon):57> return

  Daemon log (/private/var/folders/q0/9fs2d8x94gj_0hg52j_fl4jc0000gn/T/gitstatus.POWERLEVEL9K.501.62545.1591701474.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=62560
    +_gitstatus_daemon_p9k_:4> [[ 62560 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:78> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:81> zsystem flock -- /private/var/folders/q0/9fs2d8x94gj_0hg52j_fl4jc0000gn/T/gitstatus.POWERLEVEL9K.501.62545.1591701474.1.lock
    +_gitstatus_daemon_p9k_:12> uname -sm
    _gitstatus_daemon_p9k_:12: command not found: uname
    +_gitstatus_daemon_p9k_:12> uname_sm=''
    +_gitstatus_daemon_p9k_:12> return
    +_gitstatus_daemon_p9k_:72> local -i ret=127
    +_gitstatus_daemon_p9k_:73> zf_rm -f -- /private/var/folders/q0/9fs2d8x94gj_0hg52j_fl4jc0000gn/T/gitstatus.POWERLEVEL9K.501.62545.1591701474.1.lock /private/var/folders/q0/9fs2d8x94gj_0hg52j_fl4jc0000gn/T/gitstatus.POWERLEVEL9K.501.62545.1591701474.1.fifo
    +_gitstatus_daemon_p9k_:74> kill -- -62560

  System information:

    zsh:      5.7.1
    uname -a: Darwin MacBooks-MBP 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

**Comment by romkatv** [comment]
> `_gitstatus_daemon_p9k_:12: command not found: uname`

Do you know why this could be?

**Comment by supryantowp** [comment]
after I added export PATH = / home / User / development / flutter / bin: $ PATH to .zshrc

**Comment by supryantowp** [comment]
solved
solution
re-configure p10k

**Comment by romkatv** [comment]
> solved
> solution
> re-configure p10k

This makes no sense but I'm glad it's working for you now.
