### ISSUE TITLE
Question: Customizing colors?

### ISSUE THREAD

**Issue by PopeRigby** [romkatv/gitstatus#149]
I'd like to set the colors so they work better with my terminal theme. How can I do this?

**Comment by romkatv** [comment]
You didn't provide enough information for me to help you.

**Comment by PopeRigby** [comment]
Sorry about that. What information do you need? I'm using zsh and ArchLinux, if that's helpful.

**Comment by romkatv** [comment]
> Sorry about that. What information do you need?

Sorry, you are asking for too much of my time.

**Comment by PopeRigby** [comment]
Well, I gave you my OS and shell. 
* I'm also using version 1.1.3-1 of gitstatus. 
* I'm using Konsole for my terminal emulator. 
* I'm not using it through a theme, I'm just sourcing it in my `.zshrc`:

```
source /usr/share/gitstatus/gitstatus.prompt.zsh
```

* This is my prompt:

```
autoload -Uz promptinit
promptinit
autoload -U colors
colors
PROMPT='%F{blue}%~%f ${GITSTATUS_PROMPT}${GITSTATUS_PROMPT:+ }%(!.%F{red}#%f .%F{yellow}$%f '
```

* My theme is Nord theme. 
* I installed gitstatus through the [AUR](https://aur.archlinux.org/packages/gitstatus/).

**Comment by romkatv** [comment]
Thanks, this is the information I needed.

`gitstatus.prompt.zsh` is a fairly small file. You can make a copy of it and modify its content as you like. It has plenty of comments to make this not too difficult.

By the way, you don't need these:

```zsh
autoload -Uz promptinit
promptinit
autoload -U colors
colors
```

I would recommend removing them.

You might also find https://github.com/romkatv/powerlevel10k/ a better fit.

**Comment by PopeRigby** [comment]
Ok, thanks.
