### ISSUE TITLE
After new install getting error [ERROR]: gitstatus failed to initialize.    Your Git prompt may disappear or become slow.

### ISSUE THREAD

**Issue by minmaxdata** [romkatv/gitstatus#154]
When i try to run p1ok configure it does not launch the wizard 

when I exec zsh it outputs the following:

[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  Zsh log (/private/var/folders/wg/2vv9vb815hn9d2d22wfdff2m0000gn/T/gitstatus.POWERLEVEL9K.501.15418.1593835913.2.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/wg/2vv9vb815hn9d2d22wfdff2m0000gn/T/gitstatus.POWERLEVEL9K.501.15418.1593835913.2.lock
    +(anon):15> [[ 13 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ darwin19.3.0 == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /dev/fd/12
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=19125'
    +(anon):46> [[ 15 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 15 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 15 'pgid[$#pgid+1]'
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '               19125' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /private/var/folders/wg/2vv9vb815hn9d2d22wfdff2m0000gn/T/gitstatus.POWERLEVEL9K.501.15418.1593835913.2.fifo
    +(anon):63> [[ 14 == <1-> ]]
    +(anon):64> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):66> print -nru 14 -- $'hello\C-_\C-^'
    +(anon):67> local expected=$'hello\C-_0\C-^' actual
    +(anon):68> ((  1  ))
    +(anon):68> [[ ! -t 1 ]]
    +(anon):71> local -F deadline=1
    +(anon):73> true
    +(anon):74> [[ -t 15 ]]
    +(anon):75> sysread -s 1 -t 5.0000000000 -i 15 actual
    +(anon):75> return

  Daemon log (/private/var/folders/wg/2vv9vb815hn9d2d22wfdff2m0000gn/T/gitstatus.POWERLEVEL9K.501.15418.1593835913.2.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=19125
    +_gitstatus_daemon_p9k_:4> [[ 19125 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /private/var/folders/wg/2vv9vb815hn9d2d22wfdff2m0000gn/T/gitstatus.POWERLEVEL9K.501.15418.1593835913.2.lock
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='darwin x86_64'
    +_gitstatus_daemon_p9k_:13> [[ 'darwin x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=darwin
    +_gitstatus_daemon_p9k_:15> local uname_m=x86_64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:21> [[ darwin == linux ]]
    +_gitstatus_daemon_p9k_:22> cpus=+_gitstatus_daemon_p9k_:22> sysctl -n hw.ncpu
    +_gitstatus_daemon_p9k_:22> cpus=8
    +_gitstatus_daemon_p9k_:27> args+=( -t 16 )
    +_gitstatus_daemon_p9k_:30> mkfifo -- /private/var/folders/wg/2vv9vb815hn9d2d22wfdff2m0000gn/T/gitstatus.POWERLEVEL9K.501.15418.1593835913.2.fifo
    +_gitstatus_daemon_p9k_:31> print -rnu 14 -- '               19125'
    +_gitstatus_daemon_p9k_:33> zf_rm -- /private/var/folders/wg/2vv9vb815hn9d2d22wfdff2m0000gn/T/gitstatus.POWERLEVEL9K.501.15418.1593835913.2.fifo
    +_gitstatus_daemon_p9k_:35> local _gitstatus_zsh_daemon _gitstatus_zsh_version _gitstatus_zsh_downloaded
    +_gitstatus_daemon_p9k_:43> local gitstatus_plugin_dir_var=_gitstatus_plugin_dir_p9k_
    +_gitstatus_daemon_p9k_:44> local gitstatus_plugin_dir=/Users/user/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_daemon_p9k_:45> set -- -d /Users/user/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&14' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_daemon_p9k_:47> [[ 1 == (|-|+)<1-> ]]
    +_gitstatus_daemon_p9k_:48> source /Users/user/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install
    +source:1> iterm2_set_user_var awsProfile
    +iterm2_set_user_var:1> printf %s ''
    +iterm2_set_user_var:1> base64
    +iterm2_set_user_var:1> tr -d '\n'
    +iterm2_set_user_var:1> printf '\033]1337;SetUserVar=%s=%s\007' awsProfile
    +source:2> node -v
    +source:2> iterm2_set_user_var nodeVersion v14.3.0
    +iterm2_set_user_var:1> printf %s v14.3.0
    +iterm2_set_user_var:1> base64
    +iterm2_set_user_var:1> tr -d '\n'
    +iterm2_set_user_var:1> printf '\033]1337;SetUserVar=%s=%s\007' nodeVersion 'djE0LjMuMA=='
    +source:3> pwd
    +source:3> iterm2_set_user_var pwd /
    +iterm2_set_user_var:1> printf %s /
    +iterm2_set_user_var:1> base64
    +iterm2_set_user_var:1> tr -d '\n'
    +iterm2_set_user_var:1> printf '\033]1337;SetUserVar=%s=%s\007' pwd 'Lw=='
    +_gitstatus_daemon_p9k_:49> [[ -n '' ]]
    +_gitstatus_daemon_p9k_:49> return
    +_gitstatus_daemon_p9k_:84> local -i ret=1
    +_gitstatus_daemon_p9k_:85> zf_rm -f -- /private/var/folders/wg/2vv9vb815hn9d2d22wfdff2m0000gn/T/gitstatus.POWERLEVEL9K.501.15418.1593835913.2.lock /private/var/folders/wg/2vv9vb815hn9d2d22wfdff2m0000gn/T/gitstatus.POWERLEVEL9K.501.15418.1593835913.2.fifo
    +_gitstatus_daemon_p9k_:86> kill -- -19125

  System information:

    zsh:      5.8
    uname -a: Darwin MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by romkatv** [comment]
From the logs it looks like your zsh config redefines builtin `source` as a function that does something very different from the builtin. It looks along these lines:

```zsh
source() {
  iterm2_set_user_var awsProfile $AWS_PROFILE
  iterm2_set_user_var nodeVersion $(node -v)
  iterm2_set_user_var pwd $(pwd)
}
```

I've changed gitstatus source code to work around this issue. Please update and see if it helps. Even if it does, many other things may break on your system. Basically, anything that uses `source`.

It's generally not a good idea to redefine builtins. If you also redefine things like `true`, `local`, `unset`, etc., gitstatus won't work. Please don't file a bug in this case but rather fix your config.
