### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by barfin** [romkatv/gitstatus#156]
https://gist.github.com/barfin/cd8796fce729bce0a5bb56ecd62c5884

**Comment by romkatv** [comment]
If you are installing powerlevel10k through a method not listed in the [powerlevel10k docs](https://github.com/romkatv/powerlevel10k/blob/master/README.md#installation), and it doesn't work, please file bugs against the distributor. This time I've filed https://bugs.archlinux.org/task/67213 myself but in the future please do it on your own.
