### ISSUE TITLE
Read this if you are using zsh-theme-powerlevel10k community package on Arch Linux and seeing error "gitstatus failed to initialize"

### ISSUE THREAD

**Issue by romkatv** [romkatv/gitstatus#157]
If you are installing powerlevel10k through a method not listed in the [powerlevel10k docs](https://github.com/romkatv/powerlevel10k/blob/master/README.md#installation), and it doesn't work, please file bugs against the distributor. This time I've filed https://bugs.archlinux.org/task/67213 myself but in the future please do it on your own.

Installation methods not listed in the [powerlevel10k docs](https://github.com/romkatv/powerlevel10k/blob/master/README.md#installation) are not officially supported by powerlevel10k. Use them on your own risk.

**Comment by fdev31** [comment]
Thank you!
```
cp /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd ~/.cache/gitstatus
```
is working in the meantime..

**Comment by romkatv** [comment]
For the record: I don't endorse this workaround.
