### ISSUE TITLE
Faster Dots() implementation

### ISSUE THREAD

**Issue by MostParsingVex** [romkatv/gitstatus#16]
This is probably not very important but after reading your `Dots()` implementation, I couldn't help but hack together another implementation that runs more than twice as fast on my hardware. (sorry for the crufty testbench)

I believe this is faster because it avoids one or more branches. *Note that this code only works on little endian ASCII environments.* Big endian and non ASCII versions are probably fairly straightforward. 

It looks like you mostly want the *inverse* of `Dots()`, in which case you may want to apply DeMorgan's theorem to avoid the extra inversion. I haven't checked the assembler output of gcc or clang to see if it is smart enough to do that automatically for you.

    #include<iostream>
    bool Dots(const char* name) {
      if (name[0] == '.') {
        if (name[1] == 0) return true;
        if (name[1] == '.' && name[2] == 0) return true;
      }
      return false;
    }
    bool FasterDots(const char* s) {return (*(int*)s&65535) == '.' | (*(int*)s&16777215) == 0x2e2e; }
    const int len = 16777216*2;
    int main(){
      int j=0;
      int* a = new int[ len ];
      for( int i = 0; i < len; i++ ) {
        a[i] = i;
      }

      for( int k=0; k<100; k++ ) {
        for( int i = 0; i < len; i++ ) {
          //j+= Dots((char*)(a+i));
          j+= FasterDots((char*)(a+i));
        }
      }
      std::cout<<j<<'\n';
    }

Edit: Slightly less bad example code.

**Comment by romkatv** [comment]
I've changed the benchmark to be more representative. In my sample of large git repositories the ratio of files to directories is 11:1. Thus, a file name is neither "." nor ".." with probability 11/13, or 85%. Also, all `Dots()` arguments are aligned to `8 * N + 3` in real code, so I changed this as well. This required changing your code to avoid Undefined Behavior. Lastly, the result of `Dots()` is used in a branch, so I did the same in the benchmark. Here's the code:

```c++
#include <sys/time.h>

#include <cstddef>
#include <cstdlib>
#include <cstring>
#include <iostream>

bool Dots(const char* name) {
  if (name[0] == '.') {
    if (name[1] == 0) return true;
    if (name[1] == '.' && name[2] == 0) return true;
  }
  return false;
}

bool FasterDots(const char* name) {
  int x;
  std::memcpy(&x, name, sizeof(x));
  return ((x & 0xffff) == 0x2e) | ((x & 0xffffff) == 0x2e2e);
}

double WallTimeMs() {
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return 1e3 * ts.tv_sec + 1e-6 * ts.tv_nsec;
}

int main() {
  static_assert(sizeof(int) == 4);
  constexpr size_t kNumFiles = 13;
  constexpr size_t kNumIters = 256 << 20;

  alignas(8) char data[4 * kNumFiles + 3] = {};
  data[3] = '.';
  data[7] = '.';
  data[8] = '.';

  for (const char* p = data + 3; p != data + sizeof(data); p += 4) {
    bool expected = *p == '.';
    if (Dots(p) != expected || FasterDots(p) != expected) std::abort();
  }

  auto Benchmark = [&](const char* label, auto F) {
    volatile int sink = 0;
    for (size_t run = 0; run != 2; ++run) {
      double start = WallTimeMs();
      for (size_t i = 0; i != kNumIters; ++i) {
        for (const char* p = data + 3; p != data + sizeof(data); p += 4) {
          asm volatile("" : : "r,m"(p) : "memory");
          if (!F(p)) sink = 0;
        }
      }
      if (run) std::cout << label << ": " << (WallTimeMs() - start) << " ms." << std::endl;
    }
  };

  Benchmark("Dots", [](const char* s) { return Dots(s); });
  Benchmark("FasterDots", [](const char* s) { return FasterDots(s); });
}
```

Sample run:

```
$ g++ -std=c++17 -O3 dots.cc && ./a.out
Dots: 721.442 ms.
FasterDots: 1043.43 ms.
```

So on this benchmark `Dots()` is faster.

I then tried to see if it's faster on real data but couldn't get a large enough directory structure for `Dots()` to make a difference. Given that `FasterDots()` is more complex, requires conditional code for Little Endian and Big Endian, is slower on an artificial benchmark, and doesn't make a difference on performance of gitstatusd on real data, I'm inclined to keep the current version of `Dots()`.

Having said that, thanks for raising this issue. It's been fun exploring this potential optimization.
