### ISSUE TITLE
Homebrew gitstatus: `-bash: ${uname_sm,,}: bad substitution`

### ISSUE THREAD

**Issue by douglasdd** [romkatv/gitstatus#161]
Installed from Homebrew on Mac 10.14.6, as `/usr/local/Cellar/gitstatus/1.2.2` 
(/bin/bash is just Apple's `3.2.57(1)-release`)

Reproduce:

1. system as above && install gitstatus from Homebrew
2. already have an over-engineered bash prompt of my own with some git info
3. cd into a git work dir with two dirty files
4. `source /usr/local/opt/gitstatus/gitstatus.prompt.sh`

Expected: 

* prompt with some git status indicator

Actual: 

    -bash: ${uname_sm,,}: bad substitution
    
    # and prompt has no git decorations:
    ddd@roc ~/ds
    $ 

<img width="637" alt="gitstatusd-err" src="https://user-images.githubusercontent.com/438630/87225177-7213eb80-c38b-11ea-9f6c-faf25cadb583.png">

Full log (also attached):

    Last login: Sat Jun  6 14:57:34 on ttys007
    ProductName:    Mac OS X
    ProductVersion: 10.11.6
    BuildVersion:   15G1108
    [15:04:15 Sat Jul 11] X:0 !1
    [ddd@roc] ~
    $ cd ds
    [15:04:17 Sat Jul 11] >_*_>git:master<< X:0 !2
    [ddd@roc] ~/ds
    $ source /usr/local/opt/gitstatus/gitstatus.prompt.sh
    -bash: ${uname_sm,,}: bad substitution
    ddd@roc ~/ds
    $ cd bin
    ddd@roc ~/ds/bin
    $ type -a bash
    bash is /bin/bash
    ddd@roc ~/ds/settings
    $ bash --version
    GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
    Copyright (C) 2007 Free Software Foundation, Inc.
    ddd@roc ~/ds/settings
    $

[gitstatusd-err.txt](https://github.com/romkatv/gitstatus/files/4906834/gitstatusd-err.txt)

Git status in that directory:

    $ git stat
    On branch master
    Your branch is up to date with 'bitbucket/master'.
    
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)
    
            modified:   settings/brew-installed_host_roc.names
            modified:   settings/brew-installed_host_roc.txt

**Comment by romkatv** [comment]
Your bash is too old. Install the new version from brew and make it your logic shell.
