### ISSUE TITLE
Updating gitstatus made cygwin unusable.

### ISSUE THREAD

**Issue by Jeklah** [romkatv/gitstatus#164]
So I updated powerlevel10k and gitstatus would not initialise. I went to build from source following the same instructions I got it to work last time and it's totally ruined my cygwin installation. I can't launch a terminal, update or even uninstall using the script. I just have to manually delete the folder. 

Reinstallation of cygwin does not solve issue.
As a result I'm currently unable to get access to a terminal at all.

**Comment by romkatv** [comment]
Oh man, that sucks.

**Comment by romkatv** [comment]
I've received the message and I empathize. Is there anything you expect me to do on this issue or shell I close it?

**Comment by romkatv** [comment]
Closing as nothing has been requested from me.
