### ISSUE TITLE
[ERROR] macOSX - gitstatus failed to initialize

### ISSUE THREAD

**Issue by s0ap** [romkatv/gitstatus#166]
Whenever I open a terminal, I get the below error. I'm not sure what happened but it started appearing in the last 2 weeks. Can you please help fix it?

Thanks!! 
-------------------------
ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:

    GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K
 ~  GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K                                                                               ✔  at 01:45:53
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /var/folders/fy/dfkwrq3s0yz1zbszdysq7dcc0000gn/T//gitstatus.25042.xtrace.1595276175.9348340034.22574 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local daemon='' os
    +gitstatus_start_impl:8> [[ -n '' ]]
    +gitstatus_start_impl:9> os=+gitstatus_start_impl:9> uname -s
    +gitstatus_start_impl:9> os=Darwin
    +gitstatus_start_impl:9> [[ -n Darwin ]]
    +gitstatus_start_impl:10> [[ Darwin != Linux ]]
    +gitstatus_start_impl:11> local arch
    +gitstatus_start_impl:11> arch=+gitstatus_start_impl:11> uname -m
    +gitstatus_start_impl:11> arch=x86_64
    +gitstatus_start_impl:11> [[ -n x86_64 ]]
    +gitstatus_start_impl:12> daemon=/Users/vishad.bhalodia/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
    +gitstatus_start_impl:14> [[ -x /Users/vishad.bhalodia/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 ]]
                               ^ this command failed

  Your system information:

    zsh:      5.7.1
    uname -a: Darwin vishad.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

**Comment by romkatv** [comment]
According to the logs, you are using a very old version of powerlevel10k and at songs point some of us files got either deleted or corrupted. I suggest updating powerlevel10k to the latest version. See https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-update-powerlevel10k

**Comment by s0ap** [comment]
Awesome - updating the git repo fixed it. Is there a way to set it to auto-update?

**Comment by romkatv** [comment]
If you are using oh my zsh, the answer is No.
