### ISSUE TITLE
Build fails with `unexpected EOF`

### ISSUE THREAD

**Issue by indirect** [romkatv/gitstatus#167]
Hello! Thank you for `gitstatus`, it is wonderful.

I am trying to build gitstatus myself for target `arm64-apple-darwin20.0.0`. When I have pulled the latest commit, I get a shell error trying to follow the build instructions:

```
$ git sha
b157d02a9a89892f228064e06b5a817a24eea9ed
$ ./build -w -s -d docker
./build: line 481: unexpected EOF while looking for matching `''
```

Perhaps this is because my `sh` is actually Bash 3.2.57, installed with macOS?

```
$ sh --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Can you tell me what the shell requirements for the build script are, or if I am doing something else wrong? Thank you.

**Comment by romkatv** [comment]
> Perhaps this is because my `sh` is actually Bash 3.2.57, installed with macOS?

Indeed, that's the culprit.

> Can you tell me what the shell requirements for the build script are, or if I am doing something else wrong? Thank you.

Any POSIX-compliant shell should work. All versions of zsh, ash and dash that I've tried work fine. Bash 4.4 and above should work, too. I confirm that bash 3.2.57 doesn't work.

I suggest either installing a newer version of bash or using any other shell.

```zsh
zsh ./build ...
```

**Comment by indirect** [comment]
Thank you! I was able to successfully compile `gitstatus` on `arm64-apple-darwin20.0.0` by using this command:

```
$ zsh ./build -w -s -c armv8
[...]
SUCCESS: created usrbin/gitstatusd
```

**Comment by romkatv** [comment]
I've updated the build script to automatically set `-c armv8` when compiling for Apple's `arm64` architecture.
