### ISSUE TITLE
Doesn't seem to work with Android partial-clone

### ISSUE THREAD

**Issue by nfischer** [romkatv/gitstatus#169]
I'm not sure how to run gitstatus outside of a shell prompt, but I can confirm this reproduces both in powerlevel10k + zsh 5.8 and gitstatus.prompt.sh + bash 5.0.16 (I'm following [these instructions](https://github.com/romkatv/gitstatus#using-from-bash)).

gitstatus doesn't seem to work with my "partial clone" Android checkout. I recently downloaded an Android checkout with the `repo` tool's [`--partial-clone` flag](https://source.android.com/setup/build/downloading#initializing-a-repo-client) and powerlevel10k no longer shows git information in the shell prompt. It doesn't even show the git branch name, which I would think is relatively easy compared to the other info. I used to have a "regular clone" Android checkout (same steps but without the `--partial-clone` flag), and I can confirm my prompt could handle VCS info as expected in that case. So I'm fairly certain it's particular to the `--partial-clone` mode.

Repro steps:

```sh
# Create an Android checkout
$ mkdir android-checkout
$ cd android-checkout
$ repo init -u https://android.googlesource.com/platform/manifest -b master --partial-clone
$ repo sync -j30 -c # heads up: this command takes ~1hr and uses ~71G disk space

# cd'ing into any git repo should (but doesn't) show VCS info (whatever is normally shown for detached HEAD)
$ cd frameworks/base/

# Create a branch to rule out the possibility this is related to detached HEAD:
$ git checkout -b master -t aosp/master
$ git branch
* master
$ git status
On branch master
Your branch is up to date with 'aosp/master'.

nothing to commit, working tree clean
# Git knows I'm on a branch but I still don't see VCS info in my shell prompt 😢 
```

I'm aware VCS info may appear in powerlevel10k asynchronously, but the prompt doesn't seem to show the grayed-out portion I would expect if it were async. The section is completely empty, as if I were not in a git checkout:

![partial-clone-zsh-issue](https://user-images.githubusercontent.com/5801521/88972239-16da6800-d26a-11ea-8ede-3ad7e84ac052.png)

**Comment by romkatv** [comment]
Yep, almost no Git repo extensions are supported. If you want your favorite extension to work in gitstatusd, add support for it to libgit2.

**Comment by nfischer** [comment]
Thanks for taking a look! I'll keep an eye on the relevant Github issues in libgit2.

Out of curiosity, would it be possible for gitstatus to detect cases like this and fallback to showing just the branch name? That would be a big win for me even if it can't get the other status info.

**Comment by romkatv** [comment]
> would it be possible for gitstatus to detect cases like this and fallback to showing just the branch name?

gitstatusd must not open repositories that have extensions it doesn't understand. These extensions may even affect how branch names are stored, so no info can be retrieved unless all extensions are understood.

It's certainly possible to fall back to `git` command if gitstatusd cannot open a repo. It's quite a bit of work though. This is on my TODO list but I have no immediate plans to work on this.

**Comment by nfischer** [comment]
Ah, thanks for explaining! That sounds perfectly reasonable.
