### ISSUE TITLE
Getting this error every time I restart.

### ISSUE THREAD

**Issue by luigi370** [romkatv/gitstatus#170]
+(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/bc/sbd9s4q96kdfc29pw826vrl00000gn/T/gitstatus.POWERLEVEL9K.501.463.1597152180.2.lock
    +(anon):15> [[ 14 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ -n '' ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /dev/fd/13
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=503'
    +(anon):46> [[ 16 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 16 ]]
    +(anon):41> _gitstatus_daemon_p9k_
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 16 'pgid[$#pgid+1]'
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '                 503' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /private/var/folders/bc/sbd9s4q96kdfc29pw826vrl00000gn/T/gitstatus.POWERLEVEL9K.501.463.1597152180.2.fifo
    +(anon):63> [[ 15 == <1-> ]]
    +(anon):64> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):77> zle -F 16 _gitstatus_process_response_POWERLEVEL9K-_p9k_
    +(anon):90> add-zsh-hook zshexit _gitstatus_cleanup_POWERLEVEL9K-_p9k_
    +add-zsh-hook:15> emulate -L zsh
    +add-zsh-hook:17> local -a hooktypes
    +add-zsh-hook:18> hooktypes=( chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name )
    +add-zsh-hook:22> local usage='Usage: add-zsh-hook hook function\nValid hooks are:\n  chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name'
    +add-zsh-hook:24> local opt
    +add-zsh-hook:25> local -a autoopts
    +add-zsh-hook:26> integer del list help
    +add-zsh-hook:28> getopts dDhLUzk opt
    +add-zsh-hook:55> shift 0
    +add-zsh-hook:57> ((  list  ))
    +add-zsh-hook:60> ((  help || 2 != 2 || 6 == 0  ))
    +add-zsh-hook:65> local hook=zshexit_functions
    +add-zsh-hook:66> local fn=_gitstatus_cleanup_POWERLEVEL9K-_p9k_
    +add-zsh-hook:68> ((  del  ))
    +add-zsh-hook:83> ((  1  ))
    +add-zsh-hook:84> ((  0 == 0  ))
    +add-zsh-hook:85> typeset -ga zshexit_functions
    +add-zsh-hook:86> set -A zshexit_functions _p9k_worker_cleanup _gitstatus_cleanup_POWERLEVEL9K-_p9k_
    +add-zsh-hook:92> autoload -- _gitstatus_cleanup_POWERLEVEL9K-_p9k_
    +(anon):95> print -nru 15 -- $'hello\C-_\C-^'
    +(anon):96> local expected=$'hello\C-_0\C-^' actual
    +(anon):97> ((  1  ))
    +(anon):97> [[ ! -t 1 ]]
    +(anon):100> local -F deadline=1
    +(anon):102> true
    +(anon):103> [[ -t 16 ]]
    +(anon):104> sysread -s 1 -t 5.0000000000 -i 16 actual
    +(anon):104> return
                         ^ this command failed (4)

  The content of /private/var/folders/bc/sbd9s4q96kdfc29pw826vrl00000gn/T/gitstatus.POWERLEVEL9K.501.463.1597152180.2.daemon.log (gitstatus daemon log):

    +_gitstatus_daemon_p9k_:3> local pgid=503
    +_gitstatus_daemon_p9k_:4> [[ 503 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:78> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:81> zsystem flock -- /private/var/folders/bc/sbd9s4q96kdfc29pw826vrl00000gn/T/gitstatus.POWERLEVEL9K.501.463.1597152180.2.lock
    +_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='darwin x86_64'
    +_gitstatus_daemon_p9k_:13> [[ 'darwin x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=darwin
    +_gitstatus_daemon_p9k_:15> local uname_m=x86_64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:21> [[ darwin == linux ]]
    +_gitstatus_daemon_p9k_:22> cpus=+_gitstatus_daemon_p9k_:22> sysctl -n hw.ncpu
    +_gitstatus_daemon_p9k_:22> cpus=8
    +_gitstatus_daemon_p9k_:27> args+=( -t 16 )
    +_gitstatus_daemon_p9k_:30> mkfifo -- /private/var/folders/bc/sbd9s4q96kdfc29pw826vrl00000gn/T/gitstatus.POWERLEVEL9K.501.463.1597152180.2.fifo
    +_gitstatus_daemon_p9k_:31> print -rnu 13 -- '                 503'
    +_gitstatus_daemon_p9k_:33> zf_rm -- /private/var/folders/bc/sbd9s4q96kdfc29pw826vrl00000gn/T/gitstatus.POWERLEVEL9K.501.463.1597152180.2.fifo
    +_gitstatus_daemon_p9k_:35> local _gitstatus_zsh_daemon _gitstatus_zsh_version _gitstatus_zsh_downloaded
    +_gitstatus_daemon_p9k_:43> local gitstatus_plugin_dir_var=_gitstatus_plugin_dir_p9k_
    +_gitstatus_daemon_p9k_:44> local gitstatus_plugin_dir=/Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_daemon_p9k_:45> set -- -d /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_daemon_p9k_:47> [[ 1 == (|-|+)<1-> ]]
    +_gitstatus_daemon_p9k_:48> source /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install
    +/Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install:373> [ -z '' ']'
    +/Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install:374> _gitstatus_install_main /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -d /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:1> [ -n 5.7.1 ']'
    +_gitstatus_install_main:2> emulate -L sh -o no_unset
    +_gitstatus_install_main:7> local argv1=/Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:8> shift
    +_gitstatus_install_main:10> local no_check='' no_install='' uname_s='' uname_m='' gitstatus_dir='' dl_status=''
    +_gitstatus_install_main:11> local opt='' OPTARG='' OPTIND=1
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case d (h)
    +_gitstatus_install_main:14> case d (n)
    +_gitstatus_install_main:14> case d (f)
    +_gitstatus_install_main:14> case d (d)
    +_gitstatus_install_main:54> [ -n '' ']'
    +_gitstatus_install_main:58> [ -z /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus ']'
    +_gitstatus_install_main:62> gitstatus_dir=/Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case s (h)
    +_gitstatus_install_main:14> case s (n)
    +_gitstatus_install_main:14> case s (f)
    +_gitstatus_install_main:14> case s (d)
    +_gitstatus_install_main:14> case s (p)
    +_gitstatus_install_main:14> case s (m)
    +_gitstatus_install_main:14> case s (s)
    +_gitstatus_install_main:87> [ -n '' ']'
    +_gitstatus_install_main:91> [ -z darwin ']'
    +_gitstatus_install_main:95> uname_s=darwin
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case m (h)
    +_gitstatus_install_main:14> case m (n)
    +_gitstatus_install_main:14> case m (f)
    +_gitstatus_install_main:14> case m (d)
    +_gitstatus_install_main:14> case m (p)
    +_gitstatus_install_main:14> case m (m)
    +_gitstatus_install_main:76> [ -n '' ']'
    +_gitstatus_install_main:80> [ -z x86_64 ']'
    +_gitstatus_install_main:84> uname_m=x86_64
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case p (h)
    +_gitstatus_install_main:14> case p (n)
    +_gitstatus_install_main:14> case p (f)
    +_gitstatus_install_main:14> case p (d)
    +_gitstatus_install_main:14> case p (p)
    +_gitstatus_install_main:65> [ -n '' ']'
    +_gitstatus_install_main:69> [ -z 'printf . >&13' ']'
    +_gitstatus_install_main:73> dl_status='printf . >&13'
    +_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf . >&13' -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:103> shift 9
    +_gitstatus_install_main:105> : /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:107> [ -n '' -a -n '' ']'
    +_gitstatus_install_main:112> [ -z darwin ']'
    +_gitstatus_install_main:116> [ -z x86_64 ']'
    +_gitstatus_install_main:121> local daemon=''
    +_gitstatus_install_main:122> local cache_dir=/Volumes/Data/lucho/.cache/gitstatus
    +_gitstatus_install_main:124> [ -z '' ']'
    +_gitstatus_install_main:125> [ -n '' ']'
    +_gitstatus_install_main:129> [ -z '' ']'
    +_gitstatus_install_main:130> daemon=/Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd
    +_gitstatus_install_main:131> [ ! -e /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd ']'
    +_gitstatus_install_main:132> daemon=/Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-x86_64
    +_gitstatus_install_main:133> [ ! -e /Users/lucho/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-x86_64 ']'
    +_gitstatus_install_main:134> daemon=''
    +_gitstatus_install_main:138> [ -n '' ']'
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line=''
    +_gitstatus_install_main:155> [ -n '' ']'
    +_gitstatus_install_main:155> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line='uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355";'
    +_gitstatus_install_main:155> [ -n 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355";' ']'
    +_gitstatus_install_main:157> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
    +_gitstatus_install_main:158> eval 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355";'
    +_gitstatus_install_main:158> uname_s_glob=cygwin_nt-10.0
    +_gitstatus_install_main:158> uname_m_glob=i686
    +_gitstatus_install_main:158> file=gitstatusd-darwin-x86_64
    +_gitstatus_install_main:158> version=v1.0.0
    +_gitstatus_install_main:158> sha256=c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355
    +_gitstatus_install_main:160> [ -z cygwin_nt-10.0 -o -z i686 -o -z gitstatusd-darwin-x86_64 -o -z v1.0.0 -o -z c38342c7a70842067074710250fd8cebea87ae111f032277c2c70a77179b5355 ']'
    +_gitstatus_install_main:169> case darwin (cygwin_nt-10.0)
    +_gitstatus_install_main:169> case darwin (*)
    +_gitstatus_install_main:171> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line='uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad";'
    +_gitstatus_install_main:155> [ -n 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad";' ']'
    +_gitstatus_install_main:157> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
    +_gitstatus_install_main:158> eval 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad";'
    +_gitstatus_install_main:158> uname_s_glob=cygwin_nt-10.0
    +_gitstatus_install_main:158> uname_m_glob=x86_64
    +_gitstatus_install_main:158> file=gitstatusd-darwin-x86_64
    +_gitstatus_install_main:158> version=v1.0.0
    +_gitstatus_install_main:158> sha256=d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad
    +_gitstatus_install_main:160> [ -z cygwin_nt-10.0 -o -z x86_64 -o -z gitstatusd-darwin-x86_64 -o -z v1.0.0 -o -z d30b455e371cd0895c9bd1ff87b8a27e6c3f3c2970b4e993e93fe1a6943962ad ']'
    +_gitstatus_install_main:169> case darwin (cygwin_nt-10.0)
    +_gitstatus_install_main:169> case darwin (*)
    +_gitstatus_install_main:171> continue
    +_gitstatus_install_main:153> IFS='' +_gitstatus_install_main:153> read -r line
    +_gitstatus_install_main:154> line='uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a";'
    +_gitstatus_install_main:155> [ -n 'uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a";' ']'
    +_gitstatus_install_main:157> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
    +_gitstatus_install_main:158> eval 'uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.0.0"; sha256="c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a";'
    +_gitstatus_install_main:158> uname_s_glob=darwin
    +_gitstatus_install_main:158> uname_m_glob=x86_64
    +_gitstatus_install_main:158> file=gitstatusd-darwin-x86_64
    +_gitstatus_install_main:158> version=v1.0.0
    +_gitstatus_install_main:158> sha256=c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a
    +_gitstatus_install_main:160> [ -z darwin -o -z x86_64 -o -z gitstatusd-darwin-x86_64 -o -z v1.0.0 -o -z c71b30027b3c763faa3ff7ad09d66c84403851fafcf798bf5e629b98c2b8384a ']'
    +_gitstatus_install_main:169> case darwin (darwin)
    +_gitstatus_install_main:173> case x86_64 (x86_64)
    +_gitstatus_install_main:180> [ -z '' ']'
    +_gitstatus_install_main:182> local daemon=/Volumes/Data/lucho/.cache/gitstatus/gitstatusd-darwin-x86_64
    +_gitstatus_install_main:183> [ -e /Volumes/Data/lucho/.cache/gitstatus/gitstatusd-darwin-x86_64 ']'
    +_gitstatus_install_main:184> [ 1 '=' 0 ']'
    +_gitstatus_install_main:184> _gitstatus_set_daemon_p9k_ /Volumes/Data/lucho/.cache/gitstatus/gitstatusd-darwin-x86_64 v1.0.0 0
    +_gitstatus_set_daemon_p9k_:1> _gitstatus_zsh_daemon=/Volumes/Data/lucho/.cache/gitstatus/gitstatusd-darwin-x86_64
    +_gitstatus_set_daemon_p9k_:2> _gitstatus_zsh_version=v1.0.0
    +_gitstatus_set_daemon_p9k_:3> _gitstatus_zsh_downloaded=0
    +_gitstatus_install_main:185> return
    +_gitstatus_daemon_p9k_:49> [[ -n /Volumes/Data/lucho/.cache/gitstatus/gitstatusd-darwin-x86_64 ]]
    +_gitstatus_daemon_p9k_:50> [[ -n v1.0.0 ]]
    +_gitstatus_daemon_p9k_:51> [[ 0 == [01] ]]
    +_gitstatus_daemon_p9k_:53> [[ -x /Volumes/Data/lucho/.cache/gitstatus/gitstatusd-darwin-x86_64 ]]
    +_gitstatus_daemon_p9k_:54> /Volumes/Data/lucho/.cache/gitstatus/gitstatusd-darwin-x86_64 -G v1.0.0 -s -1 -u -1 -d -1 -c -1 -m -1 -v DEBUG -t 16
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[0]: "/Volumes/Data/lucho/.cache/gitstatus/gitstatusd-darwin-x86_64"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[1]: "-G"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[2]: "v1.0.0"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[3]: "-s"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[4]: "-1"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[5]: "-u"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[6]: "-1"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[7]: "-d"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[8]: "-1"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[9]: "-c"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[10]: "-1"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[11]: "-m"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[12]: "-1"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[13]: "-v"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[14]: "DEBUG"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[15]: "-t"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/gitstatus.cc:177] argv[16]: "16"
    [2020-08-11 15:23:03 00000001173dadc0 INFO src/thread_pool.cc:81] Spawning 16 thread(s)

  Your system information:

    zsh:      5.7.1
    uname -a: Darwin iMac 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

**Comment by romkatv** [comment]
Sorry, I don’t have time right not to engage in remote debugging. Try updating or reinstalling powerlevel10k. If that doesn’t help, try to debug it yourself.
