### ISSUE TITLE
[Mac] fetching gitstatusd upon a new installation of gitstatus is failing.

### ISSUE THREAD

**Issue by bluz71** [romkatv/gitstatus#171]
Hello,

It has been a while since I upgraded gitstatus, and the procedure is now quite different to late last year. Previously the built binaries where in the repository, now they are fetched the first time the gitstatus plugin script is started.

All good on Linux, the fetching is working fine. Thumbs up.

However, on MacOS Catalina using Homebrew Bash I get this error:

```sh
bash: /var/folders/mw/krwgyln92r1d5phw2prqj7k00000gn/T//gitstatus.bash.13347.PAj6x1Hu76/req.fifo: Interrupted system call

gitstatus_start: failed to start gitstatusd
```

Is the `fetching gitstatusd...[ok]` being skipped entirely?
Is there a manual fetching command I can run?

Best regards.

**Comment by romkatv** [comment]
Please post complete instructions how to reproduce this error.

**Comment by bluz71** [comment]
Ok, I will do my best:

- `git clone --depth 1 https://github.com/bluz71/bash-seafly-prompt ~/.bash-seafly-prompt`

- Add the following to `bashrc`: `. ~/.bash-seafly-prompt/command_prompt.bash`

- `git clone --depth 1 https://github.com/romkatv/gitstatus.git ~/.gitstatus`

- Start a new shell

On Linux the fetching of gitstatusd works automatically (Linux Mint).
On Mac the fetching for me does not (Catalina + Homebrew Bash).

**Comment by romkatv** [comment]
Cannot reproduce by following these instructions. Let's see if you can. Please run the following command and post its output here:

```bash
(
  set -xue
  rm -rf -- ~/.bash-seafly-prompt ~/.gitstatus
  git clone --depth 1 https://github.com/bluz71/bash-seafly-prompt ~/.bash-seafly-prompt
  git clone --depth 1 https://github.com/romkatv/gitstatus.git ~/.gitstatus
  unset BASH_ENV
  if brew list bash &>/dev/null; then
    brew upgrade bash
  else
    brew install bash
  fi
  /usr/local/bin/bash --version
  exec /usr/local/bin/bash --rcfile <(echo '. ~/.bash-seafly-prompt/command_prompt.bash') -i
)
```

**Comment by bluz71** [comment]
Hmm, that worked:

```sh
+ rm -rf -- /Users/dennis/.bash-seafly-prompt /Users/dennis/.gitstatus
+ git clone --depth 1 https://github.com/bluz71/bash-seafly-prompt /Users/dennis/.bash-seafly-prompt
Cloning into '/Users/dennis/.bash-seafly-prompt'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), 6.14 KiB | 1.23 MiB/s, done.
+ git clone --depth 1 https://github.com/romkatv/gitstatus.git /Users/dennis/.gitstatus
Cloning into '/Users/dennis/.gitstatus'...
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 67 (delta 12), reused 26 (delta 1), pack-reused 0
Unpacking objects: 100% (67/67), 111.09 KiB | 332.00 KiB/s, done.
+ unset BASH_ENV
+ brew list bash
+ brew upgrade bash
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 2 formulae.
==> Updated Casks
couchbase-server-enterprise               imgotv                                    upic
futuniuniu                                terminus

Warning: bash 5.0.18 already installed
+ /usr/local/bin/bash --version
GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
+ exec /usr/local/bin/bash --rcfile /dev/fd/63 -i
++ echo '. ~/.bash-seafly-prompt/command_prompt.bash'
[gitstatus] fetching gitstatusd .. [ok]
```

Let me re-track my original failure, I am now confused.

**Comment by romkatv** [comment]
There is probably something in your bash startup files that makes it fail. Try to find out what that is.

You can remove gitstatusd so that it gets fetched again with this command:

```bash
rm -- ~/.cache/gitstatus/gitstatusd-linux-x86_64
```

**Comment by romkatv** [comment]
Another possibility is that you aren't using the version of bash you think you are using. Type `echo $BASH_VERSION` to check.

**Comment by bluz71** [comment]
We could have multiple issues:

The fetching is being done by `exec /usr/local/bin/bash --rcfile <(echo '. ~/.bash-seafly-prompt/command_prompt.bash') -i`, but not automatically via the checked out plugin script. I can't get that to work (for now).

And, even with the hand-invoked fetching I am still getting:

```sh
-bash: /var/folders/mw/krwgyln92r1d5phw2prqj7k00000gn/T//gitstatus.bash.15700.I25WWQSwWO/req.fifo: Interrupted system call

gitstatus_start: failed to start gitstatusd
```

The `~/.cache/gitstatus` directory does exist.

So, we may need to solve the later before solving the former.

> There is probably something in your bash startup files that makes it fail.

Maybe so, but I do use the same `~/.bashrc` for both Mac and Linux and on Linux there are none of these issues. Most perplexing.

**Comment by bluz71** [comment]
> echo $BASH_VERSION

`5.0.18(1)-release`

**Comment by bluz71** [comment]
For some reason my use of the following in my `~/.bashrc` causes big problems for `gitstatus` on Mac:

```sh
set -o noclobber
```

I use it to prevent `foo > bar` accidentally overwriting file `bar`. It is a legitimate thing for a user to set.

Let me see if unsetting it also solves the fetch problem.

**Comment by bluz71** [comment]
Yes, `set -o noclobber` broke the fetching as well on Mac.

So that is the problem here.

Interestingly I also use `set -o noclobber` on Linux without causing any `gitstatus` issues. Very strange that is causes issues for `gitstatus` on Mac.

Hopefully you can work around it, it should be repeatable now for you.

**Comment by romkatv** [comment]
> The fetching is being done by `exec /usr/local/bin/bash --rcfile <(echo '. ~/.bash-seafly-prompt/command_prompt.bash') -i`

This command simply starts bash with .bashrc containing just one line:

```bash
. ~/.bash-seafly-prompt/command_prompt.bash
```

If you replace your .bashrc with this content, you can replace the command with plain `/usr/local/bin/bash -i` and you’ll get the same effect.

**Comment by bluz71** [comment]
@romkatv,

Try setting `set -o noclobber` in your Bash setup on Mac. I believe that is the issue.

**Comment by romkatv** [comment]
> @romkatv,
> 
> Try setting `set -o noclobber` in your Bash setup on Mac. I believe that is the issue.

Yeah, I’ve understood this from your previous comment. I just wanted to clear out the confusion about what the command I’ve posted does.

**Comment by romkatv** [comment]
I’ll get back to this issue in a few days. In the meantime I suggest moving your custom options to the bottom of .bashrc. It’sa good idea in general.

**Comment by bluz71** [comment]
> I’ll get back to this issue in a few days.

Sure, no worries.

> In the meantime I suggest moving your custom options to the bottom of .bashrc.

For now, I just moved `set -o noclobber` until after loading the seafly prompt, that works well.

I am glad we figured the cause quite quickly.

**Comment by bluz71** [comment]
I have said this before, but this is a genuinely great project.

Many thanks.

**Comment by romkatv** [comment]
Fixed. Thanks for reporting this issue!

**Comment by bluz71** [comment]
Cheers for such a speedy fix. Great work!
