### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by wentura77** [romkatv/gitstatus#172]
+(anon):7> setopt monitor
+(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
+(anon):10> [[ -r /proc/version ]]
+(anon):13> print -rn
+(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.1001.63407.1597616867.2.lock
+(anon):15> [[ 14 == <1-> ]]
+(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
+(anon):20> [[ openbsd6.7 == cygwin* ]]
+(anon):41> sysopen -r -o cloexec -u resp_fd /dev/fd/13
+(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=16423'
+(anon):46> [[ 16 == <1-> ]]
+(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
+(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
+(anon):51> ((  ! async  ))
+(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
+(anon):54> local pgid
+(anon):55> ((  0 < 20  ))
+(anon):56> [[ -t 16 ]]
+(anon):57> sysread -s 20 -t 5.0000000000 -i 16 'pgid[$#pgid+1]'
+(anon):41> _gitstatus_daemon_p9k_
+_gitstatus_daemon_p9k_:1> local -i pipe_fd
+(anon):55> ((  20 < 20  ))
+(anon):59> [[ '               16423' == \ #<1-> ]]
+(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
+(anon):62> sysopen -w -o cloexec -u req_fd -- /tmp/gitstatus.POWERLEVEL9K.1001.63407.1597616867.2.fifo
+(anon):63> [[ 15 == <1-> ]]
+(anon):64> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
+(anon):66> print -nru 15 -- $'hello\C-_\C-^'
+(anon):67> local expected=$'hello\C-_0\C-^' actual
+(anon):68> ((  1  ))
+(anon):68> [[ ! -t 1 ]]
+(anon):71> local -F deadline=1
+(anon):73> true
+(anon):74> [[ -t 16 ]]
+(anon):75> sysread -s 1 -t 5.0000000000 -i 16 actual
+(anon):75> return

**Comment by romkatv** [comment]
There is no prebuilt binary for openbsd. You can compile it yourself if you like.
