### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.                                                                                                                                     

### ISSUE THREAD

**Issue by andypondy** [romkatv/gitstatus#173]
when i open a new shell i get the following error

`     GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s 1 -u 1 -d 1 -c 1 -m -1 POWERLEVEL9K

[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /tmp/gitstatus.479147.xtrace.ZW8aGXPLxI (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:11> local os
    +gitstatus_start_impl:11> os=+gitstatus_start_impl:11> uname -s
    +gitstatus_start_impl:11> os=Linux 
    +gitstatus_start_impl:11> [[ -n Linux ]]
    +gitstatus_start_impl:12> [[ Linux != Linux ||+gitstatus_start_impl:12> uname -o
    +gitstatus_start_impl:12> [[ Linux != Linux || GNU/Linux != Android ]]
    +gitstatus_start_impl:13> local arch
    +gitstatus_start_impl:13> arch=+gitstatus_start_impl:13> uname -m
    +gitstatus_start_impl:13> arch=x86_64 
    +gitstatus_start_impl:13> [[ -n x86_64 ]]
    +gitstatus_start_impl:15> local daemon=/home/apatel/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64
    +gitstatus_start_impl:16> [[ -x /home/apatel/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 ]]
                               ^ this command failed

  Your system information:

    zsh:      5.8
    uname -a: Linux apatel 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`

I have seen a couple of other similar issues but those resolutions did not really fix my problem

**Comment by romkatv** [comment]
First of all, if you've defined any parameters (in `~/.zshrc` or anywhere else) whose names start with `GITSTATUS`, remove them.

Then, run this command:

```zsh
() {
  emulate -L zsh -o err_return -o xtrace
  command rm -rf -- ~/.oh-my-zsh/custom/themes/powerlevel10k
  command git clone --depth=1 -- https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
  exec zsh
}
```

**Comment by andypondy** [comment]
I don't have them in ~/.zshrc or ~/.zprofile.

anywhere else they could be set (not by me though)
