### ISSUE TITLE
gitstatusd is not registering in utmp

### ISSUE THREAD

**Issue by MikeyBeez** [romkatv/gitstatus#174]
sudo chrootkit shows the following:

Checking `chkutmp'...                                        The tty of the following user process(es) were not found
 in /var/run/utmp !
! RUID          PID TTY    CMD
! bard         7585 pts/0  /home/bard/.cache/gitstatus/gitstatusd-linux-x86_64 -G v1.0.0 -s -1 -u -1 -d -1 -c -1 -m -1 -v FATAL -t 24
! bard         7366 pts/0  /usr/bin/zsh
! bard         7547 pts/0  /usr/bin/zsh
! bard         7582 pts/0  /usr/bin/zsh
! bard         7584 pts/0  /usr/bin/zsh
! root         7625 pts/0  /bin/sh /usr/sbin/chkrootkit
! root         8318 pts/0  ./chkutmp
! root         8320 pts/0  ps axk tty,ruser,args -o tty,pid,ruser,args
! root         8319 pts/0  sh -c ps axk "tty,ruser,args" -o "tty,pid,ruser,args"

**Comment by MikeyBeez** [comment]
Thank you very much.  I'm sorry to be a pain.

**Comment by romkatv** [comment]
> Thank you very much. I'm sorry to be a pain.

No problem at all. Sorry I wasn't of much help on this issue.
