### ISSUE TITLE
Cross compile for termux

### ISSUE THREAD

**Issue by doronbehar** [romkatv/gitstatus#175]
Hi :)

I'd like to package gitstatus to termux-packages, so I'll be able to see in my prompt's git's status on termux. What I tried is:

```sh
git clone https://github.com/termux/termux-packages
cd termux-packages
mkdir packages/gitstatus
cat > packages/gitstatus/build.sh <<< EOF
TERMUX_PKG_HOMEPAGE=https://github.com/romkatv/gitstatus
TERMUX_PKG_DESCRIPTION="Git status for Bash and Zsh prompt"
TERMUX_PKG_LICENSE="GPL-V3"
TERMUX_PKG_VERSION=1.3.0
TERMUX_PKG_SRCURL=$TERMUX_PKG_HOMEPAGE.git
TERMUX_PKG_GIT_BRANCH=v$TERMUX_PKG_VERSION
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_BUILD_DEPENDS="wget"

termux_step_make() {
	termux_setup_cmake
	source ./build.info
	termux_download \
		https://github.com/romkatv/libgit2/archive/${libgit2_version}.tar.gz \
		./deps/libgit2-"$libgit2_version".tar.gz \
		$libgit2_sha256
	uname -a
	./build -w
}
EOF
./scripts/run-docker.sh ./build-package.sh -I gitstatus
```

But cmake then fails to compile a simple C program with termux' clang compiler:

```
-- Check for working C compiler: /home/builder/.termux-build/_cache/android-r21d-api-24-v3/bin/aarch64-linux-android-clang - broken
CMake Error at /home/builder/.termux-build/_cache/cmake-3.18.1/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/home/builder/.termux-build/_cache/android-r21d-api-24-v3/bin/aarch64-linux-android-clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /tmp/gitstatus-build.bDtYAyIO8l/libgit2/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make cmTC_17446/fast && /usr/bin/make  -f CMakeFiles/cmTC_17446.dir/build.make CMakeFiles/cmTC_17446.dir/build
    make[1]: Entering directory '/tmp/gitstatus-build.bDtYAyIO8l/libgit2/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_17446.dir/testCCompiler.c.o
    /home/builder/.termux-build/_cache/android-r21d-api-24-v3/bin/aarch64-linux-android-clang   -march=x86-64 -fno-plt -mtune=generic  -o CMakeFiles/cmTC_17446.dir/testCCompiler.c.o -c /tmp/gitstatus-build.bDtYAyIO8l/libgit2/build/CMakeFiles/CMakeTmp/testCCompiler.c
    clang: error: the clang compiler does not support '-march=x86-64'
    make[1]: *** [CMakeFiles/cmTC_17446.dir/build.make:85: CMakeFiles/cmTC_17446.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory '/tmp/gitstatus-build.bDtYAyIO8l/libgit2/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:140: cmTC_17446/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:14 (PROJECT)


-- Configuring incomplete, errors occurred!
```

It's a weird situation where termux already defaults to a cross compiler, and when one runs `./build-package.sh`, the correct compiler is chosen as well. OTH, gitstatus' `./build.sh` is also capable of cross compiling, but the fact it uses `-mARCH` makes the build fail? I'm not sure what's going on and I tried other variants of this as well, with no success.

Ideally, CI should push to this project's releases, assets of gitstatus compiled for all [supported platforms](https://github.com/romkatv/gitstatus/blob/3f874d9c5933d184b9b06472dcf25e8debb326a8/build#L410-L417), and this used by your awesome p10k and thus spare me the pain.

In the past you helped me compile gitstatus on the device and for that I'm grateful. But now it's different - I'm trying to cross build it and package it, so every new release of it will automatically be used on my device and thus spare me the hassle of recompiling it every release.

**Comment by doronbehar** [comment]
Useful links:

- https://github.com/termux/termux-packages/wiki/Build-environment#changing-default-behaviour
- https://github.com/termux/termux-packages/wiki/Building-packages#build-options

**Comment by romkatv** [comment]
gitstatus works out of the box on termux. Have you tried following the standard installation instructions? If they don't work, what error are you getting?

**Comment by doronbehar** [comment]
You were right :). I just didn't update powerlevel10k for too long and now my architecture is supported. Thanks for your maintenance! Sorry for the noise.
