### ISSUE TITLE
Not detecting shallow clones with 1 additional commit

### ISSUE THREAD

**Issue by a-vrma** [romkatv/gitstatus#179]
I'm on GNU bash version 5 using the prompt that ships with gitstatus
(`gitstatus.prompt.sh`). It stops detecting a repository as a git repository after 1
commit. Here is how to reproduce:

```bash
git clone --depth 1 'https://github.com/romkatv/gitstatus.git' g
cd g
printf test >> README.md
git commit -am 'test'
```

At this point, the "master" in my prompt disappears. Runnning

```bash
echo "$VCS_STATUS_RESULT"
```

gives me `norepo-sync`.

**Comment by romkatv** [comment]
Yep, that’s a known bug. See https://github.com/romkatv/powerlevel10k/issues/787.

**Comment by romkatv** [comment]
Fixed.
