### ISSUE TITLE
Problem with gitstatus initialize (termux)

### ISSUE THREAD

**Issue by proxer05** [romkatv/gitstatus#180]
Logs: https://del.dog/efainudame.txt
Device: xiaomi mi a2 lite, arm64-v8a, newest termux

**Comment by romkatv** [comment]
This is the culprit:

```text
mktemp: failed to create file via template ‘/data/data/com.termux/files/home/.cache/gitstatus/gitstatusd.XXXXXXXXXX’: Permission denied
```

Seems like on your system `$TMPDIR` is not writable. Why is that?

**Comment by proxer05** [comment]
hmm... mktemp working when i type in terminal soo idk why it dont work

**Comment by romkatv** [comment]
Sorry, I misread the log. I think the following is failing. Please try running it and see what happens:

```zsh
mkdir -p -- ~/.cache/foo && touch ~/.cache/foo/bar
```

**Comment by romkatv** [comment]
That's the problem.

**Comment by romkatv** [comment]
Try this to figure out what's wrong:

```zsh
typeset -p USER && ls -ld -- ~ ~/.cache(N)
```

What's the output?

**Comment by romkatv** [comment]
This:

```zsh
typeset -p EUID EGID && ls -ld -- ~ ~/.cache(N)
```

**Comment by proxer05** [comment]
![Screenshot_20201009-174531350](https://user-images.githubusercontent.com/62423996/95603932-402c2700-0a57-11eb-85c0-3317e39abd5b.jpg)

**Comment by romkatv** [comment]
The problem is that `~/.cache` is owned by root and no one has access to it. It's usually a bad idea to have root-owned files in your home directory. You can fix this particular problem with this command:

```zsh
sudo rm -rf ~/.cache
```

After that you can retry gitstatus initialization with this command:

```zsh
exec zsh
```

**Comment by proxer05** [comment]
wow That's working. Thx a lot!
