### ISSUE TITLE
build.info has old version number

### ISSUE THREAD

**Issue by justinkb** [romkatv/gitstatus#181]
Just a tiny thing, see title

**Comment by romkatv** [comment]
Do you mean this line? https://github.com/romkatv/gitstatus/blob/2616cd47e88bcaa4229cc60ff54459d8352535a6/build.info

This value is correct. I know it can be confusing but this parameter is not supposed to be equal to the last version released on GitHub.

**Comment by justinkb** [comment]
Guess I don't understand its purpose if it's not supposed to signify the version number...

**Comment by romkatv** [comment]
It does signify the version number. There is a comment explaining where this number is used. Note that the comment does not say that this number tracks GitHub releases in any way.

**Comment by justinkb** [comment]
if I'm building this from the v1.3.0 tag, I produce a gitstatus that incorrectly reports a v1.2.0 version, I don't understand the rationale behind not keeping this up-to-date at all

**Comment by romkatv** [comment]
> if I'm building this from the v1.3.0 tag, I produce a gitstatus that incorrectly reports a v1.2.0 version

s/incorrectly/correctly/

**Comment by justinkb** [comment]
ok, so you're insane, good to know so I can avoid future interactions

**Comment by romkatv** [comment]
You've never asked any questions, no wonder you didn't get any answers.

**Comment by justinkb** [comment]
Yeah, I didn't think to ask "why are you using a version number if not for the purpose of version numbering", since I didn't realize you were insane, my bad
