### ISSUE TITLE
gitstatus failed to initialize

### ISSUE THREAD

**Issue by buzzdan** [romkatv/gitstatus#191]
✔  GITSTATUS_LOG_LEVEL=DEBUG

export
[ERROR]: gitstatus failed to initialize.

  Zsh log (/private/var/folders/21/x4vz7kyd19z30q2f_jvn_g3c0000gn/T/gitstatus.POWERLEVEL9K.501.21552.1606397319.2.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/21/x4vz7kyd19z30q2f_jvn_g3c0000gn/T/gitstatus.POWERLEVEL9K.501.21552.1606397319.2.lock
    +(anon):15> [[ 13 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ darwin19.0 == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /dev/fd/12
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=22879'
    +(anon):46> [[ 15 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 15 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 15 'pgid[$#pgid+1]'
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '               22879' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /private/var/folders/21/x4vz7kyd19z30q2f_jvn_g3c0000gn/T/gitstatus.POWERLEVEL9K.501.21552.1606397319.2.fifo
    +(anon):63> [[ 14 == <1-> ]]
    +(anon):64> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):66> print -nru 14 -- $'}hello\C-_\C-^'
    +(anon):67> local expected=$'}hello\C-_0\C-^' actual
    +(anon):68> ((  1  ))
    +(anon):68> [[ ! -t 1 ]]
    +(anon):71> local -F deadline=1
    +(anon):73> true
    +(anon):74> [[ -t 15 ]]
    +(anon):75> sysread -s 1 -t 5.0000000000 -i 15 actual
    +(anon):75> return

  Daemon log (/private/var/folders/21/x4vz7kyd19z30q2f_jvn_g3c0000gn/T/gitstatus.POWERLEVEL9K.501.21552.1606397319.2.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=22879
    +_gitstatus_daemon_p9k_:4> [[ 22879 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /private/var/folders/21/x4vz7kyd19z30q2f_jvn_g3c0000gn/T/gitstatus.POWERLEVEL9K.501.21552.1606397319.2.lock
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='darwin x86_64'
    +_gitstatus_daemon_p9k_:13> [[ 'darwin x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=darwin
    +_gitstatus_daemon_p9k_:15> local uname_m=x86_64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:21> [[ darwin == linux ]]
    +_gitstatus_daemon_p9k_:22> cpus=+_gitstatus_daemon_p9k_:22> sysctl -n hw.ncpu
    +_gitstatus_daemon_p9k_:22> cpus=12
    +_gitstatus_daemon_p9k_:27> args+=( -t 24 )
GITSTATUS_LOG_LEVEL=DEBUG    +_gitstatus_daemon_p9k_:30> mkfifo -- /private/var/folders/21/x4vz7kyd19z30q2f_jvn_g3c0000gn/T/gitstatus.POWERLEVEL9K.501.21552.1606397319.2.fifo
    +_gitstatus_daemon_p9k_:31> print -rnu 13 -- '               22879'
    +_gitstatus_daemon_p9k_:33> zf_rm -- /private/var/folders/21/x4vz7kyd19z30q2f_jvn_g3c0000gn/T/gitstatus.POWERLEVEL9K.501.21552.1606397319.2.fifo
    +_gitstatus_daemon_p9k_:35> local _gitstatus_zsh_daemon _gitstatus_zsh_version _gitstatus_zsh_downloaded
    +_gitstatus_daemon_p9k_:43> local gitstatus_plugin_dir_var=_gitstatus_plugin_dir_p9k_
    +_gitstatus_daemon_p9k_:44> local gitstatus_plugin_dir=/Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_daemon_p9k_:45> set -- -d /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_daemon_p9k_:47> [[ 1 == (|-|+)<1-> ]]
    +_gitstatus_daemon_p9k_:48> source /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install
    +/Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install:485> [ -z '' ']'
    +/Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install:486> _gitstatus_install_main /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -d /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:1> [ -n 5.7.1 ']'
    +_gitstatus_install_main:2> emulate -L sh -o no_unset
    +_gitstatus_install_main:7> local argv1=/Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:8> shift
    +_gitstatus_install_main:10> local no_check='' no_install='' uname_s='' uname_m='' gitstatus_dir='' dl_status='' e=''
    +_gitstatus_install_main:11> local opt='' OPTARG='' OPTIND=1
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case d (h)
    +_gitstatus_install_main:14> case d (n)
    +_gitstatus_install_main:14> case d (f)
    +_gitstatus_install_main:14> case d (d)
    +_gitstatus_install_main:55> [ -n '' ']'
    +_gitstatus_install_main:59> [ -z /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus ']'
    +_gitstatus_install_main:63> gitstatus_dir=/Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case s (h)
    +_gitstatus_install_main:14> case s (n)
    +_gitstatus_install_main:14> case s (f)
    +_gitstatus_install_main:14> case s (d)
    +_gitstatus_install_main:14> case s (p)
    +_gitstatus_install_main:14> case s (e)
    +_gitstatus_install_main:14> case s (m)
    +_gitstatus_install_main:14> case s (s)
    +_gitstatus_install_main:99> [ -n '' ']'
    +_gitstatus_install_main:103> [ -z darwin ']'
    +_gitstatus_install_main:107> uname_s=darwin
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case m (h)
    +_gitstatus_install_main:14> case m (n)
    +_gitstatus_install_main:14> case m (f)
    +_gitstatus_install_main:14> case m (d)
    +_gitstatus_install_main:14> case m (p)
    +_gitstatus_install_main:14> case m (e)
    +_gitstatus_install_main:14> case m (m)
    +_gitstatus_install_main:88> [ -n '' ']'
    +_gitstatus_install_main:92> [ -z x86_64 ']'
    +_gitstatus_install_main:96> uname_m=x86_64
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case p (h)
    +_gitstatus_install_main:14> case p (n)
    +_gitstatus_install_main:14> case p (f)
    +_gitstatus_install_main:14> case p (d)
    +_gitstatus_install_main:14> case p (p)
    +_gitstatus_install_main:66> [ -n '' ']'
    +_gitstatus_install_main:70> [ -z 'printf '\''\001'\'' >&13' ']'
    +_gitstatus_install_main:74> dl_status='printf '\''\001'\'' >&13'
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case e (h)
    +_gitstatus_install_main:14> case e (n)
    +_gitstatus_install_main:14> case e (f)
    +_gitstatus_install_main:14> case e (d)
    +_gitstatus_install_main:14> case e (p)
    +_gitstatus_install_main:14> case e (e)
    +_gitstatus_install_main:77> [ -n '' ']'
    +_gitstatus_install_main:81> [ -z 13 ']'
    +_gitstatus_install_main:85> e=13
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s darwin -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:115> shift 11
    +_gitstatus_install_main:117> : 13
    +_gitstatus_install_main:118> : /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:120> [ -n '' -a -n '' ']'
    +_gitstatus_install_main:125> [ -z darwin ']'
    +_gitstatus_install_main:129> [ -z x86_64 ']'
    +_gitstatus_install_main:134> local daemon=''
    +_gitstatus_install_main:135> local cache_dir=/Users/dan_mordechay/.cache/gitstatus
    +_gitstatus_install_main:137> [ -z '' ']'
    +_gitstatus_install_main:138> [ -n '' ']'
    +_gitstatus_install_main:142> [ -z '' -a -e /Users/dan_mordechay/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd ']'
    +_gitstatus_install_main:145> [ -n '' ']'

  System information:

    zsh:      5.7.1
    uname -a: Darwin Dan-Mordechay 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by romkatv** [comment]
?
