### ISSUE TITLE
Where is the gitstatusd binary?

### ISSUE THREAD

**Issue by jasonhan-vassar** [romkatv/gitstatus#193]
Hi, this isn't really an issue or bug report, but just a question that I didn't find the answer to in the README (sorry if I missed it). Is the gitstatusd binary installed elsewhere on my system upon the first run? I saw the initialize message when I first sourced it and I don't see it again. Does this mean the binary is now installed and being called when I start my prompt?

**Comment by romkatv** [comment]
It's in `~/.cache/gitstatus` by default. You can change the location with `GITSTATUS_CACHE_DIR`.

**Comment by jasonhan-vassar** [comment]
Does gitstatus build this from `src` and then move it to `GITSTATUS_CACHE_DIR`?

**Comment by romkatv** [comment]
It gets downloaded from [releases](https://github.com/romkatv/gitstatus/releases/tag/v1.3.1) and its sha256 gets verified to ensure there was no tempering.

**Comment by romkatv** [comment]
You can disable the downloading of officially released binaries with `GITSTATUS_AUTO_INSTALL=1` and build it from source if you want. You'll need to do this every time you update gitstatus.
