### ISSUE TITLE
VCS_STATUS_NUM_STAGED reports double of correct amount inside a certain path

### ISSUE THREAD

**Issue by Cyberbeni** [romkatv/gitstatus#197]
gitstatus version: 1.4.3
macOS 11.0.1 (20B50) x64

I modify 3 files, VCS_STATUS_NUM_UNSTAGED reports 3, VCS_STATUS_NUM_STAGED reports 0 then I `git add .`, now VCS_STATUS_NUM_UNSTAGED reports 0 while VCS_STATUS_NUM_STAGED reports 6

`git status` also shows 3 files modified for the changes to be committed

When I just add and stage a new file next to these, they are also reported as 2 changes, but when I add a new file in the root or inside another directory, it displays as 1 correctly. I have this repository cloned inside 2 different folders, so I can easily interrupt my current task with a quick fix/review and both of them work the same for this. (It's a private repository)

**Comment by romkatv** [comment]
Please provide instructions how to reproduce. Which command do I need to run?

**Comment by Cyberbeni** [comment]
I will check my other repositories later but I can only reproduce it in a private repository currently. Even if I recreate the  path in a new repository, that will report the correct number.

**Comment by romkatv** [comment]
Please do the following:

1. `cd` into the repository that exhibits this issue.
2. Do what you need to do in order to trigger the bug in gitstatus.
3. Run this command after replacing `~/gitstatus` with the real path to `gitstatus` on your machine:
   ```zsh
   () {
     emulate -L zsh -o err_return
     git status
     zsh -feic '
       GITSTATUS_LOG_LEVEL=DEBUG
       source ~/gitstatus/gitstatus.plugin.zsh
       gitstatus_start -s -1 -u -1 -c -1 -d -1 -m -1 MY
       gitstatus_query MY
       typeset -m "VCS_STATUS_*"
       sleep 2
       gitstatus_query MY
       typeset -m "VCS_STATUS_*"
       cat -- $GITSTATUS_DAEMON_LOG_MY'
   } &>/tmp/gitstatus.txt
   ```
4. Attach `/tmp/gitstatus.txt` to this issue.

**Comment by Cyberbeni** [comment]
I sent you the log in email because it contains a bunch of filenames.

**Comment by romkatv** [comment]
> I sent you the log in email because it contains a bunch of filenames.

I haven't received it. My email is roman.perepelitsa@gmail.com.

**Comment by Cyberbeni** [comment]
I sent it again, then I realized my VPN client is acting up again, so I restarted it.

**Comment by romkatv** [comment]
Thanks, I've now received the same email twice.

What is the output of the following command?

```zsh
locale
```

**Comment by Cyberbeni** [comment]
```console
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by romkatv** [comment]
This is on a case-insensitive filesystem, right?

**Comment by Cyberbeni** [comment]
yes

**Comment by Cyberbeni** [comment]
Copied some of the old formulas from [here](https://github.com/romkatv/homebrew-gitstatus) and all the versions I tried have this bug (1.1.0, 1.1.1, 1.2.2, 1.3.0)

**Comment by romkatv** [comment]
I haven't looked at it yet. Before debugging this I'll need to reproduce it locally and that would be much easier if I had more info about your repository.

Please verify that the list of files in the repository is all that's necessary to reproduce this problem. To do that, run the following commands when your current directory is the root of your git repository:

```zsh
rm -rf -- /tmp/repo
git ls-files | LC_ALL=C sort >/tmp/git-files
mkdir /tmp/repo
cd /tmp/repo
git init
xargs mkdir -p -- </tmp/git-files
xargs rmdir -- </tmp/git-files 2>/dev/null
xargs touch -- </tmp/git-files
xargs git add -- </tmp/git-files
git commit -m 'initial commit'
```

When these commands finish, you'll be in `/tmp/repo`. This is a git repository that has the same files as your real git repository but these files are all empty. Please check whether gitstatus exhibits the same problem in this repository.

If you can confirm this, it would help a lot if you could send me `/tmp/git-files`.

**Comment by Cyberbeni** [comment]
Yep, still messed up with empty files, sent it to you in email.

**Comment by romkatv** [comment]
Sorry that I haven't done anything here.

**Comment by Cyberbeni** [comment]
No worries, I started using [zsh-async](https://github.com/mafredri/zsh-async) to update the prompt when `git status` parsing is ready, so the performance of `git status` parsing is not that critical anymore.

**Comment by carlosfrodriguez** [comment]
Would it be possible to reopen this issue, it also happens to me

```shell
❯ gitstatus_start MY                                                                       
~/Developer/Training/Framework/Project test *2 +6                                                                                                                                                                                                06:20:22 PM
❯ gitstatus_query -d $PWD MY
~/Developer/Training/Framework/Project test *2 +6                                                                                                                                                                                                06:20:29 PM
❯ typeset -m 'VCS_STATUS_*'
VCS_STATUS_COMMITS_BEHIND=0
VCS_STATUS_COMMIT_SUMMARY='Fixed search for restricted customer users, fixed also BOL, missing the count.'
VCS_STATUS_PUSH_REMOTE_NAME=''
VCS_STATUS_HAS_UNSTAGED=0
VCS_STATUS_PUSH_COMMITS_AHEAD=0
VCS_STATUS_WORKDIR=/Users/carlos/Developer/Training/Framework/Project
VCS_STATUS_ACTION=''
VCS_STATUS_NUM_SKIP_WORKTREE=0
VCS_STATUS_REMOTE_URL=git@git.testing.es:testproduct/test/test.git
VCS_STATUS_NUM_ASSUME_UNCHANGED=0
VCS_STATUS_COMMITS_AHEAD=0
VCS_STATUS_RESULT=ok-async
VCS_STATUS_NUM_UNSTAGED_DELETED=0
VCS_STATUS_NUM_UNSTAGED=0
VCS_STATUS_LOCAL_BRANCH=test
VCS_STATUS_NUM_STAGED_NEW=0
VCS_STATUS_HAS_CONFLICTED=0
VCS_STATUS_PUSH_REMOTE_URL=''
VCS_STATUS_PUSH_COMMITS_BEHIND=0
VCS_STATUS_REMOTE_NAME=origin
VCS_STATUS_NUM_STAGED=6
VCS_STATUS_NUM_UNTRACKED=0
VCS_STATUS_INDEX_SIZE=10843
VCS_STATUS_REMOTE_BRANCH=test
VCS_STATUS_HAS_STAGED=1
VCS_STATUS_COMMIT_ENCODING=''
VCS_STATUS_TAG=''
VCS_STATUS_HAS_UNTRACKED=0
VCS_STATUS_STASHES=2
VCS_STATUS_NUM_CONFLICTED=0
VCS_STATUS_NUM_STAGED_DELETED=0
VCS_STATUS_COMMIT=6fa9bbb7831a600bffab60ce85b82823cf563773
~/Developer/Training/Framework/Project  test *2 +6                                                                                                                                                                                                06:20:42 PM
❯ git st                    
On branch test
Your branch is up to date with 'origin/test'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   Kernel/System/CustomerCompany.pm
	modified:   Kernel/System/CustomerCompany/DB.pm
	modified:   Kernel/WebApp/Controller/API/Agent/Customer/Company/List.pm

~/Developer/Training/Framework/Project test *2 +6      
```

I have 3 files modified same are staged. but it counts the double


If I un-stage a file keeping modifications it says that I have 4, instead of 2 staged and 1 modified as:

```shell
❯ git st
On branch test
Your branch is up to date with 'origin/test'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   Kernel/System/CustomerCompany.pm
	modified:   Kernel/System/CustomerCompany/DB.pm

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Kernel/WebApp/Controller/API/Agent/Customer/Company/List.pm

~/Developer/Training/Framework/Project test *2 +4     
```
