### ISSUE TITLE
Bug running on iSH App (x86 Alpine)

### ISSUE THREAD

**Issue by Adrian-Grimm** [romkatv/gitstatus#199]
Log:
'
(anon):sysopen:41: can't open file /proc/self/fd/15: no such file or directory

[ERROR]: gitstatus failed to initialize.

  Add the following parameter to ~/.zshrc for extra diagnostics on error:

    GITSTATUS_LOG_LEVEL=DEBUG

  Restart Zsh to retry gitstatus initialization:

    exec zsh
                                                     
[ERROR]: gitstatus failed to initialize.

  Zsh log (/tmp/gitstatus.POWERLEVEL9K.0.34.1608809885.2.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 4.20.69-ish iSH 1.1.1 (91) Dec 21 2020 19:41:45' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.0.34.1608809885.2.lock
    +(anon):15> [[ 13 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ linux-musl == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/12
    (anon):sysopen:41: can't open file /proc/self/fd/12: no such file or directory
    +(anon):41> return
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd

  Daemon log (/tmp/gitstatus.POWERLEVEL9K.0.34.1608809885.2.daemon.log):
      +_gitstatus_daemon_p9k_:3> local pgid=127
    +_gitstatus_daemon_p9k_:4> [[ 127 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.0.34.1608809885.2.lock
    +_gitstatus_daemon_p9k_:12> uname_sm='linux i686' 
    _gitstatus_daemon_p9k_:zsystem:93: failed to open /tmp/gitstatus.POWERLEVEL9K.0.34.1608809885.2.lock for writing: no such file or directory
    +_gitstatus_daemon_p9k_:13> [[ 'linux i686' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=linux
    +_gitstatus_daemon_p9k_:15> local uname_m=i686
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:21> [[ linux == linux ]]
    +_gitstatus_daemon_p9k_:23> ((  ! 1  ))

  System information:

    zsh:      5.8
    uname -a: Linux Adrians-iPhone 4.20.69-ish iSH 1.1.1 (91) Dec 21 2020 19:41:45 i686 Linux

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

'

**Comment by romkatv** [comment]
This is a bug in iSH: https://github.com/ish-app/ish/issues/783.
