### ISSUE TITLE
Every login asking to remove pipes?

### ISSUE THREAD

**Issue by SultanSGillani** [romkatv/gitstatus#2]
I’m getting this on every powelevel10k login:

`rm: remove fifo '/tmp/sultan/gitstatus.18096.pipe.e8hv5uNFv6'?`

Any idea why?

**Comment by romkatv** [comment]
@SultanSGillani So many different environments... I added `-f` to this `rm`. Could you pull and try again?

**Comment by SultanSGillani** [comment]
That fixed it thanks.
