### ISSUE TITLE
I got a error message as the following:

### ISSUE THREAD

**Issue by shrewdacumen** [romkatv/gitstatus#200]
GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start POWERLEVEL9K
[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  The content of /private/var/folders/l9/7cn93zv17fx8b1q33fdr2d2m0000gn/T/gitstatus.POWERLEVEL9K.501.4297.1608826107.xtrace.log (gitstatus_start xtrace):

    +(anon):7> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):8> [[ -r /proc/version ]]
    +(anon):11> print -rn
    +(anon):12> zsystem flock -f lock_fd /private/var/folders/l9/7cn93zv17fx8b1q33fdr2d2m0000gn/T/gitstatus.POWERLEVEL9K.501.4297.1608826107.lock
    +(anon):13> [[ 13 == <1-> ]]
    +(anon):15> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):18> '(anon)' /dev/fd/15
    +(anon):1> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=16392'
    +(anon):2> sysopen -r -o cloexec -u resp_fd -- /dev/fd/15
    +(anon):3> [[ 17 == <1-> ]]
    +(anon):4> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):119> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):122> ((  ! async  ))
    +(anon):123> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):125> local pgid
    +(anon):126> ((  0 < 20  ))
    +(anon):127> [[ -t 17 ]]
    +(anon):128> sysread -s 20 -t 5.0000000000 -i 17 'pgid[$#pgid+1]'
    +(anon):128> return
                         ^ this command failed (5)

  The content of /private/var/folders/l9/7cn93zv17fx8b1q33fdr2d2m0000gn/T/gitstatus.POWERLEVEL9K.501.4297.1608826107.daemon.log (gitstatus daemon log):

    +(anon):20> local pgid=16392
    +(anon):21> [[ 16392 == <1-> ]]
    +(anon):103> ((  lock_fd == -1  ))
    +(anon):25> trap '' PIPE
    +(anon):27> [[ -z '' ]]
    +(anon):28> local kernel
    +(anon):106> zsystem flock -- /private/var/folders/l9/7cn93zv17fx8b1q33fdr2d2m0000gn/T/gitstatus.POWERLEVEL9K.501.4297.1608826107.lock
    +(anon):29> kernel=+(anon):29> uname -s
    +(anon):29> kernel=darwin
    +(anon):30> [[ -n darwin ]]
    +(anon):33> [[ '' == /* ]]
    +(anon):35> ((  0  ))
    +(anon):37> [[ -n '' ]]
    +(anon):40> local -aU os
    +(anon):41> case darwin (linux)
    +(anon):41> case darwin (cygwin_nt-*)
    +(anon):41> case darwin (mingw | msys)
    +(anon):41> case darwin (*)
    +(anon):49> os=( darwin )
    +(anon):51> local arch
    +(anon):52> arch=+(anon):52> uname -m
    +(anon):52> arch=arm64
    +(anon):53> [[ -n arm64 ]]
    +(anon):54> local daemons=( /Users/sungwook/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-arm64 /Users/sungwook/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-arm64-static /Users/sungwook/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-arm64 /Users/sungwook/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-arm64-static )
    +(anon):58> local files=( )
    +(anon):59> daemons=( )
    +(anon):61> ((  stderr_fd && 0 != 0  ))
    +(anon):71> ((  0  ))
    +(anon):71> return
    +(anon):98> local -i ret=1
    +(anon):99> kill -- -16392

  Your system information:

    zsh:      5.8
    uname -a: Darwin Mini2020.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by romkatv** [comment]
Your version of powerlevel10k is very, very old. You need to update it. See https://github.com/romkatv/powerlevel10k/#how-do-i-update-powerlevel10k
