### ISSUE TITLE
gitstatus failing to initialize

### ISSUE THREAD

**Issue by ezzuldinSt** [romkatv/gitstatus#201]
Hello @romkatv could you please help me this issue?
Every time I start my terminal I get this whole massage: 

> [ERROR]: gitstatus failed to initialize.

 Zsh log (/tmp/gitstatus.POWERLEVEL9K.0.296.1609928545.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 4.20.69-ish iSH 1.1.1 (91) Dec 21 2020 19:41:45' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.0.296.1609928545.1.lock
    +(anon):15> [[ 15 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ linux-musl == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/14
    (anon):sysopen:41: can't open file /proc/self/fd/14: no such file or directory
    +(anon):41> return
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd

  Daemon log (/tmp/gitstatus.POWERLEVEL9K.0.296.1609928545.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=461
    +_gitstatus_daemon_p9k_:4> [[ 461 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:11> local uname_sm

  System information:

    zsh:      5.8
    uname -a: Linux iPhone 4.20.69-ish iSH 1.1.1 (91) Dec 21 2020 19:41:45 i686 GNU/Linux 
  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

[ERROR]: gitstatus failed to initialize.

  Zsh log (/tmp/gitstatus.MY.0.296.1609928546.2.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_MY  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 4.20.69-ish iSH 1.1.1 (91) Dec 21 2020 19:41:45' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.MY.0.296.1609928546.2.lock
    +(anon):15> [[ 15 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_MY=lock_fd'
    +(anon):20> [[ linux-musl == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/14
    (anon):sysopen:41: can't open file /proc/self/fd/14: no such file or directory
    +(anon):41> return
    +(anon):41> _gitstatus_daemon
    +_gitstatus_daemon:1> local -i pipe_fd

  Daemon log (/tmp/gitstatus.MY.0.296.1609928546.2.daemon.log):

    +_gitstatus_daemon:3> local pgid=469
    +_gitstatus_daemon:4> [[ 469 == <1-> ]]
    +_gitstatus_daemon:5> cd -q /
    +_gitstatus_daemon:9> trap '' PIPE
    +_gitstatus_daemon:11> local uname_sm
    +_gitstatus_daemon:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon:93> zsystem flock -- /tmp/gitstatus.MY.0.296.1609928546.2.lock
    _gitstatus_daemon:zsystem:93: failed to open /tmp/gitstatus.MY.0.296.1609928546.2.lock for writing: no such file or directory
    +_gitstatus_daemon:12> uname_sm=+_gitstatus_daemon:12> uname -sm
    +_gitstatus_daemon:12> uname_sm='linux i686' 

  System information:

    zsh:      5.8
    uname -a: Linux iPhone 4.20.69-ish iSH 1.1.1 (91) Dec 21 2020 19:41:45 i686 GNU/Linux

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new
_p9k_worker_start:sysopen:6: can't open file /proc/self/fd/11: no such file or directory

**Comment by romkatv** [comment]
This is caused by a bug in iSH: https://github.com/ish-app/ish/issues/783
