### ISSUE TITLE
Fetching gitstatusd fails on Cygwin

### ISSUE THREAD

**Issue by LukeMinnich** [romkatv/gitstatus#202]
System Configuration:
- Cygwin 3.1.6
- Windows 10.0.19041 Build 19041 x64
- zsh 5.8
- oh-my-zsh
- powerlevel10k

I am having the following issue on Cygwin:

```
❯ exec zsh
[powerlevel10k] fetching gitstatusd .. \
[ERROR]: gitstatus failed to initialize.
```

Debug logs are attached. It appears to be failing when creating the gitstatus-install archive.

```
    +_gitstatus_install_main:386> n=1
    +_gitstatus_install_main:387> break
    +_gitstatus_install_main:414> trap - INT QUIT TERM ILL PIPE
    +_gitstatus_install_main:416> [ -z 1 ']'
    +_gitstatus_install_main:426> tar -C /tmp/gitstatus-install.owCzpaa3rW -xzf /tmp/gitstatus-install.owCzpaa3rW/1.tar.gz
    tar.exe: Error opening archive: Failed to open '/tmp/gitstatus-install.owCzpaa3rW/1.tar.gz'
    +_gitstatus_install_main:426> exit
```

Any help you can offer would be greatly appreciated.

[gitstatus.POWERLEVEL9K.197609.2520.1610223881.1.xtrace.log](https://github.com/romkatv/gitstatus/files/5791786/gitstatus.POWERLEVEL9K.197609.2520.1610223881.1.xtrace.log)
[gitstatus.POWERLEVEL9K.197609.2520.1610223881.1.daemon.log](https://github.com/romkatv/gitstatus/files/5791787/gitstatus.POWERLEVEL9K.197609.2520.1610223881.1.daemon.log)

**Comment by romkatv** [comment]
What's the output of `which tar`?

**Comment by LukeMinnich** [comment]
/cygdrive/c/Windows/system32/tar

**Comment by romkatv** [comment]
This is the problem. You need to change PATH so that Cygwin bin directories are listed first.

**Comment by LukeMinnich** [comment]
Oh wild - that solved it. Thanks much!
