### ISSUE TITLE
Binary files cleanup

### ISSUE THREAD

**Issue by ahmubashshir** [romkatv/gitstatus#204]
If possible, please clean up git index using [bfg]
```sh
bfg -b 512K --massive-non-file-objects-sized-up-to 512K .git/
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```
[bfg]: https://rtyley.github.io/bfg-repo-cleaner/

**Comment by romkatv** [comment]
This will rewrite history. This isn’t appropriate for a public repository.
