### ISSUE TITLE
Gitstatusd: Many lingering processes

### ISSUE THREAD

**Issue by dlehenky** [romkatv/gitstatus#206]
Hi. Love your theme, BUT - your implementation assumes that the f/w and network are agreeable to gitstatusd being able to make the OB connection to github. I have OB access rules to prohibit 80/443 traffic, normally. These are servers, not desktop systems. I only open those ports for periodic updates. How do I deal with this and not slow up the shell? -Thanks!

**Comment by romkatv** [comment]
> your implementation assumes that the f/w and network are agreeable to gitstatusd being able to make the OB connection to github.

That’s need to me. Please provide more details. Preferably, describe how to reproduce the issue.

**Comment by dlehenky** [comment]
Will do. It may have something to do with the way the ssh sessions are terminated when closing iTerm2 and leaving gitstatusd in a weird state (which wouldn't be your issue). I'll get back to you if I learn more. Sorry, I was a bit quick on the trigger opening this. Thanks again for your fine effort!

**Comment by romkatv** [comment]
Closing as non-actionable.
