### ISSUE TITLE
When I launch konsole it states this error here and when I go to use the plugin it returns a exclaimation point

### ISSUE THREAD

**Issue by Fuzzypyro** [romkatv/gitstatus#207]
[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:

    GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start POWERLEVEL9K

  If this command produces no output, add the following parameter to ~/.zshrc:

    GITSTATUS_LOG_LEVEL=DEBUG

  With this parameter gitstatus will print additional information on error.
❯ GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start POWERLEVEL9K
[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  The content of /tmp/gitstatus.POWERLEVEL9K.1000.217437.1611781956.2.xtrace.log (gitstatus_start xtrace):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 5.7.19-1-MANJARO-ARM (spikerguy@Manjaro-Vim3) (gcc version 10.2.0 (GCC), GNU ld (GNU Binutils) 2.35) #1 SMP Wed Sep 2 20:43:09 +03 2020' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.1000.217437.1611781956.2.lock
    +(anon):15> [[ 14 == <1-> ]]
    +(anon):17> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> '(anon)' /proc/self/fd/17
    +(anon):1> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=217641'
    +(anon):2> sysopen -r -o cloexec -u resp_fd -- /proc/self/fd/17
    +(anon):3> [[ 19 == <1-> ]]
    +(anon):4> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'                                              
    +(anon):121> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'                                                    
    +(anon):124> ((  ! async  ))                                                                                  
    +(anon):125> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))                                     
    +(anon):127> local pgid                                                                                       
    +(anon):128> ((  0 < 20  ))                                                                                   
    +(anon):129> [[ -t 19 ]]                                                                                      
    +(anon):130> sysread -s 20 -t 5.0000000000 -i 19 'pgid[$#pgid+1]'                                             
    +(anon):130> return                                                                                           
                         ^ this command failed (5)

  The content of /tmp/gitstatus.POWERLEVEL9K.1000.217437.1611781956.2.daemon.log (gitstatus daemon log):

    +(anon):22> local pgid=217641                                                                                 
    +(anon):23> [[ 217641 == <1-> ]]                                                                              
    +(anon):105> ((  lock_fd == -1  ))                                                                            
    +(anon):27> trap '' PIPE                                                                                      
    +(anon):29> [[ -z '' ]]                                                                                       
    +(anon):30> local kernel                                                                                      
    +(anon):108> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.1000.217437.1611781956.2.lock                       
    +(anon):31> kernel=+(anon):31> uname -s                                                                       
    +(anon):31> kernel=linux                                                                                      
    +(anon):32> [[ -n linux ]]                                                                                    
    +(anon):35> [[ '' == /* ]]                                                                                    
    +(anon):37> ((  0  ))                                                                                         
    +(anon):39> [[ -n '' ]]                                                                                       
    +(anon):42> local -aU os=( linux )                                                                            
    +(anon):43> case linux (linux)                                                                                
    +(anon):45> local os_flavor                                                                                   
    +(anon):46> os_flavor=+(anon):46> uname -o                                                                    
    +(anon):46> os_flavor=gnu/linux                                                                               
    +(anon):46> os+=( )                                                                                           
    +(anon):53> local arch                                                                                        
    +(anon):54> arch=+(anon):54> uname -m
    +(anon):54> arch=aarch64 
    +(anon):55> [[ -n aarch64 ]]
    +(anon):56> local daemons=( /home/user/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-aarch64 /home/user/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-aarch64-static /home/user/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64 /home/user/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64-static )
    +(anon):60> local files=( /home/user/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64 )
    +(anon):61> daemons=( ) 
    +(anon):63> ((  stderr_fd && 0 != 1  ))
    +(anon):64> unsetopt xtrace
    
    ERROR: missing execute permissions on gitstatusd file(s):
    
      /home/user/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64
    
    +(anon):73> ((  0  ))
    +(anon):73> return
    +(anon):100> local -i ret=1
    +(anon):101> kill -- -217641

  Your system information:

    zsh:      5.8
    uname -a: Linux Luna-Go 5.7.19-1-MANJARO-ARM #1 SMP Wed Sep 2 20:43:09 +03 2020 aarch64 GNU/Linux

**Comment by romkatv** [comment]
Try this:


```zsh
rm -rf ~/.oh-my-zsh/custom/themes/powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
exec zsh
```

**Comment by Fuzzypyro** [comment]
> Try this:
> 
> ```shell
> rm -rf ~/.oh-my-zsh/custom/themes/powerlevel10k
> git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
> exec zsh
> ```

Thank you!
