### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by svenkost** [romkatv/gitstatus#210]
I get this error every time and don't know how to fix it.

╰─ GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 -a POWERLEVEL9K
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /var/folders/sw/txzkct953n1_x2457tbp_2_00000gr/T//gitstatus.937.xtrace.1612871988.0654580593.28089 (gitstatus_start_impl xtrace):

   

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local daemon='' os
    +gitstatus_start_impl:8> [[ -n '' ]]
    +gitstatus_start_impl:9> os=+gitstatus_start_impl:9> uname -s
    +gitstatus_start_impl:9> os=Darwin 
    +gitstatus_start_impl:9> [[ -n Darwin ]]
    +gitstatus_start_impl:10> [[ Darwin != Linux ]]
    +gitstatus_start_impl:11> local arch
    +gitstatus_start_impl:11> arch=+gitstatus_start_impl:11> uname -m
    +gitstatus_start_impl:11> arch=x86_64 
    +gitstatus_start_impl:11> [[ -n x86_64 ]]
    +gitstatus_start_impl:12> daemon=/Users/skoster/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 
    +gitstatus_start_impl:14> [[ -x /Users/skoster/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 ]]
                               ^ this command failed

  Your system information:

    zsh:      5.7.1
    uname -a: Darwin skoster-mbp 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

**Comment by romkatv** [comment]
Try this:


```zsh
rm -rf /Users/skoster/powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /Users/skoster/powerlevel10k
exec zsh
```

**Comment by svenkost** [comment]
Works! Thanks @romkatv

**Comment by svenkost** [comment]
After the fix, when I go to a directory that has git status, I get the following error: 
print_icon:4: command not found: _p9k_print_icon

**Comment by romkatv** [comment]
This is not related to gitstatus. Open an issue against Powerlevel10k and attach all your configs that are necessary to reproduce the problem.
