### ISSUE TITLE
I have removed powerlevel9k and installed powerlevel10k, but still have this issue.

### ISSUE THREAD

**Issue by jjsanda** [romkatv/gitstatus#212]
[ERROR]: gitstatus failed to initialize.

  Zsh log (/private/var/folders/r7/ynk9kx_96zj9qrd7vxy6p71h0000gn/T/gitstatus.POWERLEVEL9K.501.30564.1613662029.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/r7/ynk9kx_96zj9qrd7vxy6p71h0000gn/T/gitstatus.POWERLEVEL9K.501.30564.1613662029.1.lock
    +(anon):15> [[ 17 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ darwin20.0 == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /dev/fd/16
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=30567'
    +(anon):46> [[ 19 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 19 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 19 'pgid[$#pgid+1]'
    +(anon):57> return

  Daemon log (/private/var/folders/r7/ynk9kx_96zj9qrd7vxy6p71h0000gn/T/gitstatus.POWERLEVEL9K.501.30564.1613662029.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=30567
    +_gitstatus_daemon_p9k_:4> [[ 30567 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /private/var/folders/r7/ynk9kx_96zj9qrd7vxy6p71h0000gn/T/gitstatus.POWERLEVEL9K.501.30564.1613662029.1.lock
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    _gitstatus_daemon_p9k_:12: command not found: uname
    +_gitstatus_daemon_p9k_:12> uname_sm=''
    +_gitstatus_daemon_p9k_:12> return
    +_gitstatus_daemon_p9k_:84> local -i ret=127
    +_gitstatus_daemon_p9k_:85> zf_rm -f -- /private/var/folders/r7/ynk9kx_96zj9qrd7vxy6p71h0000gn/T/gitstatus.POWERLEVEL9K.501.30564.1613662029.1.lock /private/var/folders/r7/ynk9kx_96zj9qrd7vxy6p71h0000gn/T/gitstatus.POWERLEVEL9K.501.30564.1613662029.1.fifo
    +_gitstatus_daemon_p9k_:86> kill -- -30567

  System information:

    zsh:      5.8

**Comment by romkatv** [comment]
> _gitstatus_daemon_p9k_:12: command not found: uname

This is the culprit.  `uname` is prescribed by POSIX, so any system that doesn't have it is non-compliant. Usually when you don't have standard POSIX utilities in PATH, that's because you've manually changed PATH to some invalid value. Once you fix that, gitstatus will work. You can verify by typing `uname`.

**Comment by jjsanda** [comment]
My $PATH in .zshrc file is /Users/josefsanda/opt/anaconda3/bin:/Users/josefsanda/opt/anaconda3/condabin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/josefsanda/opt/anaconda3/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/fzf/bin

So, it should find uname or am I wrong?

**Comment by romkatv** [comment]
> You can verify by typing `uname`.

☝️

**Comment by smokephil** [comment]
I get the same error:

[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  The content of /data/data/com.termux/files/usr/tmp/gitstatus.POWERLEVEL9K.10242.9508.1614409531.2.xtrace.log (gitstatus_start xtrace):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /data/data/com.termux/files/usr/tmp/gitstatus.POWERLEVEL9K.10242.9508.1614409531.2.lock
    +(anon):15> [[ 14 == <1-> ]]
    +(anon):17> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> '(anon)' /proc/self/fd/17
    +(anon):1> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=9952'
    +(anon):2> sysopen -r -o cloexec -u resp_fd -- /proc/self/fd/17
    +(anon):3> [[ 19 == <1-> ]]
    +(anon):4> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):121> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):124> ((  ! async  ))
    +(anon):125> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):127> local pgid
    +(anon):128> ((  0 < 20  ))
    +(anon):129> [[ -t 19 ]]
    +(anon):130> sysread -s 20 -t 5.0000000000 -i 19 'pgid[$#pgid+1]'
    +(anon):130> return
                         ^ this command failed (5)

  The content of /data/data/com.termux/files/usr/tmp/gitstatus.POWERLEVEL9K.10242.9508.1614409531.2.daemon.log (gitstatus daemon log):

    +(anon):22> local pgid=9952
    +(anon):23> [[ 9952 == <1-> ]]
    +(anon):105> ((  lock_fd == -1  ))
    +(anon):27> trap '' PIPE
    +(anon):29> [[ -z '' ]]
    +(anon):30> local kernel
    +(anon):31> kernel=+(anon):31> uname -s
    +(anon):108> zsystem flock -- /data/data/com.termux/files/usr/tmp/gitstatus.POWERLEVEL9K.10242.9508.1614409531.2.lock
    +(anon):31> kernel=linux
    +(anon):32> [[ -n linux ]]
    +(anon):35> [[ '' == /* ]]
    +(anon):37> ((  0  ))
    +(anon):39> [[ -n '' ]]
    +(anon):42> local -aU os=( linux )
    +(anon):43> case linux (linux)
    +(anon):45> local os_flavor
    +(anon):46> os_flavor=+(anon):46> uname -o
    +(anon):46> os_flavor=android
    +(anon):46> os+=( android )
    +(anon):53> local arch
    +(anon):54> arch=+(anon):54> uname -m
    +(anon):54> arch=armv8l
    +(anon):55> [[ -n armv8l ]]
    +(anon):56> local daemons=( /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-armv8l /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-armv8l-static /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-armv8l /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-armv8l-static /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-android-armv8l /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-android-armv8l-static /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-armv8l /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-armv8l-static )
    +(anon):60> local files=( )
    +(anon):61> daemons=( )
    +(anon):63> ((  stderr_fd && 0 != 0  ))
    +(anon):73> ((  0  ))
    +(anon):73> return
    +(anon):100> local -i ret=1
    +(anon):101> kill -- -9952

  Your system information:

    zsh:      5.8
    uname -a: Linux localhost 3.18.124-lineageos-g1eb910d #1 SMP PREEMPT Mon Jan 25 08:17:59 UTC 2021 armv8l Android

**Comment by romkatv** [comment]
> I get the same error:

It's not the same error. Please open a separate issue.
