### ISSUE TITLE
Running in a script?

### ISSUE THREAD

**Issue by spywhere** [romkatv/gitstatus#214]
Hi, I'm trying to use gitstatus in a script, in a tmux to be specific. However, even a simple script, I cannot make it to properly run. Could you help on what could go wrong here?

Mind that I'm using [antibody](https://getantibody.github.io/) for (zsh) plugin management, but in this case it should just simply help clone the repo to the default installation location (kept by the antibody itself).

To reproduce, simply create these files in the same directory with the content below and run

```
docker build -t gitstatus-test .
docker run -it --rm gitstatus-test
```

The resulting output I got would be

```
$0: git-status.sh
gitstatus installed to /root/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-romkatv-SLASH-gitstatus
gitstatus_stop : gitstatus_stop not found
gitstatus_start : gitstatus_start not found
```

----

`Dockerfile`
```
FROM alpine:3.12

WORKDIR /root
RUN apk add --no-cache git zsh curl
RUN curl -sfL git.io/antibody | sh -s - -b /usr/local/bin
COPY . /root
CMD ["zsh", "git-status.sh"]
```

`git-status.sh`
```
#!/bin/zsh

echo "\$0: $0"

if ! test "$(command -v antibody)"; then
  echo "no antibody"
  exit 1
fi

source <(antibody init)
antibody bundle <<<"romkatv/gitstatus kind:clone"

echo "gitstatus installed to $(antibody path romkatv/gitstatus)"

if ! test -d $(antibody path romkatv/gitstatus); then
  echo "gitstatus is not found"
  exit 1
fi

source $(antibody path romkatv/gitstatus)/gitstatus.plugin.zsh

echo "gitstatus_stop : $(which gitstatus_stop)"
echo "gitstatus_start : $(which gitstatus_start)"
```

**Comment by romkatv** [comment]
gitstatus can be used only from interactive zsh with zle.

**Comment by spywhere** [comment]
Hmm, I guess I have to make a script that work directly with gitstatusd then...
