### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by smokephil** [romkatv/gitstatus#215]
After updating oh-my-zsh I get the following error message:

[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  The content of /data/data/com.termux/files/usr/tmp/gitstatus.POWERLEVEL9K.10242.9508.1614409531.2.xtrace.log (gitstatus_start xtrace):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /data/data/com.termux/files/usr/tmp/gitstatus.POWERLEVEL9K.10242.9508.1614409531.2.lock
    +(anon):15> [[ 14 == <1-> ]]
    +(anon):17> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> '(anon)' /proc/self/fd/17
    +(anon):1> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=9952'
    +(anon):2> sysopen -r -o cloexec -u resp_fd -- /proc/self/fd/17
    +(anon):3> [[ 19 == <1-> ]]
    +(anon):4> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):121> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):124> ((  ! async  ))
    +(anon):125> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):127> local pgid
    +(anon):128> ((  0 < 20  ))
    +(anon):129> [[ -t 19 ]]
    +(anon):130> sysread -s 20 -t 5.0000000000 -i 19 'pgid[$#pgid+1]'
    +(anon):130> return
                         ^ this command failed (5)

  The content of /data/data/com.termux/files/usr/tmp/gitstatus.POWERLEVEL9K.10242.9508.1614409531.2.daemon.log (gitstatus daemon log):

    +(anon):22> local pgid=9952
    +(anon):23> [[ 9952 == <1-> ]]
    +(anon):105> ((  lock_fd == -1  ))
    +(anon):27> trap '' PIPE
    +(anon):29> [[ -z '' ]]
    +(anon):30> local kernel
    +(anon):31> kernel=+(anon):31> uname -s
    +(anon):108> zsystem flock -- /data/data/com.termux/files/usr/tmp/gitstatus.POWERLEVEL9K.10242.9508.1614409531.2.lock
    +(anon):31> kernel=linux
    +(anon):32> [[ -n linux ]]
    +(anon):35> [[ '' == /* ]]
    +(anon):37> ((  0  ))
    +(anon):39> [[ -n '' ]]
    +(anon):42> local -aU os=( linux )
    +(anon):43> case linux (linux)
    +(anon):45> local os_flavor
    +(anon):46> os_flavor=+(anon):46> uname -o
    +(anon):46> os_flavor=android
    +(anon):46> os+=( android )
    +(anon):53> local arch
    +(anon):54> arch=+(anon):54> uname -m
    +(anon):54> arch=armv8l
    +(anon):55> [[ -n armv8l ]]
    +(anon):56> local daemons=( /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-armv8l /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-armv8l-static /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-armv8l /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-armv8l-static /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-android-armv8l /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-android-armv8l-static /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-armv8l /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-armv8l-static )
    +(anon):60> local files=( )
    +(anon):61> daemons=( )
    +(anon):63> ((  stderr_fd && 0 != 0  ))
    +(anon):73> ((  0  ))
    +(anon):73> return
    +(anon):100> local -i ret=1
    +(anon):101> kill -- -9952

  Your system information:

    zsh:      5.8
    uname -a: Linux localhost 3.18.124-lineageos-g1eb910d #1 SMP PREEMPT Mon Jan 25 08:17:59 UTC 2021 armv8l Android

**Comment by smokephil** [comment]
I updated powerline10k to v1.14.6-3-g3920940 and after that the error was gone

**Comment by romkatv** [comment]
> I updated powerline10k to v1.14.6-3-g3920940 and after that the error was gone

👍
