### ISSUE TITLE
Git status not showing when on master branch w/ modified remote

### ISSUE THREAD

**Issue by mnewswanger** [romkatv/gitstatus#218]
Repro:
`git checkout --track <upstream>/master` or `git init` and update master branch in `.git/config` to point to a remote other than origin. `<upstream>` name doesn't seem to matter but must align w/ a defined remote (i.e. settings remote to `does-not-exist` for the master target works as intended).

VCS vars indicate no git repo is there, but `git status` reports everything properly.

**Comment by romkatv** [comment]
Please post instructions how to reproduce this problem.

**Comment by mnewswanger** [comment]
I'm not sure what happened after all - but appeared to be an issue related to my git checkout. Blowing away and re-adding remotes resolved it so not sure exactly what was off, but nothing more needed on this issue.
