### ISSUE TITLE
Setup for fish shell?

### ISSUE THREAD

**Issue by lgarron** [romkatv/gitstatus#22]
Ahoy!

I use the [`fish` shell](https://fishshell.com/), which I'm pretty happy with... except I have to disable some git commands for the prompt. Has anyone tried to make `gitstatus` work with `fish`'s `git` functions?

(I expected probably not, but I thought I'd ask before I get the itch to do it myself.)

**Comment by romkatv** [comment]
> Has anyone tried to make gitstatus work with fish's git functions?

Not that I know of.

> I expected probably not, but I thought I'd ask before I get the itch to do it myself.

I don't know anything about fish but integration with zsh is fairly straightforward. Perhaps you can use it as inspiration. It's in https://github.com/romkatv/gitstatus/blob/master/gitstatus.plugin.zsh.

**Comment by romkatv** [comment]
FYI: gitstatus now has official Bash bindings: https://github.com/romkatv/gitstatus/#using-from-bash. These are simpler than ZSH bindings as they don't support asynchronous calls. It might be an easier starting point for developing Fish bindings.

**Comment by romkatv** [comment]
This issue has died of old age.
