### ISSUE TITLE
VCS_STATUS_NUM_UNTRACKED does not honor status.showuntrackedfiles all

### ISSUE THREAD

**Issue by Syphdias** [romkatv/gitstatus#221]
For a untracked directory `VCS_STATUS_NUM_UNTRACKED` only adds 1 instead of the file count if `status.showuntrackedfiles` is `all`.

Steps to reproduce:
```
❯ cd $(mktemp -d)

/tmp/tmp.5kOLNoFQia
❯ git init
Initialized empty Git repository in /tmp/tmp.5kOLNoFQia/.git/

/tmp/tmp.5kOLNoFQia  master
❯ mkdir foo

/tmp/tmp.5kOLNoFQia  master
❯ touch foo/{bar,baz}

/tmp/tmp.5kOLNoFQia  master ?1
❯ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	foo/

nothing added to commit but untracked files present (use "git add" to track)

/tmp/tmp.5kOLNoFQia  master ?1
❯ echo $VCS_STATUS_NUM_UNTRACKED
1

/tmp/tmp.5kOLNoFQia  master ?1
❯ git config --local status.showuntrackedfiles all

/tmp/tmp.5kOLNoFQia  master ?1
❯ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	foo/bar
	foo/baz

nothing added to commit but untracked files present (use "git add" to track)

/tmp/tmp.5kOLNoFQia  master ?1
❯ echo $VCS_STATUS_NUM_UNTRACKED # expected 2
1
```

Or is my prompt using the wrong variable?

**Comment by romkatv** [comment]
You can do this:

```zsh
POWERLEVEL9K_VCS_RECURSE_UNTRACKED_DIRS=true
```

Good enough or do you need this to be customizable per repo?

**Comment by Syphdias** [comment]
> ```shell
> POWERLEVEL9K_VCS_RECURSE_UNTRACKED_DIRS=true
> ```

Thanks, I'll try that!

> Good enough or do you need this to be customizable per repo?

Yes. I discovered the setting recently and I currently use in one repository but will try it globally. So I am not sure if this matters to me on a repo basis. I just expected it to behave differently.

**Comment by romkatv** [comment]
> I just expected it to behave differently.

I think your expectations are very reasonable. I've opened #223 but there is a good chance I'll never get around to implementing it.
