### ISSUE TITLE
show upstream availability

### ISSUE THREAD

**Issue by delanym** [romkatv/gitstatus#228]
If I make a new branch, it would be nice to get an indication that there is no upstream branch.
Maybe you can use the same format as for a new untracked file: different colour, and branch name preceded by a "?"

**Comment by romkatv** [comment]
This is supported. You can use different formatting based on whether `VCS_STATUS_REMOTE_BRANCH` is set or not.

**Comment by delanym** [comment]
Why isn't this the default?

**Comment by delanym** [comment]
And I don't find `VCS_STATUS_REMOTE_BRANCH` in gitstatus.prompt.sh

**Comment by romkatv** [comment]
> Why isn't this the default?

The vast majority of conceivable configurations aren't the default. This is just one of them.

> Its not immediately clear to me how to change this.

Docs are meant to help with this.

> I don't currently customize the prompt, and I don't want to reconfigure the whole thing just for this.

Pick your battles I guess.

> And I don't find `VCS_STATUS_REMOTE_BRANCH` in gitstatus.prompt.sh

That file doesn't make use of this parameter.
