### ISSUE TITLE
Does not work on Haiku OS - can't open /tmp/zshpRfl6c: no such file or directory 

### ISSUE THREAD

**Issue by aligator** [romkatv/gitstatus#229]
Hi

I just tried to get powerlevel10k working  on [Haiku](https://www.haiku-os.org/).
But after running through the setup I get this: (with GITSTATUS_LOG_LEVEL=DEBUG)

```
~/.oh-my-zsh/custom/themes/powerlevel10k> zsh
_p9k_worker_start:6: can't open /tmp/zshpRfl6c: no such file or directory       

[ERROR]: gitstatus failed to initialize.


  Zsh log (/boot/system/cache/tmp/gitstatus.POWERLEVEL9K.0.52682.1618062296.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /boot/system/cache/tmp/gitstatus.POWERLEVEL9K.0.52682.1618062296.1.lock
    +(anon):15> [[ 14 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ haiku == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /tmp/zsh1VGIe4
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=52701'
    +(anon):46> [[ 15 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 15 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 15 'pgid[$#pgid+1]'
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '               52701' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /boot/system/cache/tmp/gitstatus.POWERLEVEL9K.0.52682.1618062296.1.fifo
    (anon):sysopen:62: can't open file /boot/system/cache/tmp/gitstatus.POWERLEVEL9K.0.52682.1618062296.1.fifo: no such file or directory
    +(anon):62> return

  Daemon log (/boot/system/cache/tmp/gitstatus.POWERLEVEL9K.0.52682.1618062296.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=52701
    +_gitstatus_daemon_p9k_:4> [[ 52701 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:93> zsystem flock -- /boot/system/cache/tmp/gitstatus.POWERLEVEL9K.0.52682.1618062296.1.lock
    +_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='haiku x86_64' 
    +_gitstatus_daemon_p9k_:13> [[ 'haiku x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=haiku
    +_gitstatus_daemon_p9k_:15> local uname_m=x86_64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 0  ))
    +_gitstatus_daemon_p9k_:23> ((  ! 0  ))
    +_gitstatus_daemon_p9k_:24> cpus=8 
    +_gitstatus_daemon_p9k_:27> args+=( -t 16 ) 
    +_gitstatus_daemon_p9k_:30> mkfifo -- /boot/system/cache/tmp/gitstatus.POWERLEVEL9K.0.52682.1618062296.1.fifo
    +_gitstatus_daemon_p9k_:31> print -rnu 15 -- '               52701'
    +_gitstatus_daemon_p9k_:33> zf_rm -- /boot/system/cache/tmp/gitstatus.POWERLEVEL9K.0.52682.1618062296.1.fifo
    +_gitstatus_daemon_p9k_:35> local _gitstatus_zsh_daemon _gitstatus_zsh_version _gitstatus_zsh_downloaded
    +_gitstatus_daemon_p9k_:43> local gitstatus_plugin_dir_var=_gitstatus_plugin_dir_p9k_
    +_gitstatus_daemon_p9k_:44> local gitstatus_plugin_dir=/boot/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_daemon_p9k_:45> set -- -d /boot/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s haiku -m x86_64 -p 'printf '\''\001'\'' >&15' -e 15 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_daemon_p9k_:47> [[ 1 == (|-|+)<1-> ]]
    +_gitstatus_daemon_p9k_:48> source /boot/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install

  System information:

    zsh:      5.8
    uname -a: Haiku shredder 1 hrev55023 Mar 31 2021 06:02:45 x86_64 x86_64 Haiku
```

/tmp exists and is writeable on Haiku. (but it is a symlink to /boot/system/cache/tmp)
As Haiku is not Linux but just a UNIX-like system there may be something missing or work differently on it.
Do you have any idea what it could be? Possible workarounds / fixes?

I can provide more information if possible / needed.

Thanks for your work :-)

**Comment by romkatv** [comment]
Looks like a bug in Haiku OS.

**Comment by aligator** [comment]
yes I think so, too. The question is whats broken there so that I can report it to Haiku.
I do not understand the code fully, but it seems to fail with the sysopen. 

You suggested in another similar problem (https://github.com/romkatv/gitstatus/issues/150) to run 
```
zsh -fc 'zmodload zsh/system && sysopen -r -o cloexec -u fd <(true)'
```
And it fails on Haiku with the same error. (can't open /tmp/...: no such file or directory)

What exactly is that sysopen for? I could not find much information about the zsh sysopen command.
As far as I understand it the -o sets a close-on-exec flag and -u sets _p9k__worker_resp_fd to the file descriptor. But what is the `-r` flag for?

**Comment by romkatv** [comment]
This looks similar to https://github.com/ish-app/ish/issues/164.

> What exactly is that sysopen for?

`sysopen` simply calls `open()` (see `man 2 open`).

> the -o sets a close-on-exec flag

You can remove it and you'll still get the same error. You can also replace `sysopen` with anything else. For example:

```zsh
exec < <(true)
```

Note that this is valid zsh and valid bash at the same time, and I think both will fail on your system. They are both supposed to work.

```shell
bash --norc -c 'exec < <(true)'
zsh -fc 'exec < <(true)'
```

**Comment by aligator** [comment]
Ok, thanks for the explanation. Now I understand what this is. So the process substition seems to behave strange on Haiku. I think I have to play around a bit with it and report the problem there.
Interestingly it doesn't fail always. `zsh -fc 'exec < <(true)'` works but `bash --norc -c 'exec < <(true)'` does not.
Maybe a timing problem? That the file it creates does not always survive the time it needs to execute the command where the file get's piped to?
When running `bash --norc -c 'exec < <(true)'` several times it mostly fails but sometimes not. 

Anyway thanks for your explanation. It is very interesting that several implementations seem to suffer a similar problem. (ish, wsl, and now haiku)

**Comment by romkatv** [comment]
> Maybe a timing problem?

Probably.

> Anyway thanks for your explanation. It is very interesting that several implementations seem to suffer a similar problem. (ish, wsl, and now haiku)

WSL doesn't have this problem. The bug has been fixed.

I think several implementations have/had this bug because the correct behavior isn't what one would intuitively expect.
