### ISSUE TITLE
Apple M1 hardware

### ISSUE THREAD

**Issue by facetheheat** [romkatv/gitstatus#230]
It would be great to add binaries supports Apple-Silicon Mac natively, instead of x86_64 binaries launched with Rosetta2.

install.info:
```
uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";
uname_s_glob="darwin";         uname_m_glob="arm64";   file="gitstatusd-${uname_s}-x86_64";
```

Thanks

**Comment by romkatv** [comment]
This is already supported: https://github.com/romkatv/gitstatus/blob/master/install.info

**Comment by facetheheat** [comment]
Yes, but it still Mach-O 64-bit executable x86_64

**Comment by romkatv** [comment]
No, it's a native arm64 binary.
