### ISSUE TITLE
Is there a way to "locally ignore" a repo? Or timeout if slow?

### ISSUE THREAD

**Issue by mathomp4** [romkatv/gitstatus#231]
A query about gitstatus. Usually it is *blazing* fast for me, but for some reason, my [spack](https://spack.readthedocs.io/en/latest/) clone seems to cause all sorts of issues. I `cd` into the directory and it just "hangs" there for awhile and eventually the prompt comes up. I think because spack is big and, well, on this system I have to use bash so I can't use powerlevel10k or zsh's async capabilities.

**Comment by romkatv** [comment]
Run this in your spack repo:

```zsh
git config --local bash.showUntrackedFiles false
git config --local bash.showDirtyState false
```

These settings only affect prompt. They'll disable the computation and the display of untracked files and staged, unstaged and conflicted changes.

The names of these config options start with "bash" because they were introduced in https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh. I've made gitstatusd respect the same options.

Alternatively, pass `-m 10000` to `gitstatus_start`. If you are using `gitstatus.prompt.sh`, you'll need to copy and modify that file. The extra option instructs gitstatusd to not skip the computation of the number of unstaged, untracked and conflicted changes if there are more than 10000 files in the repository's index. You can tune the threshold.

> I have to use bash

If you don't mind my asking, why and how are you forced?

**Comment by mathomp4** [comment]
> Run this in your spack repo:
> 
> ```shell
> git config --local bash.showUntrackedFiles false
> git config --local bash.showDirtyState false
> ```
> 
> These settings only affect prompt. They'll disable the computation and the display of untracked files and staged, unstaged and conflicted changes.

Oooh. Speedy again! Thanks!

> 
> > I have to use bash
> 
> If you don't mind my asking, why and how are you forced?

Well, it's a supercomputing center, so OS upgrades are on a different timeline. We just pretty recently moved to SLES *12*, so that meant we finally got Bash 4 as a login shell. (Before then I was using tcsh because Bash 3 was so knee-capped.) There isn't yet a viable/recent zsh on it for me to use. I did try to build zsh once and it...mainly worked, though it really wanted a more recent OS (for libraries, etc.) as well to build. But that's in a modulefile and for things to really work well, the login shells need to be "system".

Hopefully soon we can move to SLES 15 or 16, I can change my login shell to zsh, and then it's Powerlevel10k all the way! (And, I guess, once more trying to figure out what zsh plugin system to use. zinit, prezto, zplug... so many!)

**Comment by romkatv** [comment]
Thanks for the detailed response.

What's the output of `uname -ms` on that server?

**Comment by mathomp4** [comment]
> Thanks for the detailed response.
> 
> What's the output of `uname -ms` on that server?

```console
$ uname -ms
Linux x86_64
```

Not too exciting. 😄 

Note: I'm not the only "power user" waiting for new zsh on this system. Many of us get spoiled by having it on our local systems (MacBooks, etc.). 

Note 2: Your great powerlevel10k prompt led me to file [an issue](https://github.com/romkatv/powerlevel10k/issues/127) that then led me to [the libgit2 issue](https://github.com/libgit2/libgit2/issues/2263) that is still my white whale of Git Issues!

Note 3: I now realize I'm not sure I ever [tried this out](https://github.com/romkatv/powerlevel10k/issues/127#issuecomment-590782683). Or if I did, it was on a system from long ago. May be time to load up [eDEX-UI](https://github.com/GitSquared/edex-ui) and hack p10k...

**Comment by romkatv** [comment]
> > What's the output of `uname -ms` on that server?
> 
> ```
> $ uname -ms
> Linux x86_64
> ```
> 
> Not too exciting. 😄

In this case zsh4humans might just work. Give it a try.

To test it out I recommend creating a new user on your dev machine (just for testing stuff) and following this installation guide: https://github.com/romkatv/zsh4humans/tree/v5#installation. Note that I'm linking to v5, which is technically an unstable version but in practice I'm unlikely to introduce breaking changes to it.

On you install zsh4humans on the dev machine, open `~/.zshrc` and locate this line:

```zsh
# The default value if none of the overrides above match the hostname.
zstyle ':z4h:ssh:*'                   enable 'no'
```

Replace `'no'` with `'yes'`, restart zsh and try connecting to your server via ssh. You'll have not only zsh in there but a copy of your local environment. If you change anything in your local zshrc (add an alias, for example), this change will follow you around wherever you ssh.

There are also advanced features that allow you to pull command history from remote servers to local, to share command history over servers of your choice, etc. If you end up using zsh4humans, I can give you tips how to set this up.

**Comment by romkatv** [comment]
Closing as done.

Have you tried my suggestion from https://github.com/romkatv/gitstatus/issues/231#issuecomment-821217645?
