### ISSUE TITLE
gitstatus seems to keep lock on file

### ISSUE THREAD

**Issue by imme-emosol** [romkatv/gitstatus#236]
cd working-tree-copy

rm -fr '[..].git/'
rm: cannot remove '[..].git/self/objects/pack/.nfs00[..]001': Device or resource busy

lsof '[..].git/self/objects/pack/.nfs00[..]001'
COMMAND    PID USER  FD   TYPE DEVICE SIZE/OFF    NODE NAME
gitstatus ### user mem    REG   0,53     ### ### '[..].git/self/objects/pack/.nfs00[..]001'

Using zsh.
changing out of the dir does not seem to help.
closing the shell does seem to help.

**Comment by romkatv** [comment]
See https://github.com/romkatv/gitstatus/issues/52

**Comment by imme-emosol** [comment]
Ah, apparently I didn't search well enough.
