### ISSUE TITLE
gitstatus failed to initialize

### ISSUE THREAD

**Issue by yevhenshymotiuk** [romkatv/gitstatus#238]
<details>
<summary>The content of /tmp/gitstatus.15739.xtrace.1622225215.2675678730.6147 (gitstatus_start_impl xtrace):
</summary>

	+gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local daemon='' os
    +gitstatus_start_impl:8> [[ -n '' ]]
    +gitstatus_start_impl:9> os=+gitstatus_start_impl:9> uname -s
    +gitstatus_start_impl:9> os=Linux
    +gitstatus_start_impl:9> [[ -n Linux ]]
    +gitstatus_start_impl:10> [[ Linux != Linux ||+gitstatus_start_impl:10> uname -o
    +gitstatus_start_impl:10> [[ Linux != Linux || GNU/Linux != Android ]]
    +gitstatus_start_impl:11> [[ Linux != (MINGW64_NT-10.0|MSYS_NT-10.0)* ]]
    +gitstatus_start_impl:12> local arch
    +gitstatus_start_impl:12> arch=+gitstatus_start_impl:12> uname -m
    +gitstatus_start_impl:12> arch=aarch64
    +gitstatus_start_impl:12> [[ -n aarch64 ]]
    +gitstatus_start_impl:13> daemon=/nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64
    +gitstatus_start_impl:15> [[ -x /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64 ]]
    +gitstatus_start_impl:17> lock_file=/tmp/gitstatus.15739.lock.1622225215.2901721001.9453
    +gitstatus_start_impl:18> echo -n
    +gitstatus_start_impl:19> zsystem flock -f lock_fd /tmp/gitstatus.15739.lock.1622225215.2901721001.9453
    +gitstatus_start_impl:21> req_fifo=/tmp/gitstatus.15739.req.1622225215.2905707359.28858
    +gitstatus_start_impl:22> resp_fifo=/tmp/gitstatus.15739.resp.1622225215.2906219959.31240
    +gitstatus_start_impl:23> mkfifo /tmp/gitstatus.15739.req.1622225215.2905707359.28858 /tmp/gitstatus.15739.resp.1622225215.2906219959.31240
    +gitstatus_start_impl:25> local -i threads=0
    +gitstatus_start_impl:26> ((  threads > 0 ))
    +gitstatus_start_impl:27> threads=8
    +gitstatus_start_impl:28> [[ -n Linux ]]
    +gitstatus_start_impl:29> case Linux (FreeBSD)
    +gitstatus_start_impl:29> case Linux (*)
    +gitstatus_start_impl:31> ((  ! 1  ))
    +gitstatus_start_impl:31> threads=+gitstatus_start_impl:31> getconf _NPROCESSORS_ONLN
    +gitstatus_start_impl:31> threads=8
    +gitstatus_start_impl:33> ((  threads <= 32  ))
    +gitstatus_start_impl:36> local -a daemon_args=( '--lock-fd=3' '--parent-pid=15739' '--num-threads=8' '--max-num-staged=1' '--max-num-unstaged=1' '--max-num-conflicted=1' '--max-num-untracked=1' '--dirty-max-index-size=-1' '--log-level=DEBUG' )
    +gitstatus_start_impl:48> local cmd=$'\n        exec >&4\n        echo $$\n        /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64 --lock-fd=3 --parent-pid=15739 --num-threads=8 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=DEBUG\n        if [[ $? != (0|10) && $? -le 128 && -f /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64-static ]]; then\n          /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64-static --lock-fd=3 --parent-pid=15739 --num-threads=8 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=DEBUG\n        fi\n        echo -nE $\'bye\\x1f0\\x1e\''
    +gitstatus_start_impl:56> local setsid=/run/current-system/sw/bin/setsid
    +gitstatus_start_impl:57> [[ -x /run/current-system/sw/bin/setsid ]]
    +gitstatus_start_impl:57> setsid=/run/current-system/sw/bin/setsid
    +gitstatus_start_impl:58> cmd='cd /; read; /run/current-system/sw/bin/setsid zsh -dfxc $'\''\n'\''\ \ \ \ \ \ \ \ exec\ \>\&4$'\''\n'\''\ \ \ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ \ \ /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64\ --lock-fd=3\ --parent-pid=15739\ --num-threads=8\ --max-num-staged=1\ --max-num-unstaged=1\ --max-num-conflicted=1\ --max-num-untracked=1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ if\ \[\[\ \$\?\ \!=\ \(0\|10\)\ \&\&\ \$\?\ -le\ 128\ \&\&\ -f\ /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64-static\ \]\]\;\ then$'\''\n'\''\ \ \ \ \ \ \ \ \ \ /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64-static\ --lock-fd=3\ --parent-pid=15739\ --num-threads=8\ --max-num-staged=1\ --max-num-unstaged=1\ --max-num-conflicted=1\ --max-num-untracked=1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ fi$'\''\n'\''\ \ \ \ \ \ \ \ echo\ -nE\ \$\'\''bye\\x1f0\\x1e\'\'' &!; rm -f /tmp/gitstatus.15739.req.1622225215.2905707359.28858 /tmp/gitstatus.15739.resp.1622225215.2906219959.31240 /tmp/gitstatus.15739.lock.1622225215.2901721001.9453'
    +gitstatus_start_impl:64> sysopen -w -o cloexec,sync -u req_fd /tmp/gitstatus.15739.req.1622225215.2905707359.28858
    +gitstatus_start_impl:65> sysopen -r -o cloexec -u resp_fd /tmp/gitstatus.15739.resp.1622225215.2906219959.31240
    +gitstatus_start_impl:66> echo -nE $'0\nhello\C-_\C-^'
    +gitstatus_start_impl:69> ((  async  ))
    +gitstatus_start_impl:72> local reply IFS=''
    +gitstatus_start_impl:62> zsh -dfmxc 'cd /; read; /run/current-system/sw/bin/setsid zsh -dfxc $'\''\n'\''\ \ \ \ \ \ \ \ exec\ \>\&4$'\''\n'\''\ \ \ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ \ \ /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64\ --lock-fd=3\ --parent-pid=15739\ --num-threads=8\ --max-num-staged=1\ --max-num-unstaged=1\ --max-num-conflicted=1\ --max-num-untracked=1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ if\ \[\[\ \$\?\ \!=\ \(0\|10\)\ \&\&\ \$\?\ -le\ 128\ \&\&\ -f\ /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64-static\ \]\]\;\ then$'\''\n'\''\ \ \ \ \ \ \ \ \ \ /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64-static\ --lock-fd=3\ --parent-pid=15739\ --num-threads=8\ --max-num-staged=1\ --max-num-unstaged=1\ --max-num-conflicted=1\ --max-num-untracked=1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ fi$'\''\n'\''\ \ \ \ \ \ \ \ echo\ -nE\ \$\'\''bye\\x1f0\\x1e\'\'' &!; rm -f /tmp/gitstatus.15739.req.1622225215.2905707359.28858 /tmp/gitstatus.15739.resp.1622225215.2906219959.31240 /tmp/gitstatus.15739.lock.1622225215.2901721001.9453'
    +gitstatus_start_impl:73> read -ru 18 reply
    +gitstatus_start_impl:74> [[ 15834 == <1-> ]]
    +gitstatus_start_impl:75> daemon_pid=reply
    +gitstatus_start_impl:86> zle -F 18 _gitstatus_process_response_POWERLEVEL9K
    +gitstatus_start_impl:88> read -r -d $'\C-^' -u 18 -t 5.0000000000 reply
    +gitstatus_start_impl:89> [[ $'bye\C-_0' == hello0 ]]
                               ^ this command failed
</details>

<details>
<summary>The content of /tmp/gitstatus.15739.daemon-log.1622225215.2675278187.12353 (gitstatus daemon log):
</summary>

    +/etc/zshenv:5> [ -n '' ']'
    +/etc/zshenv:6> __ETC_ZSHENV_SOURCED=1
    +/etc/zshenv:8> [ -z 1 ']'
    +/etc/zshenv:12> HELPDIR=/nix/store/qjw6n0pbz503hc2g69ks1bvaa96dw07w-zsh-5.8/share/zsh/5.8/help
    +/etc/zshenv:15> p=/run/current-system/sw
    +/etc/zshenv:16> fpath+=( /run/current-system/sw/share/zsh/site-functions /run/current-system/sw/share/zsh/5.8/functions /run/current-system/sw/share/zsh/vendor-completions )
    +/etc/zshenv:15> p=/nix/var/nix/profiles/default
    +/etc/zshenv:16> fpath+=( /nix/var/nix/profiles/default/share/zsh/site-functions /nix/var/nix/profiles/default/share/zsh/5.8/functions /nix/var/nix/profiles/default/share/zsh/vendor-completions )
    +/etc/zshenv:15> p=/etc/profiles/per-user/yevhenshymotiuk
    +/etc/zshenv:16> fpath+=( /etc/profiles/per-user/yevhenshymotiuk/share/zsh/site-functions /etc/profiles/per-user/yevhenshymotiuk/share/zsh/5.8/functions /etc/profiles/per-user/yevhenshymotiuk/share/zsh/vendor-completions )
    +/etc/zshenv:15> p=/home/yevhenshymotiuk/.nix-profile
    +/etc/zshenv:16> fpath+=( /home/yevhenshymotiuk/.nix-profile/share/zsh/site-functions /home/yevhenshymotiuk/.nix-profile/share/zsh/5.8/functions /home/yevhenshymotiuk/.nix-profile/share/zsh/vendor-completions )
    +/etc/zshenv:25> test -f /etc/zshenv.local
    +zsh:1> cd /
    +zsh:1> read
    +zsh:1> rm -f /tmp/gitstatus.15739.req.1622225215.2905707359.28858 /tmp/gitstatus.15739.resp.1622225215.2906219959.31240 /tmp/gitstatus.15739.lock.1622225215.2901721001.9453
    +zsh:1> /run/current-system/sw/bin/setsid zsh -dfxc $'\n        exec >&4\n        echo $$\n        /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64 --lock-fd=3 --parent-pid=15739 --num-threads=8 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=DEBUG\n        if [[ $? != (0|10) && $? -le 128 && -f /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64-static ]]; then\n          /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64-static --lock-fd=3 --parent-pid=15739 --num-threads=8 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=DEBUG\n        fi\n        echo -nE $\'bye\\x1f0\\x1e\''
    +/etc/zshenv:5> [ -n '' ']'
    +/etc/zshenv:6> __ETC_ZSHENV_SOURCED=1
    +/etc/zshenv:8> [ -z 1 ']'
    +/etc/zshenv:12> HELPDIR=/nix/store/qjw6n0pbz503hc2g69ks1bvaa96dw07w-zsh-5.8/share/zsh/5.8/help
    +/etc/zshenv:15> p=/run/current-system/sw
    +/etc/zshenv:16> fpath+=( /run/current-system/sw/share/zsh/site-functions /run/current-system/sw/share/zsh/5.8/functions /run/current-system/sw/share/zsh/vendor-completions )
    +/etc/zshenv:15> p=/nix/var/nix/profiles/default
    +/etc/zshenv:16> fpath+=( /nix/var/nix/profiles/default/share/zsh/site-functions /nix/var/nix/profiles/default/share/zsh/5.8/functions /nix/var/nix/profiles/default/share/zsh/vendor-completions )
    +/etc/zshenv:15> p=/etc/profiles/per-user/yevhenshymotiuk
    +/etc/zshenv:16> fpath+=( /etc/profiles/per-user/yevhenshymotiuk/share/zsh/site-functions /etc/profiles/per-user/yevhenshymotiuk/share/zsh/5.8/functions /etc/profiles/per-user/yevhenshymotiuk/share/zsh/vendor-completions )
    +/etc/zshenv:15> p=/home/yevhenshymotiuk/.nix-profile
    +/etc/zshenv:16> fpath+=( /home/yevhenshymotiuk/.nix-profile/share/zsh/site-functions /home/yevhenshymotiuk/.nix-profile/share/zsh/5.8/functions /home/yevhenshymotiuk/.nix-profile/share/zsh/vendor-completions )
    +/etc/zshenv:25> test -f /etc/zshenv.local
    +zsh:3> echo 15834
    +zsh:4> /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64 '--lock-fd=3' '--parent-pid=15739' '--num-threads=8' '--max-num-staged=1' '--max-num-unstaged=1' '--max-num-conflicted=1' '--max-num-untracked=1' '--dirty-max-index-size=-1' '--log-level=DEBUG'
    zsh:4: no such file or directory: /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64
    +zsh:5> [[ 127 != (0|10) && 127 -le 128 && -f /nix/store/aqhw5hmv1x45fl2hd30sf3jzrx1pfg33-source/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-linux-aarch64-static ]]
    +zsh:8> echo -nE $'bye\C-_0\C-^'
</details>

System information:

    zsh:      5.8
    uname -a: Linux rpi4 5.10.17 #1-NixOS SMP Tue Jan 1 00:00:00 UTC 1980 aarch64 GNU/Linux

**Comment by yevhenshymotiuk** [comment]
It might be related to https://github.com/romkatv/gitstatus/issues/237, but I am not sure, because it works on my darwin machine

**Comment by romkatv** [comment]
You are attempting to use an ancient version of gitstatus that, moreover, wasn't packaged by me. Try using a newer version. If it doesn't work, report it to the packager (that would be me if you use one of the official installation methods of powerlevel10k).

> It might be related to #237

It's not related.

**Comment by yevhenshymotiuk** [comment]
I have `source ~/.p10k-pure.zsh` (https://github.com/romkatv/powerlevel10k/blob/master/config/p10k-pure.zsh) in my `.zshrc`. This file is up-to-date for now

**Comment by romkatv** [comment]
> I have `source ~/.p10k-pure.zsh` (https://github.com/romkatv/powerlevel10k/blob/master/config/p10k-pure.zsh) in my `.zshrc`. This file is up-to-date for now

I don't what you are trying to say here.

Note that sourcing this file is not something anyone should be doing (although this has no bearing on this particular issue).

**Comment by yevhenshymotiuk** [comment]
Oh, I'm sorry. I thought for a minute, that gitstatus issues are related to this specific file. `p10k` is installed using `prezto`, but it seems to be just a submodule of your repo, so I have no idea, why a gitstatus version is old

**Comment by yevhenshymotiuk** [comment]
Ok, i see https://github.com/sorin-ionescu/prezto/commit/704fc46c3f83ca1055becce65fb513a533f48982

**Comment by romkatv** [comment]
I don't know either. I'm certain that the log was produced by a very old version of gitstatus. Much older than the current version on prezto. You can check it for yourself. Go to https://github.com/sorin-ionescu/prezto/tree/master/modules/prompt/external and click on powerlevel10k. Then navigate to gitstatus/gitstatus.plugin.zsh (you'll end up at https://github.com/romkatv/powerlevel10k/blob/d26bdcd6010cfe82bc7bab07e4363b40be834cc8/gitstatus/gitstatus.plugin.zsh). Now search for "setsid" in that file and you'll find no matches. That call has been deleted [over a year ago](https://github.com/romkatv/powerlevel10k/commit/453907bbbc46befa61fca29669fe99a21faa11be#diff-3ac682aa68f40f9949588967e6999b90f923608163b5a05ebf6725d06e4a3e75).

**Comment by yevhenshymotiuk** [comment]
My config was bound to the specific very old revision of prezto. Thank you for your time

**Comment by romkatv** [comment]
I'm glad you've found the culprit.
