### ISSUE TITLE
Having trouble building b9c62ca

### ISSUE THREAD

**Issue by hikerpig** [romkatv/gitstatus#239]
I tried to run `./build -w` and get this error

![image](https://user-images.githubusercontent.com/2259688/120917933-68eae600-c6e4-11eb-9258-204f15d585fc.png)

**System:** Darwin MacBook-Pro.local 20.5.0 Darwin Kernel

**g++ --version** :
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by romkatv** [comment]
Thanks for the report. Fixed.
