### ISSUE TITLE
Support .git folders containing symlinks

### ISSUE THREAD

**Issue by noahp** [romkatv/gitstatus#24]
First off, awesome work here! amazingly fast, and IMO preferable to async prompts.

I did hit one issue; the google repo tool uses symlinks in the project .git folders, example:
```bash
> ls -al .git
total 36
drwxrwxr-x 2 npendleton npendleton 4096 Apr 10 09:33 .
drwxrwxr-x 7 npendleton npendleton 4096 Apr 10 09:32 ..
lrwxrwxrwx 1 npendleton npendleton   37 Apr 10 09:32 config -> ../../.repo/projects/tokei.git/config
lrwxrwxrwx 1 npendleton npendleton   65 Apr 10 09:32 description -> ../../.repo/project-objects/Aaronepower/tokei.git.git/description
-rw-rw-r-- 1 npendleton npendleton   41 Apr 10 09:32 HEAD
lrwxrwxrwx 1 npendleton npendleton   59 Apr 10 09:32 hooks -> ../../.repo/project-objects/Aaronepower/tokei.git.git/hooks
-rw-rw-r-- 1 npendleton npendleton 9786 Apr 10 09:32 index
lrwxrwxrwx 1 npendleton npendleton   58 Apr 10 09:32 info -> ../../.repo/project-objects/Aaronepower/tokei.git.git/info
lrwxrwxrwx 1 npendleton npendleton   35 Apr 10 09:32 logs -> ../../.repo/projects/tokei.git/logs
lrwxrwxrwx 1 npendleton npendleton   61 Apr 10 09:32 objects -> ../../.repo/project-objects/Aaronepower/tokei.git.git/objects
lrwxrwxrwx 1 npendleton npendleton   42 Apr 10 09:32 packed-refs -> ../../.repo/projects/tokei.git/packed-refs
lrwxrwxrwx 1 npendleton npendleton   35 Apr 10 09:32 refs -> ../../.repo/projects/tokei.git/refs
lrwxrwxrwx 1 npendleton npendleton   62 Apr 10 09:32 rr-cache -> ../../.repo/project-objects/Aaronepower/tokei.git.git/rr-cache
lrwxrwxrwx 1 npendleton npendleton   57 Apr 10 09:32 svn -> ../../.repo/project-objects/Aaronepower/tokei.git.git/svn
```
Unfotunately this results in a missing `scm` segment:
![image](https://user-images.githubusercontent.com/2538614/55883379-3e3c8b80-5b74-11e9-8614-46f136d694b2.png)

I'm using oh-my-zsh with the default powerlevel10k settings (I only set `ZSH_THEME="powerlevel10k/powerlevel10k"` in my `~/.zshrc`). Falling back to `vcs_info` by setting `POWERLEVEL9K_DISABLE_GITSTATUS=true` restores the segment (but it's slow again :confused: ).

You can repro by installing the `repo` tool (on ubuntu I did `sudo apt install repo`), and these commands for a test repo set:
```bash
mkdir google-repo-test && cd google-repo-test
repo init -u ssh://git@github.com/noahp/google-repo-example.git
repo sync  # clone the projects (there's only one in this example)
cd tokei
# this is where I encounter the issue; the .git folder here contains symlinks over to the
# parent .repo dir
```
I've no clue where the symlinks are interfering; I tried adding a single `LOG(FATAL)` statement to gitstatus here, but didn't notice anything:
```diff
diff --git a/src/index.cc b/src/index.cc
index afa8a5e..d2712b9 100644
--- a/src/index.cc
+++ b/src/index.cc
@@ -73,7 +73,11 @@ bool IsModified(const git_index_entry* entry, const struct stat& st, bool trust_
 }
 
 int OpenDir(int parent_fd, const char* name) {
-  return openat(parent_fd, name, O_RDONLY | O_DIRECTORY | O_CLOEXEC);
+  int ret = openat(parent_fd, name, O_RDONLY | O_DIRECTORY | O_CLOEXEC);
+  if (ret) {
+    LOG(FATAL) << "opendir error: " << name;
+  }
+  return ret;
 }
 
 void OpenTail(int* fds, size_t nfds, int root_fd, StringView dirname, Arena& arena) {
```
But I'm not sure where to see that output either.

I was using c6b74d1c95f515b80bf2c966e555ea4e687feef3 for testing (symlinked the output over, eg `ln -s /tmp/gitstatus/gitstatus/bin/gitstatusd-linux-x86_64 $ZSH_CUSTOM/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64`).

**Comment by romkatv** [comment]
Thanks for the high-quality bug report with detailed instructions how to reproduced. I've fixed the bug. Please update and try again.

**Comment by noahp** [comment]
Awesome! thank you so much for the super fast fix :hugs:
