### ISSUE TITLE
Darwin and Makefile

### ISSUE THREAD

**Issue by cheemeng** [romkatv/gitstatus#240]
gitstatus has been throwing errors on init because build.info tells it to expect v1.5.0 but the last pre-built binary for darwin was 1.3.1

doing a new build does not work because of src/options.cc

src/options.cc:57:47: error: static_assert with no message is a C++17 extension [-Werror,-Wc++17-extensions]

however in the Makefile, the flag for C++14 extension is set instead.

I could successfully recompile and install (using the build and install scripts respectively) after changing line 13 of Makefile from
`CXXFLAGS += -std=c++14 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=$(VERSION) -Wall -Werror`
to
`CXXFLAGS += -std=c++17 -funsigned-char -O3 -DNDEBUG -DGITSTATUS_VERSION=$(VERSION) -Wall -Werror`

**Comment by cheemeng** [comment]
The official binaries are at v1.3.1, so every time I start a zsh session it will complain... something like this:

```
    +_gitstatus_daemon_p9k_:63> HOME=/Users/user /Users/user/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd -G v1.5.0 -s -1 -u -1 -d -1 -c -1 -m -1 -v DEBUG -t 24
    Version mismatch. Wanted (pattern): "v1.5.0". Actual: "v1.3.1".
    +_gitstatus_daemon_p9k_:64> local -i ret=11
    +_gitstatus_daemon_p9k_:65> [[ 11 == (0|129|130|131|137|141|143|159) ]]
    +_gitstatus_daemon_p9k_:68> ((  ! _gitstatus_zsh_downloaded  ))
```

**Comment by cheemeng** [comment]
> > gitstatus has been throwing errors on init because build.info tells it to expect v1.5.0 but the last pre-built binary for darwin was 1.3.1
> 
> If you build gitstatusd yourself, then you'll have to rebuild it every time `build.info` is updated. Of you can remove your old self-built binary (it's in `/path/to/gitstatus/usrbin/gitstatusd`) and let the official binary to be downloaded automatically.
> 
> > doing a new build does not work because of src/options.cc
> > src/options.cc:57:47: error: static_assert with no message is a C++17 extension [-Werror,-Wc++17-extensions]
> 
> This has been fixed in [abbf9a7](https://github.com/romkatv/gitstatus/commit/abbf9a798d87e5a6a853f3078f904b3c8abf6c0a).
> 
> May I ask why you are building gitstatusd yourself in the first place? Do you have an issue with the official binaries?


The official binaries are at v1.3.1, so every time I start a zsh session it will complain... something like this:

```
    +_gitstatus_daemon_p9k_:63> HOME=/Users/user /Users/user/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd -G v1.5.0 -s -1 -u -1 -d -1 -c -1 -m -1 -v DEBUG -t 24
    Version mismatch. Wanted (pattern): "v1.5.0". Actual: "v1.3.1".
    +_gitstatus_daemon_p9k_:64> local -i ret=11
    +_gitstatus_daemon_p9k_:65> [[ 11 == (0|129|130|131|137|141|143|159) ]]
    +_gitstatus_daemon_p9k_:68> ((  ! _gitstatus_zsh_downloaded  ))
```

**Comment by cheemeng** [comment]
My guess is, sometimes when I update via

`git -C ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k pull
`
it updates the build.info file in my local folder as well?

**Comment by romkatv** [comment]
> The official binaries are at v1.3.1, so every time I start a zsh session it will complain... something like this:

It'll complain only if you've built gitstatusd yourself. If you don't build gitstatusd yourself, it'll just work and you'll never have to do anything.

> My guess is, sometimes when I update via
> 
> `git -C ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k pull `
> 
> it updates the build.info file in my local folder as well?

This is fine.

If you build gitstatusd yourself, then after `git pull` you might have to rebuild. If you don't build gitstatusd yourself, then you won't have to do anything after `git pull`.

Try it. Delete the existing `gitstatus` directory and run `git clone --depth=1 https://github.com/romkatv/gitstatus.git`.

**Comment by cheemeng** [comment]
Ah, I know why I built it once before. There was a false alarm of gitstatus being incorrectly flagged by virustotal. So I tried to build it locally to see if it will stop flagging. (and of course, reported it as false positive to virustotal).

Sorry to have wasted your time :-D

**Comment by romkatv** [comment]
No harm done. I’m glad you’ve gotten to the bottom of this.
