### ISSUE TITLE
gitstatus failed to initialize.

### ISSUE THREAD

**Issue by AbhinavAchha** [romkatv/gitstatus#243]
I am getting this issue for the first time. But I am not able to debug this.
the pormpt has become a bit slow in directories with .git/ folder

[gitstatus.log](https://github.com/romkatv/gitstatus/files/6653444/gistatus.log)

[gitstatus.POWERLEVEL9K.1000.5729.1623739430.2.daemon.log](https://github.com/romkatv/gitstatus/files/6653448/gitstatus.POWERLEVEL9K.1000.5729.1623739430.2.daemon.log)
[gitstatus.POWERLEVEL9K.1000.5729.1623739430.2.xtrace.log](https://github.com/romkatv/gitstatus/files/6653449/gitstatus.POWERLEVEL9K.1000.5729.1623739430.2.xtrace.log)

**Comment by romkatv** [comment]
Try this:

```zsh
rm -rf /home/abhi/powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /home/abhi/powerlevel10k
exec zsh
```

**Comment by AbhinavAchha** [comment]
yes, Thanks It has  been fixed
