### ISSUE TITLE
gitstatusd prevent disk unmount

### ISSUE THREAD

**Issue by lestofante** [romkatv/gitstatus#246]
to reproduce
- mount a disk (in my specific case an encrypted Valut)
- open a zsh terminal (yakuake in my case)
- cd to a git repo inside of the mounted disk
- cd to somewhere else like ~
- try to unmout the disk

WHAT SHOULD HAPPEN:
the disk should be unmounted as nobody uses it

WHAT HAPPEN:
unmount fail because of gitstausd.

WORK AROUND:
Fully exit all the terminal instances, even if they are not currently in any mounted folder. I *think* that if a terminal has never cd to a git folder in the mounted disk, then will not "hold" gitstatusd.

I think for some reason when I leave the git folder, gitstatusd will still check on it.

**Comment by romkatv** [comment]
See https://github.com/romkatv/gitstatus/issues?q=unmount

**Comment by lestofante** [comment]
>  gitstatusd doesn't close git repos

I would like tho change this, but instead of a wait time, releasing git folder that are not anymore in use by the shell (i use zsh if that changes thing), is that possible? if yes, where should i start to implement it properly?

**Comment by romkatv** [comment]
> I would like tho change this, but instead of a wait time, releasing git folder that are not anymore in use by the shell (i use zsh if that changes thing), is that possible?

Should be possible.

> if yes, where should i start to implement it properly?

"Properly" isn't the right word. The current behavior is intended and desired. Many users `cd` in and out of git repositories and it's valuable for them to have fast prompt whenever they do so.

To implement what you want you'll need to modify the C++ sources of gitstatusd. The easiest approach would be to remember the root directory of the repository (or a pointer to the reposotiry) from the last request and to close that repository if the new request's directory doesn't fall under it.

Closing this issue as I don't intend to do anything here.

**Comment by lestofante** [comment]
I see, I though gitstatusd would be an unique process, but it is one for shell.  
  
My use case is quite different, i use multiple console tab open to different git repo, I'll try come up with an idea with it
