### ISSUE TITLE
Using GITSTATUS_PROMPT causes incorrectly drawn cursor

### ISSUE THREAD

**Issue by jspawar** [romkatv/gitstatus#247]
I have discovered that sourcing the `gitstatus.prompt.sh` and setting my prompt variable as such `export PS1='|${GITSTATUS_PROMPT}| -> '` causes my cursor to often be incorrectly placed.

For instance, I will scroll through my command history by pressing up. I get to a command, `C-a` to get to the beginning of the line, then `C-e` to get to the end. The cursor is then placed many, many characters off into empty space instead of at the end of the actual line. If I try to go back to the beginning of the line with `C-a` it'll place the cursor somewhere randomly in the middle of the line. 

Visually, for the first case my prompt will look like:
```bash
$ curl github.com                                     ▊
```
when I'm expecting:
```bash
$ curl github.com▊
```

Visually, for the second case my prompt will look like:
```bash
$ curl gith▊ub.com`
```
when I'm expecting:
```bash
$ ▊url github.com
```

---

I have confirmed that it's because of `GITSTATUS_PROMPT` because I've removed it from my prompt variable and disabled pretty much anything else as well isolating it as much as I can to a plain terminal. Every time `GITSTATUS_PROMPT` was excluded, the cursor would be rendered correctly. Not sure why though. I even tried adding some of those prompt escape sequences after `GITSTATUS_PROMPT` just in case, but no change.

---

Some details of my machine:
- MacOS 11.4 (Intel)
- Bash 5.1.8
- iTerm2 3.4.8 (I have also used the built-in terminal which comes with MacOS)
- Installed via Homebrew

**Comment by romkatv** [comment]
I don't it's possible to fix this without any changes to your bash config. Some workarounds:

1. Use a two-line prompt with `GITSTATUS_PROMPT` on the first line.
2. Copy `gitstatus.prompt.sh` and modify it so that `gitstatus_prompt_update` assembles `PS1` directly without `GITSTATUS_PROMPT`. This way you can wrap ANSI escape codes in `\[...\]`. You'll also need to disable `promptvars`.
3. Use zsh instead of bash.

**Comment by giovannipcarvalho** [comment]
Why not escape by default on `gitstatus.prompt.sh`?

(`\001` and `\002` instead of `\[ ` and `\]` did the trick for me)

**Comment by romkatv** [comment]
I didn’t know bash recognizes 001 and 002. Do you know where it’s documented?

**Comment by giovannipcarvalho** [comment]
I think it's printf on the works. Ctrl-F "octal escapes" here[1] and here[2].

[1] https://linux.die.net/man/1/bash
[2] https://linux.die.net/man/1/printf

**Comment by romkatv** [comment]
I'd like to find bash documentation that explains how bash interprets bytes 1 and 2 in prompt. I cannot find it.

Anyway, since this works in practice I've added these escape codes.
