### ISSUE TITLE
Support for S390x architecture in build script

### ISSUE THREAD

**Issue by qdm12** [romkatv/gitstatus#249]
Hi there,

Thanks for that nice little tool.
I noticed you support a bunch of platforms in your build script, congrats on that! 👍 

Would it be possible to add support for the S390x architecture? As I don't see it [here](https://github.com/romkatv/gitstatus/blob/master/build#L451)) at least 😕 

Thanks!!

**Comment by romkatv** [comment]
Please send a PR if this is something you care about.
