### ISSUE TITLE
Alternative colors

### ISSUE THREAD

**Issue by ascherer** [romkatv/gitstatus#250]
This is more a suggestion than an issue, so feel free to ignore.

I'm using `bash` on Kubuntu with the color scheme **black on light yellow**. This makes (at least) _untracked_ and _modified_ entries hard to read.
![Screenshot_20210722_155811](https://user-images.githubusercontent.com/51143/126651697-366eef85-a1fa-40d3-af3c-036c3b8575d2.png)

So I hacked `gitstatus.prompt.sh` and changed the colors as follows:
```
local      clean=$'\001\e[38;5;076m\002'  # green foreground, Chartreuse3
#local  untracked=$'\001\e[38;5;014m\002'  # teal foreground, Aqua
local  untracked=$'\001\e[38;5;240m\002'  # Grey35 foreground
#local   modified=$'\001\e[38;5;011m\002'  # yellow foreground, Yellow
local   modified=$'\001\e[38;5;178m\002'  # Gold3 foreground
local conflicted=$'\001\e[38;5;196m\002'  # red foreground, Red1
```
![Screenshot_20210722_155704](https://user-images.githubusercontent.com/51143/126651735-ce5cd622-b920-4270-973a-cc965877201d.png)

See, e.g., [this color cheatsheet](https://jonasjacek.github.io/colors/).

**Comment by ascherer** [comment]
Addendum: On macOS (10.15.7) with its **black-on-white** terminal, **gitstatus** as installed with **brew** has sigificantly bolder colors for _untracked_ and _modified_ (also the working directory is different than on Linux). 
![Bildschirmfoto 2021-07-22 um 15 21 48](https://user-images.githubusercontent.com/51143/126646364-87989112-7137-4ed4-a0cd-60a952d62044.png)

**Comment by romkatv** [comment]
> This is more a suggestion than an issue, so feel free to ignore.

Cool, I'm open to suggestions. What is your suggestion?

P.S.

You can see how all 256 colors look like in your terminal (both the foreground and the background) with this command:

```zsh
zsh -fc 'for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\''\n'\''}; done'
```

**Comment by ascherer** [comment]
I suggest to replace colors **teal** and **yellow** in `gitstatus.prompt.sh` with the values from `gitstatus.prompt.zsh` (just by chance I picked **Gold3** without looking at the `zsh` script). In the `bash` script I'd keep the dark blue for the path item, because it matches what, e.g., `ls` does.

**Comment by romkatv** [comment]
I don't have a strong preference for the default colors either in `gitstatus.prompt.sh` or in `gitstatus.prompt.zsh`. Whatever the colors, some of them won't work with some background, so there is no way to avoid the need to customize them for some users. If the default colors are suboptimal for your terminal, go ahead and change them. 

One thing I really don't like doing is changing the UI for existing users. When someone updates gitstatus and suddenly their prompt starts using different colors, that's an issue. Unless there is a really compelling reason to change user experience, I'd rather not do it.

**Comment by ascherer** [comment]
OK.
