### ISSUE TITLE
Missing support for bare repos

### ISSUE THREAD

**Issue by mtalexan** [romkatv/gitstatus#252]
One of the gitstatus tool's primary uses seems to be within the powerlevel10k prompt.  As a comparison, the shell-script version of the git prompt that's usually packaged with git installations includes some basic details when in bare repositories, though many don't apply.  It does this by parsing a number of different status flags:
```
local repo_info rev_parse_exit_code
repo_info="$(git rev-parse --git-dir --is-inside-git-dir \
		--is-bare-repository --is-inside-work-tree \
		--short HEAD 2>/dev/null)"
rev_parse_exit_code="$?"
```

In a bare repository the `git rev-parse --is-inside-git-dir` is `true`, `--is-bare-repository` is `true`, and `--is-inside-work-tree` is `false`.  In a standard clone `git rev-parse --is-inside-git-dir` is `true`, `--is-bare-repository` is `false`, and `--is-inside-work-tree` is `true`.  The current gitstatus implementation seems to be deciding on whether or not to produce output based only on the `--is-inside-work-tree` results.

While many attributes are not valid/present for bare clones, the current branch name and a few others are.  Ideally these attributes should be based on `--is-inside-git-dir`=`true` while the rest remain dependent on `--is-inside-work-tree`=`true`.

**Comment by mtalexan** [comment]
As a counter argument to implementing this feature, the `git status` command is not available in bare repositories.  However, as noted in the initial statement, it's not `git status` that's populating the "standard" git prompt, it's information about the current repo.

**Comment by romkatv** [comment]
You are correct, bare repositories aren’t supported. If you send a high-quality PR adding the support, I’ll merge it.

As a workaround consider making your repos non-bare. Virtually all cases I’ve seen where someone uses a bare repo could use a non-bare repo instead simply by flipping the “bare” flag.

**Comment by romkatv** [comment]
Closing because I don't intend to do anything here (even though it would be nice to have support for bare repos in gitstatus).
