### ISSUE TITLE
"[ERROR]: gitstatus failed to initialize." on Mac M1

### ISSUE THREAD

**Issue by kamzata** [romkatv/gitstatus#259]
I receive this error after auto upgrade Oh My Zsh:

    [ERROR]: gitstatus failed to initialize.

    Please run the following command to install Rosetta:

    /usr/sbin/softwareupdate --install-rosetta

    See for details: https://support.apple.com/en-us/HT211861

    Once Rosetta is installed, restart your shell.

I tried to execute `/usr/sbin/softwareupdate --install-rosetta` but nothing is changed after restarted the shell.

Referral link: https://github.com/ohmyzsh/ohmyzsh/issues/10131

**Comment by pr0g** [comment]
To fix this recently I had to delete `gitstatusd-darwin-arm64` from my `.cache/gitstatus` folder on macOS. When opening the terminal again `powerlevel10k` then copied the latest version to the .cache folder and the error went away 👍 (update steps were run beforehand).

**Comment by 23493775** [comment]
I am getting: **git -C ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k pull**

remote: Enumerating objects: 3126, done.
remote: Counting objects: 100% (3126/3126), done.
remote: Compressing objects: 100% (1027/1027), done.
remote: Total 3102 (delta 2178), reused 2944 (delta 2071), pack-reused 0
Receiving objects: 100% (3102/3102), 2.26 MiB | 12.49 MiB/s, done.
Resolving deltas: 100% (2178/2178), completed with 20 local objects.
From https://github.com/romkatv/powerlevel10k
   993203a..8fefef2  master     -> origin/master
 * [new tag]         v1.10.0    -> v1.10.0
 * [new tag]         v1.10.1    -> v1.10.1
 * [new tag]         v1.11.0    -> v1.11.0
 * [new tag]         v1.12.0    -> v1.12.0
 * [new tag]         v1.13.0    -> v1.13.0
 * [new tag]         v1.14.0    -> v1.14.0
 * [new tag]         v1.14.1    -> v1.14.1
 * [new tag]         v1.14.2    -> v1.14.2
 * [new tag]         v1.14.3    -> v1.14.3
 * [new tag]         v1.14.4    -> v1.14.4
 * [new tag]         v1.14.5    -> v1.14.5
 * [new tag]         v1.14.6    -> v1.14.6
 * [new tag]         v1.15.0    -> v1.15.0
 * [new tag]         v1.16.0    -> v1.16.0
 * [new tag]         v1.16.1    -> v1.16.1
 * [new tag]         v1.17.0    -> v1.17.0
 * [new tag]         v1.18.0    -> v1.18.0
 * [new tag]         v1.19.0    -> v1.19.0
 * [new tag]         v1.6.0     -> v1.6.0
 * [new tag]         v1.6.1     -> v1.6.1
 * [new tag]         v1.7.0     -> v1.7.0
 * [new tag]         v1.8.0     -> v1.8.0
 * [new tag]         v1.8.1     -> v1.8.1
 * [new tag]         v1.8.2     -> v1.8.2
 * [new tag]         v1.9.0     -> v1.9.0
 * [new tag]         v1.9.1     -> v1.9.1
Updating 993203a..8fefef2
error: Your local changes to the following files would be overwritten by merge:
	README.md
	config/p10k-classic.zsh
	config/p10k-lean-8colors.zsh
	config/p10k-lean.zsh
	config/p10k-pure.zsh
	config/p10k-rainbow.zsh
	config/p10k-robbyrussell.zsh
	gitstatus/README.md
	gitstatus/gitstatus.plugin.zsh
	internal/configure.zsh
	internal/icons.zsh
	internal/notes.md
	internal/p10k.zsh
	internal/parser.zsh
	internal/worker.zsh
	powerlevel10k.zsh-theme
Please commit your changes or stash them before you merge.
Aborting

.... what and how do I do now , :  /

**Comment by romkatv** [comment]
This:

```zsh
sudo rm -rf -- ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k && git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
```

**Comment by 23493775** [comment]
WOW!! 
You guys are fast, haha ..  I was here working with AI (ChatGPT) on this issue; it worked and thanks : )
