### ISSUE TITLE
Custom daemon folder

### ISSUE THREAD

**Issue by gadefox** [romkatv/gitstatus#261]
I built the app successfully using docker and I'd like to have it in /usr/local/bin. I checked install script and I see it checks local file in _usrbin_ folder or it downloads release type according to OS type (in my case it's linux-i686). Then it copies the exec to local cache folder (~/.cache/gitstatus) or a directory specified in system env variable.

I created new env variable GITSTATUS_DAEMON=/usr/local/bin/gitstatusd in zshrc. Do I need to change anything else?? Ta

**Comment by gadefox** [comment]
I usually execute new commands with --help | --version at the beginning and I check the output. gitstatusd provides nice one, so I copied this file to my local bin. But yes, you're right, it's a daemon. Anyway.. GITSTATUS_DAEMON is ignored, I took a look at the code and I'll use GITSTATUS_CACHE_DIR and rename the exec, so it's with the "linux-i686" extension. Nice work, btw..

**Comment by romkatv** [comment]
>  GITSTATUS_DAEMON is ignored

I've just tried it and it works fine.

Please describe all steps necessary to reproduce the problem you are having with `GITSTATUS_DAEMON`.

> I'll use GITSTATUS_CACHE_DIR and rename the exec

May I know why you are doing this? Why not keep the binary in its original location?

Also, why are you building gitstatusd in the first place? Why not let the prebuilt binary be downloaded?

**Comment by gadefox** [comment]
Sorry, typo in the path. I'll check this again..

Well, I'm using 32 bit distro due to missing Intel's 64 bit drivers for Linux - so usually (99% of time) I can't find any prebuilt packages for the ia32 e.g. your 4humans installation script ,) so I'm installing everything manually (compiling zsh w/ suggestions etc. etc.).

**Comment by gadefox** [comment]
Plus I want to configure this globally so I don't need to do it twice (4 root).

**Comment by romkatv** [comment]
> Sorry, typo in the path. I'll check this again.

I'll assume it works fine if I don't hear from you. If it broke, there would be an outcry already.

> Well, I'm using 32 bit distro due to missing Intel's 64 bit drivers for Linux - so usually (99% of time) I can't find any prebuilt packages for the ia32

There are prebuilt gitstatusd binaries for linux-i686. Have you had issues with them?

> 4 root

My personal advice is to not touch shell configs for root and not login as root except in an emergency when you cannot login as your regular user.

**Comment by gadefox** [comment]
> Have you had issues with them?
No, I haven't and now I see the configuration works perfectly - it downloads the exec when I remove GITSTATUS_DAEMON env variable from the config, otherwise it uses my prebuilt release.

> My personal advice is to not touch shell configs for root and not login as root except in an emergency when you cannot login as your regular user.
Of course.. and now I'm thinking I'll add the condition to the config, so it ignores all zsh plugins (oh-my etc.) for the root.. Thanks,
