### ISSUE TITLE
using clang on armv7l  gitstatusd does not compile

### ISSUE THREAD

**Issue by Lunarequest** [romkatv/gitstatus#265]
using `CXX=clang` gitstatusd does not compile, it complains about `-fstack-clash-protection` not being used during compilation could this be fixed? this is an arm specific issue.

**Comment by romkatv** [comment]
> could this be fixed?

Probably. If you find out how, please send a PR. I won't be looking into it myself.

**Comment by romkatv** [comment]
Closing because I don't intend to do anything. Please post a note or a send a PR if you figure out how to solve this.
