### ISSUE TITLE
Can't change option: monitor

### ISSUE THREAD

**Issue by AM2i9** [romkatv/gitstatus#267]
I am trying to launch WPILib VSCode, and I am getting the following error from gitstatus:

```text
~/w/2021/vscode/VSCode-linux-x64 > ./code
[main 2021-09-27T20:42:34.010Z] update#ctor - updates are disabled by user preference

[ERROR]: gitstatus failed to initialize.


  Zsh log (/tmp/gitstatus.POWERLEVEL9K.1000.37469.1632775354.1.xtrace.log):

    +(anon):7> setopt monitor
    (anon):setopt:7: can't change option: monitor
    +(anon):7> return

  System information:

    zsh:      5.8
    uname -a: Linux AM2i9-Manjaro 5.13.19-2-MANJARO #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64 GNU/Linux

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new
terminate called after throwing an instance of 'char const*'
Server response: 
zsh: abort (core dumped)  ./code
```

**Comment by romkatv** [comment]
It looks like `./code` has crashed. That seems like a bigger problem.

Usually you see `can't change option: monitor` when you are attempting to use gitstatus in zsh prompt without a controlling terminal. It makes no sense to use gitstatus in zsh prompt without a controlling terminal, so don't do that.

**Comment by cory02** [comment]
I am having this issue with a controlling terminal.  I am using a WSL2 docker container:

x-docker:Thu 7:12pm:/home/user%> zsh

[ERROR]: gitstatus failed to initialize.


  Zsh log (/tmp/gitstatus.POWERLEVEL9K.648365.881.1633029174.1.xtrace.log):

    +(anon):7> setopt monitor
    (anon):setopt:7: can't change option: monitor
    +(anon):7> return

  System information:

    zsh:      5.8
    uname -a: Linux x-docker 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new
_p9k_worker_start:setopt:1: can't change option: monitor

**Comment by romkatv** [comment]
@cory02 Yep, it does not work without a controlling TTY. It makes no sense to use interactive shell in such environment.
