### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by WorstPIlot** [romkatv/gitstatus#268]
fox@FOX-PC:~$ zsh

[ERROR]: gitstatus failed to initialize.

  Zsh log (/tmp/gitstatus.POWERLEVEL9K.1000.2769.1633508892.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.1000.2769.1633508892.1.lock
    +(anon):15> [[ 18 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ linux-gnu == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/17
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=2776'
    +(anon):41> _gitstatus_daemon_p9k_
    +(anon):46> [[ 20 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):51> ((  ! async  ))
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 20 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 20 'pgid[$#pgid+1]'
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '                2776' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /tmp/gitstatus.POWERLEVEL9K.1000.2769.1633508892.1.fifo
    +(anon):63> [[ 17 == <1-> ]]
    +(anon):64> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):66> print -nru 17 -- $'}hello\C-_\C-^'
    +(anon):67> local expected=$'}hello\C-_0\C-^' actual
    +(anon):68> ((  1  ))
    +(anon):68> [[ ! -t 1 ]]
    +(anon):71> local -F deadline=1
    +(anon):73> true
    +(anon):74> [[ -t 20 ]]
    +(anon):75> sysread -s 1 -t 5.0000000000 -i 20 actual
    +(anon):75> return

  Daemon log (/tmp/gitstatus.POWERLEVEL9K.1000.2769.1633508892.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=2776
    +_gitstatus_daemon_p9k_:4> [[ 2776 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.1000.2769.1633508892.1.lock
    +_gitstatus_daemon_p9k_:12> uname_sm='linux x86_64'
    +_gitstatus_daemon_p9k_:13> [[ 'linux x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=linux
    +_gitstatus_daemon_p9k_:15> local uname_m=x86_64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:21> [[ linux == linux ]]
    +_gitstatus_daemon_p9k_:23> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:23> cpus=+_gitstatus_daemon_p9k_:23> getconf _NPROCESSORS_ONLN
    +_gitstatus_daemon_p9k_:23> cpus=24
    +_gitstatus_daemon_p9k_:27> args+=( -t 32 )
    +_gitstatus_daemon_p9k_:30> mkfifo -- /tmp/gitstatus.POWERLEVEL9K.1000.2769.1633508892.1.fifo
    +_gitstatus_daemon_p9k_:31> print -rnu 13 -- '                2776'
    +_gitstatus_daemon_p9k_:33> zf_rm -- /tmp/gitstatus.POWERLEVEL9K.1000.2769.1633508892.1.fifo
    +_gitstatus_daemon_p9k_:35> local _gitstatus_zsh_daemon _gitstatus_zsh_version _gitstatus_zsh_downloaded
    +_gitstatus_daemon_p9k_:43> local gitstatus_plugin_dir_var=_gitstatus_plugin_dir_p9k_
    +_gitstatus_daemon_p9k_:44> local gitstatus_plugin_dir=/usr/share/zsh-theme-powerlevel10k/gitstatus
    +_gitstatus_daemon_p9k_:45> set -- -d /usr/share/zsh-theme-powerlevel10k/gitstatus -s linux -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_daemon_p9k_:47> [[ 1 == (|-|+)<1-> ]]
    +_gitstatus_daemon_p9k_:48> source /usr/share/zsh-theme-powerlevel10k/gitstatus/install
    +/usr/share/zsh-theme-powerlevel10k/gitstatus/install:467> [ -z '' ']'
    +/usr/share/zsh-theme-powerlevel10k/gitstatus/install:468> _gitstatus_install_main /usr/share/zsh-theme-powerlevel10k/gitstatus -d /usr/share/zsh-theme-powerlevel10k/gitstatus -s linux -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:1> [ -n 5.8 ']'
    +_gitstatus_install_main:2> emulate -L sh -o no_unset
    +_gitstatus_install_main:7> local argv1=/usr/share/zsh-theme-powerlevel10k/gitstatus
    +_gitstatus_install_main:8> shift
    +_gitstatus_install_main:10> local no_check='' no_install='' uname_s='' uname_m='' gitstatus_dir='' dl_status='' e=''
    +_gitstatus_install_main:11> local opt='' OPTARG='' OPTIND=1
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /usr/share/zsh-theme-powerlevel10k/gitstatus -s linux -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case d (h)
    +_gitstatus_install_main:14> case d (n)
    +_gitstatus_install_main:14> case d (f)
    +_gitstatus_install_main:14> case d (d)
    +_gitstatus_install_main:55> [ -n '' ']'
    +_gitstatus_install_main:59> [ -z /usr/share/zsh-theme-powerlevel10k/gitstatus ']'
    +_gitstatus_install_main:63> gitstatus_dir=/usr/share/zsh-theme-powerlevel10k/gitstatus
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /usr/share/zsh-theme-powerlevel10k/gitstatus -s linux -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case s (h)
    +_gitstatus_install_main:14> case s (n)
    +_gitstatus_install_main:14> case s (f)
    +_gitstatus_install_main:14> case s (d)
    +_gitstatus_install_main:14> case s (p)
    +_gitstatus_install_main:14> case s (e)
    +_gitstatus_install_main:14> case s (m)
    +_gitstatus_install_main:14> case s (s)
    +_gitstatus_install_main:99> [ -n '' ']'
    +_gitstatus_install_main:103> [ -z linux ']'
    +_gitstatus_install_main:107> uname_s=linux
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /usr/share/zsh-theme-powerlevel10k/gitstatus -s linux -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case m (h)
    +_gitstatus_install_main:14> case m (n)
    +_gitstatus_install_main:14> case m (f)
    +_gitstatus_install_main:14> case m (d)
    +_gitstatus_install_main:14> case m (p)
    +_gitstatus_install_main:14> case m (e)
    +_gitstatus_install_main:14> case m (m)
    +_gitstatus_install_main:88> [ -n '' ']'
    +_gitstatus_install_main:92> [ -z x86_64 ']'
    +_gitstatus_install_main:96> uname_m=x86_64
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /usr/share/zsh-theme-powerlevel10k/gitstatus -s linux -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case p (h)
    +_gitstatus_install_main:14> case p (n)
    +_gitstatus_install_main:14> case p (f)
    +_gitstatus_install_main:14> case p (d)
    +_gitstatus_install_main:14> case p (p)
    +_gitstatus_install_main:66> [ -n '' ']'
    +_gitstatus_install_main:70> [ -z 'printf '\''\001'\'' >&13' ']'
    +_gitstatus_install_main:74> dl_status='printf '\''\001'\'' >&13'
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /usr/share/zsh-theme-powerlevel10k/gitstatus -s linux -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case e (h)
    +_gitstatus_install_main:14> case e (n)
    +_gitstatus_install_main:14> case e (f)
    +_gitstatus_install_main:14> case e (d)
    +_gitstatus_install_main:14> case e (p)
    +_gitstatus_install_main:14> case e (e)
    +_gitstatus_install_main:77> [ -n '' ']'
    +_gitstatus_install_main:81> [ -z 13 ']'
    +_gitstatus_install_main:85> e=13
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /usr/share/zsh-theme-powerlevel10k/gitstatus -s linux -m x86_64 -p 'printf '\''\001'\'' >&13' -e 13 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:115> shift 11
    +_gitstatus_install_main:117> : 13
    +_gitstatus_install_main:118> : /usr/share/zsh-theme-powerlevel10k/gitstatus
    +_gitstatus_install_main:120> [ -n '' -a -n '' ']'
    +_gitstatus_install_main:125> [ -z linux ']'
    +_gitstatus_install_main:129> [ -z x86_64 ']'
    +_gitstatus_install_main:134> local daemon=''
    +_gitstatus_install_main:135> local cache_dir=/home/fox/.cache/gitstatus
    +_gitstatus_install_main:137> [ -z '' ']'
    +_gitstatus_install_main:138> [ -n '' ']'
    +_gitstatus_install_main:142> [ -z '' -a -e /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd ']'
    +_gitstatus_install_main:143> daemon=/usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd
    +_gitstatus_install_main:145> [ -n /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd ']'
    +_gitstatus_install_main:146> local gitstatus_version='' libgit2_version=''
    +_gitstatus_install_main:147> . /usr/share/zsh-theme-powerlevel10k/gitstatus/build.info
    +/usr/share/zsh-theme-powerlevel10k/gitstatus/build.info:6> gitstatus_version=v1.5.1
    +/usr/share/zsh-theme-powerlevel10k/gitstatus/build.info:21> libgit2_version=tag-82cefe2b42300224ad3c148f8b1a569757cc617a
    +/usr/share/zsh-theme-powerlevel10k/gitstatus/build.info:22> libgit2_sha256=dc701c4e2080f7901f5d599d642b629569e5581086b9838d481d09f284dc7621
    +_gitstatus_install_main:151> [ -z v1.5.1 ']'
    +_gitstatus_install_main:155> local version=v1.5.1
    +_gitstatus_install_main:156> _gitstatus_install_daemon_found 0 _gitstatus_set_daemon_p9k_
    +_gitstatus_install_daemon_found:1> local installed=0
    +_gitstatus_install_daemon_found:2> shift
    +_gitstatus_install_daemon_found:3> [ 1 '=' 0 ']'
    +_gitstatus_install_daemon_found:3> _gitstatus_set_daemon_p9k_ /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd v1.5.1 0
    +_gitstatus_set_daemon_p9k_:1> _gitstatus_zsh_daemon=/usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd
    +_gitstatus_set_daemon_p9k_:2> _gitstatus_zsh_version=v1.5.1
    +_gitstatus_set_daemon_p9k_:3> _gitstatus_zsh_downloaded=0
    +_gitstatus_install_main:157> return
    +_gitstatus_daemon_p9k_:49> [[ -n /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd ]]
    +_gitstatus_daemon_p9k_:50> [[ -n v1.5.1 ]]
    +_gitstatus_daemon_p9k_:51> [[ 0 == [01] ]]
    +_gitstatus_daemon_p9k_:53> ((  UID == EUID  ))
    +_gitstatus_daemon_p9k_:54> local home=/home/fox
    +_gitstatus_daemon_p9k_:62> [[ -x /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd ]]
    +_gitstatus_daemon_p9k_:63> HOME=/home/fox /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd -G v1.5.1 -s -1 -u -1 -d -1 -c -1 -m -1 -v DEBUG -t 32
    /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd)
    /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd)
    /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd)
    /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd)
    +_gitstatus_daemon_p9k_:64> local -i ret=1
    +_gitstatus_daemon_p9k_:65> [[ 1 == (0|129|130|131|137|141|143|159) ]]
    +_gitstatus_daemon_p9k_:68> ((  ! _gitstatus_zsh_downloaded  ))
    +_gitstatus_daemon_p9k_:69> [[ 1 == (|-|+)<1-> ]]
    +_gitstatus_daemon_p9k_:70> [[ /usr/share/zsh-theme-powerlevel10k/gitstatus/usrbin/gitstatusd == /home/fox/.cache/gitstatus/* ]]
    +_gitstatus_daemon_p9k_:71> return
    +_gitstatus_daemon_p9k_:84> local -i ret=1
    +_gitstatus_daemon_p9k_:85> zf_rm -f -- /tmp/gitstatus.POWERLEVEL9K.1000.2769.1633508892.1.lock /tmp/gitstatus.POWERLEVEL9K.1000.2769.1633508892.1.fifo
    +_gitstatus_daemon_p9k_:86> kill -- -2776

  System information:

    zsh:      5.8
    uname -a: Linux FOX-PC 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by WorstPIlot** [comment]
Hello i see lib errors on launch, how can i fix it?

**Comment by romkatv** [comment]
Where did `/usr/share/zsh-theme-powerlevel10k` come from? How did you install it?

**Comment by WorstPIlot** [comment]
Well i copied ~/.zshrc from my Manjaro machine and then copied anything it's required, after it.
/usr/share/zsh/manjaro-zsh-config
/usr/share/zsh/manjaro-zsh-prompt
/usr/share/zsh/plugins
/usr/share/zsh-theme-powerlevel10k
so basically it's working properly but with 
[ERROR]: gitstatus failed to initialize.

**Comment by romkatv** [comment]
You cannot copy `/usr/share/zsh-theme-powerlevel10k` from one machine to another, especially when the two machines use different Linux distributions. It doesn't work because one distro has glibc and another doesn't.

You'll need to install powerlevel10k on the new machine with one of the supported installation methods.

**Comment by WorstPIlot** [comment]
Alright, thanks I'look into it.
