### ISSUE TITLE
[ERROR]: gitstatus failed to initialize on AlmaLinux 8 with Bash

### ISSUE THREAD

**Issue by anonyno** [romkatv/gitstatus#281]
This happens with even the most minimal `.bashrc`:

```
source ~/gitstatus/gitstatus.plugin.sh
gitstatus_stop && gitstatus_start
PS1='$ '
```

I created a log by inserting `set -x` at the top of `gitstatus.plugin.sh` and using script(1) to record my Bash session. [Here it is](https://github.com/romkatv/gitstatus/files/7612900/log2.txt).

Problem can't be reproduced on my Fedora machine with identical dotfiles.

**Comment by romkatv** [comment]
Please do the following:

1. Remove `set -x` that you've added previously.
2. Add this at the top of `.bashrc`: `GITSTATUS_LOG_LEVEL=DEBUG`
3. Restart bash with `exec bash`.
4. Post the output of this command: `cat -- "$GITSTATUS_DAEMON_LOG"`

**Comment by anonyno** [comment]
Ok here it is: [daemon.log](https://github.com/romkatv/gitstatus/files/7631019/daemon.log).

**Comment by romkatv** [comment]
>     tar: command not found

This is the culprit ☝️ -- you need to install tar.

**Comment by anonyno** [comment]
Thank you!
