### ISSUE TITLE
Running on a jailbroken iPod touch 7th gen.  I don't expect the dev to support such a niche platform, but it would be nice for someone to translate this so I can maybe fix it myself.

### ISSUE THREAD

**Issue by OldWorldOrdr** [romkatv/gitstatus#298]
(anon):sysopen:41: can't open file /dev/fd/14: no such file or directory

[ERROR]: gitstatus failed to initialize.

  Add the following parameter to ~/.zshrc for extra diagnostics on error:

    GITSTATUS_LOG_LEVEL=DEBUG

  Restart Zsh to retry gitstatus initialization:

    exec zsh
_p9k_worker_start:sysopen:12: can't open file /dev/fd/11: no such file or directory

[ERROR]: gitstatus failed to initialize.

  Zsh log (/private/var/tmp/gitstatus.POWERLEVEL9K.501.6856.1643756928.2.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/tmp/gitstatus.POWERLEVEL9K.501.6856.1643756928.2.lock
    +(anon):15> [[ 13 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ darwin == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /dev/fd/12
    (anon):sysopen:41: can't open file /dev/fd/12: no such file or directory
    +(anon):41> return
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd

  Daemon log (/private/var/tmp/gitstatus.POWERLEVEL9K.501.6856.1643756928.2.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=8048
    +_gitstatus_daemon_p9k_:4> [[ 8048 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /

  System information:

    zsh:      5.8
    uname -a: Darwin Joeys-iPod-Touch 20.6.0 Darwin Kernel Version 20.6.0: Tue Aug 24 21:10:43 PDT 2021; root:xnu-7195.140.44~1/RELEASE_ARM64_T8010 iPod9,1 arm64 N112AP Darwin

**Comment by romkatv** [comment]
This looks quite similar to the iSH bug: https://github.com/ish-app/ish/issues/783

**Comment by OldWorldOrdr** [comment]
It is likely the same issue.  I ran the command provided in the linked issue and the output was very similar to what the issue says.

	zsh:sysopen:1: can't open file /dev/fd/12: no such file or directory

**Comment by romkatv** [comment]
Yes, that looks like the same bug. Closing.
