### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by weilbith** [romkatv/gitstatus#3]
Hey! :wave: 
Great work. I was skeptic in first place when I hear it uses a daemon for each shell, since I tend to spawn many of them with _TMux_. But the performance caught me! Not sure how I handle zombie daemons by _TMux_ sessions I forgot about, but I guess this is a general setup problem of mine.

Since I try to keep my computer clean, I always prefer a package version for all my tools. Handling arbitrary repositories is a nightmare. Dependency management etc not even mentioned. So do you consider to publish this also as a package. As a ArchLinux user I would prefer it as an AUR first of cause. :stuck_out_tongue_winking_eye:

**Comment by romkatv** [comment]
I've never released ArchLinux packages. If you could provide me with the instructions/configs, I can promise to maintain them and to make regular releases.

**Comment by weilbith** [comment]
Haha, I'm about myself to getting started here for some projects by my own. Struggled on some problems and since then found no time to dig more into the functionality. I try to remember it and come back as soon as I feel comfortable enough. :+1: 

Note:
I guess a `*-git` package would be enough here as well, so no release management necessary.

**Comment by romkatv** [comment]
There is now AUR package called `zsh-theme-powerlevel10k-git`. It's not owned by me though.

Let me know if this doesn't work for you for some reason.

**Comment by weilbith** [comment]
I can confirm that it works. I'm happy. :hugs:
