### ISSUE TITLE
Retrieve the changes count

### ISSUE THREAD

**Issue by MathPlayer** [romkatv/gitstatus#30]
I switched not too long ago from my own custom zsh theme to https://github.com/romkatv/powerlevel10k which uses this repository to handle the git status information in the prompt.
Before the switch I was using https://github.com/olivierverdier/zsh-git-prompt in order to get the git status in the prompt. zsh-git-prompt offers the change count for staged, changed, conflicts in the prompt (see https://github.com/olivierverdier/zsh-git-prompt#examples).
Furthermore, using the Haskell backend was fast enough for me.

Is it possible to get the change count in the git prompt using this tool?

**Comment by romkatv** [comment]
Do I understand it correctly that whenever Powerlevel10k displays a glyph that signifies the presence of staged/unstaged files, you'd like to see, in addition, the number of said files?

For example, right now this is how it looks when I have 2 staged, 3 unstaged and 4 untracked files.

![before](https://user-images.githubusercontent.com/1282067/58251188-5d2d6080-7d63-11e9-9de0-f8cfe7f7be80.png)

And here's how it could look like with the counts:

![after](https://user-images.githubusercontent.com/1282067/58251208-674f5f00-7d63-11e9-9bf9-947d9b813077.png)

**Comment by MathPlayer** [comment]
Yes, I would like to be able to configure/see those numbers, maybe even including the untracked files count (e.g. '4' after '?').
![last screenshot](https://user-images.githubusercontent.com/1282067/58251208-674f5f00-7d63-11e9-9bf9-947d9b813077.png)
I was looking a bit in the source code and I stopped at https://github.com/romkatv/gitstatus/blob/master/src/gitstatus.cc#L108 which seems to get only true/false flags.
If showing the numbers is already possible, please let me know how (and possibly document it).

**Comment by romkatv** [comment]
This is done. Note, however, that gitstatusd counts untracked files differently from `git status` command. If your repo have a directory with N untracked files, none of which are ignored via `.gitignore`, and zero files in the index, `git status` will report the _directory_ as untracked, while gitstatus will report all files in it as untracked. Reporting files is more consistent. E.g., if gitstatus says there are N untracked files, it means that `git add .` will increase the number of staged files by N. It's also consistent with the way empty untracked directories are handled: neither `git status` nor gitstatusd will report this directory as untracked, but this makes much more sense for gitstatusd.

To enable the display of the counters in Powerlevel10k you can define the following parameters:

```zsh
POWERLEVEL9K_VCS_MAX_NUM_STAGED=-1
POWERLEVEL9K_VCS_MAX_NUM_UNSTAGED=-1
POWERLEVEL9K_VCS_MAX_NUM_UNTRACKED=99
```

Each parameter specifies how many changes/files of the certain type can be reported at most. The default is `1`, in which case the numbers are not shown as they aren't informative (the icon is enough). Negative value means infinity. It's OK to set `MAX_NUM_STAGED` and `MAX_NUM_UNSTAGED` to infinity, like I did above, but it's not a good idea to set `MAX_NUM_UNTRACKED` to infinity. In some repositories, when you build a project, it'll create an untracked directory with a million files. Scanning all of them can be very slow. It's better to display `99` untracked files in this case, which already conveys the idea that there are many untracked files.

Please let me know whether this works for you.

**Comment by romkatv** [comment]
By the way, https://github.com/romkatv/dotfiles-public/blob/master/.purepower is a better starting point with Powerlevel10k than the default settings (the defaults are quite awful but have to be maintained for backward compatibility). You can install it like so:

```zsh
( cd && curl -fsSLO https://raw.githubusercontent.com/romkatv/dotfiles-public/master/.purepower )
echo 'source ~/.purepower' >>! ~/.zshrc
```

Then add `~/.purepower` to your own dotfiles and edit it to suit your needs.

**Comment by MathPlayer** [comment]
This was a really quick update. I tested it for a bit, it seems to work like a charm:

<img width="691" alt="Screenshot 2019-05-24 at 01 57 29" src="https://user-images.githubusercontent.com/1119787/58293831-7a941600-7dc7-11e9-8f41-a46570e26383.png">

I read about purepower in the Powerlevel10k's README, maybe I'll give it a shot. I don't feel too much of a problem in configuring Powerlevel10k to suit my needs though.

Thank you!

**Comment by romkatv** [comment]
@MathPlayer I was alerted by @syphdias to the fact that the new parameters I added to Powerlevel10k have names inconsistent with the existing parameters. I've renamed them. Powerlevel10k will still recognize the old parameters for some time. Please rename them in your configs.

```
old                                => new
POWERLEVEL9K_VCS_MAX_NUM_STAGED    => POWERLEVEL9K_VCS_STAGED_MAX_NUM
POWERLEVEL9K_VCS_MAX_NUM_UNSTAGED  => POWERLEVEL9K_VCS_UNSTAGED_MAX_NUM
POWERLEVEL9K_VCS_MAX_NUM_UNTRACKED => POWERLEVEL9K_VCS_UNTRACKED_MAX_NUM
```

**Comment by MathPlayer** [comment]
Thanks for tagging me, I will update my configuration soon.
