### ISSUE TITLE
gitstatusd-darwin-x86_64 fails to run?

### ISSUE THREAD

**Issue by seasonedgeek** [romkatv/gitstatus#300]
Upon executing `ps` on the CL, I see this notification:

`49090 ttys000    0:00.05 /Users/tstewart/.cache/gitstatus/gitstatusd-darwin-x86_64 -G v1.5.1 -s -1 -u -1 -d -1 -c -1 -m -1 -v FATAL -t 24`

What does it mean, other than a fatal event? Would the notification disappear upon upgrading `gitstatusd` to `v1.5.3`?

Thanks.

**Comment by romkatv** [comment]
`ps` lists processes, not events. The output you see is fine.
