### ISSUE TITLE
Add support for DragonFly BSD

### ISSUE THREAD

**Issue by msvetlik** [romkatv/gitstatus#301]
I've prepared PR https://github.com/romkatv/gitstatus/pull/297 with modifications needed for DragonFly BSD detection and clean compilation. Please merge it if you are fine with changes. It has been tested on latest version of DragonFly BSD 6.2.1. You can test in VM, image can be downloaded here: https://www.dragonflybsd.org/download/

**Comment by romkatv** [comment]
Thanks for the ping. The PR fell through the cracks. I wouldn't have noticed it if you didn't open the issue.

Merged with a few changes. Could you check that it still works for you?

**Comment by msvetlik** [comment]
No worries, I will retest and let you know.
