### ISSUE TITLE
Append :z to the podman run volume argument

### ISSUE THREAD

**Issue by lukaspastor** [romkatv/gitstatus#302]
Avoid permission error on volume when building with podman by using `-v "$dir":/out:z` on line
https://github.com/romkatv/gitstatus/blob/f889c13d18fbf6f3109d6889be34d50af04d99b9/build#L650

**Comment by romkatv** [comment]
Does it work with docker?

**Comment by lukaspastor** [comment]
Yes it does. Instaled docker today on fedora 33 and there is no issue with docker. As I see it the flag is necessary only when podman is used.

I hope this is not the worst place, but I wanted to thank you for all your work you put into this as well as all your work around zsh shell. There are people from whom it is truly joy to learn from. I had been reading your code for about two years now and not once went empty handed. So credit where credit's due. Thank you.

**Comment by lukaspastor** [comment]
I did not know about that, thanks for the link.

> Is this something you actually need? If you really need, I can add a flag that you'll have to pass explicitly.

That's ok, I don't want to take up your time. I was just curious about the error and found this worked for me.
