### ISSUE TITLE
gitstatusd-msys_nt-10.0-x86_64 perceived as a threat and blocked by Trend Micro Apex One 

### ISSUE THREAD

**Issue by ninoCan** [romkatv/gitstatus#305]
I have installed the powerlevel10k on my git-sdk 1.0.8 environment on on Windows 10 Enterprise in my company's laptop. 

When I start git bash, my organization's antivirus perceive the `$HOME/.cache/gitstatus/gitstatusd-msys_nt-10.0-x86_64` as a treat, probably because is targeting `C:\git-sdk-64\mingw64\lib\ruby\gems\3.0.0\gems\typeprof-0.15.2\Gemfile.lock` for a 'Create' operation and terminates it. I believe this to be a false positive.

As far as I understand, the gitpush binary in question is built by p10k automatically. For this reason, I tried to substitute with the git repo. Automatic build from p10k, attains the same outcome.  When trying to build it myself with `build -m "$(uname -m)" -w` it fails with the following:
```
Detecting C compiler ABI info failed to compile with the following output:
Change Dir: C:/Users/antcan/AppData/Local/Temp/gitstatus-build.3D9aPKIUQb/libgit2/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/git-sdk-64/usr/bin/ninja.exe cmTC_34db8 && [1/2] Building C object CMakeFiles/cmTC_34db8.dir/CMakeCCompilerABI.c.obj
FAILED: CMakeFiles/cmTC_34db8.dir/CMakeCCompilerABI.c.obj
C:\git-sdk-64\mingw64\bin\cc.exe   -march=x86-64 -fno-plt -D_FORTIFY_SOURCE=2 -Wformat -fpie -ffile-prefix-map=/tmp/gitstatus-build.3D9aPKIUQb/= -fstack-clash-protection -fcf-protection -mtune=generic -O3 -DNDEBUG    -v -o CMakeFiles/cmTC_34db8.dir/CMakeCCompilerABI.c.obj -c 'C:/git-sdk-64/mingw64/share/cmake-3.22/Modules/CMakeCCompilerABI.c'
/bin/sh: C:git-sdk-64mingw64bincc.exe: command not found
ninja: build stopped: subcommand failed.




Determining if the C compiler works failed with the following output:
Change Dir: C:/Users/antcan/AppData/Local/Temp/gitstatus-build.3D9aPKIUQb/libgit2/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/git-sdk-64/usr/bin/ninja.exe cmTC_674a3 && [1/2] Building C object CMakeFiles/cmTC_674a3.dir/testCCompiler.c.obj
FAILED: CMakeFiles/cmTC_674a3.dir/testCCompiler.c.obj
C:\git-sdk-64\mingw64\bin\cc.exe   -march=x86-64 -fno-plt -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fpie -ffile-prefix-map=/tmp/gitstatus-build.3D9aPKIUQb/= -fstack-clash-protection -fcf-protection -mtune=generic -O3 -DNDEBUG -o CMakeFiles/cmTC_674a3.dir/testCCompiler.c.obj -c 'C:/Users/antcan/AppData/Local/Temp/gitstatus-build.3D9aPKIUQb/libgit2/build/CMakeFiles/CMakeTmp/testCCompiler.c'
/bin/sh: C:git-sdk-64mingw64bincc.exe: command not found
ninja: build stopped: subcommand failed.
```

Do you have any advice in this regard? Or even, before I keep banging my head against it, do you think manual build is going to have any benefits?

**Comment by romkatv** [comment]
> gitstatusd-msys_nt-10.0-x86_64 perceived as a threat and blocked by Trend Micro Apex One

File a bug against Trend Micro Apex One if you can.

> Do you have any advice in this regard?

Nope. If you fix it, please send a PR.

>  Or even, before I keep banging my head against it, do you think manual build is going to have any benefits?

It'll create the same binary, so it won't help.

**Comment by romkatv** [comment]
Closing because I don't intend to do anything here.

**Comment by ninoCan** [comment]
> File a bug against Trend Micro Apex One if you can.

I will! Thank you for your time!
