### ISSUE TITLE
hints on how shell integration should work?

### ISSUE THREAD

**Issue by colemickens** [romkatv/gitstatus#307]
Hi,

I'm trying my hand at adding `gitstatus` support to `starship-rs` via a fork of code from `gitstatus-rs`. I tried for quite a while to decipher what the zsh integration is doing but it's way over my head and I wound up with multiple tabs open discussing or looking for information on zsh internals.

Is there documentation on how it works? Or how I could try to replicate at least a tiny bit of the optimizations?

I'm curious about:
- how is the current shell's gitstatusd instance tracked? Is there a PID tracked somewhere, does the shell internally hold onto stdin/err somehow?
- how does the cache work? how does it map to a shell or gitstatusd instance?
- is that cache just the prompt? how is it invalidated?

I realize that I probably can't utilize zsh async since starship is just executing as a single process, but that's something for later, or maybe it is feasible to run a single starship segment separately async via extra zsh shell config. It may not be very necessary for me though, between gitstatus's awesome speed and some other tmpfs-worktree-magic I'm doing.

Thanks in advance, and thanks anyway even if you just close out this non-issue issue. Cheers!

**Comment by romkatv** [comment]
What are you trying to achieve? Do you want to invoke gitstatusd from starship-rs? That won't speed things up. Do you want to run gistatusd as daemon and communicate with it via IPC from starship-rs? If so, there is no need to read zsh code because you'll be writing very different rust code. Run `gitstatusd --help` and that's all the docs you'll need.

**Comment by romkatv** [comment]
By the way, if you are using zsh, you can try powerlevel10k. I'm not aware of any advantages of starship over powerlevel10k when it comes to zsh. I'm aware of any advantages of powerlevel10k though.

**Comment by colemickens** [comment]
Sure, the idea is to have starship try to launch/connect to a gitstatusd instance *per-ptty*. And I wanted to validate that that was roughly what powerlevel10k was doing, but again, I got lost in the weeds trying to track how it was managing gitstatusd instances or their stdin/out, and similarly couldn't figure out what the additional prompt caching was for.

I am indeed a heavy user and advocate of powerlevel10k. I fully anticipate that I will not be able to achieve the same performance as powerlevel10k's use of gitstatusd. There are what basically boil down to personal reasons why I'm willing to burn some time testing out Starship even if it means  leaving certain zsh optimizations on the table, for now.

I'll just assume that a gitstatusd-per-tty with some way to send/receive to stdin/out will be good enough to get an initial prototype working.

If you don't have any more hints for me, we can close this out. Thanks for the tips and for powerlevel10k, it's hard to explain to others how *just* how good it is sometimes.

**Comment by romkatv** [comment]
Powerlevel10k does indeed run one gitstatusd process per interactive zsh. See https://github.com/romkatv/powerlevel10k#why-does-powerlevel10k-spawn-extra-processes. You can also observe this by starting an interactive zsh and checking `ps`, then starting another interactive zsh and checking `ps` once again.

How you communicate with gitstatusd is up to you. The bindings for zsh and bash use two fifos -- one for requests and another for responses. You might want to read the bash bindings as they are a lot simpler than for zsh.

Powerlevel10k uses some caches for performance and some other caches as fallbacks for the time when fresh results from gitstatusd aren't available. See https://github.com/romkatv/powerlevel10k#why-does-git-status-sometimes-appear-grey-and-then-gets-colored-after-a-short-period-of-time.

The integration code between gitstatus and powerlevel10k is fairly complex and there is a lot of it -- thousands of lines of dense hand-optimized zsh code. I cannot recommend reading it. If you want to implement *something* that works, read `gistatusd --help` and work with that. If you are familiar with systems programming and basic POSIX stuff, that should be enough. If not, read about fifos and file descriptors. You can also use unix domain sockets -- some things will be easier than with fifos, others might be a bit harder, but at the end of the day it'll works just as well.

**Comment by colemickens** [comment]
>I cannot recommend reading it.

😆. yes, I could tell quickly that it was not meant for mere mortals. As for the rest, I know enough to be dangerous; I think I'll have something going here soon.

Again, thank you so much for powerlevel10k and taking the time to advise me so much here.
