### ISSUE TITLE
Gitstatus failed to initialize

### ISSUE THREAD

**Issue by sevenday4** [romkatv/gitstatus#314]
[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  The content of /tmp/gitstatus.POWERLEVEL10K.1000.8905.1652125996.2.xtrace.log (gitstatus_start xtrace):

    +(anon):7> ((  ! _GITSTATUS_STATE_POWERLEVEL10K  ))
    +(anon):8> [[ -r /proc/version && 'Linux version 5.17.5-zen1-1-zen (linux-zen@archlinux) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.38) #1 ZEN SMP PREEMPT Wed, 27 Apr 2022 20:56:14 +0000' == *Microsoft* ]]
    +(anon):11> print -rn
    +(anon):12> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL10K.1000.8905.1652125996.2.lock
    +(anon):13> [[ 13 == <1-> ]]
    +(anon):15> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL10K=lock_fd'
    +(anon):18> '(anon)' /proc/self/fd/15
    +(anon):1> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL10K=9653'
    +(anon):2> sysopen -r -o cloexec -u resp_fd -- /proc/self/fd/15
    +(anon):3> [[ 17 == <1-> ]]
    +(anon):4> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL10K=resp_fd'
    +(anon):118> typeset -gi '_GITSTATUS_STATE_POWERLEVEL10K=1'
    +(anon):121> ((  ! async  ))
    +(anon):122> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL10K == sysparams[pid]  ))
    +(anon):124> local pgid
    +(anon):125> ((  0 < 20  ))
    +(anon):126> [[ -t 17 ]]
    +(anon):127> sysread -s 20 -t 5.0000000000 -i 17 'pgid[$#pgid+1]'
    +(anon):127> return
                         ^ this command failed (5)

  The content of /tmp/gitstatus.POWERLEVEL10K.1000.8905.1652125996.2.daemon.log (gitstatus daemon log):

    +(anon):20> local pgid=9653
    +(anon):21> [[ 9653 == <1-> ]]
    +(anon):102> ((  lock_fd == -1  ))
    +(anon):25> trap '' PIPE
    +(anon):27> [[ -z '' ]]
    +(anon):28> local kernel
    +(anon):29> kernel=+(anon):105> zsystem flock -- /tmp/gitstatus.POWERLEVEL10K.1000.8905.1652125996.2.lock
    +(anon):29> uname -s
    +(anon):29> kernel=linux 
    +(anon):30> [[ -n linux ]]
    +(anon):33> [[ '' == /* ]]
    +(anon):35> ((  0  ))
    +(anon):37> [[ -n '' ]]
    +(anon):40> local -aU os
    +(anon):41> case linux (linux)
    +(anon):43> os=+(anon):43> uname -o
    +(anon):43> os=( gnu/linux ) 
    +(anon):44> [[ gnu/linux == android ]]
    +(anon):44> os=( linux ) 
    +(anon):50> local arch
    +(anon):51> arch=+(anon):51> uname -m
    +(anon):51> arch=x86_64 
    +(anon):52> [[ -n x86_64 ]]
    +(anon):53> local daemons=( /home/sevenday4/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-x86_64 /home/sevenday4/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-x86_64-static /home/sevenday4/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 /home/sevenday4/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static )
    +(anon):57> local files=( /home/sevenday4/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 /home/sevenday4/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static )
    +(anon):58> daemons=( ) 
    +(anon):60> ((  stderr_fd && 0 != 2  ))
    +(anon):61> unsetopt xtrace
    
    ERROR: missing execute permissions on gitstatusd file(s):
    
      /home/sevenday4/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64
      /home/sevenday4/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static
    
    +(anon):70> ((  0  ))
    +(anon):70> return
    +(anon):97> local -i ret=1
    +(anon):98> kill -- -9653

  Your system information:

    zsh:      5.8.1
    uname -a: Linux sevenday4-hplaptop15bs0xx 5.17.5-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 27 Apr 2022 20:56:14 +0000 x86_64 GNU/Linux

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by romkatv** [comment]
You are using an ancient version of powerlevel10k. You need to upgrade.

**Comment by sevenday4** [comment]
Apparently then, in the Arch AUR is behind. Will try straight from github and see if that changes anything.

**Comment by sevenday4** [comment]
I git cloned powerlevel10k and replaced the files and I am not getting the error. The Arch AUR does need to be updated though. Thanks for your help Roman.

**Comment by romkatv** [comment]
Which AUR are you using? I just tried installing zsh-theme-powerlevel10k-git (this is the AUR that I maintain) and it's the newest version.
