### ISSUE TITLE
what a mess!! please help me~

### ISSUE THREAD

**Issue by sparklabel** [romkatv/gitstatus#323]
![image](https://user-images.githubusercontent.com/103993205/177841985-e8b80f0d-5fe7-4ed3-8ecd-6067c7418861.png)

I tried re-install oh-my-zsh and powerlevel10k.
So, I un-install those and then the yellow works pop up after 'p10k configure' completed.
Although I spent whole day to solve this self, there's no way to get it.

Please let me know the solution for this.
Thank you.

**Comment by romkatv** [comment]
See those errors at the very top? They aren't coming from gitstatus, so you don't need to open an issue here. Your `PATH` is broken, hence none of the basic commands work.
