### ISSUE TITLE
ZSH Startup error

### ISSUE THREAD

**Issue by hypeitnow** [romkatv/gitstatus#333]
Hi, 

After installing the powerlevel with ohmyzsh setup I started getting following error. 

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 21 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 21 'pgid[$#pgid+1]'
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '                  43' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /tmp/gitstatus.POWERLEVEL9K.1000.4.1659697909.1.fifo
    (anon):sysopen:62: can't open file /tmp/gitstatus.POWERLEVEL9K.1000.4.1659697909.1.fifo: no such file or directory
    +(anon):62> return

  System information:

    zsh:      5.9
    uname -a: Linux GDNLPDAPD446 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linu
[gitstatus.POWERLEVEL9K.1000.4.1659697909.1.xtrace.log](https://github.com/romkatv/gitstatus/files/9268068/gitstatus.POWERLEVEL9K.1000.4.1659697909.1.xtrace.log)
[gitstatus.POWERLEVEL9K.1000.529.1659698007.1.xtrace.log](https://github.com/romkatv/gitstatus/files/9268069/gitstatus.POWERLEVEL9K.1000.529.1659698007.1.xtrace.log)

**Comment by romkatv** [comment]
It's a bug in the OS. See https://github.com/microsoft/WSL/issues/8441.
