### ISSUE TITLE
Incorrect default number of threads

### ISSUE THREAD

**Issue by zzamboni** [romkatv/gitstatus#34]
Not sure if this is a documentation issue or a bug. The help message says:

    -t, --num-threads=NUM [default=-1]
     Use this many threads to scan git workdir for unstaged and untracked files.
     Non-positive value means as many threads as there are CPUs.

However, at least on macOS, it always seems to use 1 thread by default:

```
[~]─> gitstatusd 
[2019-06-05 13:59:43 INFO src/gitstatus.cc:142] argv[0]: /Users/taazadi1/.elvish/package-data/gitstatus/gitstatusd
[2019-06-05 13:59:43 INFO src/thread_pool.cc:81] Spawning 1 thread(s)
```

I have a 6-core CPU with hyperthreading, so the system reports 12 CPUs:

```
[~]─> sysctl hw.ncpu
hw.ncpu: 12
[~]─> getconf _NPROCESSORS_ONLN
12
```

**Comment by romkatv** [comment]
Thanks for the report. The documentation is wrong. I've fixed it.

ZSH and Bash bindings set this flag to `min(32, 2 * cpus)`. I recommend doing the same for Elvish.

**Comment by href** [comment]
Oh that's good to know: I applied this on my side.

https://github.com/href/elvish-gitstatus/commit/0d5d5298ad6d5c1e858cd95bd3923f42a35e3757
