### ISSUE TITLE
Error in powerlevel10k theme after migrating to M1 mac

### ISSUE THREAD

**Issue by sherri-22** [romkatv/gitstatus#343]
I've been using powerlevel10k for years and have been very happy with it, but recently I migrated to M1 mac (chip Apple M1 Pro) from intel based Mac (2.2 GHz 6-Core Intel Core i7) and have been seeing these errors on prompt:

ZSH_THEME=powerlevel10k/powerlevel10k

```
`~ ❯ source .zshrc                                                                                                               7s ⎈ live-aws-k8s-2 00:18:18
[ERROR]: gitstatus failed to initialize.                                                                                                                     

  Your git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:
    GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K

```

~ ❯  GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K                                          ⎈ live-aws-k8s-2 00:18:24
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /var/folders/89/gd22f09d3pg3km71sxvbv4_c0000gp/T//gitstatus.31254.xtrace.Resiry0P6A (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:11> local os
    +gitstatus_start_impl:11> os=+gitstatus_start_impl:11> uname -s
    +gitstatus_start_impl:11> os=Darwin 
    +gitstatus_start_impl:11> [[ -n Darwin ]]
    +gitstatus_start_impl:12> [[ Darwin != Linux ]]
    +gitstatus_start_impl:13> local arch
    +gitstatus_start_impl:13> arch=+gitstatus_start_impl:13> uname -m
    +gitstatus_start_impl:13> arch=arm64 
    +gitstatus_start_impl:13> [[ -n arm64 ]]
    +gitstatus_start_impl:15> local daemon=/Users/smalik/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-arm64
    +gitstatus_start_impl:16> [[ -x /Users/smalik/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-arm64 ]]
                               ^ this command failed

  Your system information:

    zsh:      5.8.1
    uname -a: Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new
`

Could you please suggest something?

**Comment by sherri-22** [comment]
`~ ❯ uname -a                                                                                                                       ⎈ live-aws-k8s-2 00:26:16
Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
`

**Comment by romkatv** [comment]
You need to upgrade:

```zsh
git -C /Users/smalik/.oh-my-zsh/custom/themes/powerlevel10k pull
```
