### ISSUE TITLE
[powerlevel10k] fetching gitstatusd - FAIL

### ISSUE THREAD

**Issue by MartinZvelebil** [romkatv/gitstatus#344]
Hello,

I just installed powerlevel10k on my Ubuntu, inside windows terminal, using WSL2 and Oh my ZSH. I'm having a fetching gitstatusd fail (It won't end). The log is in the attachment. 

Thank you!

[log.txt](https://github.com/romkatv/gitstatus/files/9500270/log.txt)

**Comment by romkatv** [comment]
Does this work?

```zsh
curl -kfsSLO https://gitee.com/romkatv/gitstatus/raw/release-v1.5.4/release/gitstatusd-linux-x86_64.tar.gz && ls -l gitstatusd-linux-x86_64.tar.gz
```
