### ISSUE TITLE
gitstatus failed to initialize.

### ISSUE THREAD

**Issue by hamelsveld** [romkatv/gitstatus#346]
I get the following error and suggesting to open a issue here.....
Can you please advice?

`[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:

    GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 -a POWERLEVEL9K
Updating Fig to latest version...
(To turn off automatic updates, run fig settings app.disableAutoupdates true)
╭─ ~ ▓▒░·····································································································································································································░▒▓ ✔ | at 11:41:16 ─╮
╰─ GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 -a POWERLEVEL9K                                                                                                                                       ─╯
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /var/folders/k4/49px7vr50mq1bjl77826yg5c0000gn/T//gitstatus.4767.xtrace.1662975709.0994489193.24911 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local daemon='' os
    +gitstatus_start_impl:8> [[ -n '' ]]
    +gitstatus_start_impl:9> os=+gitstatus_start_impl:9> uname -s
    +gitstatus_start_impl:9> os=Darwin 
    +gitstatus_start_impl:9> [[ -n Darwin ]]
    +gitstatus_start_impl:10> [[ Darwin != Linux ]]
    +gitstatus_start_impl:11> local arch
    +gitstatus_start_impl:11> arch=+gitstatus_start_impl:11> uname -m
    +gitstatus_start_impl:11> arch=arm64 
    +gitstatus_start_impl:11> [[ -n arm64 ]]
    +gitstatus_start_impl:12> daemon=/Users/sven/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-arm64 
    +gitstatus_start_impl:14> [[ -x /Users/sven/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-arm64 ]]
                               ^ this command failed

  Your system information:

    zsh:      5.8.1
    uname -a: Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new
`

**Comment by romkatv** [comment]
You need to upgrade:

```zsh
git -C /Users/sven/.oh-my-zsh/custom/themes/powerlevel10k pull
```
