### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by agarciadelarco** [romkatv/gitstatus#349]
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /var/folders/mj/q7ffgdxd3kq6w9g3wq0qzg6h0000gp/T//gitstatus.46029.xtrace.1663065520.7510240078.26769 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local os
    +gitstatus_start_impl:8> local daemon=/Users/alfredogarcia/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-arm64
    +gitstatus_start_impl:9> [[ -n /Users/alfredogarcia/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-arm64 ]]
    +gitstatus_start_impl:16> [[ -x /Users/alfredogarcia/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-arm64 ]]
                               ^ this command failed

  Your system information:

    zsh:      5.8.1
    uname -a: Darwin X21087.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64

**Comment by romkatv** [comment]
You need to upgrade:

```zsh
git -C /Users/alfredogarcia/.oh-my-zsh/custom/themes/powerlevel10k pull
```

**Comment by agarciadelarco** [comment]
That worked perfect! Big big thanks! :)
