### ISSUE TITLE
Missing `gitstatusd-darwin-x86_64-static`

### ISSUE THREAD

**Issue by fvm** [romkatv/gitstatus#35]
Of course, let me start by mentioning how much I appreciate the work you're putting into this. I really enjoy using gitstatus as a part of powerlevel10k.
I tried adding my zsh setup on a new computer I'm using and ran into issues with the gitstatus binary when applying the powerlevel10k antigen bundle. Specifically, it seems that there's no suitable gitstatusd for my platform.

I `applied` the antigen theme and got the following on starting a new session:
```
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:

    GITSTATUS_ENABLE_LOGGING=1 gitstatus_start -s 1 -u 1 -d 1 -m -1 POWERLEVEL9K
```
Ok, so I ran that and got
```
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /var/folders/z3/rhtcsfrs1hv1s01kbqnvrlnh0000gq/T//gitstatus.45363.xtrace.gVWoQDheFK (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:8> local os
    +gitstatus_start_impl:8> os=+gitstatus_start_impl:8> uname -s
    +gitstatus_start_impl:8> os=Darwin
    +gitstatus_start_impl:8> [[ -n Darwin ]]
    +gitstatus_start_impl:9> [[ Darwin != Linux ]]
    +gitstatus_start_impl:10> local arch
    +gitstatus_start_impl:10> arch=+gitstatus_start_impl:10> uname -m
    +gitstatus_start_impl:10> arch=x86_64
    +gitstatus_start_impl:10> [[ -n x86_64 ]]
    +gitstatus_start_impl:11> local ldd_v
    +gitstatus_start_impl:11> ((  0  ))
    +gitstatus_start_impl:11> true
    +gitstatus_start_impl:12> local linkage
    +gitstatus_start_impl:12> [[ '' == (*glibc*|*gnu\ libc*) ]]
    +gitstatus_start_impl:12> linkage=-static
    +gitstatus_start_impl:14> local daemon=/Users/fvm/.antigen/bundles/romkatv/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static
    +gitstatus_start_impl:15> [[ -f /Users/fvm/.antigen/bundles/romkatv/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static ]]
                               ^ this command failed

  Your system information:

    zsh:      5.7.1
    uname -a: Darwin 192.168.2.120 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64
```
Ok, so that made me think: "Why does that fail?". Kinda obvious, there's no binary at `~/.antigen/bundles/romkatv/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static`. Now, my first thought was: "Maybe that got dropped in the latest version", but going through the git history, that doesn't appear to be the case.

So, I tried digging around for why `[[ '' == (*glibc*|*gnu\ libc*) ]]` fails. Well, to be honest, I don't get a lot further than this:
```
~$ (*glibc*|*gnu\ libc*)
zsh: no matches found: *glibc*
zsh: no matches found: *gnu libc*
```
Now, from what I can tell, that shouldn't even exist for MacOS, but I'm probably wrong on that. It does, however, make me wonder why I even get to that part.

Any ideas? Perhaps on what I'm blatantly overlooking?

**Comment by romkatv** [comment]
Sorry about that. Should be fixed now. Please update.

Huge thanks for opening the issue!

**Comment by fvm** [comment]
Hurray! Yup, it works
