### ISSUE TITLE
Please check for bugs

### ISSUE THREAD

**Issue by deuxksy** [romkatv/gitstatus#358]
![9DD12775-508A-43B9-9F69-83584F58B124](https://user-images.githubusercontent.com/8334910/197824164-df1cd845-5f1f-40f5-8aef-0c2af2956593.png)

I'm using  iPad Pro “ios”
https://ish.app/

  System information

    zsh:      5.8.1
    uname -a: Linux Pro 4.20.69-ish iSH 1.2.3 (298) Dec 17 2021 06:08:24 i686 Linux

**Comment by romkatv** [comment]
See https://github.com/romkatv/gitstatus/issues/271
