### ISSUE TITLE
I can't configure powerlevel10k theme on ASUS merlin firmware

### ISSUE THREAD

**Issue by jklim83** [romkatv/gitstatus#361]
Hello All,

I just installed zsh+oh-my-shell and tried to apply the powerlevel10 theme on that.
However, it is hard to go through. I think some command doesn't compile on aarch64 architecture.
If you have some idea or apply the best way for the powerlevel10 theme, please give me a hint and way.

I had attached a debug log as follows.

--------------------------------------------------------------------------------------------------------

                               Apply changes to ~/.zshrc?

(y)  Yes (recommended).

(n)  No. I know which changes to apply and will do it myself.

(r)  Restart from the beginning.
(q)  Quit and do nothing.

**Choice [ynrq]: ask_zshrc_edit:62: command not found: mktemp**

--- stack trace (most recent call first) ---
/tmp/home/root/.oh-my-zsh/custom/themes/powerlevel10k/internal/wizard.zsh:1638
/tmp/home/root/.oh-my-zsh/custom/themes/powerlevel10k/internal/wizard.zsh:2152
/tmp/home/root/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh:6878
/tmp/home/root/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh:7006
zsh:1
--- end of stack trace ---

Press ENTER to continue.

[ERROR]: gitstatus failed to initialize.

  Zsh log (/tmp/gitstatus.POWERLEVEL9K.0.233626.1669556916.3.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 4.1.51 (merlin@ubuntu-dev) (gcc version 5.5.0 (Buildroot 2017.11.1) ) #2 SMP PREEMPT Sat Aug 13 16:57:29 EDT 2022' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.0.233626.1669556916.3.lock
    +(anon):15> [[ 13 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ linux-gnu == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/12
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=235952'
    +(anon):46> [[ 15 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):41> _gitstatus_daemon_p9k_
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 15 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 15 'pgid[$#pgid+1]'
    +(anon):57> return

  Daemon log (/tmp/gitstatus.POWERLEVEL9K.0.233626.1669556916.3.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=235952
    +_gitstatus_daemon_p9k_:4> [[ 235952 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:93> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.0.233626.1669556916.3.lock
    +_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='linux aarch64'
    +_gitstatus_daemon_p9k_:13> [[ 'linux aarch64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=linux
    +_gitstatus_daemon_p9k_:15> local uname_m=aarch64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 0  ))
    +_gitstatus_daemon_p9k_:23> ((  ! 0  ))
    +_gitstatus_daemon_p9k_:24> cpus=8
    +_gitstatus_daemon_p9k_:27> args+=( -t 16 )
    +_gitstatus_daemon_p9k_:30> mkfifo -- /tmp/gitstatus.POWERLEVEL9K.0.233626.1669556916.3.fifo
    _gitstatus_daemon_p9k_:30: command not found: mkfifo
    +_gitstatus_daemon_p9k_:30> return
    +_gitstatus_daemon_p9k_:84> local -i ret=127
    +_gitstatus_daemon_p9k_:85> zf_rm -f -- /tmp/gitstatus.POWERLEVEL9K.0.233626.1669556916.3.lock /tmp/gitstatus.POWERLEVEL9K.0.233626.1669556916.3.fifo
    +_gitstatus_daemon_p9k_:86> kill -- -235952

  System information:

    zsh:      5.9
    uname -a: Linux XXXXXXX 4.1.51 #2 SMP PREEMPT Sat Aug 13 16:57:29 EDT 2022 aarch64 ASUSWRT-Merlin

Thanks in advance,
JK Lim

**Comment by romkatv** [comment]
> `command not found: mktemp`

This is the problem. Install `mktemp`.

**Comment by romkatv** [comment]
I've committed https://github.com/romkatv/powerlevel10k/commit/8d47270e8c17672e9323373e4df3699cb43545ff. Maybe it'll help you.

**Comment by jklim83** [comment]
@romkatv , Thanks for the quick answer and support.

**Comment by jklim83** [comment]
@romkatv , I just had done for your new wizard.zsh. But, no luck... it doesn't work...
Did I do it the right way? 
I just tried the below command to update your commit of thread 8d47270.
"git -C ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k pull"
and I checked the change thing on the actual file (~/.oh-my-zsh/customer/themes/powerlevel10k/internal/wizarch.zsh) that you mentioned from thread 8d47270. However, it didn't change. So, I changed that line on that file thru the vi command.
But, the same error occurred as the below.

-----------------------------------------------------------------------------------------------------------
                               Apply changes to ~/.zshrc?

(y)  Yes (recommended).

(n)  No. I know which changes to apply and will do it myself.

(r)  Restart from the beginning.
(q)  Quit and do nothing.

Choice [ynrq]: ask_zshrc_edit:62: command not found: mktemp


--- stack trace (most recent call first) ---
/tmp/home/root/.oh-my-zsh/custom/themes/powerlevel10k/internal/wizard.zsh:1643
/tmp/home/root/.oh-my-zsh/custom/themes/powerlevel10k/internal/wizard.zsh:2158
/tmp/home/root/.oh-my-zsh/custom/themes/powerlevel10k/internal/configure.zsh:77
/tmp/home/root/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh:9217
/opt/bin/zsh:1
--- end of stack trace ---

Press ENTER to continue.

------------------------------------------------------------------------------------------------------------------------


Sorry, if I'm a wrong applying mistake, please let me know that way. I'll follow up on your guide.

Thanks in advance,
JK Lim.

**Comment by romkatv** [comment]
Oh, there was another call to `mktemp` that I forgot to replace. Done now. Please try again.

**Comment by jklim83** [comment]
@romkatv, Thanks. It worked.

However, it happened something different issue. I think this can't be resolved till compiled for gitstatus command on the aarch64 platform. I'm happy to use this even at this stage.


Thanks in advance,
JK Lim.
------------------------------------------------------------------------------------------------------------------

New config: ~/.p10k.zsh.
Backup of ~/.zshrc: /tmp/.zshrc.1669635291.0610604286.

See ~/.zshrc changes:

  diff /tmp/.zshrc.1669635291.0610604286 ~/.zshrc

File feature requests and bug reports at https://github.com/romkatv/powerlevel10k/issues


[ERROR]: gitstatus failed to initialize.


  Zsh log (/tmp/gitstatus.POWERLEVEL9K.0.958536.1669635291.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 4.1.51 (merlin@ubuntu-dev) (gcc version 5.5.0 (Buildroot 2017.11.1) ) #2 SMP PREEMPT Sat Aug 13 16:57:29 EDT 2022' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.0.958536.1669635291.1.lock
    +(anon):15> [[ 14 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ linux-gnu == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/13
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=958868'
    +(anon):46> [[ 16 == <1-> ]]
    +(anon):41> _gitstatus_daemon_p9k_
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 16 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 16 'pgid[$#pgid+1]'
    +(anon):57> return

  Daemon log (/tmp/gitstatus.POWERLEVEL9K.0.958536.1669635291.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=958868
    +_gitstatus_daemon_p9k_:4> [[ 958868 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.0.958536.1669635291.1.lock
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='linux aarch64'
    +_gitstatus_daemon_p9k_:13> [[ 'linux aarch64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=linux
    +_gitstatus_daemon_p9k_:15> local uname_m=aarch64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 0  ))
    +_gitstatus_daemon_p9k_:23> ((  ! 0  ))
    +_gitstatus_daemon_p9k_:24> cpus=8
    +_gitstatus_daemon_p9k_:27> args+=( -t 16 )
    +_gitstatus_daemon_p9k_:30> mkfifo -- /tmp/gitstatus.POWERLEVEL9K.0.958536.1669635291.1.fifo
    _gitstatus_daemon_p9k_:30: command not found: mkfifo
    +_gitstatus_daemon_p9k_:30> return
    +_gitstatus_daemon_p9k_:84> local -i ret=127
    +_gitstatus_daemon_p9k_:85> zf_rm -f -- /tmp/gitstatus.POWERLEVEL9K.0.958536.1669635291.1.lock /tmp/gitstatus.POWERLEVEL9K.0.958536.1669635291.1.fifo
    +_gitstatus_daemon_p9k_:86> kill -- -958868

  System information:

    zsh:      5.9
    uname -a: Linux XXXXXXXXX 4.1.51 #2 SMP PREEMPT Sat Aug 13 16:57:29 EDT 2022 aarch64 ASUSWRT-Merlin

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by romkatv** [comment]
> I think this can't be resolved till compiled for gitstatus command on the aarch64 platform. I'm happy to use this even at this stage.

gitstatus works fine on aarch64.

> `_gitstatus_daemon_p9k_:30: command not found: mkfifo`

This is the problem. You need to install `mkfifo`.

**Comment by romkatv** [comment]
Do you actually intend to use `git` on the router? If not, simply remove `vcs` from `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` in `~/.p10k.zsh`.

**Comment by jklim83** [comment]
> 

Yes, I think this is a good way to use on a router. So, I removed it as you mentioned.

Thanks,
JK Lim.
