### ISSUE TITLE
gitstatus failed to initialize

### ISSUE THREAD

**Issue by XIYO** [romkatv/gitstatus#362]
I used a translator.

Thank you for making such a great program.

I installed it in **asuswrt** of asus AC88U.

The first test was with the oh my zsh guide.(https://github.com/romkatv/powerlevel10k#oh-my-zsh)
But nothing happens after source ~.zshrc. (No error output either)

The second test was installed in **manual mode**.
An error has occurred, I will attach the log below.

------------------------------
[ERROR]: gitstatus failed to initialize.

  Zsh log (/tmp/gitstatus.POWERLEVEL9K.0.14417.1671087070.2.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 2.6.36.4brcmarm (merlin@ubuntu-dev) (gcc version 4.5.3 (Buildroot 2012.02) ) #1 SMP PREEMPT Sun Jul 24 17:39:55 EDT 2022' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.0.14417.1671087070.2.lock
    +(anon):15> [[ 13 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ linux-gnu == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/12
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=27520'
    +(anon):46> [[ 15 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 15 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 15 'pgid[$#pgid+1]'
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):57> return

  Daemon log (/tmp/gitstatus.POWERLEVEL9K.0.14417.1671087070.2.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=27520
    +_gitstatus_daemon_p9k_:4> [[ 27520 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.0.14417.1671087070.2.lock
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='linux armv7l'
    +_gitstatus_daemon_p9k_:13> [[ 'linux armv7l' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=linux
    +_gitstatus_daemon_p9k_:15> local uname_m=armv7l
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 0  ))
    +_gitstatus_daemon_p9k_:23> ((  ! 0  ))
    +_gitstatus_daemon_p9k_:24> cpus=8
    +_gitstatus_daemon_p9k_:27> args+=( -t 16 )
    +_gitstatus_daemon_p9k_:30> mkfifo -- /tmp/gitstatus.POWERLEVEL9K.0.14417.1671087070.2.fifo
    _gitstatus_daemon_p9k_:30: command not found: mkfifo
    +_gitstatus_daemon_p9k_:30> return
    +_gitstatus_daemon_p9k_:84> local -i ret=127
    +_gitstatus_daemon_p9k_:85> zf_rm -f -- /tmp/gitstatus.POWERLEVEL9K.0.14417.1671087070.2.lock /tmp/gitstatus.POWERLEVEL9K.0.14417.1671087070.2.fifo
    +_gitstatus_daemon_p9k_:86> kill -- -27520

  System information:

    zsh:      5.9
    uname -a: Linux RT-AC88U-3060 2.6.36.4brcmarm #1 SMP PREEMPT Sun Jul 24 17:39:55 EDT 2022 armv7l ASUSWRT-Merlin

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by romkatv** [comment]
> `_gitstatus_daemon_p9k_:30: command not found: mkfifo`

This is the problem. You need to install `mkfifo`.

Do you actually intend to use `git` on the router? If not, simply remove `vcs` from `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` in `~/.p10k.zsh`.
