### ISSUE TITLE
help with p10k error afer update

### ISSUE THREAD

**Issue by Kareto** [romkatv/gitstatus#366]
[ERROR]: gitstatus failed to initialize.

  Zsh log (/tmp/gitstatus.POWERLEVEL9K.1001.83866.1673651309.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 6.0.0-2parrot1-amd64 (team@parrotsec.org) (gcc-11 (Parrot 11.2.0-18really16parrot1) 11.2.0, GNU ld (GNU Binutils for Parrot) 2.37.90.20220130) #1 SMP PREEMPT_DYNAMIC Debian 6.0.2-1parrot1 (2022-10-18)' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.1001.83866.1673651309.1.lock
    +(anon):15> [[ 16 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ linux-gnu == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/15
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=83868'
    +(anon):46> [[ 18 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):41> _gitstatus_daemon_p9k_
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 18 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 18 'pgid[$#pgid+1]'
    +(anon):57> return

  Daemon log (/tmp/gitstatus.POWERLEVEL9K.1001.83866.1673651309.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=83868
    +_gitstatus_daemon_p9k_:4> [[ 83868 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.1001.83866.1673651309.1.lock
    _gitstatus_daemon_p9k_:12: command not found: uname
    +_gitstatus_daemon_p9k_:12> uname_sm='' 
    +_gitstatus_daemon_p9k_:12> return
    +_gitstatus_daemon_p9k_:84> local -i ret=127
    +_gitstatus_daemon_p9k_:85> zf_rm -f -- /tmp/gitstatus.POWERLEVEL9K.1001.83866.1673651309.1.lock /tmp/gitstatus.POWERLEVEL9K.1001.83866.1673651309.1.fifo
    +_gitstatus_daemon_p9k_:86> kill -- -83868

  System information:

    zsh:      5.8
    uname -a: Linux parrot 6.0.0-2parrot1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.2-1parrot1 (2022-10-18) x86_64 GNU/Linux

**Comment by romkatv** [comment]
Your `PATH` is broken. It doesn't contain the system directories, hence `uname` is not found.
