### ISSUE TITLE
Manual installation possible?

### ISSUE THREAD

**Issue by dennym** [romkatv/gitstatus#367]
Hey there. I have here a quite restrictive setup. I managed to get powerlevel10k installed through some custom proxysettings. Unfortunatly the proxy does not work with the `curl` and `wget` commands in the gitstatus install script. I managed to download the file manually and `tar`ed it into the `~/.cache/gitstatus` folder. Is there a way to skip that download and proceed directly with the setup or a completely different way of installing the plugin by hand?

The install script is quite hard to read and I couldn't figure out what is next after un`tar`ing the downloaded file...

best

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#how-do-i-install-powerlevel10k-on-a-machine-without-internet-access

**Comment by dennym** [comment]
Ah perfect! Went to far down into the rabbithole to see the simple solution :) Closed
