### ISSUE TITLE
Is it possible to periodically update the gitstatus?

### ISSUE THREAD

**Issue by ezrafree** [romkatv/gitstatus#368]
Hello,

I am using gitstatus in p10k and was wondering if it's possible to somehow have the gitstatus update periodically in the background? ie. it'd update on it's own without my having to go to each tab/panel and hit enter. I've looked through the documentation, read through the README, etc. and am not seeing any mention of a polling interval, etc.

Does anyone know if there would be a way to do this? It wouldn't have to be very often or anything, even every few minutes or so would be fine.

Thanks in advance!

**Comment by romkatv** [comment]
Powerlevel10k displays info in prompt. It doesn't make changes to your filesystem. If you want to execute `git fetch` in some directories periodically, you'll need to do this outside of powerlevel10k.

**Comment by ezrafree** [comment]
@romkatv thank you for your response. Just to clarify a bit more, if I'm not mistaken `git fetch` would fetch from the remote, whereas I am only looking to update the information that `gitstatus`/`powerlevel10k` displays based on what's happening locally.

For example, I have one iTerm2 window, and I use split panes so I am looking at 3 "panes" of terminal windows. If I change branches in one of these panes, I would like to see the branch name change in the other panes as well.

Currently I have to go into each pane and either run a command, or just hit enter, to update the information displayed in that pane's prompt. Is there any way to simply trigger a reload of the information being displayed?

**Comment by romkatv** [comment]
Your original question was clear and I should've been able to understand it but somehow I didn't. Thanks for clarifying.

You can force a refresh of prompt every 30 seconds by adding the following code snippet to `~/.zshrc`:

```zsh
# Refreshes prompt.
TRAPALRM() {
  local f
  for f in chpwd "${chpwd_functions[@]}" precmd "${precmd_functions[@]}"; do
    [[ "${+functions[$f]}" == 0 ]] || "$f" &>/dev/null || true
  done
  p10k display -r
}

# Invoke TRAPALRM every 30 seconds.
TMOUT=30
```

Be aware of the following zsh bug that will get triggered by this code: https://www.zsh.org/mla/workers/2019/msg00161.html. It won't matter to you unless you are relying on menu completion.

**Comment by ezrafree** [comment]
Working perfectly, thanks @romkatv!
