### ISSUE TITLE
Xonsh Shell Support

### ISSUE THREAD

**Issue by anirrudh** [romkatv/gitstatus#37]
[Xonsh](https://xon.sh/ ) is a python-powered shell, and I am trying to port some popular plugins that I use for myself over.

**Comment by romkatv** [comment]
Is this a notification that you are in the process of implementing gitstatusd bindings for Xonsh?

**Comment by anirrudh** [comment]
Yes -- rather, hopefully, as I plan to port it over. I'm not fully sure if I can port over Powerlevel10K or I'd have to seriously reconfigure it yet :).

**Comment by romkatv** [comment]
> Yes -- rather, hopefully, as I plan to port it over.

Go for it :rocket:

**Comment by anki-code** [comment]
@anirrudh hi! Do you have news around porting for xonsh?

**Comment by romkatv** [comment]
This issue has died of old age.
