### ISSUE TITLE
Problem on MacOS when restarted from a crash

### ISSUE THREAD

**Issue by jcbasso** [romkatv/gitstatus#372]
Hello there!
I am having a problem on MacOS where gitstatus is unable to start immediately into an already existing terminal when booting.

Steps that reproduce the problem on my machine:
1. Have a terminal open using `gitstatus`.
2. Turnoff computer through a crash. Example: Waiting for the battery to die.
3. Turn on computer back on.
4. Open already existing terminal -> Failure arise when loading `gitstatus`.

These are the logs:
```bash
[ERROR]: gitstatus failed to initialize.


  Zsh log (/private/var/folders/8n/s15ccwl52zlgp6rbh2y_4t180000gp/T/gitstatus.MY.502.767.1675464340.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_MY  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/8n/s15ccwl52zlgp6rbh2y_4t180000gp/T/gitstatus.MY.502.767.1675464340.1.lock
    +(anon):15> [[ 16 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_MY=lock_fd'
    +(anon):20> [[ darwin21.0 == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /dev/fd/15
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_MY=983'
    +(anon):46> [[ 18 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_MY=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_MY=1'
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_MY == sysparams[pid]  ))
    +(anon):41> _gitstatus_daemon
    +(anon):54> local pgid
    +_gitstatus_daemon:1> local -i pipe_fd
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 18 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 18 'pgid[$#pgid+1]'
    +(anon):57> return

  Daemon log (/private/var/folders/8n/s15ccwl52zlgp6rbh2y_4t180000gp/T/gitstatus.MY.502.767.1675464340.1.daemon.log):

    +_gitstatus_daemon:3> local pgid=983
    +_gitstatus_daemon:4> [[ 983 == <1-> ]]
    +_gitstatus_daemon:5> cd -q /
    +_gitstatus_daemon:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon:9> trap '' PIPE
    +_gitstatus_daemon:11> local uname_sm
    +_gitstatus_daemon:93> zsystem flock -- /private/var/folders/8n/s15ccwl52zlgp6rbh2y_4t180000gp/T/gitstatus.MY.502.767.1675464340.1.lock
    +_gitstatus_daemon:12> uname_sm=+_gitstatus_daemon:12> uname -sm
    +_gitstatus_daemon:12> uname_sm='darwin x86_64' 
    +_gitstatus_daemon:13> [[ 'darwin x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon:14> local uname_s=darwin
    +_gitstatus_daemon:15> local uname_m=x86_64
    +_gitstatus_daemon:17> [[ '' == <1-> ]]
    +_gitstatus_daemon:20> local cpus
    +_gitstatus_daemon:21> ((  ! 1  ))
    +_gitstatus_daemon:21> [[ darwin == linux ]]
    +_gitstatus_daemon:22> cpus=+_gitstatus_daemon:22> sysctl -n hw.ncpu
    +_gitstatus_daemon:22> cpus=12 
    +_gitstatus_daemon:27> args+=( -t 24 ) 
    +_gitstatus_daemon:30> mkfifo -- /private/var/folders/8n/s15ccwl52zlgp6rbh2y_4t180000gp/T/gitstatus.MY.502.767.1675464340.1.fifo

  System information:

    zsh:      5.8.1
    uname -a: Darwin JCs-Mac.fibertel.com.ar 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64
```

Maybe it is useful _(or not)_, but I am not using powerlevel, but gitstatusd directly synchronously like in [gitstatus.prompt.zsh](https://github.com/romkatv/gitstatus/blob/master/gitstatus.prompt.zsh).

**Comment by jcbasso** [comment]
Another point is that this only happens on crash reboot. On normal reboots it works like a charm

**Comment by romkatv** [comment]
Apparently this command hangs:

```zsh
mkfifo -- /private/var/folders/8n/s15ccwl52zlgp6rbh2y_4t180000gp/T/gitstatus.MY.502.767.1675464340.1.fifo
```

The directory is `$TMPDIR`.

`mkfifo` is a part of the OS. It's not supposed to hang.

**Comment by jcbasso** [comment]
Thank you very much for the response Roman! 
I see, very strange, it sounds like a race condition problem on MacOs on this cases.

I will try adding some retries on the `mkfifo` command and let you know if I was able to solve it by this! _(it takes some time to retest since I need my battery to drain to reproduce the problem 😞)_

**Comment by romkatv** [comment]
> I will try adding some retries on the `mkfifo` command

Keep in mind that this command *hangs*. If you want to retry it, you'll need to kill it first.

I think a better course of action would be to confirm that something like `mkfifo -- ${TMPDIR}/blah` hangs after your laptop runs out of battery and dies. If you can confirm this, the next step would be to report this to Apple.

**Comment by jcbasso** [comment]
Thanks for the suggestion! 
I didn't explain the implementation but  indeed I took that approach, waiting for certain amount of time since then killing it and retying it a few times.

By reproducing the error I found out that the problem is not that they are hanging but the commands are taking longer than usual. I found it because it broke in a previous command _(`sysctl -n hw.ncpu` on this case)_.

I ended up increasing the timeout waiting for the daemon, and it indeed fixed the problem. 
It is not a perfect solution for obvious reasons that if it really hangs it will take a lot of time to timeout, though that is not more usual in my case than this latency problem.

**Comment by romkatv** [comment]
It's it noticeable that the machine is extremely slow when you are starting the shell?

**Comment by jcbasso** [comment]
The shell starts automatically since Mac saves the state and reopens everything.

It is noticeable that the computer is opening many things, though I am not sure if I would call it _extremely slow_ since the graphical aspects look to work without any stuttering, though multiple things are being open.

The shell initialization though takes some time since it is open until it is ready to use _(maybe 15/30 seconds?)_

**Comment by romkatv** [comment]
I see. 15-30 seconds is around 100 slower than normal, so it makes sense that things are timing out.

I'm not sure what I can do here. You have a workaround: run `exec zsh` when initialization fails. Good enough?

**Comment by jcbasso** [comment]
I also think there is nothing that can be on the `master`. 
I will maintain the increased `timeout` on a local branch since I think is the best for me.

Thank you very much Roman, this thread was useful for me to understand what was going on.
I will close the issue!
