### ISSUE TITLE
OpenBSD - Error: no such instruction: `endbr64`

### ISSUE THREAD

**Issue by Kusoneko** [romkatv/gitstatus#375]
Hello,

I've been trying to install p10k on my openbsd machine, unfortunately, the setup I use on my other machines apparently uses gitstatus and I got a message when sourcing p10k that I should compile gitstatus manually on OpenBSD, so, I went in powerlevel10k/gitstatus and tried the build parameters stated in the readme, I got everything installed, docker isn't supported on OBSD.

Below is the full build log, I removed all the flags for the build command as:
1. docker isn't a thing on openbsd
2. all the dependencies are installed
3. everything already got downloaded, so it's pointless to do it again

It compiles from 0% to 100%, but at the linker it returns a whole bunch of Assembler error messages about the `endbr64` instruction not existing. I am running on 64-bit OpenBSD 7.2 with a 64-bit CPU, so I'm not sure what that error is about.

Any help would be apprectiated.

[log.txt](https://github.com/romkatv/gitstatus/files/10821529/log.txt)

**Comment by romkatv** [comment]
I've never seen this before. This looks like an issue with the compiler/linker toolchain. Try googling the error.

**Comment by Kusoneko** [comment]
I've managed to fix it, it's a bit weird but apparently, according to my relatively short exploration of search results, it's something to do with the assembly code the compiler compiles to containing instructions the assembler that's used at the linking step does not have implemented, or a similar story. For the record, I edited Makefile (not sure what exactly that does though) to replace g++ with clang++ and same with the openbsd eg++ thing in the build script's code. It successfully compiled using clang++, which makes me wonder why it's even asking for gcc/g++ if clang does the job?

**Comment by romkatv** [comment]
Thanks for the update.

From your explanation it seems like your gcc toolchain is broken. It's a good idea to fix it. Also note that you can set the default C++ compiler with `export CXX=clang++`, so it's not necessary to modify the source code.

Anyway, I'm glad you've solve the problem.
