### ISSUE TITLE
Incorrect status in zsh p10k prompt

### ISSUE THREAD

**Issue by timkgh** [romkatv/gitstatus#377]
`gitstatusd` has been working fine for a few years against a big monorepo making the prompt usable, but recently `v1.5.4` has been showing staged, unstaged and untracked files when in fact none really exist, `git status` is clean.

How can I debug this? I'm not sure what may have changed. May be something in the repo git config settings that I have no control over, they just get pushed to the entire team.

Is there a way to tell it to drop its cache when it gets in this state and start clean, without starting a new zsh instance?

**Comment by romkatv** [comment]
There were no recent changes in gitstatusd, so something must have changed on your machine. Maybe a new git version. Maybe a different git config. Try to narrow it down.

> Is there a way to tell it to drop its cache when it gets in this state and start clean, without starting a new zsh instance?

`exec zsh`

**Comment by timkgh** [comment]
This looks like a similar issue: https://github.com/romkatv/powerlevel10k/issues/2232
