### ISSUE TITLE
Multiplatform usage

### ISSUE THREAD

**Issue by dougluce** [romkatv/gitstatus#378]
I'm running a few FreeBSD machines of two different architectures (amd64 and arm64). I'd like to share the same installation of gitstatusd (via p10k/prezto) by way of NFS-distributed home directories.

It's not clear on a quick scan of the code if gitstatus is set up for this to work. It does seem that on amd64 it'll fire up `~/.cache/gitstatus/gitstatusd-freebsd-amd64` and work just fine. But on arm64 it doesn't appear to find `~/.cache/gitstatus/gitstatusd-freebsd-arm64` and do the same. Instead I get this message:
```
[ERROR]: gitstatus failed to initialize.

There is no prebuilt gitstatusd for freebsd arm64.

See: https://github.com/romkatv/gitstatus#compiling
```
And if I then follow the compilation steps verbatim on arm64, I'll get this output on amd64: https://gist.github.com/dougluce/7b1bc4c1c4a3e79dea23377b93adc2fa 
Before I dive too deep into this, I'm wondering: has this been dealt with already (and I've just not set up my installation properly)?

**Comment by romkatv** [comment]
`~/.cache/gitstatus` is the location where gitstatusd binaries downloaded from the internet are stored. It is not the location where binaries compiled by users are stored.

If you build gitstatusd locally, you'll see a binary under the gitstatus directory. You can copy that binary between machines. If you place it in the same location, it'll be found just like it gets found on the machine where it was compiled.

**Comment by romkatv** [comment]
> And if I then follow the compilation steps verbatim on arm64, I'll get this output on amd64: https://gist.github.com/dougluce/7b1bc4c1c4a3e79dea23377b93adc2fa

This is the error:

```text
_gitstatus_daemon_p9k_:63: exec format error: /usr/home/doug/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/usrbin/gitstatusd
```

I suppose it's self-explanatory. You can see the same error if you try to execute `/usr/home/doug/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/usrbin/gitstatusd` directly.

**Comment by dougluce** [comment]
Not sure if I made my setup clear as you wrote "you can copy that binary between machines." The machines share the same filesystem (so there's no copying to be done). Outside of gitstatus, I deal with multiarch binaries with different types of arch-selecting logic (like arch-specific PATH setting or symlinks to a local FS).

Looks like it works if I add this line to `install.info`:

`uname_s_glob="freebsd";        uname_m_glob="arm64";   file="gitstatusd-${uname_s}-${uname_m}";     version="v1.5.3"; sha256="whatever";`

And manually place an arm64 version at `~/.cache/gitstatus/gitstatusd-freebsd-arm64`. I assume this fakes it out into thinking a version was downloaded from the internet.

**Comment by romkatv** [comment]
If you place the binary under `/usr/home/doug/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/usrbin`, you won't have to edit `install.info`. That's what I meant.

However, your previous message indicates that you are attempting to execute a binary that does not match machine architecture. I'm unsure if you are trying to describe two problems simultaneously or what.

**Comment by romkatv** [comment]
You can also set `GITSTATUS_DAEMON=/path/go/gitstatusd` if you want to keep the binary someplace else.
