### ISSUE TITLE
macOS Mojave + bash: a problem and a solution

### ISSUE THREAD

**Issue by beaugunderson** [romkatv/gitstatus#38]
I had `/bin` before `/usr/local/bin` in my path, so `/bin/bash` was taking precedence and `gitstatus_start` was failing. `/usr/local/bin/bash` is 5.0.7(1)-release; `/bin/bash` is 3.2.57(1)-release.

One specific issue seems to be that the newer bash supports `wait -n` syntax while the older bash does not.

Reversing the order fixed the issue. :)

Feel free to close this; I just wanted it to be searchable in case someone else had the same problem.

**Comment by romkatv** [comment]
I've replaced `wait -n` with `wait %1`. Could you update gitstatus, revert your `PATH` changes and check whether it works now?

**Comment by romkatv** [comment]
I believe this problem is fixed. Please reopen if not. If you could confirm that my fix has indeed fixed the problem, that would be really nice. Either way, thanks for the bug report!

**Comment by beaugunderson** [comment]
@romkatv indeed that fixed the issue, thanks so much!

**Comment by romkatv** [comment]
Thanks for the verification!
