### ISSUE TITLE
Extra @-symbol on prompt

### ISSUE THREAD

**Issue by mathomp4** [romkatv/gitstatus#382]
I use gitstatus in bash mode on many a system and on all of them save one it looks like:
```
mathomp4@pfe21 ~
$
```
or:
```
mathomp4@discover23 ~
$
```

But on one system it looks like:
```
mathomp4@gs6101-anvil ~
@$
```

Does anyone know where that extra `@` is from? I am just baffled. I haven't fiddled with `PS1`:
```
mathomp4@gs6101-anvil ~
@$ env | grep PS1
mathomp4@gs6101-anvil ~
@$
```

**Comment by mathomp4** [comment]
> Perhaps `declare -p PS1` will give you a clue.

Huh:

```
@$ declare -p PS1
declare -- PS1="\\[\\033[01;33m\\]\\u@\\h\\[\\033[00m\\] \\[\\033[01;34m\\]\\w\\[\\033[00m\\]\${GITSTATUS_PROMPT:+ \$GITSTATUS_PROMPT}\\n\\[\\033[01;\$((31+!\$?))m\\]\\\$\\[\\033[00m\\] \\[\\e]0;\\u@\\h: \\w\\a\\]"
```

That is...long.

**Comment by romkatv** [comment]
If you remove `\${GITSTATUS_PROMPT:+ \$GITSTATUS_PROMPT}`, you should be able to reproduce this problem without gitstatus. Have fun debugging!
