### ISSUE TITLE
[Bash in Linux] Incompatibility between gitstatus and fzf-tab-completion utilities, terminal exits

### ISSUE THREAD

**Issue by bluz71** [romkatv/gitstatus#383]
Hello @romkatv,

Long-time user of `gitstatus` via my [bash-seafly-prompt](https://github.com/bluz71/bash-seafly-prompt) script.

A couple days ago I wanted to use [fzf-tab-completion](https://github.com/lincheney/fzf-tab-completion) in my Bash configuration.

No good, there is a bad interaction between `gitstatus` and `fzf-tab-completion` when doing Bash tab completion; basically the terminal GUI window (Alacritty & GNOME-Terminal) will close upon hitting `ENTER` after a completion.

I can repeat the issue with this minimal `~/.bashrc` file:

```bash
_command_prompt() {
    if ! hash gitstatus_query 2>/dev/null || ! gitstatus_query -p; then
        return
    fi
}

if [[ -r ~/.gitstatus/gitstatus.plugin.sh ]]; then
    source ~/.gitstatus/gitstatus.plugin.sh
    gitstatus_stop && gitstatus_start -c 0 -d 0
fi

PROMPT_COMMAND=_command_prompt

. ~/fzf-tab-completion/bash/fzf-bash-completion.sh
bind -x '"\t": fzf_bash_completion'
```

I installed `fzf-tab-completion` via `git clone https://github.com/lincheney/fzf-tab-completion` in the home directory. The `fzf` utility needs to be installed somewhere in the `$PATH`.

Then do `cd <TAB>`, select a directory from the `fzf` list followed by `ENTER` to execute the `cd` command. BOOM, the window will close.

Maybe `fzf-tab-completion` is at fault, I don't know, but I have come here first. Hopefully an easy fix either here, or at `fzf-tab-completion` or possibly even my `bash-seafly-prompt` script.

Regards.

**Comment by romkatv** [comment]
I'm afraid I won't commit to debugging this.

**Comment by bluz71** [comment]
Ok, sad for me, but life goes on.

**Comment by bluz71** [comment]
@lincheney, author of `fzf-tab-completion` [implemented a fix](https://github.com/lincheney/fzf-tab-completion/commit/7de33435821237aaaeec79137bb9d407fa5a17cb) for this issue.
