### ISSUE TITLE
cygwin/windows support

### ISSUE THREAD

**Issue by hoshsadiq** [romkatv/gitstatus#39]
Hello, any chance we can get cygwin/windows support please?

**Comment by romkatv** [comment]
I thought everyone is using WSL on Windows nowadays. Why aren't you?

(Asking to figure out how useful cygwin would be.)

**Comment by hoshsadiq** [comment]
Company I work for still uses Windows 7 and everything is heavily locked down. Would it be very hard to get cygwin support?

Honestly I could have lived without gitstatus on cygwin since I'm primarily a Linux user, but p10k is so slow inside git dirs. Takes about 2 seconds to load. Outside of git directories, p10k is fast and usable and close to the speeds I get on my linux machine.

**Comment by romkatv** [comment]
> Would it be very hard to add cygwin support?

I currently build gitstatusd for 7 different architectures and 4 operating systems on 4 different physical devices. It's not too much work for the initial port to cygwin but it entails maintenance along the road.

> Honestly I could have lived without gitstatus on cygwin since I'm primarily a Linux user, but p10k is so slow inside git dirs. Takes about 2 seconds to load. Outside of git directories, p10k is fast and usable and close to the speeds I get on my linux machine.

Makes sense. If gitstatus isn't available, p10k falls back to `vcs_info` -- the same library that p9k and many other ZSH themes use. This library makes several `git` calls and `git` is slow.

I'll install cygwin tomorrow and try to port gitstatus. If I manage to build a decent binary without too many dynamic dependencies, I'll add cygwin to the list of supported platforms. I'll ping you on this issue and will ask you to verify that the binary works for you. I'd very much prefer not to install Windows 7 myself.

**Comment by romkatv** [comment]
I managed to build gitstatusd on cygwin without much trouble but unfortunately zsh bindings don't work because fifos are broken on cygwin. I'll try to find a workaround later but for now it would be nice if you could verify that the binary works on your system. Please run the following commands from ZSH on Cygwin and post its output here:

```zsh
git clone https://github.com/romkatv/gitstatus.git ~/gitstatus
cd ~/gitstatus
echo -nE id$'\x1f'$PWD$'\x1e' | ./bin/gitstatusd-cygwin_nt-10.0-x86_64 | {
  local resp
  IFS=$'\x1f' read -rd $'\x1e' -A resp && print -lr -- "${(@qq)resp}"
}
```

**Comment by hoshsadiq** [comment]
![image](https://user-images.githubusercontent.com/600045/59688999-b5c31280-91d6-11e9-9575-af329bfb6fa9.png)

**Comment by romkatv** [comment]
I figured out how exactly fifos are broken on cygwin and ported gitstatus ZSH bindings. Please update powerlevel10k and try using it on Cygwin without disabling gitstatus. Let me know whether it works and whether performance is tolerable.

**Comment by hoshsadiq** [comment]
Nice! I'll report back tomorrow.

**Comment by hoshsadiq** [comment]
Perfect! It works and it's fast! Thanks for the quick fix :)

**Comment by romkatv** [comment]
Thanks for the confirmation!
