### ISSUE TITLE
Problem with pk10 config

### ISSUE THREAD

**Issue by gbruzual** [romkatv/gitstatus#394]
Last login: Mon Jul 10 14:06:54 on ttys000
[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  The content of /private/var/folders/l5/fmk624t514g2qckw4f15ytz80000gn/T/gitstatus.POWERLEVEL9K.501.20642.1689019713.1.xtrace.log (gitstatus_start xtrace):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/l5/fmk624t514g2qckw4f15ytz80000gn/T/gitstatus.POWERLEVEL9K.501.20642.1689019713.1.lock
    +(anon):15> [[ 16 == <1-> ]]
    +(anon):17> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> '(anon)' /dev/fd/18
    +(anon):1> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=20653'
    +(anon):2> sysopen -r -o cloexec -u resp_fd -- /dev/fd/18
    +(anon):3> [[ 20 == <1-> ]]
    +(anon):4> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):120> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):123> ((  ! async  ))
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):123> ((  ! async  ))
    +(anon):124> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):126> local pgid
    +(anon):127> ((  0 < 20  ))
    +(anon):128> [[ -t 20 ]]
    +(anon):129> sysread -s 20 -t 5.0000000000 -i 20 'pgid[$#pgid+1]'
    +(anon):129> return
                         ^ this command failed (5)

  The content of /private/var/folders/l5/fmk624t514g2qckw4f15ytz80000gn/T/gitstatus.POWERLEVEL9K.501.20642.1689019713.1.daemon.log (gitstatus daemon log):

    +(anon):22> local pgid=20653
    +(anon):23> [[ 20653 == <1-> ]]
    +(anon):104> ((  lock_fd == -1  ))
    +(anon):27> trap '' PIPE
    +(anon):29> [[ -z '' ]]
    +(anon):30> local kernel
    +(anon):31> kernel=+(anon):107> zsystem flock -- /private/var/folders/l5/fmk624t514g2qckw4f15ytz80000gn/T/gitstatus.POWERLEVEL9K.501.20642.1689019713.1.lock
    +(anon):31> uname -s
    +(anon):31> kernel=darwin
    +(anon):32> [[ -n darwin ]]
    +(anon):35> [[ '' == /* ]]
    +(anon):37> ((  0  ))
    +(anon):39> [[ -n '' ]]
    +(anon):42> local -aU os
    +(anon):43> case darwin (linux)
    +(anon):43> case darwin (cygwin_nt-*)
    +(anon):43> case darwin (mingw* | msys*)
    +(anon):43> case darwin (*)
    +(anon):50> os=( darwin )
    +(anon):52> local arch
    +(anon):53> arch=+(anon):53> uname -m
    +(anon):53> arch=arm64
    +(anon):54> [[ -n arm64 ]]
    +(anon):55> local daemons=( /Users/bruzual/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-arm64 /Users/bruzual/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-arm64-static /Users/bruzual/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-darwin-arm64 /Users/bruzual/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/bin/gitstatusd-darwin-arm64-static )
    +(anon):59> local files=( )
    +(anon):60> daemons=( )
    +(anon):62> ((  stderr_fd && 0 != 0  ))
    +(anon):72> ((  0  ))
    +(anon):72> return
    +(anon):99> local -i ret=1
    +(anon):100> kill -- -20653

  Your system information:

    zsh:      5.9
    uname -a: Darwin Gustavos-MacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new
~ ❯

**Comment by romkatv** [comment]
Run this:

```zsh
zprezto-update
```

Then restart zsh with `exec zsh`.

**Comment by gbruzual** [comment]
Thanks a lot.

It did work

Gustavo
