### ISSUE TITLE
error al intentar ser usurio root en virtualbox parrot os

### ISSUE THREAD

**Issue by LUISDIAZ19** [romkatv/gitstatus#405]
[ERROR]: gitstatus failed to initialize.

  Zsh log (/tmp/gitstatus.POWERLEVEL9K.0.99120.1692289758.2.xtrace.log): 
Daemon log (/tmp/gitstatus.POWERLEVEL9K.0.99120.1692289758.2.daemon.log):

**Comment by romkatv** [comment]
Can you describe the issue in English?
