### ISSUE TITLE
VCS_STATUS_WORKDIR displayed on prompt instead of status

### ISSUE THREAD

**Issue by peschkaj** [romkatv/gitstatus#42]
In one particular on my system the gitstatus plugin correctly displays the git status the very first time I'm in that directory but afterwards, the directory name is replaced with `VCS_STATUS_WORKDIR`:

![image](https://user-images.githubusercontent.com/71570/60927390-9dd33180-a25e-11e9-970f-aee8619821cb.png)

This repository is from the seL4 microkernel and, as long as you have `repo` installed, this can be duplicated by running:

```
mkdir sel4test
cd sel4test
repo init -u https://github.com/seL4/sel4test-manifest.git
repo sync
cd kernel
echo "hi"
```

The `.git/config` for the kernel directory looks like this:

```
[core]
        repositoryformatversion = 0
        filemode = true
[filter "lfs"]
        smudge = git-lfs smudge --skip -- %f
        process = git-lfs filter-process --skip
[remote "seL4"]
        url = https://github.com/seL4/seL4.git
        projectname = seL4.git
        fetch = +refs/heads/*:refs/remotes/seL4/*
```

I'm not sure what other info would be helpful to troubleshoot this.

**Comment by romkatv** [comment]
If you have `AUTO_NAME_DIRS` option set, this is its intended behavior. You can add `unsetopt AUTO_NAME_DIRS` to your `.zshrc` to turn it off. Few people set this option intentionally.
