### ISSUE TITLE
I have this problem 

### ISSUE THREAD

**Issue by haniissa** [romkatv/gitstatus#421]
[ERROR]: gitstatus failed to initialize.

  Zsh log (/tmp/gitstatus.POWERLEVEL9K.197609.895.1707814850.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'MINGW64_NT-10.0-19045 version 3.4.9-be826601.x86_64 (@fv-az885-303) (gcc version 11.3.0 (GCC) ) 2023-09-07 12:36 UTC' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.197609.895.1707814850.1.lock
    +(anon):15> [[ 17 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ msys == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/16
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=917'
    +(anon):46> [[ 19 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 19 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 19 'pgid[$#pgid+1]'
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '                 917' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /tmp/gitstatus.POWERLEVEL9K.197609.895.1707814850.1.fifo
    +(anon):63> [[ 18 == <1-> ]]
    +(anon):64> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):66> print -nru 18 -- $'}hello\C-_\C-^'
    +(anon):67> local expected=$'}hello\C-_0\C-^' actual
    +(anon):68> ((  1  ))
    +(anon):68> [[ ! -t 1 && ! -t 0 ]]
    +(anon):69> local -F deadline='EPOCHREALTIME + 4'
    +(anon):73> true
    +(anon):74> [[ -t 19 ]]
    +(anon):75> sysread -s 1 -t 5.0000000000 -i 19 actual
    +(anon):75> return

  Daemon log (/tmp/gitstatus.POWERLEVEL9K.197609.895.1707814850.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=917
    +_gitstatus_daemon_p9k_:4> [[ 917 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.197609.895.1707814850.1.lock
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='mingw64_nt-10.0-19045 x86_64'
    +_gitstatus_daemon_p9k_:13> [[ 'mingw64_nt-10.0-19045 x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=mingw64_nt-10.0-19045
    +_gitstatus_daemon_p9k_:15> local uname_m=x86_64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 0  ))
    +_gitstatus_daemon_p9k_:23> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:23> cpus=+_gitstatus_daemon_p9k_:23> getconf _NPROCESSORS_ONLN
    +_gitstatus_daemon_p9k_:23> cpus=4
    +_gitstatus_daemon_p9k_:27> args+=( -t 8 )
    +_gitstatus_daemon_p9k_:30> mkfifo -- /tmp/gitstatus.POWERLEVEL9K.197609.895.1707814850.1.fifo
    +_gitstatus_daemon_p9k_:31> print -rnu 17 -- '                 917'
    +_gitstatus_daemon_p9k_:33> zf_rm -- /tmp/gitstatus.POWERLEVEL9K.197609.895.1707814850.1.fifo
    +_gitstatus_daemon_p9k_:35> local _gitstatus_zsh_daemon _gitstatus_zsh_version _gitstatus_zsh_downloaded
    +_gitstatus_daemon_p9k_:43> local gitstatus_plugin_dir_var=_gitstatus_plugin_dir_p9k_
    +_gitstatus_daemon_p9k_:44> local gitstatus_plugin_dir=/c/Users/jazmi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_daemon_p9k_:45> set -- -d /c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s mingw64_nt-10.0-19045 -m x86_64 -p 'printf '\''\001'\'' >&17' -e 17 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_daemon_p9k_:47> [[ 1 == (|-|+)<1-> ]]
    +_gitstatus_daemon_p9k_:48> source /c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install
    +/c/Users/jazmi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install:467> [ -z '' ']'
    +/c/Users/jazmi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install:468> _gitstatus_install_main /c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -d /c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s mingw64_nt-10.0-19045 -m x86_64 -p 'printf '\''\001'\'' >&17' -e 17 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:1> [ -n 5.8 ']'
    +_gitstatus_install_main:2> emulate -L sh -o no_unset
    +_gitstatus_install_main:7> local argv1=/c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:8> shift
    +_gitstatus_install_main:10> local no_check='' no_install='' uname_s='' uname_m='' gitstatus_dir='' dl_status='' e=''
    +_gitstatus_install_main:11> local opt='' OPTARG='' OPTIND=1
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s mingw64_nt-10.0-19045 -m x86_64 -p 'printf '\''\001'\'' >&17' -e 17 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case d (h)
    +_gitstatus_install_main:14> case d (n)
    +_gitstatus_install_main:14> case d (f)
    +_gitstatus_install_main:14> case d (d)
    +_gitstatus_install_main:55> [ -n '' ']'
    +_gitstatus_install_main:59> [ -z /c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus ']'
    +_gitstatus_install_main:63> gitstatus_dir=/c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s mingw64_nt-10.0-19045 -m x86_64 -p 'printf '\''\001'\'' >&17' -e 17 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case s (h)
    +_gitstatus_install_main:14> case s (n)
    +_gitstatus_install_main:14> case s (f)
    +_gitstatus_install_main:14> case s (d)
    +_gitstatus_install_main:14> case s (p)
    +_gitstatus_install_main:14> case s (e)
    +_gitstatus_install_main:14> case s (m)
    +_gitstatus_install_main:14> case s (s)
    +_gitstatus_install_main:99> [ -n '' ']'
    +_gitstatus_install_main:103> [ -z mingw64_nt-10.0-19045 ']'
    +_gitstatus_install_main:107> uname_s=mingw64_nt-10.0-19045
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s mingw64_nt-10.0-19045 -m x86_64 -p 'printf '\''\001'\'' >&17' -e 17 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case m (h)
    +_gitstatus_install_main:14> case m (n)
    +_gitstatus_install_main:14> case m (f)
    +_gitstatus_install_main:14> case m (d)
    +_gitstatus_install_main:14> case m (p)
    +_gitstatus_install_main:14> case m (e)
    +_gitstatus_install_main:14> case m (m)
    +_gitstatus_install_main:88> [ -n '' ']'
    +_gitstatus_install_main:92> [ -z x86_64 ']'
    +_gitstatus_install_main:96> uname_m=x86_64
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s mingw64_nt-10.0-19045 -m x86_64 -p 'printf '\''\001'\'' >&17' -e 17 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case p (h)
    +_gitstatus_install_main:14> case p (n)
    +_gitstatus_install_main:14> case p (f)
    +_gitstatus_install_main:14> case p (d)
    +_gitstatus_install_main:14> case p (p)
    +_gitstatus_install_main:66> [ -n '' ']'
    +_gitstatus_install_main:70> [ -z 'printf '\''\001'\'' >&17' ']'
    +_gitstatus_install_main:74> dl_status='printf '\''\001'\'' >&17'
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s mingw64_nt-10.0-19045 -m x86_64 -p 'printf '\''\001'\'' >&17' -e 17 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case e (h)
    +_gitstatus_install_main:14> case e (n)
    +_gitstatus_install_main:14> case e (f)
    +_gitstatus_install_main:14> case e (d)
    +_gitstatus_install_main:14> case e (p)
    +_gitstatus_install_main:14> case e (e)
    +_gitstatus_install_main:77> [ -n '' ']'
    +_gitstatus_install_main:81> [ -z 17 ']'
    +_gitstatus_install_main:85> e=17
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s mingw64_nt-10.0-19045 -m x86_64 -p 'printf '\''\001'\'' >&17' -e 17 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:115> shift 11
    +_gitstatus_install_main:117> : 17
    +_gitstatus_install_main:118> : /c/Users/jazmi/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:120> [ -n '' -a -n '' ']'
    +_gitstatus_install_main:125> [ -z mingw64_nt-10.0-19045 ']'
    +_gitstatus_install_main:129> [ -z x86_64 ']'
    +_gitstatus_install_main:134> local daemon=''
    +_gitstatus_install_main:135> local cache_dir=/c/Users/jazmsis/.cache/gitstatus
    +_gitstatus_install_main:137> [ -z '' ']'
    +_gitstatus_install_main:138> [ -n '' ']'
    +_gitstatus_install_main:142> [ -z '' -a -e /c/Users/jazmsis/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd ']'
    +_gitstatus_install_main:145> [ -n '' ']'
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'

  System information:

    zsh:      5.8
    uname -a: MINGW64_NT-10.0-19045 DESKTOP-jazmsis 3.4.9-be826601.x86_64 2023-09-07 12:36 UTC x86_64 Msys

 If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by romkatv** [comment]
The version of powerlevel10k you are using is quite old. Try updating it. I am not sure it'll help but it might.

```zsh
git -C ~/.oh-my-zsh/custom/themes/powerlevel10k pull
```

**Comment by haniissa** [comment]
thanks, man , I think this mean was updated.
[powerlevel10k] fetching gitstatusd .. [ok]
