### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by trip1e** [romkatv/gitstatus#423]
My problem:
```
ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:

    GITSTATUS_LOG_LEVEL=DEBUG GITSTATUS_NUM_THREADS=20 GITSTATUS_DAEMON=/Users/trip1e/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-arm64 gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 -a POWERLEVEL9K

  If this command produces no output, add the following parameter to ~/.zshrc:

    GITSTATUS_LOG_LEVEL=DEBUG

  With this parameter, gitstatus will print additional information on error.

```

Output:
![SCR-20240213-wxy](https://github.com/romkatv/gitstatus/assets/24723771/f49c7959-d83a-4b98-9575-6ab9d76ec041)

**Comment by romkatv** [comment]
Congratulations on getting a new laptop. You need to update powerlevel10k:

```zsh
git -C ~/.oh-my-zsh/custom/themes/powerlevel10k pull
```

**Comment by trip1e** [comment]
Thank you, problem solved. 
If the terminal would have directly prompted me to use this command I wouldn't have had to create the issue.

**Comment by romkatv** [comment]
Indeed. Unfortunately, I cannot remotely update old versions of powerlevel10k on people's laptops.

**Comment by trip1e** [comment]
But I found another bug after that update.
When resizing the window, it duplicates the contents of the terminal.


https://github.com/romkatv/gitstatus/assets/24723771/2c3920a9-d181-4902-b7d3-a63301d72e11

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#horrific-mess-when-resizing-terminal-window
