### ISSUE TITLE
Gitstatus error on ohmyzsh terminal

### ISSUE THREAD

**Issue by SolomonChidera** [romkatv/gitstatus#424]
[ERROR]: gitstatus failed to initialize.

  Zsh log (/tmp/gitstatus.POWERLEVEL9K.1000.158.1710087992.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 21 ]]
    +(anon):57> sysread -s 20 -t 10.0000000000 -i 21 'pgid[$#pgid+1]'
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '                 314' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /tmp/gitstatus.POWERLEVEL9K.1000.158.1710087992.1.fifo
    (anon):sysopen:62: can't open file /tmp/gitstatus.POWERLEVEL9K.1000.158.1710087992.1.fifo: no such file or directory
    +(anon):62> return

  System information:

    zsh:      5.8.1
    uname -a: Linux DESKTOP-N0BIVTD 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by romkatv** [comment]
It's a bug in the OS: https://github.com/microsoft/WSL/issues/8441#issuecomment-1139469707.

**Comment by SolomonChidera** [comment]
> It's a bug in the OS: [microsoft/WSL#8441 (comment)](https://github.com/microsoft/WSL/issues/8441#issuecomment-1139469707).

Ohh okay, will disable the error then and use it just like I've been doing
