### ISSUE TITLE
Can you release prebuilt binaries of v1.5.5

### ISSUE THREAD

**Issue by gabriel254** [romkatv/gitstatus#431]

**Comment by romkatv** [comment]
Can you describe the problem you are having?

**Comment by gabriel254** [comment]
I need to build a docker image and use it in an **OFFLINE** environment, so I have to download the binary to "$HOME/.cache/gitstatus"

**Comment by romkatv** [comment]
What's stopping you from doing that?

**Comment by gabriel254** [comment]
I can compile it locally and copy it into the docker image. It would be convenient that there are officially released binaries just like `v1.5.4`

**Comment by romkatv** [comment]
Can you describe what you are doing, what you expect and what you observe?

Also, if you are using powerlevel10k, see [this FAQ](https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#how-do-i-install-powerlevel10k-on-a-machine-without-internet-access). If you are using gitstatus without powerlvel10k, it should be straightforward to adapt these instructions for it.

**Comment by gabriel254** [comment]
Thanks for your help, I do use `powerlevel10k`.  I followed the instructions and run the following commands:

```sh
target_uname="linux x86_64"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
GITSTATUS_CACHE_DIR="$HOME"/powerlevel10k/gitstatus/usrbin ~/powerlevel10k/gitstatus/install -f -s "${target_uname% *}" -m "${target_uname#* }"
```

And I got the binary `$HOME/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-x86_64`.

```sh
$HOME/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-x86_64 --version
v1.5.4
```

But this is `v1.5.4`, not the latest `v1.5.5`

**Comment by romkatv** [comment]
If you follow the instructions, does powerlevel10k work as intended?

**Comment by gabriel254** [comment]
Yes, all things are fine. I just want to make sure all the binary I use are the latest versions, though I didn't notice any difference between them.

**Comment by romkatv** [comment]
It's all fine, don't worry. When you open an issue next time, make sure to include these crucial parts:

1. What you do.
2. What you expect to happen.
3. What actually happens.
