### ISSUE TITLE
Files added with `git add -N` are reported as "staged"

### ISSUE THREAD

**Issue by dorian-marchal** [romkatv/gitstatus#44]
This is inconsistent with `git status`:

```shell
mkdir /tmp/foobar

cd /tmp/foobar/

git init
# Initialized empty Git repository in /tmp/foobar/.git/

source ~/gitstatus/gitstatus.plugin.sh

gitstatus_start

echo foo > a

git add -N a

git status
# On branch master
#
# No commits yet
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
# 	new file:   a
#
# no changes added to commit (use "git add" and/or "git commit -a")

gitstatus_query

echo $VCS_STATUS_NUM_STAGED
# 1 ← Expected 0

echo $VCS_STATUS_NUM_UNSTAGED
# 1
```

**Comment by romkatv** [comment]
Thanks for reporting this bug.

How important is this to you?

**Comment by dorian-marchal** [comment]
Not very important, it just surprised me.

**Comment by romkatv** [comment]
I agree it's surprising. It's clearly a bug in gitstatusd.

I was asking about the importance to figure out how to prioritize fixing the bug. Based on your reply I'll put off fixing it for now and will get to it once I'm done with more urgent matters.

**Comment by dorian-marchal** [comment]
> Based on your reply I'll put off fixing it for now and will get to it once I'm done with more urgent matters.

Seems fine. :+1:

For completeness, I found that the behavior is different when the file is empty (but still wrong):

```shell
# From the previous repro:
git rm a

touch a

git add -N b

git status
# On branch master
#
# No commits yet
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
# 	new file:   a
#
# no changes added to commit (use "git add" and/or "git commit -a")

gitstatus_query

echo $VCS_STATUS_NUM_STAGED
# 1 ← Expected 0

echo $VCS_STATUS_NUM_UNSTAGED
# 0 ← Expected 1
```

**Comment by romkatv** [comment]
> For completeness, I found that the behavior is different when the file is empty (but still wrong):

Makes sense. `git add -N file` adds `file` to the index _without content_. gitstatusd behaves as if `git add -N file` was adding `file` to the index _with empty content_.

**Comment by romkatv** [comment]
This is done. When using `git add -N`, the number of staged and unstaged changes reported by gitstatus should be consistent with git.

I don't use `git add -N` myself and the implementation wasn't trivial, so please double-check that it works as you would expect.

**Comment by dorian-marchal** [comment]
Thank you! 

> I don't use git add -N myself and the implementation wasn't trivial

I hope it doesn't add too much complexity to `gitstatusd`.

> please double-check that it works as you would expect.

I'm updating right now and will report if I find any issue. :+1:

**Comment by romkatv** [comment]
> I hope it doesn't add too much complexity to `gitstatusd`.

Naah, it's not complex. Changes are small but they are in 3 separate places and each of them isn't obvious.

> I'm updating right now and will report if I find any issue. 👍

Thanks!
