### ISSUE TITLE
Turn off false Warning

### ISSUE THREAD

**Issue by silverhadch** [romkatv/gitstatus#446]
[ERROR]: gitstatus failed to initialize.

There is no prebuilt gitstatusd for openbsd amd64.

See: https://github.com/romkatv/gitstatus#compiling

Let me turn off this warning, gitstatus is installed correctly!!!!

**Comment by romkatv** [comment]
It's not a warning.

**Comment by silverhadch** [comment]
Yeah it an error message but its false since i already have it installed, is there a way to turn off the output. But doesnt quite matter i switched to another git status and starship prompt.

**Comment by romkatv** [comment]
It's not false.

**Comment by silverhadch** [comment]
It sure is i installed correctly and used it, the error is simply false but that doesnt matter anymore.

**Comment by romkatv** [comment]
You can check whether gitstatus works by running the following command:

In zsh:

```zsh
typeset -pm 'GITSTATUS_DAEMON_PID*'
```

In bash:

```bash
typeset -p GITSTATUS_DAEMON_PID
```

If these commands succeed, gitstatus works. If they don't, gitstatus does not work.

What happens if you run one of these commands (depending on your shell)?

**Comment by romkatv** [comment]
It's not needed. I only wanted to show that your assertion was false. Out of courtesy.
