### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by MercedesDF** [romkatv/gitstatus#447]
System information:

    zsh:      5.8.1
    uname -a: Linux aitormerche 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new
_p9k_worker_receive:sysopen:40: can't open file /tmp/p10k.worker.1000.161.1732215847.fifo: no such file or directory

**Comment by romkatv** [comment]
It's a bug in WSL2.

**Comment by MercedesDF** [comment]
ok. Iḿ trying to my pc works on. Itś a few old and iḿ lerning.
