### ISSUE TITLE
Using gitstatus in oh-my-zsh theme.

### ISSUE THREAD

**Issue by Izorkin** [romkatv/gitstatus#45]
How can I call gitstatus from customized theme oh-my-zsh? I'm using the following code to show status:
```
function vcs_info() {
  test -d ".bzr" && which bzr >/dev/null 2>&1 && bzr_prompt_info
  test -d ".git" && which git >/dev/null 2>&1 && git_prompt_info
  test -d ".hg"  && which hg  >/dev/null 2>&1 && hg_prompt_info
}
```
How can I replace git_prompt_info() function with a function using gitstatus plugin?

**Comment by romkatv** [comment]
The easiest and best way to use gitstatus is via [Powerlevel10k](https://github.com/romkatv/powerlevel10k/).

```zsh
git clone https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
cp $ZSH_CUSTOM/themes/powerlevel10k/config/p10k-lean.zsh ~/
echo 'source ~/p10k-lean.zsh' >>! ~/.zshrc
```

Then set `ZSH_THEME=powerlevel10k/powerlevel10k` in your `~/.zshrc`.

If you really want to integrate with gitstatus manually, read the documentation.
