### ISSUE TITLE
Power level 10k git status error

### ISSUE THREAD

**Issue by DanielAtCosmicDNA** [romkatv/gitstatus#450]
I would like to report this problem after I have just updated powerlevel 10k. From the outset it looks like Powerlevel10k is complaining about the current gitstatus version.

[gitstatus.POWERLEVEL9K.1000.1228.1733164948.1.daemon.log](https://github.com/user-attachments/files/17982513/gitstatus.POWERLEVEL9K.1000.1228.1733164948.1.daemon.log)
[gitstatus.POWERLEVEL9K.1000.1228.1733164948.1.xtrace.log](https://github.com/user-attachments/files/17982514/gitstatus.POWERLEVEL9K.1000.1228.1733164948.1.xtrace.log)

Here is my system info:

zsh:      5.9
    uname -a: Linux Birkbeck 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux

**Comment by romkatv** [comment]
Try this:

```zsh
rm ~/.antigen/bundles/romkatv/powerlevel10k/gitstatus/usrbin/gitstatusd && exec zsh
```

**Comment by DanielAtCosmicDNA** [comment]
I just tested it fixed the problem for me.
