### ISSUE TITLE
There is no gitstatusd binary for sunos-i86pc

### ISSUE THREAD

**Issue by AlanBStone** [romkatv/gitstatus#47]
Here's the message that appears:

[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /tmp/gitstatus.1584.xtrace.XXXX2Ka4ld (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:11> local os
    +gitstatus_start_impl:11> os=+gitstatus_start_impl:11> uname -s
    +gitstatus_start_impl:11> os=SunOS 
    +gitstatus_start_impl:11> [[ -n SunOS ]]
    +gitstatus_start_impl:12> [[ SunOS != Linux ]]
    +gitstatus_start_impl:13> local arch
    +gitstatus_start_impl:13> arch=+gitstatus_start_impl:13> uname -m
    +gitstatus_start_impl:13> arch=i86pc 
    +gitstatus_start_impl:13> [[ -n i86pc ]]
    +gitstatus_start_impl:15> local daemon=/export/home/hitch/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-sunos-i86pc
    +gitstatus_start_impl:16> [[ -f /export/home/hitch/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-sunos-i86pc ]]
                               ^ this command failed

  Your system information:

    zsh:      5.7.1
    uname -a: SunOS openindiana 5.11 illumos-8d13991861 i86pc i386 i86pc

Thanks,

Alan

**Comment by romkatv** [comment]
SunOS on PowerPC? Do those things still exist?

I don't provide a binary for this system and frankly I don't think I will. You can try [building gitstatusd yourself](https://github.com/romkatv/gitstatus#compiling).

1. Install `cmake`, GNU `make` and `gcc`.
2. Run this command:

```zsh
zsh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/gitstatus/master/build.zsh)"
```

If something doesn't work, improvise.

A simpler solution is define `POWERLEVEL9K_DISABLE_GITSTATUS=true`. This will get rid of the error but it'll also make your prompt much slower.

**Comment by AlanBStone** [comment]
Thanks much!  Everything else works fantastic, as I have modified it where possible, but this error had me confused.  Thanks for the suggestion and I will build it.

Thanks,

Alan

**Comment by romkatv** [comment]
Have you succeeded in building gitstatusd? Did you have to change anything in the build script or the code? Could you share your changes?

**Comment by AlanBStone** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Not yet. Have been preoccupied with a couple other projects. I will share when completed. Alan                                                                                                                                             Alan Blaine StoneU.S.: +1-202-760-4707INTL: +40-755-539-328Email: stoneab@gmail.com Sent from my BlackBerry - the most secure mobile device                                                                                                                                                                           From: notifications@github.comSent: July 28, 2019 09:57To: gitstatus@noreply.github.comReply-to: reply@reply.github.comCc: stoneab@gmail.com; author@noreply.github.comSubject: Re: [romkatv/gitstatus] GITSTATUS ERROR (#47)  Have you succeeded in building gitstatusd? Did you have to change anything in the build script or the code? Could you share your changes?

**Comment by romkatv** [comment]
Closing as I don't plan to do anything here and there is no other activity.
