### ISSUE TITLE
GitStatus support async pulling of git remote?

### ISSUE THREAD

**Issue by megalithic** [romkatv/gitstatus#49]
Hi there! Love your plugin, I've written just a super basic prompt where I use your gitstatus plugin to pull the vcs info (git specifically). Is there a way to enable async pulling of the git remote (similar to Pure's capability to do that)?

**Comment by romkatv** [comment]
> Is there a way to enable async pulling of the git remote.

Nope, and it's unlikely that it'll every be added. It could be a reasonable feature for [powerlevel10k](https://github.com/romkatv/powerlevel10k/) but not for gitstatus. gitstatus is a essentially a fast `git status` with output in more convenient format. If you need periodic `git fetch`, it's best to implement it on the side. There are no benefits form bundling `git status` with `git fetch` in a single package.

**Comment by romkatv** [comment]
Closing as out of scope.
