### ISSUE TITLE
gitstatusd keeping files opened

### ISSUE THREAD

**Issue by aperum** [romkatv/gitstatus#52]
Sometimes gitstatusd seems to open a file and doesn't close it until being killed.
It happens often enough to interfere with daily filesystem rotations etc.:

cannot unmount '/poudriere/ports/default': Device busy
The following processes are using '/poudriere/ports/default':
USER     CMD          PID   FD MOUNT      INUM MODE         SZ|DV R/W
root     gitstatusd-freebsd- 55320    4 /poudriere/ports/default 307301 -r--r--r--  127462930  r
[Error 03:32:08] Can't destroy ZFS filesystem 'data/poudriere/ports/default'.

Even 6 hours after that the file is still open:

╰ fstat -p 55320
USER     CMD          PID   FD MOUNT      INUM MODE         SZ|DV R/W
root     gitstatusd-freebsd- 55320 text /shareddata   2188 -rwxr-xr-x  3252072  r
root     gitstatusd-freebsd- 55320 ctty /dev        241 crw--w----   pts/1 rw
root     gitstatusd-freebsd- 55320   wd /            20 drwxr-xr-x      36  r
root     gitstatusd-freebsd- 55320 root /             4 drwxr-xr-x      32  r
root     gitstatusd-freebsd- 55320    0 -         18865 prw-r--r--       0  r
root     gitstatusd-freebsd- 55320    1 -         18867 prw-r--r--       0  w
root     gitstatusd-freebsd- 55320    2 /dev         16 crw-rw-rw-    null  w
root     gitstatusd-freebsd- 55320    3 -         18863 -rw-------       0  r
root     gitstatusd-freebsd- 55320    4 /poudriere/ports/default 307301 -r--r--r--  127462930  r

This is on: 12.0-RELEASE-p7 amd64

**Comment by romkatv** [comment]
I cannot read this output. Which file is being used?

**Comment by aperum** [comment]
In this case its the directory /poudriere/ports/default

**Comment by aperum** [comment]
Just to be precise, gitstatusd was used here by powerlevel10k and the directory /poudriere/ports/default is populated with a git respository.

**Comment by romkatv** [comment]
gitstatusd is not supposed to open directories. It creates two fifos in `${TMPDIR:/tmp}`, deletes them and keeps file descriptors open. The other ends of the fifos are being kept open by zsh. These fifos are used for communication between zsh and gitstatusd.

If what you are seeing is consistent with this story, then it's working as expected. If you are seeing that gitstatusd keeps some other files open, please tell me the file names. On Linux you can do it with `lsof -p $GITSTATUS_DAEMON_PID_POWERLEVEL9K` and `ls -l /proc/$GITSTATUS_DAEMON_PID_POWERLEVEL9K/fd` but I don't know whether this works on BSD.

**Comment by romkatv** [comment]
> Just to be precise, gitstatusd was used here by powerlevel10k and the directory /poudriere/ports/default is populated with a git respository.

Oh, so it's a git repo. That makes sense. Yes, gitstatusd doesn't close git repos. If this breaks your workflow, I'll see if it's possible to fix without much pain.

Note that gitstatusd is tied to the zsh that has spawned it. If you restart zsh, its gitstatusd will restart too.

**Comment by aperum** [comment]
I thought about just killing the zsh process but actually these zsh instances are interactive shells in tmux sessions. So killing them would interfere with the user experience. 

Maybe the possibility to send gitstatusd a SIGHUP or SIGUSR so it releases its currently open files/directories could mitigate the situation if its too much effort to fix otherwise.

**Comment by romkatv** [comment]
> I thought about just killing the zsh process but actually these zsh instances are interactive shells in tmux sessions. So killing them would interfere with the user experience.

If you kill gitstatusd, the shell that has spawned it will lose its Git prompt.

> Maybe the possibility to send gitstatusd a SIGHUP or SIGUSR so it releases its currently open files/directories could mitigate the situation if its too much effort to fix otherwise.

This sounds hacky and more difficult to implement than a proper solution.

I'm adding an option to release git repositories that haven't been used for N seconds. I'll set the default value to something like 1 hour. Will this work for you?

**Comment by aperum** [comment]
This should suffice for my work case. Thanks!

**Comment by romkatv** [comment]
This is done. Please update powerlevel10k. Once you do, gitstatusd will automatically close Git repositories for which the parent zsh hasn't requested Git status for 1 hour.

**Comment by aperum** [comment]
For faster testing i added --repo-ttl-seconds=300 to the daemon_args in gitstatus_plugin and this works for me, after 5 minutes the file handles are gone!

Thanks alot for the fast reaction and fix!

**Comment by romkatv** [comment]
Thanks for the verification and confirmation!
