### ISSUE TITLE
Request: Count individual files in untracked directory (--untracked-files)

### ISSUE THREAD

**Issue by dorian-marchal** [romkatv/gitstatus#53]
`git status` supports an `--untracked-files` option that can be used to list individual files in untracked directories.

Could a similar option be added to `romkatv/gitstatus` ?

Example :

```sh
mkdir /tmp/foobar

cd /tmp/foobar/

git init
# Initialized empty Git repository in /tmp/foobar/.git/

source ~/gitstatus/gitstatus.plugin.sh

gitstatus_start

mkdir foo

touch foo/bar

touch foo/baz

git status --untracked-files
# On branch master
# 
# No commits yet
# 
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
# 
# 	foo/bar
# 	foo/baz
# 
# nothing added to commit but untracked files present (use "git add" to track)

gitstatus_query

echo $VCS_STATUS_NUM_UNTRACKED
1 # ← Would be "2".
```

**Comment by romkatv** [comment]
Is it OK for you if this is implemented as a flag of `gitstatus_start` rather than a flag of `gitstatus_query`?

P.S.

You need to call `gitstatus_start -u -1` or it'll never report `VCS_STATUS_NUM_UNTRACKED` above `1`.

**Comment by romkatv** [comment]
By the way, gitstatus used to work just like you are asking. This really sucked because sometimes you run `make` in a directory, it creates a single `bin` subdirectory with a sprawling tree, and suddenly you have 1000000000 untracked files and Git prompt is slow to update. `git status` would just show `bin` as untracked.

**Comment by dorian-marchal** [comment]
> Is it OK for you if this is implemented as a flag of gitstatus_start rather than a flag of gitstatus_query?

It would be just fine :+1:

> By the way, gitstatus used to work just like you are asking. This really sucked because sometimes you run make in a directory, it creates a single bin subdirectory with a sprawling tree, and suddenly you have 1000000000 untracked files

This is not a problem for me, I always add these files to `.gitignore`.

> You need to call gitstatus_start -u -1 or it'll never report VCS_STATUS_NUM_UNTRACKED above 1.

Thanks, I forgot to add this flag in my example.

**Comment by romkatv** [comment]
> This is not a problem for me, I always add these files to `.gitignore`.

Me too! Unfortunately, sometimes I have to use code written by people other than myself. The problem I described isn't uncommon if you build code from git repos.

**Comment by romkatv** [comment]
This is done. Pass `-e` to `gitstatus_start` to count untracked files in untracked directories the same way as `git status --untracked-files`.

**Comment by EBoisseauSierra** [comment]
@romkatv Could you please detail how to enable this option in a `.p10k.zsh` config file?

**Comment by romkatv** [comment]
> @romkatv Could you please detail how to enable this option in a `.p10k.zsh` config file?

@EBoisseauSierra 

Define this:

```zsh
typeset -g POWERLEVEL9K_VCS_RECURSE_UNTRACKED_DIRS=true
```

I just added this parameter so you'll need to update powerlevel10k to the latest version for it to work.
