### ISSUE TITLE
Arm v5 support

### ISSUE THREAD

**Issue by eloo** [romkatv/gitstatus#55]
Hi,
is it maybe possible to support older ARMs too?
Like armv5tel?

Would be great so we can use powerlevel10k also on NAS systems ;)

Thanks

**Comment by romkatv** [comment]
I don't provide compiled binaries for the long tail of architectures but it's not too difficult to compile gitstatusd yourself. Install `gcc`, `make` and `cmake` and run this:

```
zsh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/gitstatus/master/build.zsh)"
```

It works find on armv7, so there is a good chance it'll just work on v5 too. I've even compiled it on a phone with no problems.
