### ISSUE TITLE
Is there any way to reuse `gitstatusd` like ssh-agent?

### ISSUE THREAD

**Issue by number5** [romkatv/gitstatus#56]
When you have many terminal windows opened, there are too many `gitstatusd` processes
```
λ pgrep gitstatusd
2204
2844
2994
14099
21102
29556
31407
39205
41703
42366
52679
74793
```

**Comment by romkatv** [comment]
> Is there any way to reuse `gitstatusd` like ssh-agent?

Not out of the box, no.

> When you have many terminal windows opened, there are too many `gitstatusd` processes

Too many in what sense? Apart from the multi-line output from `pgrep gitstatusd`, does the existence of multiple `gitstatusd` processes cause problems for you?

**Comment by romkatv** [comment]
Closing for the lack of information. Please reopen if having multiple `gitstatusd` processes causes problems for you.
