### ISSUE TITLE
Windows native port

### ISSUE THREAD

**Issue by ksawerykarwacki** [romkatv/gitstatus#57]
Are there any plans to port this to native windows code or is there any way to run this within powershell(powershell core would be also cool) as currently there's only git-posh which is super slow. 

I know there's wsl and magic stuff but sometimes we're stuck with windows tools and have to work somehow ;)

**Comment by romkatv** [comment]
I've no plans for providing native Windows port.

Note that you can freely run the Linux binary as long as you have WSL installed. You can run it from Powershell, or even form cmd.exe. All you need to do is to prefix the path to the binary with `wsl.exe`.

![image](https://user-images.githubusercontent.com/1282067/63352040-a3915c00-c360-11e9-9659-b6d6a3f7670a.png)

Here I'm starting gitstatusd, sending it a Git status request for my current directory, and displaying the result. Normally the same instance of gitstatusd is used for many requests but here I'm sending just one and shutting the daemon down.

There are no Powershell bindings, so someone would have to implement them. Bindings are responsible for launching gitstatusd, and for sending it requests and parsing responses. Powershell bindings will have to be implemented whether there is a native gitstatusd binary or not.
