### ISSUE TITLE
Evaluate the feasibility of mingw port

### ISSUE THREAD

**Issue by pnuzhdin** [romkatv/gitstatus#58]
```
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:

    GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K
 ~ ❯ GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /tmp/gitstatus.4176.xtrace.8VbPwLfBYz (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:11> local os
    +gitstatus_start_impl:11> os=+gitstatus_start_impl:11> uname -s
    +gitstatus_start_impl:11> os=MINGW64_NT-10.0-18362
    +gitstatus_start_impl:11> [[ -n MINGW64_NT-10.0-18362 ]]
    +gitstatus_start_impl:12> [[ MINGW64_NT-10.0-18362 != Linux ]]
    +gitstatus_start_impl:13> local arch
    +gitstatus_start_impl:13> arch=+gitstatus_start_impl:13> uname -m
    +gitstatus_start_impl:13> arch=x86_64
    +gitstatus_start_impl:13> [[ -n x86_64 ]]
    +gitstatus_start_impl:15> local daemon=/c/Users/pnzhd/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-mingw64_nt-10.0-18362-x86_64
    +gitstatus_start_impl:16> [[ -f /c/Users/pnzhd/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-mingw64_nt-10.0-18362-x86_64 ]]
                               ^ this command failed

  Your system information:

    zsh:      5.7.1
    uname -a: MINGW64_NT-10.0-18362 blackportable 3.0.7-338.x86_64 2019-07-11 10:58 UTC x86_64 Msys
```

**Comment by romkatv** [comment]
What environment is this? How do you start your terminal and zsh?

**Comment by pnuzhdin** [comment]
windows 10 + msys2 + conemu with the following task:
CHERE_INVOKING=1 & set MSYSTEM=MINGW64 & set MSYS2_PATH_TYPE=inherit & set “PATH=%ConEmuDrive%\msys64\mingw64\bin;%ConEmuDrive%\msys64\usr\bin;%PATH%” & cmd /c ""zsh" --login -i"

**Comment by romkatv** [comment]
Thanks. I'll see if it's feasible to port gitstatus to this platform without too much effort. Might take a few days.

FYI: gitstatus works on Cygwin (64 bit) and WSL. I have little motivation to port it to other Linux emulation environments given that it's only a matter of time before everyone switches to WSL.

**Comment by iamsureshraju** [comment]
Do we have any solution or workaround yet.

**Comment by romkatv** [comment]
> Do we have any solution or workaround yet.

There is no gitstatusd binary for mingw. A workaround is to either not use gitstatus, or switch to WSL.

I haven't looked into this issue and unlikely will at time soon. If anyone wants to try building gitstatus for mingw, please go ahead. Once you manage to build it, the next step is to verify that bindings work. The only problem that you should expect to face at this point is with fifos. Cygwin has somewhat broken fifos, which required a workaround in bash and zsh bindings for gitstatusd, and mingw might also have something of the sort.

**Comment by dm19** [comment]
WSL isn't an option for people without Admin privileges (and our company doesn't even use a recent enough Windows build for WSL), but msys/mingw can be installed by unprivileged users, so I don't think WSL will be a complete replacement.

**Comment by romkatv** [comment]
@dm19 If you would like gitstatus to work on mingw, maybe you could try building it and seeing if it works? Unless someone does the work, it won't get done.

**Comment by romkatv** [comment]
I went ahead and built gitstatusd for msys. If you update gitstatus/powerlevel10k to the latest version, it'll just work.

**Comment by iamsureshraju** [comment]
Could you please explain how can I generate gitstatusd, because I still face issue even after pulling the latest commit.
+gitstatus_start_impl:15> [[ -x '/c/Users/Owner/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-mingw64 _nt-10.0-17763-x86_64' ]]
                               ^ this command failed

If I tried to copy from the msys file then I am facing the below error. Please advise.
powerlevel10k/gitstatus/bin/gitstatusd-mingw64 _nt-10.0-17763-x86_64: error while loading shared libraries: cygwin1.dll: cannot open shared object file: No such file or directory

**Comment by romkatv** [comment]
> Could you please explain how can I generate gitstatusd, because I still face issue even after pulling the latest commit.
> +gitstatus_start_impl:15> [[ -x '/c/Users/Owner/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-mingw64 _nt-10.0-17763-x86_64' ]]
> ^ this command failed

Apparently you have a different mingw64 from mine. Mine doesn't include Windows version number (17763 in your case) in the output of `uname`. I've modified gitstatus to strip this number off.

> If I tried to copy from the msys file then I am facing the below error. Please advise.
> powerlevel10k/gitstatus/bin/gitstatusd-mingw64 _nt-10.0-17763-x86_64: error while loading shared libraries: cygwin1.dll: cannot open shared object file: No such file or directory

Bizarre. The msys binary doesn't have a dependency on cygwin1.dll. Is it possible that you've copied the wrong file?

Could you revert your changes, update powerlevel10k and try again? If it doesn't work, please tell me how you've installed the environment from which you are trying to use powerlevel10k.

**Comment by lamuertepeluda** [comment]
Hi there,

I have the latest version of msys2 on the following Windows Version

```
uname
MINGW64_NT-10.0-18362
```


tried to compile gitstatus since powerleve10k gives this error

```
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:

    GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 -a POWERLEVEL9K
```

Running that command does not produce any output so I tried to compile gitstatus

```
pacman -S mingw-w64-x86_64-cmake
```

then

```
zsh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/gitstatus/master/build.zsh)"
```

it stops like this:

```
make: *** No targets specified and no makefile found. Stop.
```

this is the folder content

```
 ls  C:/msys64/tmp/gitstatus/libgit2/build
ALL_BUILD.vcxproj          cmake_install.cmake  CMakeFiles  INSTALL.vcxproj          libgit2.pc   src                 ZERO_CHECK.vcxproj.filters
ALL_BUILD.vcxproj.filters  CMakeCache.txt       deps        INSTALL.vcxproj.filters  libgit2.sln  ZERO_CHECK.vcxproj
```

Any clues? Would it be possible to use `git status` instead of `gitstatus` as fallback, even though performances would be a bit worse (from what I understood)?

**Comment by romkatv** [comment]
@lamuertepeluda  

Please update powerlevl10k to the latest version, add `GITSTATUS_LOG_LEVEL=DEBUG` to your `~/.zshrc` and restart zsh twice. Post the full error message here along with the output of `typeset -m 'POWERLEVEL9K_*|ZSH_VERSION|GITSTATUS_*'`.

**Comment by lamuertepeluda** [comment]
```
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:

    GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 -a POWERLEVEL9K
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /tmp/gitstatus.3824.xtrace.1573642181.0573935509.20954 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local daemon=/c/Users/VitoMacchia/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-mingw64_nt-10.0-18362-x86_64 os
    +gitstatus_start_impl:8> [[ -n /c/Users/VitoMacchia/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-mingw64_nt-10.0-18362-x86_64 ]]
    +gitstatus_start_impl:15> [[ -x /c/Users/VitoMacchia/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-mingw64_nt-10.0-18362-x86_64 ]]
                               ^ this command failed

  Your system information:

    zsh:      5.7.1
    uname -a: MINGW64_NT-10.0-18362 LAPTOP-PU9T2150 3.0.7-338.x86_64 2019-07-11 10:58 UTC x86_64 Msys

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new
```
[typeset.txt](https://github.com/romkatv/gitstatus/files/3840704/typeset.txt)

@romkatv done. typeset output in the attached file

**Comment by romkatv** [comment]
Thanks for providing the debug info. I've changed the code to match the output of `uname -s` more aggressively on Windows as there seems to be great variety in output from mingw and msys. Please update powerlevel10k and restart zsh. If the error disappears, remove `GITSTATUS_LOG_LEVEL` from your config.

**Comment by lamuertepeluda** [comment]
great, it seems to work now! 😃

**Comment by romkatv** [comment]
> Would it be possible to use `git status` instead of `gitstatus` as fallback, even though performances would be a bit worse (from what I understood)?

That would be `POWERLEVEL9K_DISABLE_GITSTATUS=true`. I didn't want to answer this earlier because it's much better the bug that prevents `gitstatus` from working rather than disabling it.

**Comment by iamsureshraju** [comment]
Thank you. This update fixed my issue too and the prompt is pretty fast. 
I have only one issue pending. Could you please advise.

zsh: Can't add module parameter `aliases': parameter already exists
zsh: Can't add module parameter `aliases': parameter already exists
/c/Users/Owner/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh:5969: Can't add module parameter `aliases': parameter already exists
/c/Users/Owner/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh:zsh/parameter:5969: error when adding parameter `aliases'

**Comment by romkatv** [comment]
@iamsureshraju Googling that error message has just one hit: https://github.com/msys2/MSYS2-packages/issues/793. The error says that you have a global variables called `aliases`, which isn't possible for mortals to create (unless you are running into bugs in msys). I've tried to suppress this error message where I'm loading `zsh/parameter`. Please update powerlevel10k and try again.
