### ISSUE TITLE
.gitignore resolution is inconsistent with `git status`

### ISSUE THREAD

**Issue by dorian-marchal** [romkatv/gitstatus#59]
Under specific conditions, `gitstatusd` and `git status` do not resolve `.gitignore` the same way.

Here is an example: https://github.com/dorian-marchal/gitstatus-issue-59

```sh
cd /tmp
git clone https://github.com/dorian-marchal/gitstatus-issue-59
cd gitstatus-issue-59

mkdir foo
touch foo/bar
touch foo/baz

. ~/gitstatus/gitstatus.plugin.sh

gitstatus_start -e -d 99

gitstatus_query

git status # Reports a new foo/ dir.
git status --untracked-files # Reports two new foo/{bar,baz} files.

echo $VCS_STATUS_NUM_UNTRACKED # 0
echo $VCS_STATUS_HAS_UNTRACKED # 0
```

**Comment by dorian-marchal** [comment]
This is not an important issue for me, but I thought you should know.

I noticed it when I wanted to index a new dot file in my home repo, with this `.gitignore`:

```sh
# Ignore everything except some dot files.
*
!/.gitconfig
!/.gitignore
!/.bashrc
!/.psqlrc
!/.tmux.conf
!/.vimrc
!/.ssh/
!/.ssh/config # <- Here.
```

For now, I can simply disable `gitstatusd` when I'm working on this repo.

**Comment by romkatv** [comment]
Thanks for the bug report.

I'm using libgit2 to filter out ignored files. This part of libgit2 is riddled with bugs and is terribly inefficient. The amount of time I spent patching it could've been used to roll my own implementation from scratch several times over. Oh well. Maybe someday.

I've fixed the bug that was affecting your test case, and another one that I noticed during my own testing. I haven't released the new binaries though. You can either wait for the next release (not soon) or build gitstatusd yourself (it's fairly easy).

P.S.

You can simplify your dotfiles `.gitignore` and incidentally implement a workaround for the bug in gitstatusd. Put `*` in it and nothing else. To add new files, use `git add -f path/to/file`. I used to do this with my own dotfiles and it worked great. `.gitignore` is used only by `git add` and for filtering untracked files and for nothing else. So even with the blanket `*` in `.gitignore` you'll still see added/modified/deleted/etc files. I used to think that having ignored files in the index is somehow bad, but while implementing gitstatusd I learned that it isn't.

Another approach is to not have `.gitignore` in dotfiles at all and suppressed untracked files with `git config --local status.showUntrackedFiles no`. This is what I'm using right now with my own dotfiles. The advantage is that you don't need to pass `-f` to `git add` and that you can still display untracked files in some directory if you want to: `git status -u ~/.ssh`.

**Comment by dorian-marchal** [comment]
Thanks :+1:

> The amount of time I spent patching it could've been used to roll my own implementation from scratch several times over.

Out of curiosity, do you submit your patches upstream?

> P.S.

Thanks, that's good to know, your second approach seems great. :ok_hand:

**Comment by romkatv** [comment]
> Out of curiosity, do you submit your patches upstream?

Not anymore. My patches from several months ago are still stuck in limbo, so I don't consider it worth my or anyone else's time to send patches to libgit2.

**Comment by dorian-marchal** [comment]
That's sad. Too bad all maintainers aren't like you. :wink:

**Comment by romkatv** [comment]
For the sake of context, gitstatusd started as a simple binary that used libgit2 for everything Git-related. Over time I reimplemented all parts that have non-trivial contribution to latency, so that nowadays if you look at CPU profile of gitstatusd there is virtually no libgit2. This makes gitstatusd 40-something times faster than libgit2. Some things are still done via libgit2, and these are the worst parts of gitstatusd both in terms of performance and correctness. If I were starting over I would cut that dependency altogether. I also wouldn't commit compiled binaries to Git -- this stupid design decision constraints my ability to release new binaries, as they cause repository size bloat for all users.

**Comment by romkatv** [comment]
For the reference, I linked to my test cases and the bug fix on the existing libgit2 issue: https://github.com/libgit2/libgit2/issues/3535#issuecomment-527177583. If libgit2 devs or users find this useful, they can cherry pick.
