### ISSUE TITLE
[Question] Portable to use with Golang

### ISSUE THREAD

**Issue by sinetoami** [romkatv/gitstatus#60]
I want to use gitstatus to check some git info of repositories from anywhere. 

It's possible tu use gitstatus in a cli tool build with Golang? I guess so. But I actually don't know how to do that. How can I do that? 

Thanks!

**Comment by romkatv** [comment]
These two sections from the docs are relevant:

- https://github.com/romkatv/gitstatus/blob/master/README.md#how-it-works
- https://github.com/romkatv/gitstatus/blob/master/README.md#using-from-other-shells

However, you might have better luck using libgit2 instead. It has Go bindings.
