### ISSUE TITLE
Outputting zshoptions

### ISSUE THREAD

**Issue by Meroje** [romkatv/gitstatus#61]
Since https://github.com/romkatv/gitstatus/commit/4861c44d5e79a3e5e3693c0000830ce6b272d0b1 my shell has been printing options at initialization. It happens because I have no options to restore and setopt is called without arguments.

I patched it by testing the variable `[[ -n ${_gitstatus_opts[@]} ]] && setopt ${_gitstatus_opts[@]}`. I guess piping to dev/null would work too.

BTW I noticed powerlevel10k is doing something very similar so maybe someone could have the same issue there.

**Comment by romkatv** [comment]
Thanks for the report! Fixed.
