### ISSUE TITLE
Question: Multiple remotes

### ISSUE THREAD

**Issue by markusdd** [romkatv/gitstatus#63]
Hi,

I'm currently trying to incorporate the use of this great project into bash-it to get rid of the resource consuming separate git calls.
At one point there is a distinction if there are multiple remotes.

I do not see this case exposed by gitstatusd.

What is the current and expected behavior for this?

**Comment by maximbaz** [comment]
I believe it follows the remote that you configured for a branch using `git branch --set-upstream`, and you can only configure one upstream per branch, so there's no ambiguity.

**Comment by markusdd** [comment]
that makes sense
