### ISSUE TITLE
Powerlevel 10K issue after Mac OS Catalina upgrade.

### ISSUE THREAD

**Issue by pdhayes** [romkatv/gitstatus#67]
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /var/folders/wx/1ms5rdls36v7tdznsx_rj_xh0000gn/T//gitstatus.2619.xtrace.1570583994.2085020542.11846 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local daemon='' os
    +gitstatus_start_impl:8> [[ -n '' ]]
    +gitstatus_start_impl:9> os=+gitstatus_start_impl:9> uname -s
    +gitstatus_start_impl:9> os=Darwin
    +gitstatus_start_impl:9> [[ -n Darwin ]]
    +gitstatus_start_impl:10> [[ Darwin != Linux ]]
    +gitstatus_start_impl:11> local arch
    +gitstatus_start_impl:11> arch=+gitstatus_start_impl:11> uname -m
    +gitstatus_start_impl:11> arch=x86_64
    +gitstatus_start_impl:11> [[ -n x86_64 ]]
    +gitstatus_start_impl:12> local dir
    +gitstatus_start_impl:12> dir=.
    +gitstatus_start_impl:13> daemon=./bin/gitstatusd-darwin-x86_64
    +gitstatus_start_impl:15> [[ -x ./bin/gitstatusd-darwin-x86_64 ]]
                               ^ this command failed

  Your system information:

    zsh:      5.7.1
    uname -a: Darwin Paulss-MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64

**Comment by romkatv** [comment]
This looks the same as https://github.com/romkatv/gitstatus/issues/66. The solution is to update powerlevel10k to the latest version.

**Comment by pdhayes** [comment]
Worked for me. Thanks!
