### ISSUE TITLE
Idk how to fix this!!

### ISSUE THREAD

**Issue by ReDCeNTipeDe** [romkatv/gitstatus#70]
#70  will send you a picture,i want to know what is mean in picture and how can i fix it cause it annoy me pls help me.Thx 
---------------------this is problem--------------
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /data/data/com.termux/files/usr/tmp/gitstatus.22142.xtrace.1570957737.5955820084.13773 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local daemon='' os
    +gitstatus_start_impl:8> [[ -n '' ]]
    +gitstatus_start_impl:9> os=+gitstatus_start_impl:9> uname -s
    +gitstatus_start_impl:9> os=Linux
    +gitstatus_start_impl:9> [[ -n Linux ]]
    +gitstatus_start_impl:10> [[ Linux != Linux ||+gitstatus_start_impl:10> uname -o
    +gitstatus_start_impl:10> [[ Linux != Linux || Android != Android ]]
    +gitstatus_start_impl:10> os=Android
    +gitstatus_start_impl:11> local arch
    +gitstatus_start_impl:11> arch=+gitstatus_start_impl:11> uname -m
    +gitstatus_start_impl:11> arch=armv7l
    +gitstatus_start_impl:11> [[ -n armv7l ]]
    +gitstatus_start_impl:12> daemon=/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-armv7l
    +gitstatus_start_impl:14> [[ -x /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-armv7l ]]
                               ^ this command failed
![Screenshot_20191013_161457](https://user-images.githubusercontent.com/43487032/66713601-f6bee280-edd6-11e9-8028-1f2e10d3a295.png)

**Comment by romkatv** [comment]
You can drag-and-drop images into the edit box of this issue.

**Comment by ReDCeNTipeDe** [comment]
@

> You can drag-and-drop images into the edit box of this issue.
Oh i update issus ,look again pls

**Comment by romkatv** [comment]
There is no binary for your architecture.

What device is this?

What is the output of `uname -a`?

What happens if you type the following command?

```zsh
$ZSH_CUSTOM/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-aarch64
```

**Comment by ReDCeNTipeDe** [comment]
> There is no binary for your architecture.
> 
> What device is this?
> 
> What is the output of `uname -a`?
> 
> What happens if you type the following command?
> 
> ```shell
> $ZSH_CUSTOM/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-aarch64
> ```

I test by using Termux Sir.

**Comment by romkatv** [comment]
> I test by using Termux Sir.

This doesn't any of my questions.

**Comment by ReDCeNTipeDe** [comment]
> > I test by using Termux Sir.
> 
> This doesn't answer any of my questions.

Okok first i use Android .
Second idk too .
Last it say :zsh: no such file or directory: 
ZSH_CUSTOM/powerlevel10k/gitstatus/bin/gitstatusd-android-aarch64

**Comment by romkatv** [comment]
What kind of device are you using? Is it a phone? What is the model?

Please type this command and post its output:

```zsh
uname -a
```

Please type this command and post its output. Make sure to include the leading `$` in the command. It is a part of the command.

```zsh
$ZSH_CUSTOM/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-aarch64
```

**Comment by ReDCeNTipeDe** [comment]
> What kind of device are you using? Is it a phone? What is the model?
> 
> Please type this command and post its output:
> 
> ```shell
> uname -a
> ```
> 
> Please type this command and post its output. Make sure to include the leading `$` in the command. It is a part of the command.
> 
> ```shell
> $ZSH_CUSTOM/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-aarch64
> ```

This it sir
![Screenshot_20191013_164230](https://user-images.githubusercontent.com/43487032/66713720-81541180-edd8-11e9-8367-abe1a3be2cd5.png)

**Comment by romkatv** [comment]
Thank you. Could you answer the question about your device as well?

> What kind of device are you using? Is it a phone? What is the model?

Here's an example of the answer I'm looking for: "I'm using a tablet. The model is Xiaomi Mi Pad 4."

**Comment by ReDCeNTipeDe** [comment]
> Thank you. Could you answer the question about your device as well?
> 
> > What kind of device are you using? Is it a phone? What is the model?
> 
> Here's an example of the answer I'm looking for: "I'm using a tablet. The model is Xiaomi Mi Pad 4."

Oh i see ,sorry about that ,im not good english.
Im using a phone.The model is Vivo Y53 or Vivo 1606 sir.

**Comment by romkatv** [comment]
Got it. I'll see if I can find a way to build gitstatus for Android ARMv7 (this is what you are using).

For now I recommend disabling gitstatus so that you don't got that error every time you start zsh. You can do it by typing this command:

```zsh
echo POWERLEVEL9K_DISABLE_GITSTATUS=true >>! ~/.zshrc
```

**Comment by ReDCeNTipeDe** [comment]
> Got it. I'll see if I can find a way to build gitstatus for Android ARMv7 (this is what you are using).
> 
> For now I recommend disabling gitstatus so that you don't got that error every time you start zsh. You can do it by typing this command:
> 
> ```shell
> echo POWERLEVEL9K_DISABLE_GITSTATUS=true >>! ~/.zshrc
> ```

Oh it work!!! Thx alot i love you ,but it not a ~/.zshrc work to me,but it work if it be .zshrc idk why, but it ok Hahaha

**Comment by romkatv** [comment]
Just to be clear, this doesn't fix the problem, it simply removes the error message. Since there is no gitstatusd for your phone, your prompt will be slow, especially in Git repositories. If you don't need Git status in your prompt or don't know what it is, you can disable it with the following command (it will make your prompt fast).

```zsh
echo POWERLEVEL9K_VCS_DISABLED=true
```

**Comment by ReDCeNTipeDe** [comment]
> Just to be clear, this doesn't fix the problem, it simply removes the error message. Since there is no gitstatusd for your phone, your prompt will be slow, especially in Git repositories. If you don't need Git status in your prompt or don't know what it is, you can disable it with the following command (it will make your prompt fast).
> 
> ```shell
> echo POWERLEVEL9K_VCS_DISABLED=true
> ```

oh thx sir

**Comment by romkatv** [comment]
Sorry, that command is missing a redirect at the end. It should have the same ending like the previous command you used.

**Comment by ReDCeNTipeDe** [comment]
> Sorry, that command is missing a redirect at the end. It should have the same ending like the previous command you used.

oh.It okay sir,im okay with it  cause it not a danger anymore.

**Comment by romkatv** [comment]
> I'll see if I can find a way to build gitstatus for Android ARMv7 (this is what you are using).

After Googling for some time it seems there is little value in porting gitstatusd to ARMv7 on Android. There are few such devices in the world and they are likely to disappear in a few years altogether.

Since you have two reasonable workarounds to choose from (`POWERLEVEL9K_VCS_DISABLED=true` and `POWERLEVEL9K_DISABLE_GITSTATUS=true`), I'm closing this issue.

**Comment by ReDCeNTipeDe** [comment]
> > I'll see if I can find a way to build gitstatus for Android ARMv7 (this is what you are using).
> 
> After Googling for some time it seems there is little value in porting gitstatusd to ARMv7 on Android. There are few such devices in the world and they are likely to disappear in a few years altogether.
> 
> Since you have two reasonable workarounds to choose from (`POWERLEVEL9K_VCS_DISABLED=true` and `POWERLEVEL9K_DISABLE_GITSTATUS=true`), I'm closing this issue.

Thx y so much, it helpful for me
