### ISSUE TITLE
use legacy git status instead of gitstatusd

### ISSUE THREAD

**Issue by paulprogrammer** [romkatv/gitstatus#75]
My corp laptop won't allow the use of gitstatusd, but I would still like to have the vcs extensions.  Is there a way to force the legacy powerlevel9k behavior instead of relying on getstatusd?

**Comment by romkatv** [comment]
You can do this:

```zsh
POWERLEVEL9K_DISABLE_GITSTATUS=true
```

It'll be terribly slow though. Not as slow as powerlevel9k but still unbearable.
