### ISSUE TITLE
VCS_STATUS_HAS_STAGED and VCS_STATUS_HAS_UNSTAGED not set after `git add .`

### ISSUE THREAD

**Issue by bluz71** [romkatv/gitstatus#76]
Hello again,

There seems to be an issue with `gitstatus` after commit `0b4f14b`.
Just updated today and `git add .` is causing issues.

Steps:

- Download and use my [seafly](https://github.com/bluz71/bash-seafly-prompt) Bash theme
- Install the latest `gitstatus`
- Check out any repository, say **seafly** above
- Make any old quick change to `command_prompt.bash`
- Do `git add .`
- Notice the prompt now has no Git details, this will be `VCS_STATUS_HAS_STAGED` and `VCS_STATUS_HAS_UNSTAGED` will not be set (for the moment)
- Hit `Enter`, now all is good again
- Do `~/.bashrc`, Git details disappear again

Commit `0b4f14b` was good.
Commit `fdae101` seems to be the bad one.

Best regards.

**Comment by romkatv** [comment]
Thanks for the report!

libgit2 has introduced a bug in https://github.com/libgit2/libgit2/commit/8a23597b73f4ea83d87ee22bf62c36aadb97e095 which I've picked up when merging upstream changes. I've fixed it my fork and sent https://github.com/libgit2/libgit2/pull/5295 upstream. Please update gitstatus and try again.

**Comment by bluz71** [comment]
Indeed, now fixed. 

Many thanks, I appreciate it.
