### ISSUE TITLE
Support for vcsh ($GIT_DIR + worktree) broken?

### ISSUE THREAD

**Issue by cdlm** [romkatv/gitstatus#78]
It looks like gitstatus's support of subshells launched by [vcsh](https://github.com/RichiH/vcsh) was recently broken.

I'm using zprezto and powerlevel10k; the git prompt segment shows as expected inside normal git clones, but when I `vcsh enter foo`, nothing appears in the prompt even if `git status` shows changes. If I then kill `gitstatusd`, it seems like p10k falls back to slower code which correctly follows `$GIT_DIR` and the prompt segment appears…

I'm pretty sure I've seen the prompt work for vcsh subshells after gitstatus was integrated in p10k… Today after an update of zprezto/powerlevel10k I remarked it didn't show up anymore.

**Comment by romkatv** [comment]
Thanks for the report!

Apparently I've broken bug parity. Fixed one bug and this has caused another bug to show its ugly face.

I've fixed it in https://github.com/romkatv/gitstatus/tree/gitdir. Could you verify that it fixes your problem?

1. `git clone --depth=1 -b gitdir https://github.com/romkatv/gitstatus.git ~/gitstatus-gitdir`
2. Add `POWERLEVEL9K_GITSTATUS_DIR=~/gitstatus-gitdir` at the bottom of `~/.zshrc`.

If you can confirm that it works, I'll push the fix to gitstatus/master and to powerlevel10k.

**Comment by cdlm** [comment]
It works! 👍

**Comment by romkatv** [comment]
Thanks for the confirmation.

I've pushed the fix to gitstatus and powerlevel10k master branches. Powerlevel10k from prezto will be fixed on https://github.com/sorin-ionescu/prezto/pull/1761 is merged.

**Comment by romkatv** [comment]
Once again, thanks for the bug report :hugs:

**Comment by romkatv** [comment]
> Powerlevel10k from prezto will be fixed on [sorin-ionescu/prezto#1761](https://github.com/sorin-ionescu/prezto/pull/1761) is merged.

The PR has been merged.
