### ISSUE TITLE
Not showing the current tag

### ISSUE THREAD

**Issue by heruan** [romkatv/gitstatus#79]
Hello! Is tag of the current commit hash supposed to be shown on the prompt? This is my `git log`:

```
commit fdef48718e204dcd65b4586b98174eaa54fa9ec1 (HEAD -> master, tag: 2.1.1, origin/release/2.1.1, origin/master, release/2.1.1)
Author: Giovanni Lovato <giovanni.lovato@axians.it>
Date:   Tue Nov 12 16:37:55 2019 +0100

    Bump version to 2.1.1

...
```

So I would expect to see `2.1.1` somewhere in the prompt, but there's none:

<img width="473" alt="Screenshot 2019-11-12 at 16 44 32" src="https://user-images.githubusercontent.com/851745/68686307-bab0a600-056b-11ea-9241-928cad409c4c.png">

**Comment by romkatv** [comment]
(I'm assuming you are using powerlevel10k rather than calling gitstatus directly.)

This is working as expected. Formatting is controlled by your config (usually `~/.p10k.zsh`). You can customize it there.

https://github.com/romkatv/powerlevel10k/blob/d93f3960baaa8676fc9e475d21438116f82cfe1f/config/p10k-classic.zsh#L329-L337

Specifically this part:

https://github.com/romkatv/powerlevel10k/blob/d93f3960baaa8676fc9e475d21438116f82cfe1f/config/p10k-classic.zsh#L363-L379

The same thing in pseudo code:

```
if (on a branch) {
  show branch
} else if (there is at least one tag that resolves to HEAD) {
  show the lexicographically greatest tag
} else {
  show HEAD
}
```

If you type `git checkout 2.1.1`, you'll see `#2.2.1` instead of `master`. And `git checkout HEAD~1` will show something like `@12345678` (assuming you don't have a tag pointing to this commit).

If you want to display both a branch and a tag in your situation, here's one way to do it:

```zsh
local res
if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
  res+="${clean}${POWERLEVEL9K_VCS_BRANCH_ICON}${(V)VCS_STATUS_LOCAL_BRANCH//\%/%%}"
fi
if [[ -n $VCS_STATUS_TAG ]]; then
  res+="${meta}#${clean}${(V)VCS_STATUS_TAG//\%//%%}"
fi
if [[ -z $res ]]; then
  res+="${meta}@${clean}${VCS_STATUS_COMMIT[1,8]}"
fi
```

**Comment by heruan** [comment]
Thank you @romkatv! I was used to P9K with the `git` plugin which showed both branch and tag. Currently, I have this in my `.p10k.zsh` (auto-generated):

```sh
    local res
    local where  # branch name, tag or commit
    if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
      res+="${clean}${POWERLEVEL9K_VCS_BRANCH_ICON}"
      where=${(V)VCS_STATUS_LOCAL_BRANCH}
    elif [[ -n $VCS_STATUS_TAG ]]; then
      res+="${meta}#"
      where=${(V)VCS_STATUS_TAG}
    else
      res+="${meta}@"
      where=${VCS_STATUS_COMMIT[1,8]}
    fi
```

I guess I need a new `if` to handle when both `VCS_STATUS_LOCAL_BRANCH` and `VCS_STATUS_TAG` are defined?

**Comment by romkatv** [comment]
> I guess I need a new `if` to handle when both `VCS_STATUS_LOCAL_BRANCH` and `VCS_STATUS_TAG` are defined?

Please read my previous reply in full. It contains an answer to your question.

**Comment by ziurjam** [comment]
My code looks like though:
`
    local res
    local where  # branch or tag
    if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
      res+="${clean}${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}"
      where=${(V)VCS_STATUS_LOCAL_BRANCH}
    fi
    if [[ -n $VCS_STATUS_TAG ]]; then
      #res+="${meta}#"
      where+="#${(V)VCS_STATUS_TAG}"
    fi
`

**Comment by romkatv** [comment]
@ziurjam OK. For the benefit of future readers, I'll point out that this code is broken and shouldn't be copied. See my comment above (https://github.com/romkatv/gitstatus/issues/79#issuecomment-553309034) for correct code.

**Comment by ziurjam** [comment]
@romkatv OK. 
Btw... my .p10k.zsh contains the following block. Do I need to remove as well, since you are no longer using "where" var?
```bash
 393     # Display the current Git commit if there is no branch or tag.
 394     # Tip: To always display the current Git commit, remove `[[ -z $where ]] &&` from the next line.
 395     [[ -z $where ]] && res+="${meta}@${clean}${VCS_STATUS_COMMIT[1,8]}"
```

**Comment by romkatv** [comment]
@ziurjam I suggest that you use the code I posted above. That code already incorporates `VCS_STATUS_COMMIT`.
