### ISSUE TITLE
Support custom root directory

### ISSUE THREAD

**Issue by Seirdy** [romkatv/gitstatus#81]
Users who use [`yadm`](https://yadm.io/) to manage dotfiles make their `$HOME` a git repository and selectively add files. The root directory is `~/.yadm` instead of `~/.git`.

Currently, I symlink `~/.git` to `~/.yadm` so that I can have the `vcs` prompt element tell me about the status of my dotfile repo; however, this has unintentional side effects. For example, vim plugins and IDEs end up thinking `$HOME` is a project and end up monitoring my entire `$HOME` for changes, which is too expensive.

Allowing users to define a custom root pattern would alleviate this issue for anybody who manages dotfiles with a simple git directory and custom root pattern.

**Comment by romkatv** [comment]
gitstatus respects `GIT_DIR`, so if you set `GIT_DIR=~.yadm` while in home directory, you'll see Git status in prompt. For example, in zsh:

```zsh
function yadm-gitstatus() {
  emulate -L zsh
  if [[ ${(%):-%~} == '~' ]]; then
    GIT_DIR=~/.yadm
  else
    unset GIT_DIR
  fi
}

autoload -Uz add-zsh-hook
add-zsh-hook chpwd yadm-gitstatus
yadm-gitstatus
```

**Comment by Seirdy** [comment]
Thanks for this; fixed for me.

**Comment by romkatv** [comment]
Thanks for the confirmation.
