### ISSUE TITLE
Report added, deleted, renamed

### ISSUE THREAD

**Issue by BlueDrink9** [romkatv/gitstatus#82]
I often find I've accidentally added an untracked file I'd rather ignore, or found that I haven't staged the old renamed file so it appears as a new file instead. Having these reported in my bash prompt alerts me of this instantly.

Having switching to gitstatus, these are features I'm missing.
**If it is possible within the engine framework**, this info would be excellent to have reportable.

**Comment by romkatv** [comment]
There is a counter for the number of unstaged deleted files.

```bash
#   VCS_STATUS_NUM_UNSTAGED_DELETED The number of unstaged deleted files. Note that renamed files
#                                   are reported as deleted plus added.
```

I can add counters for unstaged added, staged deleted and staged added. Will this work for you?

As the comment above says, gitstatus doesn't detect moves/renames and instead treats them as a deletions and additions. Detecting moves/renames is non-trivial and I'd rather not implement it.

**Comment by BlueDrink9** [comment]
Those counters would be great. A shame about renames, but understandable. Thanks!

**Comment by romkatv** [comment]
I've added `VCS_STATUS_NUM_STAGED_NEW` and `VCS_STATUS_NUM_STAGED_DELETED` but haven't yet released the new version of gitstatus.

On which Operating System(s) are you using gitstatus? I'll prioritize the next release for them.

**Comment by BlueDrink9** [comment]
Awesome! Linux via Powerlevel10k (zsh theme)

**Comment by romkatv** [comment]
I've released `gitstatusd-linux-x86_64`.

To take advantage of the new counters, open `~/.p10k.zsh`, search for `my_git_formatter` and edit its source code. Use `VCS_STATUS_NUM_STAGED_NEW`, `VCS_STATUS_NUM_STAGED_DELETED` and `VCS_STATUS_NUM_UNSTAGED_DELETED` similarly to the other `VCS_STATUS_*` parameters that are already in use.

**Comment by wookayin** [comment]
`VCS_STATUS_NUM_STAGED_{NEW,DELETED}` works well but they really do not tell where a move/rename was made. For example,

```
$ git status --porcelain
D  deleted_file
R  old_name -> new_name
A  new_added_file
```

where `deleted_file` and `new_added_file` are substantially different so it is not regarded as renaming. In this situation gitstatus will report `VCS_STATUS_NUM_STAGED_NEW=2` and `VCS_STATUS_NUM_STAGED_DELETED=2` but actually the number of renamed is 1. 

Note that `git-info` from prezto implements `$git_info[renamed]` in this way through parsing of `git status`. I hope `renamed` could be added as a separate variable!

(A side note: this would be not necessary for UNSTAGED, though, but only for STAGED)

**Comment by romkatv** [comment]
@wookayin https://github.com/romkatv/gitstatus/issues/82#issuecomment-561576392

> ```shell
> #   VCS_STATUS_NUM_UNSTAGED_DELETED The number of unstaged deleted files. Note that renamed files
> #                                   are reported as deleted plus added.
> ```
> 
> As the comment above says, gitstatus doesn't detect moves/renames and instead treats them as a deletions and additions. Detecting moves/renames is non-trivial and I'd rather not implement it.

Detecting moves/renames is still non-trivial and I'd still rather not implement it.
