### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by h0bd0b1in** [romkatv/gitstatus#83]
This old guy has reared his head again.

OS: Mac OS X 10.11.6 El Capitan

[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.xtrace.1575710348.7891459465.11876 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local daemon='' os
    +gitstatus_start_impl:8> [[ -n '' ]]
    +gitstatus_start_impl:9> os=+gitstatus_start_impl:9> uname -s
    +gitstatus_start_impl:9> os=Darwin
    +gitstatus_start_impl:9> [[ -n Darwin ]]
    +gitstatus_start_impl:10> [[ Darwin != Linux ]]
    +gitstatus_start_impl:11> [[ darwin != (mingw|msys)* ]]
    +gitstatus_start_impl:12> local arch
    +gitstatus_start_impl:12> arch=+gitstatus_start_impl:12> uname -m
    +gitstatus_start_impl:12> arch=x86_64
    +gitstatus_start_impl:12> [[ -n x86_64 ]]
    +gitstatus_start_impl:13> daemon=/Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
    +gitstatus_start_impl:15> [[ -x /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 ]]
    +gitstatus_start_impl:17> lock_file=/var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.lock.1575710348.8082311153.19614
    +gitstatus_start_impl:18> echo -n
    +gitstatus_start_impl:19> zsystem flock -f lock_fd /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.lock.1575710348.8082311153.19614
    +gitstatus_start_impl:21> req_fifo=/var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.req.1575710348.8088519573.9852
    +gitstatus_start_impl:22> resp_fifo=/var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.resp.1575710348.8089029789.7184
    +gitstatus_start_impl:23> mkfifo /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.req.1575710348.8088519573.9852 /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.resp.1575710348.8089029789.7184
    +gitstatus_start_impl:25> local -i threads=0
    +gitstatus_start_impl:26> ((  threads > 0 ))
    +gitstatus_start_impl:27> threads=8
    +gitstatus_start_impl:28> [[ -n Darwin ]]
    +gitstatus_start_impl:29> case Darwin (FreeBSD)
    +gitstatus_start_impl:29> case Darwin (*)
    +gitstatus_start_impl:31> ((  ! 1  ))
    +gitstatus_start_impl:31> threads=+gitstatus_start_impl:31> getconf _NPROCESSORS_ONLN
    +gitstatus_start_impl:31> threads=4
    +gitstatus_start_impl:33> ((  threads <= 32  ))
    +gitstatus_start_impl:36> local -a daemon_args=( '--lock-fd=3' '--parent-pid=1080' '--num-threads=4' '--max-num-staged=1' '--max-num-unstaged=1' '--max-num-conflicted=1' '--max-num-untracked=1' '--dirty-max-index-size=-1' '--log-level=DEBUG' )
    +gitstatus_start_impl:48> local cmd=$'\n        exec >&4\n        echo $$\n        /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 --lock-fd=3 --parent-pid=1080 --num-threads=4 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=DEBUG\n        if [[ $? != (0|10) && $? -le 128 && -f /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static ]]; then\n          /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static --lock-fd=3 --parent-pid=1080 --num-threads=4 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=DEBUG\n        fi\n        echo -nE $\'bye\\x1f0\\x1e\''
    +gitstatus_start_impl:56> local setsid=/usr/local/opt/util-linux/bin/setsid
    +gitstatus_start_impl:57> [[ -x /usr/local/opt/util-linux/bin/setsid ]]
    +gitstatus_start_impl:57> setsid=''
    +gitstatus_start_impl:62> local zsh=/proc/self/exe
    +gitstatus_start_impl:63> [[ -x /proc/self/exe ]]
    +gitstatus_start_impl:63> zsh=zsh
    +gitstatus_start_impl:64> cmd='cd /; read;  zsh -dfxc $'\''\n'\''\ \ \ \ \ \ \ \ exec\ \>\&4$'\''\n'\''\ \ \ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ \ \ /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64\ --lock-fd=3\ --parent-pid=1080\ --num-threads=4\ --max-num-staged=1\ --max-num-unstaged=1\ --max-num-conflicted=1\ --max-num-untracked=1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ if\ \[\[\ \$\?\ \!=\ \(0\|10\)\ \&\&\ \$\?\ -le\ 128\ \&\&\ -f\ /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static\ \]\]\;\ then$'\''\n'\''\ \ \ \ \ \ \ \ \ \ /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static\ --lock-fd=3\ --parent-pid=1080\ --num-threads=4\ --max-num-staged=1\ --max-num-unstaged=1\ --max-num-conflicted=1\ --max-num-untracked=1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ fi$'\''\n'\''\ \ \ \ \ \ \ \ echo\ -nE\ \$\'\''bye\\x1f0\\x1e\'\'' &!; rm -f /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.req.1575710348.8088519573.9852 /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.resp.1575710348.8089029789.7184 /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.lock.1575710348.8082311153.19614'
    +gitstatus_start_impl:70> sysopen -w -o cloexec,sync -u req_fd /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.req.1575710348.8088519573.9852
    +gitstatus_start_impl:71> sysopen -r -o cloexec -u resp_fd /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.resp.1575710348.8089029789.7184
    +gitstatus_start_impl:68> zsh -dfmxc 'cd /; read;  zsh -dfxc $'\''\n'\''\ \ \ \ \ \ \ \ exec\ \>\&4$'\''\n'\''\ \ \ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ \ \ /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64\ --lock-fd=3\ --parent-pid=1080\ --num-threads=4\ --max-num-staged=1\ --max-num-unstaged=1\ --max-num-conflicted=1\ --max-num-untracked=1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ if\ \[\[\ \$\?\ \!=\ \(0\|10\)\ \&\&\ \$\?\ -le\ 128\ \&\&\ -f\ /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static\ \]\]\;\ then$'\''\n'\''\ \ \ \ \ \ \ \ \ \ /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static\ --lock-fd=3\ --parent-pid=1080\ --num-threads=4\ --max-num-staged=1\ --max-num-unstaged=1\ --max-num-conflicted=1\ --max-num-untracked=1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ fi$'\''\n'\''\ \ \ \ \ \ \ \ echo\ -nE\ \$\'\''bye\\x1f0\\x1e\'\'' &!; rm -f /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.req.1575710348.8088519573.9852 /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.resp.1575710348.8089029789.7184 /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.lock.1575710348.8082311153.19614'
    +gitstatus_start_impl:72> echo -nE $'0\nhello\C-_\C-^'
    +gitstatus_start_impl:75> ((  async  ))
    +gitstatus_start_impl:78> local reply IFS=''
    +gitstatus_start_impl:79> read -ru 15 reply
    +gitstatus_start_impl:80> [[ 1195 == <1-> ]]
    +gitstatus_start_impl:81> daemon_pid=reply
    +gitstatus_start_impl:92> zle -F 15 _gitstatus_process_response_POWERLEVEL9K
    +gitstatus_start_impl:94> read -r -d $'\C-^' -u 15 -t 5.0000000000 reply
    +gitstatus_start_impl:95> [[ $'bye\C-_0' == hello0 ]]
                               ^ this command failed

  The content of /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.daemon-log.1575710348.7891271114.23390 (gitstatus daemon log):

    +zsh:1> cd /
    +zsh:1> read
    +zsh:1> rm -f /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.req.1575710348.8088519573.9852 /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.resp.1575710348.8089029789.7184 /var/folders/y5/dxhrsgpn47l9n3jk_9ks5f3w0000gn/T//gitstatus.1080.lock.1575710348.8082311153.19614
    +zsh:1> zsh -dfxc $'\n        exec >&4\n        echo $$\n        /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 --lock-fd=3 --parent-pid=1080 --num-threads=4 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=DEBUG\n        if [[ $? != (0|10) && $? -le 128 && -f /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static ]]; then\n          /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static --lock-fd=3 --parent-pid=1080 --num-threads=4 --max-num-staged=1 --max-num-unstaged=1 --max-num-conflicted=1 --max-num-untracked=1 --dirty-max-index-size=-1 --log-level=DEBUG\n        fi\n        echo -nE $\'bye\\x1f0\\x1e\''
    +zsh:3> echo 1195
    +zsh:4> /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 '--lock-fd=3' '--parent-pid=1080' '--num-threads=4' '--max-num-staged=1' '--max-num-unstaged=1' '--max-num-conflicted=1' '--max-num-untracked=1' '--dirty-max-index-size=-1' '--log-level=DEBUG'
    dyld: Symbol not found: __ZdlPvm
      Referenced from: /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 (which was built for Mac OS X 10.13)
      Expected in: /usr/lib/libc++.1.dylib
     in /Users/h0bd0b1in/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
    +zsh:5> [[ 133 != (0|10) && 133 -le 128 ]]
    +zsh:8> echo -nE $'bye\C-_0\C-^'

  Your system information:

    zsh:      5.7.1
    uname -a: Darwin hylonome.ixni.ne 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64

I'm guessing based on this that 10.13 is the minimum supported version (which makes sense since Apple only supports their last three OSes themselves)? I can try build it myself on this machine if that will work?

**Comment by romkatv** [comment]
> I'm guessing based on this that 10.13 is the minimum supported version (which makes sense since Apple only supports their last three OSes themselves)?

Correct.

> I can try build it myself on this machine if that will work?

Yes, that should work. Please open another issues if you run into issues building gitstatusd.
