### ISSUE TITLE
Rebase: Show current and total number of commit

### ISSUE THREAD

**Issue by windtaenzer** [romkatv/gitstatus#87]
Would it be possible to add the number of the current commit and the total number to gitstatus?  With this it would be possible to display somthing like this `@abcdef12 rebase 2/15 ✖1 ●1` in the VCS segment of the promt.
I know this feature from https://github.com/magicmonty/bash-git-prompt, which I used before I switched to zsh and P10k and I would be really happy to see support for this in gitstatus. The corresponding code in bash-git-prompt is https://github.com/magicmonty/bash-git-prompt/blob/master/gitstatus.sh#L57, maybe this helps to get this numbers.

**Comment by romkatv** [comment]
> Would it be possible to add the number of the current commit?

It is possible. See [VCS_STATUS_COMMIT](https://github.com/romkatv/gitstatus/blob/4a075f4b6148f38440b7efcf9642c3f6c7cd3ec2/gitstatus.plugin.sh#L231).

> ... and the total number to gitstatus?

What's that?

**Comment by romkatv** [comment]
If you want Git status in your Powerlevel10k prompt to always show the current commit, run `p10k configure` to generate `~/.p10k.zsh`. Then open `~/.p10k.zsh` and search for this piece:

```zsh
# Display the current Git commit if there is no branch or tag.
# Tip: To always display the current Git commit, remove `[[ -z $where ]] &&` from the next line.
[[ -z $where ]] && res+="${meta}@${clean}${VCS_STATUS_COMMIT[1,8]}"
```

Heed the tip.

**Comment by romkatv** [comment]
> > ... and the total number to gitstatus?
> 
> What's that?

Do you mean these two values from [bash-git-prompt](https://github.com/magicmonty/bash-git-prompt/blob/master/gitstatus.sh#L57)?

```bash
__git_prompt_read "${git_dir}/rebase-merge/msgnum" step
__git_prompt_read "${git_dir}/rebase-merge/end" total
```

**Comment by windtaenzer** [comment]
Yes, that are the numbers I meant. Looks that my description was a bit unclear. I want to see how much commits getting rebased and on which commit I currently am (the number, not the commit id).

**Comment by romkatv** [comment]
Got it. This shouldn't be difficult to add but it'll require a new release of gitstatusd.

Which operating system(s) do you want to use this on?

**Comment by windtaenzer** [comment]
I'll use it on Mac OS 10.14 and 10.15.

**Comment by romkatv** [comment]
This is done. Will publish new gistatusd binaries in a few days.

**Comment by romkatv** [comment]
> Will publish new gistatusd binaries in a few days.

And done.
