### ISSUE TITLE
Show delta from @{push} as well as @{upstream}

### ISSUE THREAD

**Issue by gibfahn** [romkatv/gitstatus#89]
I just started looking at Powerlevel10k and it looks great, there's just one thing I'd lose by moving to `gitstatus`, which is being able to know the delta between the current branch and the `@{push}` branch as well as the `@{upstream}` delta which is currently shown. 

I went into a bit more detail about how I use `@{push}` [here](https://fahn.co/posts/a-better-pull-request-workflow-with-git-push-branches.html), and the commands I use in my current prompt [here](https://stackoverflow.com/a/59417578/2799191).

Does this seem like something that might be doable? I can see it might not be desirable to always check this, as `@{push}` is relatively new in Git, and most people aren't yet aware of it. However I think once you discover it you start to wonder how you ever did without it.

**Comment by gibfahn** [comment]
This is how I am currently working around it, which is obviously not hugely fast, but works:

```sh
local -a push_behind_ahead=(${(ps:\t:)"$(command git rev-list --left-right --count HEAD...@{push} 2>/dev/null)"})
local VCS_STATUS_PUSH_COMMITS_AHEAD="${push_behind_ahead[1]}"
local VCS_STATUS_PUSH_COMMITS_BEHIND="${push_behind_ahead[2]}"
```

**Comment by romkatv** [comment]
I've implemented this but haven't yet pushed a new release. Please try it and let me know whether it works for you.

You can either build gitstatusd from master yourself or tell me which OS you are using and I'll build a beta binary for you. Once you can confirm that this feature works as you expect, I'll rebuild all gitstatusd binaries.

**Comment by romkatv** [comment]
> Once you can confirm that this feature works as you expect, I'll rebuild all gitstatusd binaries.

Timed out waiting and released new gitstatusd binaries. Closing as done.

**Comment by gibfahn** [comment]
https://github.com/romkatv/gitstatus/commit/11198dfe3b07388df0c85afc2c09bed5adb7f3f8 works perfectly, thanks!
