### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by theskinnyghost** [romkatv/gitstatus#90]
Hello,
I'm having an issue when opening iterm2 on my mac. It just happend overnight, yesterday it worked just fine.

```
[ERROR]: gitstatus failed to initialize.
Your git prompt may disappear or become slow.
Run the following command to retry with extra diagnostics:

GITSTATUS_LOG_LEVEL=DEBUG GITSTATUS_NUM_THREADS=24 GITSTATUS_DAEMON=/Users/lucaricci/Dropbox/Mackup/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K

If this command produces no output, add the following parameter to ~/.zshrc:

GITSTATUS_LOG_LEVEL=DEBUG

With this parameter, gitstatus will print additional information on error.
```

I've then ran the command suggested and this is the output

```
[ERROR]: gitstatus failed to initialize.

Your git prompt may disappear or become slow.

The content of /var/folders/sb/bwm_yx6d2vg434lffkhml17h0000gn/T//gitstatus.686.xtrace.1578472195.9602088928.3204 (gitstatus_start_impl xtrace):

+gitstatus_start_impl:6> ((  daemon_pid == -1  ))
+gitstatus_start_impl:7> local daemon=/Users/lucaricci/Dropbox/Mackup/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 os
+gitstatus_start_impl:8> [[ -n /Users/lucaricci/Dropbox/Mackup/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 ]]
+gitstatus_start_impl:15> [[ -x /Users/lucaricci/Dropbox/Mackup/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 ]]
^ this command failed

Your system information:

zsh:      5.7.1
uname -a: Darwin MacBook-Pro.fritz.box 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

If you need help, open an issue and attach this whole error message to it:

https://github.com/romkatv/gitstatus/issues/new
```

Let me know if you need further info.
Look forward to hearing from you.
Thank you,
Luca

**Comment by romkatv** [comment]
The error says that the following file either doesn't exist or isn't executable:

```zsh
/Users/lucaricci/Dropbox/Mackup/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
```

Try executing it manually to see what the problem is. If the file has disappeared or got corrupted, remove the powerlevel10k directory and `git clone` it again.

**Comment by theskinnyghost** [comment]
Hi @romkatv, I removed it and `git clone`d it again and it works fine now. 🎉 Thank you very much for your help. 🙇‍♂️

**Comment by romkatv** [comment]
Great! Thanks for the confirmation.

**Comment by skalinets** [comment]
instead of removing / cloning again you could just `git fetch; git reset origin/master --hard`

**Comment by romkatv** [comment]
> instead of removing / cloning again you could just `git fetch; git reset origin/master --hard`

Only if `.git` hasn't been corrupted as well.

**Comment by benwizen** [comment]
Updating powerlevel10k worked for me.
Please refer to https://github.com/romkatv/powerlevel10k#how-do-i-update-powerlevel10k

**Comment by LOGANLEEE** [comment]
> Updating powerlevel10k worked for me. Please refer to https://github.com/romkatv/powerlevel10k#how-do-i-update-powerlevel10k

worked for me. 2021 map M1 Pro migrated from intel map 16
