### ISSUE TITLE
Feature Request: Transient Prompt only when last command has finished

### ISSUE THREAD

**Issue by jasonkena** [romkatv/gitstatus#91]
Losing the current directory or Python environment in the prompt makes it difficult to formulate the next command.

Please help

**Comment by romkatv** [comment]
> Transient Prompt only when last command has finished

I'm afraid this impossible to implement. The moment a command starts executing, it gets full control over the content of the terminal. When the command finishes, there is no way to find the previous prompt. It may have disappeared above the terminal view port, was erased, moved or even changed by the completed command.

If you need to refer to the information in the past prompts, do not enable transient prompt.

**Comment by jasonkena** [comment]
Ok, thanks for your help
