### ISSUE TITLE
Request: check for skip-worktree and assume-unchanged bits

### ISSUE THREAD

**Issue by olets** [romkatv/gitstatus#97]
I'm experimenting with porting my existing Git prompt over to use GitStatus. Wonderful how much faster it is!

Two things in my prompt that I'm not able to use GitStatus for are showing whether any files have the `--skip-worktree` bit set and whether any files have the `--assume-unchanged` bit set.

A basic, unoptimized demo

```shell
git ls-files -v $(git rev-parse --show-toplevel) | grep '^[sS]' 1>/dev/null && echo 'there is a file with the --skip-worktree bit set'
git ls-files -v $(git rev-parse --show-toplevel) | grep '^[[:lower:]]' 1>/dev/null && echo 'there is a file with the --assume-unchanged bit set'
```

Would it be possible to add that? Based on the commit message I looked at 4a075f4b6148f38440b7efcf9642c3f6c7cd3ec2 to see if I could figure it out myself… and could not :)

I'm on zsh on macOS using a customized version of `gitstatus.prompt.zsh`.

**Comment by romkatv** [comment]
It's not difficult to add but I cannot promise doing it any time soon.

For future reference, given `struct git_index_entry* e`
- `--skip-worktree` bit is set iff `e->flags_extended & GIT_INDEX_ENTRY_SKIP_WORKTREE`.
- `--assume-unchanged` bit is set iff `e->flags & GIT_INDEX_ENTRY_VALID`.

**Comment by romkatv** [comment]
This is done. gitstatus now sets `VCS_STATUS_NUM_SKIP_WORKTREE` and `VCS_STATUS_NUM_ASSUME_UNCHANGED`. I'll publish new gitstatusd binaries in a few days.

**Comment by romkatv** [comment]
> I'll publish new gitstatusd binaries in a few days.

And done.

**Comment by olets** [comment]
Amazing, thanks very much! (And apologies for not responding to the first message)
